BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Τι χρειάζεται ένας TRAINER…\p"
	.string "Γνώση…\n"
	.string "Στρατηγική…\l"
	.string "Τύχη…\l"
	.string "Κότσια…\l"
	.string "Πνεύμα…\l"
	.string "Γενναιότητα…\l"
	.string "Και ικανότητα…\p"
	.string "Λοιπόν, εγώ είμαι έτοιμος για όλα!\n"
	.string "Θα είμαι ασταμάτητος σε κάθε κτίριο!\p"
	.string "Ε; POKéMON;\n"
	.string "Τι είναι αυτό;$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Ξέρεις για τους FRONTIER BRAINS;\p"
	.string "Έτσι αποκαλεί ο SCOTT τους επτά\n"
	.string "ειδικούς TRAINERS των εγκαταστάσεων\l"
	.string "στο BATTLE FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Στο BATTLE TOWER, ένα μεγάλο κορίτσι\n"
	.string "μου είπε ότι έχω ταλέντο στις μάχες!\p"
	.string "Μου αρέσουν πιο πολύ τα POKéMON\n"
	.string "CONTESTS!\p"
	.string "Αλλά δεν είμαι καλός στα CONTESTS!\p"
	.string "Μάλλον το να έχεις ταλέντο και το να\n"
	.string "σου αρέσει κάτι δεν είναι το ίδιο.$"

