PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "Στην περιοχή HOENN, υπάρχουν τρία \n"
	.string "POKéMON που αντιπροσωπεύουν τη \l"
	.string "δύναμη της πέτρας, του πάγου και \l"
	.string "του ατσαλιού.\p"
	.string "Το καθένα από αυτά λέγεται ότι \n"
	.string "κρύβεται βαθιά μέσα σε σπηλιές.\p"
	.string "Αυτή είναι η ιστορία που άκουσα \n"
	.string "όταν ήμουν μικρό παιδί.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "“Έξι τελείες ανοίγουν τρεις \n"
	.string "πόρτες.”\p"
	.string "Ο παππούς το έλεγε συνέχεια αυτό, \n"
	.string "αλλά δεν ξέρω τι εννοούσε.$"

