.set LOCALID_ATTENDANT, 1

FallarborTown_BattleTentCorridor_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FallarborTown_BattleTentCorridor_OnFrame
	.byte 0

FallarborTown_BattleTentCorridor_OnFrame:
	map_script_2 VAR_TEMP_0, 0, FallarborTown_BattleTentCorridor_EventScript_EnterCorridor
	.2byte 0

FallarborTown_BattleTentCorridor_EventScript_EnterCorridor::
	lockall
	setvar VAR_TEMP_0, 1
	applymovement LOCALID_ATTENDANT, FallarborTown_BattleTentCorridor_Movement_WalkToDoor
	applymovement OBJ_EVENT_ID_PLAYER, FallarborTown_BattleTentCorridor_Movement_WalkToDoor
	waitmovement 0
	opendoor 2, 1
	waitdooranim
	applymovement LOCALID_ATTENDANT, FallarborTown_BattleTentCorridor_Movement_AttendantEnterDoor
	applymovement OBJ_EVENT_ID_PLAYER, FallarborTown_BattleTentCorridor_Movement_PlayerEnterDoor
	waitmovement 0
	closedoor 2, 1
	waitdooranim
	setvar VAR_0x8006, 0
	warp MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM, 4, 4
	waitstate
	releaseall
	end

FallarborTown_BattleTentCorridor_Movement_WalkToDoor:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

FallarborTown_BattleTentCorridor_Movement_PlayerEnterDoor:
	walk_up
FallarborTown_BattleTentCorridor_Movement_AttendantEnterDoor:
	walk_up
	set_invisible
	step_end

@ Leftover text from when this was a Contest Hall in R/S
@ Unused
FallarborTown_ContestHall_Text_DoAllRightInPreliminary:
	.string "Τα πάμε καλά στον προκριματικό, \n"
	.string "αλλά δεν μπορούμε να κερδίσουμε \l"
	.string "ποτέ τις εντυπώσεις…\p"
	.string "Αυτό σημαίνει πως πρέπει να δω \n"
	.string "τι κάνουν οι άλλοι διαγωνιζόμενοι…$"

@ Unused
FallarborTown_ContestHall_Text_MonAllTheseRibbons:
	.string "Κοίτα!\n"
	.string "Το POKéMON μου κέρδισε RIBBONS!\p"
	.string "Έχουν κερδίσει τα δικά σου POKéMON\n"
	.string "RIBBONS;\l"
	.string "Μπορείς να τα ελέγξεις στο POKéNAV.$"

@ Unused
FallarborTown_ContestHall_Text_CantWinEverywhere:
	.string "Δεν μπορώ να κερδίσω τους LEADERS…\p"
	.string "Δεν μπορώ να κερδίσω τους CONTESTS…\p"
	.string "Έχω πάει παντού, αλλά όλα είναι \n"
	.string "μάταια…$"

@ Unused
FallarborTown_ContestHall_Text_SuperRankStage:
	.string "POKéMON CONTESTS\n"
	.string "SUPER RANK STAGE!$"
