gText_ApprenticeChallenge0::
	.string "Εμμ, είμαι ο μαθητής {STR_VAR_2}\n"
	.string "του {STR_VAR_1}.\n"
	.string "Σνιφ... Με έχει κυριεύσει το άγχος...$"

gText_ApprenticeChallenge1::
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1}!\n"
	.string "Ορίστε, ερχόμαστε!$"

gText_ApprenticeChallenge2::
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1}!\n"
	.string "Δέξου την πρόκλησή μου!$"

gText_ApprenticeChallenge3::
	.string "Εμμ... Είμαι ο μαθητής {STR_VAR_2}\n"
	.string "του {STR_VAR_1}...\n"
	.string "Λες κάποιος σαν εμένα να κερδίσει;$"

gText_ApprenticeChallenge4::
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1}!\n"
	.string "Θα σου επιτρέψω να με προκαλέσεις!$"

gText_ApprenticeChallenge5::
	.string "Είμαι πολυάσχολος, αλλά είμαι\n"
	.string "ο μαθητής {STR_VAR_2} του {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1}.\n"
	.string "Χαίρομαι που σε γνωρίζω!$"

gText_ApprenticeChallenge7::
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1}.\n"
	.string "Μπορούμε να ξεκινήσουμε;$"

gText_ApprenticeChallenge8::
	.string "Ααα! Είμαι ο μαθητής {STR_VAR_2}\n"
	.string "του {STR_VAR_1}!\n"
	.string "Θα βάλω τα δυνατά μου!$"

gText_ApprenticeChallenge9::
	.string "Γιούχου! Μαθητής {STR_VAR_2} του {STR_VAR_1}!\n"
	.string "Ετοιμάσου!$"

gText_ApprenticeChallenge10::
	.string "Είμαι ο 1.000ος μαθητής του {STR_VAR_1}!\n"
	.string "Βασικά, ο μαθητής {STR_VAR_2}!$"

gText_ApprenticeChallenge11::
	.string "Ναι, είμαι ο μαθητής {STR_VAR_2}\n"
	.string "του {STR_VAR_1}!\n"
	.string "Ας αρχίσει το πάρτι!$"

gText_ApprenticeChallenge12::
	.string "Γιούχου! Είμαι ο μαθητής\n"
	.string "{STR_VAR_2} του {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "Κουχ! Είμαι ο μαθητής {STR_VAR_2}\n"
	.string "του {STR_VAR_1}.\n"
	.string "Χαίρομαι που σε γνωρίζω! Κουχ!$"

gText_ApprenticeChallenge14::
	.string "Αυτό είναι αγχωτικό...\n"
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Είμαι ο μαθητής {STR_VAR_2} του {STR_VAR_1},\n"
	.string "και αυτό δεν είναι ψέμα.$"

gText_ApprenticePleaseTeach0::
	.string "Εσύ είσαι... {PLAYER};\n"
	.string "Ω! Σνιφ... κλαψ...\p"
	.string "Ω! Σ-συγγνώμη...\n"
	.string "Τρέμω από το άγχος μου,\l"
	.string "δεν μπορώ να σταματήσω το κλάμα...\p"
	.string "Με λένε {STR_VAR_1}, και σε θαυμάζω\n"
	.string "πραγματικά, {PLAYER}.\p"
	.string "Είχα αυτό το όνειρο να σε συναντήσω\n"
	.string "και να σε ρωτήσω για τα POKéMON.\p"
	.string "Σε παρακαλώ, {PLAYER}!\n"
	.string "Μάθε μου για τα POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Ω... Μ-μα...\n"
	.string "Σνιφ... Ουάααααα!\p"
	.string "Σε παρακαλώ!\n"
	.string "Σε ικετεύω, σε παρακαλώ!$"

gText_ApprenticeWhichLevelMode0::
	.string "Αλήθεια; Θα το κάνεις;\n"
	.string "Τέλεια! Φανταστικά! Αουυού!\p"
	.string "Ω... συγγνώμη...\n"
	.string "Η χαρά μου είναι τόσο μεγάλη\l"
	.string "που με έπιασαν τα κλάματα...\p"
	.string "Εμμ... τότε πες μου σε παρακαλώ!\n"
	.string "Είναι για το BATTLE TOWER.\p"
	.string "Τι είναι καλύτερο για μένα: Level 50\n"
	.string "ή το Open Level;$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Ουάαααα!\p"
	.string "Ω! Χίλια συγγνώμη!\n"
	.string "Μου έδωσες τόση χαρά διαλέγοντας\l"
	.string "το επίπεδο, που έβαλα τα κλάματα...\p"
	.string "Σνιφ...\n"
	.string "Σε ευχαριστώ πάρα πολύ!\l"
	.string "Σε παρακαλώ, μίλα μου ξανά!$"

gText_ApprenticePleaseTeach1::
	.string "Ουάου! Εσύ είσαι {PLAYER}, έτσι;\n"
	.string "Έχεις απίστευτη δύναμη, ε;\p"
	.string "Με λένε {STR_VAR_1}!\n"
	.string "Μόλις έγινα TRAINER!\p"
	.string "Σε παρακαλώ, {PLAYER}!\n"
	.string "Θέλεις να με καθοδηγήσεις και να\l"
	.string "μου μάθεις πολλά για τους TRAINERS;$"

gText_ApprenticeRejectTeaching1::
	.string "Ωωω, γιατί;\n"
	.string "Ω, σε παρακαλώ! Σε παρακαλώ πολύ!\l"
	.string "Σε παρακαλώ, καθοδήγησέ με!$"

gText_ApprenticeWhichLevelMode1::
	.string "Γιούπι! Τέλεια!\p"
	.string "Το πρώτο πράγμα που ήθελα να σε\n"
	.string "ρωτήσω είναι για το BATTLE TOWER!\p"
	.string "Τα Level 50 και Open Level Rooms...\n"
	.string "Ποιο θα ήταν το ιδανικό για μένα;$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, ε; Έχεις δίκιο!\n"
	.string "Θα βάλω τα δυνατά μου εκεί!\p"
	.string "Αν ξανασυναντηθούμε, σε παρακαλώ\n"
	.string "μάθε μου και κάτι άλλο!$"

gText_ApprenticePleaseTeach2::
	.string "Εμμ... Εσύ είσαι {PLAYER};\n"
	.string "Το όνομά μου είναι {STR_VAR_1}.\p"
	.string "Θέλω να γίνω POKéMON TRAINER,\n"
	.string "αλλά δεν ξέρω τι να κάνω...\p"
	.string "Σκέφτηκα λοιπόν να ζητήσω τη\n"
	.string "συμβουλή σου, μιας και είσαι famous.\p"
	.string "{PLAYER}, δώσε μου μια συμβουλή;$"

gText_ApprenticeRejectTeaching2::
	.string "Ω, μα...\p"
	.string "Θέλω ειλικρινά να γίνω POKéMON\n"
	.string "TRAINER!\p"
	.string "Σε παρακαλώ, μπορείς να απαντήσεις\n"
	.string "στις ερωτήσεις μου;$"

gText_ApprenticeWhichLevelMode2::
	.string "Σε ευχαριστώ!\n"
	.string "Ορίστε αμέσως η πρώτη μου ερώτηση!\p"
	.string "Το BATTLE TOWER έχει δύο επίπεδα,\n"
	.string "Level 50 και Open Level, σωστά;\p"
	.string "Ποιο επίπεδο πιστεύεις ότι είναι\n"
	.string "πιο κατάλληλο για μένα;$"

gText_ApprenticeLevelModeThanks2::
	.string "Ω, η πρόκληση {STR_VAR_1};\n"
	.string "Κατάλαβα!\p"
	.string "Αν έχω άλλη ερώτηση, θα έρθω\n"
	.string "πάλι εδώ για τη συμβουλή σου!$"

gText_ApprenticePleaseTeach3::
	.string "Ω; Ε; Εσύ είσαι...\n"
	.string "Όχι, δεν μπορεί να είναι αλήθεια.\p"
	.string "Δεν υπάρχει περίπτωση κάποιος\n"
	.string "σαν εμένα να συναντήσει {PLAYER}.\p"
	.string "...Είσαι στ' αλήθεια {PLAYER};\n"
	.string "Δεν πιστεύω ότι σου μιλάω!\p"
	.string "Όταν συμβαίνει κάτι τόσο καλό,\n"
	.string "μόνο τρομερά πράγματα θα μου\l"
	.string "συμβούν τώρα, το ξέρω...\p"
	.string "...Συγγνώμη...\n"
	.string "Είμαι... {STR_VAR_1}...\p"
	.string "Δεν υπάρχει τίποτα ιδιαίτερο σε\n"
	.string "μένα για το οποίο να καμαρώνω...\p"
	.string "Δεν θα έπρεπε καν να μιλάω για\n"
	.string "μένα γιατί θα με ξεχάσεις...\p"
	.string "Είχα αυτό το όνειρο ότι αν σε\n"
	.string "έβλεπα, {PLAYER}, ίσως μπορούσα να\l"
	.string "ζητήσω συμβουλές για TRAINERS.\p"
	.string "Αλλά δεν νομίζω ότι θα δεχόσουν.\p"
	.string "...Ή μήπως θα είχες την καλοσύνη\n"
	.string "να μου δώσεις μια συμβουλή;$"

gText_ApprenticeRejectTeaching3::
	.string "Το ήξερα...\p"
	.string "Έπρεπε να συμβεί γιατί είμαι ένα\n"
	.string "τόσο βαρετό μηδενικό...\p"
	.string "Αλλά σκέφτηκα ίσως...\n"
	.string "Δεν θα το ξανασκεφτείς, έτσι;\p"
	.string "Αλλά δεν μπορώ να τα παρατήσω.\n"
	.string "Θα σε ρωτήσω όσο έχω την τύχη!\p"
	.string "Σε παρακαλώ, θα ήθελες να μου\n"
	.string "δώσεις μια συμβουλή;$"

gText_ApprenticeWhichLevelMode3::
	.string "Αλήθεια; Δεν το πιστεύω!\n"
	.string "Θα μου δώσεις συμβουλή!\l"
	.string "Είμαι... γεμάτος χαρά...\p"
	.string "Αυτό που θέλω να σε ρωτήσω είναι\n"
	.string "ασήμαντο, αλλά δεν αποφασίζω...\p"
	.string "Στο BATTLE TOWER, σε αφήνουν να\n"
	.string "διαλέξεις Level 50 ή Open Level.\p"
	.string "Σε ποιο πιστεύεις ότι ακόμα κι\n"
	.string "εγώ μπορεί να έχω μια ελπίδα;$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}; Εντάξει!\n"
	.string "Αλλά όντως πιστεύεις ότι κάποιος\n"
	.string "σαν εμένα έχει ελπίδα;\p"
	.string "Θα προσπαθήσω, αν και δεν νομίζω\n"
	.string "ότι θα πιάσει.\p"
	.string "Σε ευχαριστώ πολύ που αφιέρωσες\n"
	.string "χρόνο σε κάποιον σαν εμένα.$"

gText_ApprenticePleaseTeach4::
	.string "Ω! Εσύ είσαι {PLAYER}, έτσι;\p"
	.string "Έχω ακούσει ότι είσαι ξεφτέρι\n"
	.string "στα POKéMON!\p"
	.string "Με λένε {STR_VAR_1}!\n"
	.string "Θα γίνουμε φίλοι!\p"
	.string "Το ήξερες;\p"
	.string "Δεν μπορείς να κερδίσεις στο\n"
	.string "BATTLE FRONTIER με όσα μαθαίνεις\l"
	.string "στο TRAINER'S SCHOOL.\p"
	.string "Θέλω να ακούσω τις συμβουλές σου.\n"
	.string "Συμφωνείς, έτσι δεν είναι;$"

gText_ApprenticeRejectTeaching4::
	.string "Ε; Γιατί μου αρνείσαι;\n"
	.string "Εγώ είμαι που σου το ζητάω!\l"
	.string "Πρέπει να το ξανασκεφτείς!$"

gText_ApprenticeWhichLevelMode4::
	.string "Εντάξει, υπάρχει κάτι λοιπόν.\n"
	.string "Θέλω να αποφασίσεις για μένα.\p"
	.string "Ξέρεις ότι το BATTLE TOWER έχει\n"
	.string "δωμάτια Level 50 και Open Level;\p"
	.string "Ποιο πιστεύεις ότι είναι καλό\n"
	.string "για μένα, {PLAYER};$"

gText_ApprenticeLevelModeThanks4::
	.string "Οπότε το {STR_VAR_1} μου ταιριάζει;\n"
	.string "Σε ευχαριστώ!\p"
	.string "Ξέροντας ότι εσύ αποφάσισες,\n"
	.string "{PLAYER}, δεν θα στεναχωρηθώ και\l"
	.string "τόσο αν χάσω.\p"
	.string "Θα σε ξαναρωτήσω για συμβουλές.\n"
	.string "Γεια!$"

gText_ApprenticePleaseTeach5::
	.string "Ω, γεια σου, {PLAYER}!\n"
	.string "Σε ξέρω γιατί είσαι famous!\l"
	.string "Πες με {STR_VAR_1}! Χαίρομαι!\p"
	.string "Είμαι TRIATHLETE, οπότε κρατιέμαι\n"
	.string "σε φόρμα όσο εκπαιδεύω POKéMON.\p"
	.string "Κάνω κι άλλα πράγματα βέβαια,\n"
	.string "δουλειά, ύπνο, χορό...\p"
	.string "Με τόσες ασχολίες, δεν είναι\n"
	.string "εύκολο να γίνω καλός TRAINER.\p"
	.string "Λοιπόν, έχω μια πρόταση!\p"
	.string "Κάποιος λόγος υπάρχει που ειδωθήκαμε.\n"
	.string "Θέλεις λοιπόν, {PLAYER}, να μοιραστείς\l"
	.string "τη σοφία σου μαζί μου πού και πού;$"

gText_ApprenticeRejectTeaching5::
	.string "Ω, μα σε παρακαλώ!\n"
	.string "Κάποιος σαν εμένα χρειάζεται\l"
	.string "κάποιον σαν εσένα, {PLAYER}!\p"
	.string "Ειλικρινά, χρειάζομαι τη συμβουλή σου!$"

gText_ApprenticeWhichLevelMode5::
	.string "Ευχαριστώ! Αυτό μάλιστα!\n"
	.string "Ας αρχίσουμε με κάτι εύκολο!\p"
	.string "Ξέρεις για τις δύο διαδρομές του\n"
	.string "BATTLE TOWER, έτσι δεν είναι;\l"
	.string "Το Level 50 και το Open Level.\p"
	.string "Για έναν πολυάσχολο τύπο σαν εμένα,\n"
	.string "ποιο θα έπρεπε να προτιμήσω;$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, ε; Έγινε, το 'πιασα.\n"
	.string "Θα βρω χρόνο και θα το δοκιμάσω!\p"
	.string "...Ώπα, καλύτερα να πάω στη δουλειά!\n"
	.string "Ευχαριστώ! Τα λέμε!$"

gText_ApprenticePleaseTeach6::
	.string "Αποκλείεται! Μπα!\n"
	.string "Είσαι μήπως ο αληθινός {PLAYER};\p"
	.string "Α-χα! Τέλεια! Με λένε {STR_VAR_1},\n"
	.string "χαίρομαι πολύ που σε γνωρίζω!\p"
	.string "{PLAYER}, έχεις μεγάλη δύναμη,\n"
	.string "έτσι δεν είναι;\p"
	.string "Όλοι μιλάνε για σένα!\p"
	.string "Ω! Μου ήρθε μια φοβερή ιδέα!\n"
	.string "Θα παίρνω συμβουλές από σένα,\n"
	.string "{PLAYER}! Θα γίνω πιο δυνατός/ή!\l"
	.string "Δεν είναι φοβερή ιδέα;\n"
	.string "Σε παρακαλώ, θέλω τη συμβουλή σου!$"

gText_ApprenticeRejectTeaching6::
	.string "Αχαχαχα, μπορείς να παριστάνεις\n"
	.string "τον κακό, αλλά δεν με ξεγελάς!\l"
	.string "Στην πραγματικότητα λες ναι, ε;$"

gText_ApprenticeWhichLevelMode6::
	.string "Γιούπι! Ήξερα ότι έχεις καλή καρδιά,\n"
	.string "{PLAYER}!\p"
	.string "Τι να σε ρωτήσω πρώτα;\n"
	.string "...Ω, σκέφτηκα κάτι!\p"
	.string "Τυμπανοκρουσίες, παρακαλώ!\n"
	.string "Η ερώτησή μου είναι...\p"
	.string "Αν έμπαινα σε μια πρόκληση του\n"
	.string "BATTLE TOWER, πού να πήγαινα;\p"
	.string "Level 50 ή Open Level;\n"
	.string "Ποιο μου ταιριάζει περισσότερο;$"

gText_ApprenticeLevelModeThanks6::
	.string "Ω-ω-ω!\n"
	.string "{STR_VAR_1}, ε;!\l"
	.string "Ευχαριστώ για την τέλεια απάντηση!\p"
	.string "Νομίζω αυτά ήθελα να σε ρωτήσω\n"
	.string "για σήμερα.\p"
	.string "Ας βρεθούμε πάλι εδώ, εντάξει;\n"
	.string "Ευχαριστώ!$"

gText_ApprenticePleaseTeach7::
	.string "Με συγχωρείτε, αλλά...\n"
	.string "Εσείς είστε {PLAYER};\p"
	.string "Με λένε {STR_VAR_1} και χαίρομαι\n"
	.string "πολύ για τη γνωριμία μας.\p"
	.string "Σας θαυμάζω από καιρό...\p"
	.string "... ... ... ... ... ...\p"
	.string "Εμμ... ελπίζω να μη σας φανεί\n"
	.string "βάρος αυτό που θα ζητήσω, αλλά...\p"
	.string "Μπορώ να γίνω μαθητής σας,\n"
	.string "{PLAYER};$"

gText_ApprenticeRejectTeaching7::
	.string "Ω...!\p"
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\p"
	.string "...Πρέπει να λιποθύμησα από το σοκ.\n"
	.string "Συγγνώμη, μάλλον παραάκουσα.\p"
	.string "Σας παρακαλώ! Πείτε ότι θα με\n"
	.string "δεχτείτε ως μαθητή σας!$"

gText_ApprenticeWhichLevelMode7::
	.string "Ω... τι μεγάλη χαρά!\p"
	.string "Δεν θέλω να σπαταλήσω τον χρόνο σας,\n"
	.string "οπότε συμβουλεύστε με σε αυτό.\p"
	.string "Σκοπεύω να μπω σε μια πρόκληση\n"
	.string "του BATTLE TOWER σύντομα.\p"
	.string "Όμως, υπάρχουν δύο επίπεδα...\p"
	.string "Ποιο θα ήταν το πιο κατάλληλο;\n"
	.string "Level 50 ή Open Level;$"

gText_ApprenticeLevelModeThanks7::
	.string "Το {STR_VAR_1} είναι η επιλογή σας!\n"
	.string "Μάλιστα. Θα βάλω τα δυνατά μου!\p"
	.string "Σας ευχαριστώ, {PLAYER}.\n"
	.string "Ελπίζω να μπορώ να βασίζομαι σε\n"
	.string "εσάς πάλι. Να προσέχετε!$"

gText_ApprenticePleaseTeach8::
	.string "Ααα! Ααα! {PLAYER}!\n"
	.string "Μου μίλησες!\l"
	.string "Είμαι... τρισευτυχισμένος/η!\p"
	.string "Εγώ! Το όνομά μου είναι {STR_VAR_1}!\n"
	.string "Μόλις έγινα TRAINER!\p"
	.string "Χαίρομαι τόσο που σε γνώρισα,\n"
	.string "{PLAYER}, θρύλε των POKéMON!\p"
	.string "Ω-ω-ω, το 'χω!\n"
	.string "Θα μου κάνεις μια μεγάλη χάρη;\p"
	.string "Σε παρακαλώ, πάρε με για μαθητή!\n"
	.string "Θέλω να μάθω από σένα!$"

gText_ApprenticeRejectTeaching8::
	.string "Ουάαααα!\n"
	.string "{PLAYER}, με απέρριψες...\l"
	.string "Είναι... μια ανεκτίμητη εμπειρία!\p"
	.string "{PLAYER}, σε παρακαλώ! Θέλω μια\n"
	.string "θετική απάντηση αυτή τη φορά!\p"
	.string "Σε ικετεύω για την καθοδήγησή σου!$"

gText_ApprenticeWhichLevelMode8::
	.string "Αααα! Είπες ναι, {PLAYER}!\n"
	.string "Είπες ναι!\p"
	.string "Δεν θα κλείσω μάτι απόψε...\n"
	.string "Σε ευχαριστώ πάρα πολύ!\p"
	.string "Λοιπόν, ορίστε η ερώτησή μου!\p"
	.string "Στο BATTLE TOWER, τι είναι σωστό\n"
	.string "για μένα, Level 50 ή Open Level;$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Το κατάλαβα πλήρως!\n"
	.string "Το κατάλαβα απόλυτα!\l"
	.string "Είμαι τρελά ευτυχισμένος/η!\p"
	.string "Ελπίζω να θέλεις να με μάθεις\n"
	.string "κι άλλα κάποια άλλη στιγμή.$"

gText_ApprenticePleaseTeach9::
	.string "Ουάου! Λες να είσαι...\n"
	.string "Να είσαι ο {PLAYER};!\l"
	.string "Αυτός ο δυνατός και famous TRAINER;\l"
	.string "Γεια, τι τύχη είναι αυτή!\p"
	.string "Γεια, με λένε {STR_VAR_1}!\p"
	.string "Έψαχνα για έναν δάσκαλο POKéMON.\p"
	.string "Και την πιο κατάλληλη στιγμή,\n"
	.string "εμφανίστηκες εσύ, {PLAYER}!\p"
	.string "Οπότε, ορίστε, {PLAYER}!\n"
	.string "Δέξου με ως μαθητή σου!$"

gText_ApprenticeRejectTeaching9::
	.string "Γκουάαα!\n"
	.string "Έχεις πολύ cool και δυνατή αύρα...\p"
	.string "Μη μου το χαλάς, σε παρακαλώ.\n"
	.string "Εγώ σου το ζητάω!$"

gText_ApprenticeWhichLevelMode9::
	.string "Ω, ναι! Αυτό θα πει απάντηση!\n"
	.string "Εξαιρετική, θα έλεγα!\p"
	.string "Λοιπόν, τι λες για μια πρώτη\n"
	.string "συμβουλή για το BATTLE TOWER;\p"
	.string "Αν πήγαινα, τι θα ήταν καλύτερο;\n"
	.string "Level 50 ή Open Level;$"

gText_ApprenticeLevelModeThanks9::
	.string "Α-χα, {STR_VAR_1} λοιπόν!\n"
	.string "ΟΚ, όλα καλά!\l"
	.string "Θα πάω να δείξω τι αξίζω!\p"
	.string "Εντάξει, θα σε έχω για μέντορα!\n"
	.string "Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Ω, γεια, {PLAYER}, σωστά;\n"
	.string "Σε έψαχνε η αστυνομία!\p"
	.string "... ... ...\n"
	.string "Φυσικά και λέω ψέματα!\p"
	.string "Εγώ είμαι ο/η {STR_VAR_1}. Παρά την\n"
	.string "εμφάνισή μου, είμαι ο CHAMPION!\l"
	.string "...Κι αυτό ψέμα είναι!\p"
	.string "Αυτό όμως δεν είναι ψέμα.\n"
	.string "Δεν είμαι πολύ καλός στις μάχες.\p"
	.string "Θέλεις λοιπόν να γίνεις ο master\n"
	.string "μου για όλα τα POKéMON;$"

gText_ApprenticeRejectTeaching10::
	.string "Αν πρόκειται να είσαι έτσι,\n"
	.string "θα σου δείξω τι θα κάνω!\p"
	.string "Ουάαα! Ουάαα! Ουάαα!\n"
	.string "Χικ!\p"
	.string "Αχαχαχα, αυτά ήταν FAKE TEARS!\p"
	.string "Έλα τώρα, θα γίνεις ο POKéMON\n"
	.string "master μου;$"

gText_ApprenticeWhichLevelMode10::
	.string "Γιούπι!\n"
	.string "Θα σου αγοράσω ένα σκάφος γι' αυτό!\p"
	.string "Φυσικά πάλι ψέματα λέω!\n"
	.string "Όμως... ευχαριστώ, master!\p"
	.string "Ξέρεις ότι έχει Level 50 και\n"
	.string "Open Level στο BATTLE TOWER;\p"
	.string "Δυσκολεύομαι να αποφασίσω ποιο\n"
	.string "επίπεδο να προκαλέσω...\p"
	.string "Μπορείς να διαλέξεις, master;$"

gText_ApprenticeLevelModeThanks10::
	.string "Οπότε το {STR_VAR_1} είναι καλύτερο;\n"
	.string "Τότε θα πάω στο άλλο επίπεδο!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ, master!\n"
	.string "Ελπίζω να συνεχίσεις να με μαθαίνεις!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "Που σημαίνει ahoy, δηλαδή γεια!\p"
	.string "Είμαι ο {STR_VAR_1}, ο SAILOR που\n"
	.string "ραπάρει!\p"
	.string "Σειρά σου τώρα, πες μου για σένα,\n"
	.string "για δοκίμασε!\p"
	.string "Α-χα, α-χα!\n"
	.string "{PLAYER} είναι το όνομά σου,\l"
	.string "και τα POKéMON η δουλειά σου!\p"
	.string "Και είσαι σε μια ηλικία,\n"
	.string "που ο κόσμος σου δίνει αξία!\p"
	.string "Όπως και να 'χει, ήθελα να πω,\n"
	.string "πως είσαι ο δέκατος TRAINER\l"
	.string "που μιλάω σήμερα.\p"
	.string "Ας το γιορτάσουμε λοιπόν!\n"
	.string "Γίνε ο μέντοράς μου τώρα!$"

gText_ApprenticeRejectTeaching11::
	.string "Μα!\n"
	.string "Πρέπει να συνεργαστείς μαζί μου!\p"
	.string "Μη με τυραννάς άλλο!\n"
	.string "Γίνε ο μέντοράς μου, σε παρακαλώ!$"

gText_ApprenticeWhichLevelMode11::
	.string "Αυτό είναι!\n"
	.string "{PLAYER}, έχεις τσαγανό!\p"
	.string "Ορίστε λοιπόν η πρώτη ερώτηση,\n"
	.string "που θέλει τη δική σου απάντηση!\p"
	.string "Είναι για το BATTLE TOWER,\n"
	.string "και τη δική μου δύναμη!\p"
	.string "Level 50 και Open Level υπάρχουν,\n"
	.string "ποιο είναι αυτό που μου ταιριάζει;$"

gText_ApprenticeLevelModeThanks11::
	.string "Οπότε {STR_VAR_1} λες, ε;\n"
	.string "Θα πάω να το αντιμετωπίσω!\p"
	.string "Αν χρειαστώ ποτέ συμβουλή,\n"
	.string "{PLAYER}, θα σε ακούσω πολύ!$"

gText_ApprenticePleaseTeach12::
	.string "Ε, εσύ δεν είσαι {PLAYER};\n"
	.string "Τι να κάνω; Να σου μιλήσω;\l"
	.string "Γιατί όχι; Ήδη σου μιλάω!\p"
	.string "{PLAYER}, σε ξάφνιασα;\n"
	.string "Καλύτερα να σου πω ποιος είμαι!\p"
	.string "{STR_VAR_1} μπορείς να με φωνάζεις.\n"
	.string "Το πιο λαμπρό αστέρι της κιθάρας,\l"
	.string "αυτός είμαι!\p"
	.string "Με πιάνεις;\n"
	.string "Με πιάνεις!\p"
	.string "Η τύχη μου είναι στα ύψη,\n"
	.string "έχω μια παράκληση για σένα!\p"
	.string "{PLAYER}, άσε με να γίνω μαθητής σου!\n"
	.string "Θέλω να μου τα μάθεις όλα!$"

gText_ApprenticeRejectTeaching12::
	.string "Με απορρίπτεις λοιπόν;\n"
	.string "Θα πρέπει να σε ρωτήσω ξανά!\p"
	.string "{PLAYER}, σε ικετεύω να με δεχτείς!\n"
	.string "Πρέπει να μου τα μάθεις όλα!$"

gText_ApprenticeWhichLevelMode12::
	.string "Τυχερός/ή, ναι, γιούχου!\n"
	.string "Να σου κάνω μια ερώτηση;\p"
	.string "Μιας και είμαστε κοντά στο\n"
	.string "BATTLE TOWER, τι λες για μια ερώτηση;\p"
	.string "Από τις επιλογές που βλέπεις,\n"
	.string "ποια είναι η σωστή για μένα;$"

gText_ApprenticeLevelModeThanks12::
	.string "Αν προτείνεις το {STR_VAR_1},\n"
	.string "πρέπει να είναι το καλύτερο!\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις.\p"
	.string "Θα σε ξαναδώ, έξυπνε φίλε μου!$"

gText_ApprenticePleaseTeach13::
	.string "Ω, γεια! Εσύ εκεί!\n"
	.string "Μπορείς να μου κάνεις ένα μασάζ;\p"
	.string "...Ναι, εκεί! Αυτό είναι!\n"
	.string "Άουτς! Ωωω, αυτό είναι τέλειο!\p"
	.string "Με λένε {STR_VAR_1}.\n"
	.string "Κάνω προπόνηση καράτε, αλλά το\n"
	.string "σώμα μου δεν το αντέχει...\p"
	.string "Αποφάσισα να παλέψω με POKéMON\n"
	.string "για να σκληραγωγηθώ.\p"
	.string "Εσύ είσαι {PLAYER}, έτσι;\n"
	.string "Ο CHAMPION του POKéMON LEAGUE;\p"
	.string "Άκου, θα μπορούσες να μου δώσεις\n"
	.string "μια συμβουλή;$"

gText_ApprenticeRejectTeaching13::
	.string "Ω, γιατί;\p"
	.string "Υπόσχομαι να μη γίνω βάρος!\n"
	.string "Σε παρακαλώ;$"

gText_ApprenticeWhichLevelMode13::
	.string "Ευχαριστώ. Πολύ ευγενικό εκ μέρους σου!\n"
	.string "...Κουχ! Κουχ!\p"
	.string "Ουφ, πρέπει να σκληραγωγηθώ γρήγορα...\n"
	.string "Θα πάω αμέσως στο BATTLE TOWER,\n"
	.string "αλλά τι θα ήταν καλύτερο;\l"
	.string "Level 50 ή Open Level;$"

gText_ApprenticeLevelModeThanks13::
	.string "Χμμ, εντάξει. Το {STR_VAR_1}.\n"
	.string "Θα πάω εκεί αμέσως.\p"
	.string "Ελπίζω να συνεχίσω να σου ζητάω\n"
	.string "βοήθεια--είσαι ο μέντοράς μου!$"

gText_ApprenticePleaseTeach14::
	.string "Ε... εμμ...\n"
	.string "{PLAYER}...;\p"
	.string "Σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Με κάνεις να ντρέπομαι...\p"
	.string "Με λένε {STR_VAR_1}.\p"
	.string "Ντρέπομαι πολύ που το λέω, αλλά\n"
	.string "ερευνώ αρχαία ερείπια και τέτοια.\p"
	.string "Ντρέπομαι ακόμα πιο πολύ που μου\n"
	.string "κινεί το ενδιαφέρον το FRONTIER.\p"
	.string "{PLAYER}, έχεις τη φήμη του\n"
	.string "σκληρού TRAINER...\p"
	.string "Μου είναι δύσκολο να το πω,\n"
	.string "αλλά θέλω να σε ρωτήσω κάτι.\p"
	.string "Θα γινόσουν ο δάσκαλός μου και\n"
	.string "να μου έδινες συμβουλές;$"

gText_ApprenticeRejectTeaching14::
	.string "Σε παρακαλώ, μη με διώχνεις έτσι!\n"
	.string "Δεν αντέχω τόση ταπείνωση.\p"
	.string "Σε παρακαλώ, γίνε ο δάσκαλός μου!\n"
	.string "Χρειάζομαι τη συμβουλή σου!$"

gText_ApprenticeWhichLevelMode14::
	.string "Σ-σε ευχαριστώ...\p"
	.string "Αλλά σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Με μπερδεύεις τελείως.\p"
	.string "Σε παρακαλώ, απάντησέ μου χωρίς\n"
	.string "να με κοιτάς στα μάτια.\p"
	.string "Στο BATTLE TOWER...\n"
	.string "Ποιο επίπεδο να δοκιμάσω;$"

gText_ApprenticeLevelModeThanks14::
	.string "Ω... Εντάξει!\n"
	.string "Θα το δοκιμάσω.\p"
	.string "Ελπίζω να τα πάω καλά χωρίς να\n"
	.string "μπερδευτώ τελείως...\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Αν ξαναβρεθούμε, ελπίζω να είσαι\l"
	.string "το ίδιο εξυπηρετικός/ή.$"

gText_ApprenticePleaseTeach15::
	.string "Χμμ; Φαίνεσαι να είσαι ο {PLAYER}...\n"
	.string "Αλλά είσαι όντως αληθινός;\p"
	.string "Μπορείς να με φωνάζεις {STR_VAR_1}.\p"
	.string "Σκεφτόμουν να γίνω μαθητής κάποιου\n"
	.string "δυνατού TRAINER.\p"
	.string "Οπότε, είμαι τυχερός που ήρθες!\n"
	.string "...Είσαι όντως ο {PLAYER}, έτσι;\p"
	.string "Όχι, αν είσαι αληθινός, εντάξει.\n"
	.string "Απλώς θέλω να με αναγνωρίσεις\l"
	.string "ως μαθητή σου.$"

gText_ApprenticeRejectTeaching15::
	.string "Ω;\n"
	.string "Τι θα μπορούσε να σε κάνει να αρνηθείς;\p"
	.string "Ζητώ συγγνώμη που αμφέβαλα για\n"
	.string "την ταυτότητά σου.\p"
	.string "Δέξου τη συγγνώμη μου και\n"
	.string "δέξου με ως μαθητή σου.$"

gText_ApprenticeWhichLevelMode15::
	.string "Όντως με δέχεσαι;\n"
	.string "Δεν θέλω να το γιορτάσω πρόωρα.\p"
	.string "Αν είναι αλήθεια, συγγνώμη.\n"
	.string "Αλλά τώρα, θέλω τη συμβουλή σου.\p"
	.string "Αν έμπαινα στο BATTLE TOWER,\n"
	.string "τι θα μου άξιζε;\l"
	.string "Level 50 ή Open Level;$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1};\n"
	.string "Το εννοείς;\p"
	.string "Καταλαβαίνω. Αν είναι έτσι, εντάξει.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Ξέρω ότι γίνομαι ενοχλητικός/ή,\n"
	.string "αλλά χαίρομαι που με δέχτηκες.\p"
	.string "Ας ξανασυναντηθούμε!$"

gText_ApprenticeWhatHeldItem0::
	.string "Αχ... Σνιφ...\n"
	.string "Ω, {PLAYER}!\p"
	.string "Έχω βρεθεί σε ένα τρομερό δίλημμα\n"
	.string "και δεν μπορώ να αποφασίσω.\p"
	.string "Δεν ξέρω τι αντικείμενο πρέπει να\n"
	.string "δώσω στο {STR_VAR_1} μου.\p"
	.string "Πες μου σε παρακαλώ, {PLAYER}.\n"
	.string "Τι θα έπρεπε να κρατάει;$"

gText_ApprenticeHoldNothing0::
	.string "Αλήθεια; Δεν πρέπει το\n"
	.string "{STR_VAR_1} μου να κρατάει τίποτα;$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Ω, εντάξει! Χαίρομαι που λύθηκε!\n"
	.string "Τέλεια! Φανταστικά! Αουυού!\p"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeThanksHeldItem0::
	.string "Ω, χαίρομαι τόσο...\n"
	.string "Νομίζω πως έχω αυτό το {STR_VAR_1}.\p"
	.string "Χαίρομαι που λύθηκε το θέμα!\n"
	.string "Τέλεια! Φανταστικά! Αουυού!\p"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Ουάαα! Μη μου το χαλάς!\p"
	.string "Αυτό το {STR_VAR_1} μου το είχαν\n"
	.string "ξαναπροτείνει, σνιφ...\p"
	.string "Ή μήπως εννοείς να μην κρατάει\n"
	.string "τίποτα το {STR_VAR_2} μου;$"

gText_ApprenticeWhatHeldItem1::
	.string "Γιούπι! {PLAYER}, εσύ είσαι!\n"
	.string "Τέλεια! Ήθελα να σε ρωτήσω κάτι!\p"
	.string "Δίνεις αντικείμενα στα POKéMON σου;\n"
	.string "Θέλω να δώσω και στα δικά μου...\p"
	.string "Ποιο αντικείμενο θα ήταν καλό\n"
	.string "για το {STR_VAR_1};\p"
	.string "Εσύ τι λες;$"

gText_ApprenticeHoldNothing1::
	.string "Ε; Εννοείς ότι το {STR_VAR_1}\n"
	.string "δεν χρειάζεται να κρατάει τίποτα;$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Ω, κατάλαβα! Αυτό θα κάνω!\n"
	.string "Ευχαριστώ που με έμαθες!$"

gText_ApprenticeThanksHeldItem1::
	.string "Ω, ποπώ! Ένα {STR_VAR_1}, ε;\n"
	.string "Εντάξει, αυτό θα κάνω!\p"
	.string "Ευχαριστώ που με έμαθες!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ω, εμμ, όχι, δεν εννοούσα αυτό.\n"
	.string "Θέλω να μάθω για ένα αντικείμενο\l"
	.string "διαφορετικό από αυτά που ξέρω.\p"
	.string "Ή εννοείς ότι το POKéMON μου δεν\n"
	.string "πρέπει να κρατάει τίποτα πάλι;$"

gText_ApprenticeWhatHeldItem2::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Είναι για το {STR_VAR_1} μου...\p"
	.string "Θέλω να του δώσω ένα καλό item.\n"
	.string "Τι θα του ταίριαζε;$"

gText_ApprenticeHoldNothing2::
	.string "Ω, οπότε το {STR_VAR_1} μου δεν\n"
	.string "χρειάζεται να κρατάει τίποτα;$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Εντάξει, το έπιασα!\n"
	.string "Τα λέμε ξανά!$"

gText_ApprenticeThanksHeldItem2::
	.string "Ω, το αντικείμενο {STR_VAR_1};\n"
	.string "Κατάλαβα!\p"
	.string "Θα βάλω τα δυνατά μου να το βρω!\n"
	.string "Τα λέμε ξανά!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Κάποιος μου έχει πει ήδη για\n"
	.string "το {STR_VAR_1}.\p"
	.string "Θέλω το POKéMON μου να κρατάει\n"
	.string "ένα διαφορετικό αντικείμενο.\p"
	.string "Ή μήπως νομίζεις ότι το {STR_VAR_2}\n"
	.string "δεν πρέπει να κρατάει τίποτα;$"

gText_ApprenticeWhatHeldItem3::
	.string "Γεια σου, {PLAYER}...\n"
	.string "Συγγνώμη που σε ενοχλώ, αλλά ήθελα\l"
	.string "να σε ρωτήσω και κάτι άλλο.\p"
	.string "Δεν νομίζω ότι είμαι αρκετά καλός/ή\n"
	.string "να νικήσω μόνος/η μου, γι' αυτό\l"
	.string "σκέφτομαι να δώσω στο {STR_VAR_1}\l"
	.string "μου να κρατάει ένα αντικείμενο.\p"
	.string "Αλλά δεν ξέρω τι θα ήταν καλό.\p"
	.string "{PLAYER}, σε παρακαλώ, μπορείς να\n"
	.string "αποφασίσεις εσύ για μένα;$"

gText_ApprenticeHoldNothing3::
	.string "Ένα POKéMON κάποιου σαν εμένα θα\n"
	.string "ήταν καλύτερα χωρίς αντικείμενο;$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Καταλαβαίνω...\n"
	.string "Λες ότι δεν πρέπει να βασίζομαι\n"
	.string "σε αντικείμενα. Θα το παλέψω!\p"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeThanksHeldItem3::
	.string "Το αντικείμενο {STR_VAR_1}, οκ.\n"
	.string "Δεν ξέρω αν μπορώ να το βρω...\l"
	.string "Όχι! Θα κάνω τα πάντα να το βρω!\p"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Ω, μα...\n"
	.string "Νομίζω πως το έχω ξανακούσει...\p"
	.string "Μήπως φταίει που δεν χρησιμοποίησα\n"
	.string "σωστά το {STR_VAR_1};\p"
	.string "Ή εννοείς ότι δεν πρέπει να δώσω\n"
	.string "τίποτα στο {STR_VAR_2} μου;$"

gText_ApprenticeWhatHeldItem4::
	.string "Ω, {PLAYER}.\n"
	.string "Ήθελα να σε ρωτήσω κάτι.\p"
	.string "Ξέρεις που διάλεξες ποιο POKéMON\n"
	.string "θα έπρεπε να έχω;\p"
	.string "Αλλά δεν σε ρώτησα ποτέ τι\n"
	.string "αντικείμενο θα πρέπει να κρατάει.\p"
	.string "Μιας και μου έδωσες συμβουλή,\n"
	.string "τι λες να το πάμε ως το τέλος;\p"
	.string "Τι θα ήταν καλό; Θέλω το {STR_VAR_1}\n"
	.string "μου να κρατάει κάτι.$"

gText_ApprenticeHoldNothing4::
	.string "Ω! Οπότε το {STR_VAR_1} μου θα\n"
	.string "κάνει ό,τι μπορεί με άδεια χέρια;$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Αν νομίζεις ότι είναι το καλύτερο,\n"
	.string "αυτό θα κάνω.\p"
	.string "Ξέροντας ότι εσύ αποφάσισες,\n"
	.string "{PLAYER}, δεν θα στεναχωρηθώ και\l"
	.string "τόσο αν χάσω.\p"
	.string "Θα σε ξαναρωτήσω για συμβουλές.\n"
	.string "Γεια!$"

gText_ApprenticeThanksHeldItem4::
	.string "Το αντικείμενο {STR_VAR_1}, ε;\n"
	.string "Όχι κακό. Θα το χρησιμοποιήσω!\p"
	.string "Ξέροντας ότι εσύ αποφάσισες,\n"
	.string "{PLAYER}, δεν θα στεναχωρηθώ και\l"
	.string "τόσο αν χάσω.\p"
	.string "Θα σε ξαναρωτήσω για συμβουλές.\n"
	.string "Γεια!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Ε; Τι λες;\n"
	.string "Μου είχες πει για το {STR_VAR_1}\n"
	.string "ήδη από πριν.\p"
	.string "Ή εννοείς ότι το {STR_VAR_2} μου\n"
	.string "θα κάνει ό,τι μπορεί με άδεια χέρια;$"

gText_ApprenticeWhatHeldItem5::
	.string "Γεια σου, {PLAYER}!\p"
	.string "Είμαστε πολυάσχολοι, αλλά φαίνεται\n"
	.string "να συναντιόμαστε συχνά ούτως ή άλλως!\p"
	.string "Σήμερα έχω περπάτημα, καθάρισμα\n"
	.string "και βούρτσισμα.\p"
	.string "Δεν είχα καν χρόνο να αγοράσω κάτι\n"
	.string "για το αγαπημένο μου {STR_VAR_1}.\p"
	.string "Δεν έχω καθόλου χρόνο, οπότε τι λες\n"
	.string "να με συμβουλέψεις για το τι πρέπει\l"
	.string "να κρατάει το {STR_VAR_1} μου;$"

gText_ApprenticeHoldNothing5::
	.string "Ω, οπότε επειδή είμαι πολυάσχολος,\n"
	.string "λες ότι το {STR_VAR_1} δεν θέλει κάτι;$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Εντάξει, το 'πιασα.\n"
	.string "Δεν θα χρειαστώ καθόλου χρόνο.\p"
	.string "Ευχαριστώ για σήμερα!\n"
	.string "Τα λέμε εκεί έξω!$"

gText_ApprenticeThanksHeldItem5::
	.string "Εντάξει, το 'πιασα.\n"
	.string "Θα βρω χρόνο κάπως και θα βρω\l"
	.string "το {STR_VAR_1} που πρότεινες.\p"
	.string "Χαίρομαι που βρήκα καλό μέντορα.\n"
	.string "Ευχαριστώ! Τα λέμε εκεί έξω!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Ε; Ξέρω ήδη για αυτό το {STR_VAR_1}.\p"
	.string "Ω, σωστά, κατάλαβα.\n"
	.string "Οπότε μιας και είμαι πολυάσχολος,\n"
	.string "λες ότι το {STR_VAR_2} δεν θέλει κάτι;$"

gText_ApprenticeWhatHeldItem6::
	.string "Γεια σου, {PLAYER}! Εγώ είμαι!\n"
	.string "Χρειάζομαι τις γνώσεις σου πάλι.\l"
	.string "Σε παρακαλώ, θέλω τη συμβουλή σου!\p"
	.string "Τυμπανοκρουσίες, παρακαλώ!\n"
	.string "Η ερώτησή μου είναι...\p"
	.string "Αν ήθελα να δώσω στο {STR_VAR_1}\n"
	.string "μου ένα item, ποιο θα ήταν;$"

gText_ApprenticeHoldNothing6::
	.string "Αλήθεια; Το {STR_VAR_1} μου δεν\n"
	.string "χρειάζεται item, αυτό λες;$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Εντάξει, αυτό θα κάνω!\p"
	.string "Νομίζω αυτά ήθελα να σε ρωτήσω\n"
	.string "για σήμερα.\p"
	.string "Ας βρεθούμε πάλι εδώ, εντάξει;\n"
	.string "Ευχαριστώ!$"

gText_ApprenticeThanksHeldItem6::
	.string "Α-χα! Ένα {STR_VAR_1}.\n"
	.string "Τι cool επιλογή!\l"
	.string "Θα το δοκιμάσω οπωσδήποτε!\p"
	.string "Νομίζω αυτά ήθελα να σε ρωτήσω\n"
	.string "για σήμερα.\p"
	.string "Ας βρεθούμε πάλι εδώ, εντάξει;\n"
	.string "Ευχαριστώ!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Αχαχαχα! Τι αστείο!\n"
	.string "Μου είχες ξαναπεί για αυτό το\n"
	.string "πριν!\p"
	.string "Είσαι καλά, {PLAYER};\p"
	.string "Ω, στάσου! Το {STR_VAR_2} μου δεν\n"
	.string "χρειάζεται item, αυτό λες;$"

gText_ApprenticeWhatHeldItem7::
	.string "Γεια σου, {PLAYER}. Ελπίζω να είσαι\n"
	.string "καλά.\p"
	.string "Θα μπορούσα να ζητήσω τη συμβουλή\n"
	.string "σου;\p"
	.string "Σε μια πρόσφατη μάχη, ο αντίπαλος\n"
	.string "φάνηκε να έχει δώσει ένα item στο\l"
	.string "POKéMON του.\p"
	.string "Σαν αποτέλεσμα, ηττήθηκα...\p"
	.string "Δεν θέλω να μείνω πίσω.\n"
	.string "Θα ήθελα να δώσω και στο δικό μου\l"
	.string "{STR_VAR_1} ένα αντικείμενο.\p"
	.string "Θα χαιρόμουν αν αποφάσιζες εσύ\n"
	.string "τι θα ήταν σωστό για το POKéMON μου...$"

gText_ApprenticeHoldNothing7::
	.string "Με άλλα λόγια... το POKéMON μου\n"
	.string "δεν χρειάζεται να κρατάει item;$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Το κατάλαβα απόλυτα τώρα!\n"
	.string "Θα συνεχίσω να προσπαθώ έτσι.\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Ελπίζω να σε ξανασυμβουλευτώ.\l"
	.string "Να προσέχεις!$"

gText_ApprenticeThanksHeldItem7::
	.string "Ένα {STR_VAR_1} λοιπόν!\n"
	.string "Θα το παραγγείλω αμέσως.\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Ελπίζω να σε ξανασυμβουλευτώ.\l"
	.string "Να προσέχεις!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Μου το έχεις ήδη πει αυτό,\n"
	.string "και το έχω ήδη.\p"
	.string "Ή μήπως λες... ότι το POKéMON μου\n"
	.string "δεν χρειάζεται να κρατάει item;$"

gText_ApprenticeWhatHeldItem8::
	.string "Εκ! {PLAYER}!\n"
	.string "Χαίρομαι τόσο πολύ που σε βλέπω!\p"
	.string "Ωωω! Υπάρχει κάτι που έπρεπε\n"
	.string "οπωσδήποτε να σε ρωτήσω, {PLAYER}!\p"
	.string "Σε παρακαλώ, διάλεξε τι πρέπει να\n"
	.string "κρατάει το {STR_VAR_1} μου!$"

gText_ApprenticeHoldNothing8::
	.string "Ω, πω! Δεν την περίμενα αυτή την\n"
	.string "απάντηση! Οπότε δεν χρειάζεται;$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Κατάλαβα απόλυτα!\n"
	.string "Θα συνεχίσω χωρίς αντικείμενο!\p"
	.string "Ελπίζω να δεχτείς να με μάθεις\n"
	.string "κι άλλα κάποια άλλη στιγμή.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Αυτό θα βάλω!\p"
	.string "Εμμ... λες, {PLAYER}, να βάζεις\n"
	.string "κι εσύ αυτό στα POKéMON σου;\p"
	.string "Θα το πάρω οπωσδήποτε!\n"
	.string "Ελπίζω να δεχτείς να με μάθεις\n"
	.string "κι άλλα κάποια άλλη στιγμή.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Ω; Μου είχες προτείνει αυτό το\n"
	.string "{STR_VAR_1} και πριν.\p"
	.string "Είναι όντως το καλύτερο;\n"
	.string "Ή μήπως εννοείς ότι το {STR_VAR_2}\n"
	.string "δεν χρειάζεται να κρατάει τίποτα;$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "Maestro μου, {PLAYER}!\p"
	.string "Θέλω τη συμβουλή σου για\n"
	.string "POKéMON εργαλεία.\p"
	.string "Τι νομίζεις ότι θα ήταν καλό για\n"
	.string "το {STR_VAR_1} μου να κρατάει;\p"
	.string "Μη ντρέπεσαι τώρα.\n"
	.string "Πες το χωρίς φόβο!$"

gText_ApprenticeHoldNothing9::
	.string "Ω; Οπότε λες ότι το {STR_VAR_1}\n"
	.string "κερδίζει και χωρίς αντικείμενο;$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno!\n"
	.string "Θα δώσω τον καλύτερο εαυτό μου!\p"
	.string "Εντάξει, ευχαριστώ, όπως πάντα!\n"
	.string "Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Α-χα, ένα {STR_VAR_1} λοιπόν;\n"
	.string "Si, bueno!\l"
	.string "Θα πάω να βρω ένα, έτσι απλά!\p"
	.string "Εντάξει, ευχαριστώ, όπως πάντα!\n"
	.string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Όχι, όχι! Μου το είχες ξαναπεί\n"
	.string "για αυτό το {STR_VAR_1}.\p"
	.string "Ω, στάσου ένα λεπτό...\n"
	.string "Οπότε λες ότι το {STR_VAR_2} μου\n"
	.string "κερδίζει και χωρίς αντικείμενο;$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}, συνέβη κάτι\n"
	.string "απίστευτο!\p"
	.string "Ξύπνησα το πρωί και τα POKéMON μου\n"
	.string "είχαν 10 NUGGETS!\p"
	.string "Φυσικά και λέω ψέματα!\n"
	.string "Ουαχαχαχα!\p"
	.string "Αυτό όμως δεν είναι ψέμα.\n"
	.string "Δεν είμαι πολύ καλός στο να\n"
	.string "διαλέγω items για τα POKéMON.\p"
	.string "Οπότε, τι λες να διαλέξεις εσύ\n"
	.string "τι θα κρατάει το {STR_VAR_1}, master;$"

gText_ApprenticeHoldNothing10::
	.string "Τι σημαίνει αυτό;\n"
	.string "Να μην κρατάει τίποτα;$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Οκ, άρα να μην κρατάει τίποτα.\n"
	.string "Τότε καλύτερα να του πάρω κάτι!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ, master!\n"
	.string "Ελπίζω να συνεχίσεις να με μαθαίνεις!$"

gText_ApprenticeThanksHeldItem10::
	.string "Οκ, άρα ένα {STR_VAR_1}!\n"
	.string "Θα του δώσω οτιδήποτε άλλο!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ, master!\n"
	.string "Ελπίζω να συνεχίσεις να με μαθαίνεις!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Εμμ, μου το είχες ξαναπεί αυτό,\n"
	.string "έτσι δεν είναι;\p"
	.string "Δεν υπάρχει κάτι άλλο;\p"
	.string "Ή εννοείς να μην βάλω τίποτα\n"
	.string "στο {STR_VAR_2} μου;$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y!\n"
	.string "Που σημαίνει ahoy!\p"
	.string "Ο SAILOR που ραπάρει είμαι εγώ!\n"
	.string "Και μια ερώτηση σου φέρνω εδώ!\p"
	.string "Είναι για αντικείμενο,\n"
	.string "που θέλει συμβουλή!\p"
	.string "Το {STR_VAR_1} μου θέλει ένα item,\n"
	.string "ποιο να 'ναι αυτό; Πες μου εσύ!$"

gText_ApprenticeHoldNothing11::
	.string "Αλήθεια λες;\n"
	.string "Το {STR_VAR_1} μου δεν θέλει\l"
	.string "τίποτα να κρατάει;$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Οκ, σε άκουσα, να είσαι σίγουρος!\n"
	.string "Χωρίς τίποτα θα πάει και το δικό μου!\p"
	.string "Αν χρειαστώ ποτέ συμβουλή,\n"
	.string "{PLAYER}, θα σε ακούσω πολύ!$"

gText_ApprenticeThanksHeldItem11::
	.string "Οκ, ένα {STR_VAR_1},\n"
	.string "αυτό θα χρησιμοποιήσω.\l"
	.string "Ήξερα ότι έπρεπε να σε ρωτήσω!\p"
	.string "Αν χρειαστώ ποτέ συμβουλή,\n"
	.string "{PLAYER}, θα σε ακούσω πολύ!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Οκ, ένα {STR_VAR_1} λες;\n"
	.string "Μου το είπες και τις προάλλες.\l"
	.string "Θέλω μια νέα ιδέα, άλλες συμβουλές.\p"
	.string "Ή, τι, είναι αλήθεια;\n"
	.string "Το POKéMON μου δεν θέλει\l"
	.string "τίποτα στα χέρια;$"

gText_ApprenticeWhatHeldItem12::
	.string "Ε, {PLAYER}!\n"
	.string "Σε βρήκα πάλι σήμερα!\p"
	.string "Τι να κάνω; Να σε ρωτήσω;\n"
	.string "Γιατί όχι; Ήδη σου μιλάω!\p"
	.string "{PLAYER}, με βαρέθηκες;\n"
	.string "Μπα, αποκλείεται, δεν μπορεί.\p"
	.string "Θα με ακούσεις;\n"
	.string "Ψάχνω για συμβουλή--γι' αυτό\l"
	.string "σου μιλάω.\p"
	.string "Είναι για ένα item για το\n"
	.string "{STR_VAR_1} μου που να είναι καλό.\l"
	.string "Η αναποφασιστικότητα με τρώει.$"

gText_ApprenticeHoldNothing12::
	.string "Το {STR_VAR_1} μου δεν θέλει τίποτα;\n"
	.string "Δεν θέλει να κρατάει τίποτα;$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Αν το τίποτα είναι το καλύτερο,\n"
	.string "θα κάνω αυτό που λες!\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις.\p"
	.string "Θα σε ξαναδώ, έξυπνε φίλε μου!$"

gText_ApprenticeThanksHeldItem12::
	.string "Αν το {STR_VAR_1} είναι το καλύτερο,\n"
	.string "θα κάνω αυτό που λες!\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις.\p"
	.string "Θα σε ξαναδώ, έξυπνε φίλε μου!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Δεν έχω ξανακούσει για αυτό το\n"
	.string "{STR_VAR_1} πριν;\l"
	.string "Είμαι σίγουρος, αυτό είναι βέβαιο!\p"
	.string "Χρειάζομαι κάτι νέο!\n"
	.string "Ή, το {STR_VAR_2} μου δεν θέλει τίποτα;\l"
	.string "Δεν θέλει να κρατάει τίποτα;$"

gText_ApprenticeWhatHeldItem13::
	.string "Γκουάα! Άουτς! {PLAYER}, έσπασα\n"
	.string "το χέρι μου! Μην το αγγίζεις!\p"
	.string "Μάλλον το έσπασα ενώ δοκίμαζα\n"
	.string "items με την ομάδα των POKéMON\l"
	.string "μου.\p"
	.string "Έτσι όπως είναι τα πράγματα,\n"
	.string "πρέπει να αποφασίσεις εσύ.\p"
	.string "{PLAYER}, τι νομίζεις ότι θα ήταν\n"
	.string "καλό να κρατάει το {STR_VAR_1};$"

gText_ApprenticeHoldNothing13::
	.string "Άουτς...\p"
	.string "Οπότε η πρότασή σου είναι το\n"
	.string "{STR_VAR_1} μου να μην κρατάει τίποτα;$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Χμμ, εντάξει. Αυτό θα είναι πιο\n"
	.string "εύκολο για μένα τώρα.\p"
	.string "Ελπίζω να συνεχίσω να σου ζητάω\n"
	.string "βοήθεια έτσι.$"

gText_ApprenticeThanksHeldItem13::
	.string "Χμμ, εντάξει. Ένα {STR_VAR_1}.\n"
	.string "Το χέρι του POKéMON είναι οκ,\n"
	.string "οπότε θα του το δώσω αμέσως.\p"
	.string "Ελπίζω να συνεχίσω να σου ζητάω\n"
	.string "βοήθεια έτσι.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Όχι, όχι, μου είχες ξαναπεί για\n"
	.string "αυτό το {STR_VAR_1}, θυμάσαι;\p"
	.string "Τι λες να μου πεις κάτι ακόμα\n"
	.string "καλύτερο;\p"
	.string "Ω, στάσου ένα λεπτό.\n"
	.string "Οπότε η πρότασή σου είναι το\n"
	.string "{STR_VAR_2} μου να μην κρατάει τίποτα;$"

gText_ApprenticeWhatHeldItem14::
	.string "Ε... εμμ...\n"
	.string "{PLAYER}...\p"
	.string "Σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Τα POKéMON μου δεν έχουν τίποτα.\p"
	.string "Ντρέπομαι πολύ γι' αυτό, αλλά\n"
	.string "πραγματικά θέλω τη συμβουλή σου.\p"
	.string "Δεν ξέρω τι item θα έκανε το\n"
	.string "{STR_VAR_1} μου δυνατό.\p"
	.string "{PLAYER}, τι νομίζεις ότι θα ήταν\n"
	.string "καλό;$"

gText_ApprenticeHoldNothing14::
	.string "Ω... Οπότε, νομίζεις πως θα ήταν\n"
	.string "καλύτερα χωρίς item το {STR_VAR_1};$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Ω... Εντάξει!\n"
	.string "Θα πάω χωρίς αντικείμενο.\p"
	.string "Αυτό όμως με αγχώνει.\n"
	.string "Δεν θα είναι πολύ cool;\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Αν ξαναβρεθούμε, ελπίζω να είσαι\l"
	.string "το ίδιο εξυπηρετικός/ή.$"

gText_ApprenticeThanksHeldItem14::
	.string "Ω... Εντάξει!\n"
	.string "Θα του δώσω το {STR_VAR_1}.\p"
	.string "Αυτό όμως με αγχώνει.\n"
	.string "Δεν θα είναι πολύ cool;\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Αν ξαναβρεθούμε, ελπίζω να είσαι\l"
	.string "το ίδιο εξυπηρετικός/ή.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "Μ-μα το έχω ξανακούσει αυτό.\p"
	.string "Μη με διώχνεις έτσι, σε παρακαλώ!\n"
	.string "Δεν αντέχω τόση ταπείνωση.\p"
	.string "Ω... Μήπως βιάζομαι;\n"
	.string "Μήπως νομίζεις πως θα ήταν καλύτερα\n"
	.string "χωρίς item το {STR_VAR_2};$"

gText_ApprenticeWhatHeldItem15::
	.string "Χμμ; Φαίνεσαι να είσαι ο {PLAYER}...\n"
	.string "Αλλά είσαι όντως; Μήπως έχεις δίδυμο;\p"
	.string "Ω, όχι, μην ανησυχείς!\n"
	.string "Αν είσαι όντως ο {PLAYER}, σε\l"
	.string "παρακαλώ ξέχασε την αγένειά μου.\p"
	.string "Αυτό που θα ήθελα είναι λίγο ακόμα\n"
	.string "από την ωραία συμβουλή σου.\p"
	.string "Έχω εδώ το {STR_VAR_1} μου και θέλω\n"
	.string "να του δώσω ένα βολικό item.\p"
	.string "Τι θα του άξιζε;$"

gText_ApprenticeHoldNothing15::
	.string "Είναι καλύτερα χωρίς τίποτα;\n"
	.string "Το εννοείς;$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Καταλαβαίνω. Αν είναι έτσι, οκ.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Ας ξανασυναντηθούμε!$"

gText_ApprenticeThanksHeldItem15::
	.string "Ένα {STR_VAR_1};\n"
	.string "Το εννοείς;\p"
	.string "Καταλαβαίνω. Αν είναι έτσι, οκ.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Ελπίζω το POKéMON μου να μπορέσει\n"
	.string "να το χρησιμοποιήσει σωστά.\p"
	.string "Ας ξανασυναντηθούμε!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Όχι, όχι, στάσου ένα λεπτό.\n"
	.string "Νομίζω πως μου το είπες πριν.\p"
	.string "Θα ήθελα να μου προτείνεις\n"
	.string "κάτι διαφορετικό αυτή τη φορά.\p"
	.string "Μήπως εννοείς ότι το {STR_VAR_2}\n"
	.string "μου δεν πρέπει να κρατάει τίποτα;\l"
	.string "Το εννοείς;$"

gText_ApprenticeWhichMonFirst0::
	.string "Ουάα, {PLAYER}!\n"
	.string "Έχω ένα δίλημμα, σνιφ...\p"
	.string "Θέλω να αρχίσω να μάχομαι με άλλους,\n"
	.string "αλλά δεν ξέρω τι να κάνω.\p"
	.string "Πώς πρέπει να βάλω τα POKéMON μου\n"
	.string "ώστε να είναι όσο πιο δυνατά γίνεται;\p"
	.string "Πες μου σε παρακαλώ, {PLAYER}.\n"
	.string "Αν ήσουν εσύ, ποιο από αυτά τα\l"
	.string "POKéMON θα έστελνες πρώτο;$"

gText_ApprenticeMonFirstThanks0::
	.string "Το {STR_VAR_1} μου να βγει πρώτο;\n"
	.string "Ουάαααα!\p"
	.string "Ω! Συγγνώμη!\n"
	.string "Με έκανες τόσο χαρούμενο/η που\n"
	.string "διάλεξες το πρώτο μου POKéMON,\l"
	.string "και με έπιασαν τα κλάματα...\p"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeWhichMonFirst1::
	.string "Γιούπι! Είναι {PLAYER}!\n"
	.string "Τέλεια! Ήθελα να σε ρωτήσω κάτι!\p"
	.string "Εμμ, από τα POKéMON μου, ποιο\n"
	.string "νομίζεις ότι πρέπει να βγει πρώτο;$"

gText_ApprenticeMonFirstThanks1::
	.string "Το {STR_VAR_1} μου; Σωστά.\n"
	.string "Εντάξει, αυτό θα κάνω!\p"
	.string "Ευχαριστώ που με έμαθες!$"

gText_ApprenticeWhichMonFirst2::
	.string "Γεια σου, {PLAYER}!\p"
	.string "Νομίζω πως στη μάχη είναι πολύ\n"
	.string "σημαντικό ποιο POKéMON βγαίνει πρώτο.\p"
	.string "Από τα POKéMON που έχω, ποιο\n"
	.string "θα ήταν καλό να στείλω πρώτο;$"

gText_ApprenticeMonFirstThanks2::
	.string "Το {STR_VAR_1} μου πρώτο;\n"
	.string "Εντάξει, το έπιασα!\p"
	.string "Τα λέμε ξανά!$"

gText_ApprenticeWhichMonFirst3::
	.string "Γεια σου, {PLAYER}...\n"
	.string "Συγγνώμη που σε ενοχλώ πάλι με\n"
	.string "άλλη μια ερώτηση.\p"
	.string "Έχω τόσο λίγη αυτοπεποίθηση, δεν\n"
	.string "ξέρω τι θα έκανα χωρίς εσένα.\p"
	.string "Μπορεί να είναι χάσιμο χρόνου να\n"
	.string "ανησυχώ γι' αυτό, αλλά δεν μπορώ\l"
	.string "να αποφασίσω κάτι...\p"
	.string "Ποιο από τα POKéMON μου πρέπει να\n"
	.string "στείλω πρώτο στη μάχη;$"

gText_ApprenticeMonFirstThanks3::
	.string "Το {STR_VAR_1} μου;\n"
	.string "Κατάλαβα!\p"
	.string "Δεν μπορώ να πιστέψω ότι μπαίνεις\n"
	.string "στον κόπο να μου απαντάς τόσο συχνά!\p"
	.string "Σε ευχαριστώ τόσο πολύ που μου\n"
	.string "μιλάς... Σε ευχαριστώ!$"

gText_ApprenticeWhichMonFirst4::
	.string "Ω, {PLAYER}! Εγώ είμαι!\n"
	.string "Χαίρομαι που σε βλέπω γιατί έχω\n"
	.string "ένα μικρό προβληματάκι.\p"
	.string "Δεν ξέρω πώς να βάλω τα POKéMON μου\n"
	.string "στη σειρά. Αποφασίζεις εσύ;\p"
	.string "Ω, δεν χρειάζεται να αποφασίσεις\n"
	.string "όλη την ομάδα τώρα.\p"
	.string "Τι λες να διαλέξεις μόνο το\n"
	.string "πρώτο POKéMON για μένα;$"

gText_ApprenticeMonFirstThanks4::
	.string "Το {STR_VAR_1} μου; Τέλεια!\p"
	.string "Ξέροντας ότι εσύ αποφάσισες,\n"
	.string "{PLAYER}, δεν θα στεναχωρηθώ και\l"
	.string "τόσο αν χάσω.\p"
	.string "Θα σε ξαναρωτήσω για συμβουλές.\n"
	.string "Γεια!$"

gText_ApprenticeWhichMonFirst5::
	.string "Γεια, δάσκαλε {PLAYER}!\n"
	.string "Είμαι πάλι πολυάσχολος σήμερα!\p"
	.string "Έχω ποδήλατο, ψώνια και\n"
	.string "σιγοτραγούδισμα.\p"
	.string "Δεν είχα καν χρόνο να αποφασίσω\n"
	.string "πώς να βάλω στη σειρά την ομάδα.\p"
	.string "Οπότε, τι λες να δεις την ομάδα;\n"
	.string "Ποιο πρέπει να βγει πρώτο;$"

gText_ApprenticeMonFirstThanks5::
	.string "Εντάξει, το 'πιασα.\n"
	.string "Έχω αρκετό χρόνο τουλάχιστον για\n"
	.string "να βάλω το {STR_VAR_1} στην αρχή!\p"
	.string "Ώπα, με περιμένει η κοπέλα μου!\n"
	.string "Ευχαριστώ! Τα λέμε εκεί έξω!$"

gText_ApprenticeWhichMonFirst6::
	.string "Γιούχου! Γεια σου, {PLAYER}!\n"
	.string "Πάντα κυκλοφορείς με σκληρό ύφος!\p"
	.string "Άκου, θέλω κάτι από εσένα πάλι!\n"
	.string "Είναι το συνηθισμένο!\p"
	.string "Τυμπανοκρουσίες, παρακαλώ!\n"
	.string "Η ερώτησή μου είναι για την ομάδα.\p"
	.string "Ποιο δικό μου POKéMON πρέπει να\n"
	.string "βγει πρώτο στη μάχη;$"

gText_ApprenticeMonFirstThanks6::
	.string "Χμχμ!\n"
	.string "Το {STR_VAR_1} μου, ε;\l"
	.string "Ευχαριστώ για την cool απάντηση!\p"
	.string "Νομίζω αυτά ήθελα να σε ρωτήσω\n"
	.string "για σήμερα.\p"
	.string "Ας βρεθούμε πάλι εδώ, εντάξει;\n"
	.string "Ευχαριστώ!$"

gText_ApprenticeWhichMonFirst7::
	.string "Σε ευχαριστώ πολύ που σταμάτησες\n"
	.string "να μου μιλήσεις, {PLAYER}.\p"
	.string "Ξέρω ότι εκμεταλλεύομαι την\n"
	.string "καλοσύνη σου, αλλά μπορώ να ρωτήσω;\p"
	.string "Θα ήθελα να αποφασίσεις τη σειρά\n"
	.string "της ομάδας των POKéMON μου.\p"
	.string "Θα με χαροποιούσε αν διάλεγες\n"
	.string "ποιο POKéMON θα έρθει πρώτο.$"

gText_ApprenticeMonFirstThanks7::
	.string "Το {STR_VAR_1} λοιπόν!\n"
	.string "Θα το βάλω πρώτο αμέσως!\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Ελπίζω να σε ξανασυμβουλευτώ.\l"
	.string "Να προσέχεις!$"

gText_ApprenticeWhichMonFirst8::
	.string "Εκ! {PLAYER}!\n"
	.string "Χαίρομαι τόσο πολύ που σε βλέπω!\p"
	.string "Τα POKéMON μου έγιναν πολύ πιο\n"
	.string "δυνατά!\p"
	.string "Αλλά δεν κερδίζω πάντα. Φαίνεται\n"
	.string "να εξαρτάται από το ποιο βγαίνει.\p"
	.string "{PLAYER}, σε παρακαλώ, βοήθησέ με!\p"
	.string "Σε παρακαλώ, διάλεξε ποιο POKéMON\n"
	.string "μου πρέπει να βγει πρώτο!$"

gText_ApprenticeMonFirstThanks8::
	.string "Αχ... Πλέω σε πελάγη ευτυχίας...\p"
	.string "Είναι σαν όνειρο να αποφασίζεις\n"
	.string "εσύ για μένα, {PLAYER}.\p"
	.string "Αλλά κατάλαβα απόλυτα!\n"
	.string "Θα βάλω το {STR_VAR_1} μου πρώτο!\p"
	.string "Ελπίζω να δεχτείς να με μάθεις\n"
	.string "κι άλλα κάποια άλλη στιγμή.$"

gText_ApprenticeWhichMonFirst9::
	.string "Γεια χαρά!\n"
	.string "Μέντορά μου, {PLAYER}!\l"
	.string "Δώσε μου τη σοφή συμβουλή σου!\p"
	.string "Έφτιαξα μια ομάδα από τρία\n"
	.string "POKéMON. Ως εδώ καλά.\p"
	.string "Αλλά η σειρά μάχης της ομάδας δεν\n"
	.string "έχει οριστεί ακόμα.\p"
	.string "Εδώ μπαίνεις εσύ, {PLAYER}!\n"
	.string "Διάλεξε ποιο POKéMON ξεκινάει!\p"
	.string "Μη ντρέπεσαι τώρα.\n"
	.string "Πες το χωρίς φόβο!$"

gText_ApprenticeMonFirstThanks9::
	.string "Α-χα, το {STR_VAR_1} μου ξεκινάει!\n"
	.string "ΟΚ, όλα καλά!\l"
	.string "Θα αλλάξω τη σειρά, έτσι απλά!\p"
	.string "Εντάξει, ευχαριστώ, όπως πάντα!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}, άκου!\n"
	.string "Είναι κρίση!\p"
	.string "Τα POKéMON μου, και τα τρία,\n"
	.string "μπαίνουν στη μάχη μαζί!\p"
	.string "Φυσικά αυτό είναι αδύνατο!\n"
	.string "Ουαχαχαχα!\p"
	.string "Αυτό όμως δεν είναι ψέμα.\n"
	.string "Δεν είμαι πολύ καλός στο να\n"
	.string "βάζω στη σειρά τα POKéMON.\p"
	.string "Οπότε, τι λες να διαλέξεις ποιο\n"
	.string "θα βγει πρώτο, master;$"

gText_ApprenticeMonFirstThanks10::
	.string "Οκ, το {STR_VAR_1} διάλεξες;\n"
	.string "Οποιοδήποτε άλλο θα έβαζα πρώτο!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ, master!\n"
	.string "Ελπίζω να συνεχίσεις να με μαθαίνεις!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y!\n"
	.string "Που σημαίνει ahoy!\p"
	.string "Ο SAILOR που ραπάρει είμαι εγώ!\n"
	.string "Μια ερώτηση σου φέρνω εδώ!\p"
	.string "Είναι ερώτηση για την ομάδα,\n"
	.string "που θέλει συμβουλή!\p"
	.string "Από αυτά εδώ, ποιο βγαίνει πρώτο\n"
	.string "στη μάχη; Πες μου εσύ!$"

gText_ApprenticeMonFirstThanks11::
	.string "Οκ, σε άκουσα, να είσαι σίγουρος!\n"
	.string "Θα τους αλλάξω σειρά αμέσως!\p"
	.string "Αν χρειαστώ ποτέ συμβουλή,\n"
	.string "{PLAYER}, θα σε ακούσω πολύ!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "Πώς είσαι;\p"
	.string "Τι να κάνω; Να σε ρωτήσω;\n"
	.string "Α-χα, έχω κάτι να ρωτήσω!\l"
	.string "Με ακούς;\l"
	.string "Με ακούς!\p"
	.string "Πρέπει να διαλέξεις ποιο\n"
	.string "POKéMON μου θα ξεκινήσει!\l"
	.string "Στη μάχη, εννοώ.$"

gText_ApprenticeMonFirstThanks12::
	.string "Το {STR_VAR_1} μου; Ναι!\n"
	.string "Αυτό θα γίνει, κανένα πρόβλημα!\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις.\p"
	.string "Θα σε ξαναδώ, έξυπνε φίλε μου!$"

gText_ApprenticeWhichMonFirst13::
	.string "...Ωχ... άουτς... {PLAYER}...\n"
	.string "Πόνεσε το στομάχι μου ξαφνικά...\p"
	.string "...Καλυτερεύει τώρα...\p"
	.string "Μάλλον αγχώθηκα πολύ σκεπτόμενος\n"
	.string "πώς να βάλω στη σειρά την ομάδα\l"
	.string "των POKéMON μου.\p"
	.string "Έτσι όπως είναι τα πράγματα,\n"
	.string "πρέπει να αποφασίσεις εσύ.\p"
	.string "{PLAYER}, ποιο POKéMON πρέπει να\n"
	.string "βγει πρώτο; Για να κερδίσω, εννοώ.$"

gText_ApprenticeMonFirstThanks13::
	.string "Χμμ, εντάξει.\n"
	.string "Το {STR_VAR_1} βγαίνει πρώτο.\p"
	.string "Θα φτιάξω τη σειρά έτσι μετά\n"
	.string "το βραδινό μου.\p"
	.string "Ελπίζω να συνεχίσω να σου ζητάω\n"
	.string "βοήθεια έτσι.$"

gText_ApprenticeWhichMonFirst14::
	.string "Ε... εμμ...\n"
	.string "{PLAYER}?\p"
	.string "Σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Με κάνεις να νιώθω άβολα.\p"
	.string "Εμμ...\n"
	.string "Θέλω πραγματικά τη συμβουλή σου.\p"
	.string "Ντρέπομαι που το λέω, αλλά\n"
	.string "διάλεξα την ομάδα των 3 POKéMON.\l"
	.string "Δεν μπορώ να βρω τη σειρά όμως.\p"
	.string "Ποιο POKéMON να στείλω πρώτο\n"
	.string "ώστε τουλάχιστον να φαίνομαι οκ;$"

gText_ApprenticeMonFirstThanks14::
	.string "Ω... Εντάξει!\n"
	.string "Θα ξεκινήσω με το {STR_VAR_1}.\p"
	.string "Ελπίζω να τα πάω καλά χωρίς\n"
	.string "να νιώσω άβολα.\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Αν ξαναβρεθούμε, ελπίζω να είσαι\l"
	.string "το ίδιο εξυπηρετικός/ή.$"

gText_ApprenticeWhichMonFirst15::
	.string "Χμμ; Φαίνεσαι να είσαι ο {PLAYER}...\n"
	.string "Αλλά είσαι όντως; Μήπως είσαι σωσίας;\p"
	.string "Ω, όχι, μην ανησυχείς!\n"
	.string "Αν είσαι όντως ο {PLAYER}, σε\l"
	.string "παρακαλώ ξέχασε την αγένειά μου.\p"
	.string "Αυτό που θα ήθελα είναι η συμβουλή σου.\p"
	.string "Έχω εδώ την ομάδα των POKéMON.\n"
	.string "Θα ήθελα να μου πεις ποιο\n"
	.string "πρέπει να βγει πρώτο στη μάχη.$"

gText_ApprenticeMonFirstThanks15::
	.string "Το {STR_VAR_1} μου...\n"
	.string "Μου κάνεις πλάκα;\p"
	.string "Καταλαβαίνω. Αν είναι έτσι, οκ.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Είμαι όπως με βλέπεις, αλλά θα\n"
	.string "δώσω τον καλύτερο εαυτό μου.\p"
	.string "Ας ξανασυναντηθούμε!$"

gText_ApprenticeWhichMon0::
	.string "Σνιφ...\n"
	.string "Ω, {PLAYER}!\p"
	.string "Τι τέλειος συγχρονισμός!\n"
	.string "Υπάρχει κάτι που δεν μπορώ να βρω...\p"
	.string "Δεν μπορώ να αποφασίσω ποιο\n"
	.string "POKéMON να χρησιμοποιήσω.\p"
	.string "Δεν μπορώ να διαλέξω ανάμεσα στο\n"
	.string "{STR_VAR_1} και στο {STR_VAR_2}...\p"
	.string "{PLAYER}, ποιο νομίζεις ότι θα μου\n"
	.string "δώσει μια ευκαιρία να νικήσω;$"

gText_ApprenticeMonThanks0::
	.string "Σνιφ... Ε... Κατάλαβα!\n"
	.string "Ω! Συγγνώμη!\l"
	.string "Με έκανες τόσο χαρούμενο/η, κλαίω...\p"
	.string "Θα βάλω τα δυνατά μου να πιάσω\n"
	.string "ένα {STR_VAR_1}!\p"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeWhichMon1::
	.string "Γιούπι! Είναι {PLAYER}!\n"
	.string "Ήρθες στην κατάλληλη στιγμή!\l"
	.string "Χρειάζομαι τη συμβουλή σου πάλι!\p"
	.string "Είμαι μπερδεμένος/η--να πάρω το\n"
	.string "{STR_VAR_1} ή το {STR_VAR_2}...\p"
	.string "Ποιο νομίζεις ότι πρέπει να έχω,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Ω, οπότε το {STR_VAR_1} είναι καλύτερο!\n"
	.string "Εντάξει, αυτό θα κάνω!\p"
	.string "Ευχαριστώ που με έμαθες!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, γεια σου!\n"
	.string "Έχω μια ερώτηση που ήθελα να κάνω.\p"
	.string "Έχω δίλημμα για το αν πρέπει να\n"
	.string "μάθω στο {STR_VAR_1} ή στο {STR_VAR_2}.\p"
	.string "Ποιο POKéMON νομίζεις ότι θα\n"
	.string "είναι πιο δυνατό;$"

gText_ApprenticeMonThanks2::
	.string "Το {STR_VAR_1} είναι η επιλογή σου;\n"
	.string "Εντάξει, το έπιασα!\p"
	.string "Θα πάω να πιάσω ένα δυνατό\n"
	.string "{STR_VAR_1} αμέσως!\p"
	.string "Τα λέμε ξανά!$"

gText_ApprenticeWhichMon3::
	.string "Γεια σου, {PLAYER}...\p"
	.string "Εμμ, μάλλον θα με έχεις ήδη ξεχάσει...\p"
	.string "...Αλλά δεν πειράζει αν μπορείς\n"
	.string "να μου δώσεις μια συμβουλή...\p"
	.string "Δεν μπορώ να αποφασίσω ποιο είδος\n"
	.string "POKéMON να εκπαιδεύσω...\p"
	.string "Είμαι ανάμεσα στο {STR_VAR_1}\n"
	.string "και στο {STR_VAR_2}, αλλά εκεί\l"
	.string "κόλλησα...\p"
	.string "{PLAYER}, μάλλον δεν θέλεις να σε\n"
	.string "ενοχλώ, αλλά σε παρακαλώ διάλεξε.$"

gText_ApprenticeMonThanks3::
	.string "Αλλά θα μου δώσει σημασία ένα\n"
	.string "άγριο {STR_VAR_1};\p"
	.string "Θα προσπαθήσω!\p"
	.string "Αλλά θα μπορέσω καν να το πιάσω;\n"
	.string "Όχι! Θα βάλω τα δυνατά μου!\p"
	.string "Σε ευχαριστώ!$"

gText_ApprenticeWhichMon4::
	.string "Ω, {PLAYER}! Χαίρομαι που σε βλέπω!\n"
	.string "Ήμουν έτοιμος να σε ψάξω!\p"
	.string "Μπορείς να διαλέξεις τι είδους\n"
	.string "POKéMON να χρησιμοποιήσω;\p"
	.string "Για παράδειγμα...\n"
	.string "Τι λες για το {STR_VAR_1}\n"
	.string "και το {STR_VAR_2};\p"
	.string "Ποιο από τα δύο πιστεύεις ότι\n"
	.string "είναι καλύτερο;$"

gText_ApprenticeMonThanks4::
	.string "Το {STR_VAR_1}; Τέλεια!\p"
	.string "Ξέροντας ότι εσύ αποφάσισες,\n"
	.string "{PLAYER}, δεν θα στεναχωρηθώ και\l"
	.string "τόσο αν χάσω.\p"
	.string "Θα σε ξαναρωτήσω για συμβουλές.\n"
	.string "Γεια!$"

gText_ApprenticeWhichMon5::
	.string "Α, ο {PLAYER}! Πώς πάει;\n"
	.string "Είμαι πάλι πολυάσχολος όπως πάντα!\p"
	.string "Θέλω να τα πάω καλά και με POKéMON,\n"
	.string "αλλά δεν έχω αποφασίσει ακόμα\n"
	.string "ποιο POKéMON να χρησιμοποιήσω.\p"
	.string "Ξέρεις πώς το {STR_VAR_1} δείχνει\n"
	.string "δυνατό; Αλλά και το {STR_VAR_2} είναι\l"
	.string "δύσκολο να το αγνοήσεις.\p"
	.string "{PLAYER}, δώσε μου τη συμβουλή σου!\n"
	.string "Ποιο θα ήταν καλό για μένα;$"

gText_ApprenticeMonThanks5::
	.string "Εντάξει, το 'πιασα.\n"
	.string "Θα βρω χρόνο κάπως και θα πιάσω\l"
	.string "το {STR_VAR_1} που μου πρότεινες.\p"
	.string "Χαίρομαι που βρήκα καλό μέντορα.\n"
	.string "Ευχαριστώ! Τα λέμε εκεί έξω!$"

gText_ApprenticeWhichMon6::
	.string "Ω!\n"
	.string "Γιούπι, είναι ο {PLAYER}!\p"
	.string "Δεν έχασα χρόνο να καυχηθώ στους\n"
	.string "φίλους μου που σε γνώρισα!\p"
	.string "Χρειάζομαι τις γνώσεις σου πάλι.\n"
	.string "Είναι κάτι εύκολο για εσένα!\p"
	.string "Τυμπανοκρουσίες, παρακαλώ!\n"
	.string "Η ερώτηση που έχω είναι...\p"
	.string "Αν επρόκειτο να εκπαιδεύσω ένα\n"
	.string "POKéMON ανάμεσα στο {STR_VAR_1}\l"
	.string "ή στο {STR_VAR_2}, ποιο θα ήταν;$"

gText_ApprenticeMonThanks6::
	.string "Αααχ!\n"
	.string "Το {STR_VAR_1}, ε;\l"
	.string "Ευχαριστώ για την cool απάντηση!\p"
	.string "Νομίζω αυτά ήθελα να σε ρωτήσω\n"
	.string "για σήμερα.\p"
	.string "Ας βρεθούμε πάλι εδώ, εντάξει;\n"
	.string "Ευχαριστώ!$"

gText_ApprenticeWhichMon7::
	.string "Ω, εσύ είσαι, {PLAYER};\n"
	.string "Χαίρομαι πολύ που σε ξαναβλέπω!\p"
	.string "Από τότε που έγινα μαθητής σου,\n"
	.string "η αυτοπεποίθησή μου ανθίζει.\p"
	.string "Νομίζω πως είμαι έτοιμος να έχω\n"
	.string "ένα δικό μου POKéMON!\p"
	.string "{PLAYER}, μπορώ να σε βάλω να\n"
	.string "διαλέξεις ποιο να εκπαιδεύσω;\p"
	.string "Οι επιλογές είναι το {STR_VAR_1}\n"
	.string "ή το {STR_VAR_2}...\l"
	.string "Ποιο POKéMON είναι για μένα;$"

gText_ApprenticeMonThanks7::
	.string "Ένα {STR_VAR_1} λοιπόν!\n"
	.string "Θα βρω ένα αμέσως!\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Ελπίζω να σε ξανασυμβουλευτώ.\l"
	.string "Να προσέχεις!$"

gText_ApprenticeWhichMon8::
	.string "Εκ! {PLAYER}! Σε ξαναβρήκα!\n"
	.string "Εγώ... είμαι πανευτυχής!\p"
	.string "Ω-ω-ω, ξέρω!\n"
	.string "Δεν πρέπει να χάσω την ευκαιρία!\p"
	.string "Μπορώ να σου ζητήσω μια χάρη;\n"
	.string "Διάλεξε ένα POKéMON για μένα!\p"
	.string "Σε παρακαλώ, ποιο θα ήταν καλύτερο,\n"
	.string "το {STR_VAR_1} ή το {STR_VAR_2};$"

gText_ApprenticeMonThanks8::
	.string "Ουάου! Αποφάσισες για μένα!\n"
	.string "Θα εκπαιδεύσω ένα {STR_VAR_1} όσο\l"
	.string "καλύτερα μπορώ.\p"
	.string "Ελπίζω να δεχτείς να με μάθεις\n"
	.string "κι άλλα κάποια άλλη στιγμή.$"

gText_ApprenticeWhichMon9::
	.string "Έι, έι!\n"
	.string "Μέντορά μου, {PLAYER}!\p"
	.string "Γεια, σε έψαχνα για λίγη ακόμα\n"
	.string "από τη σοφή συμβουλή σου!\p"
	.string "Ποιο POKéMON θα ήταν σωστό για\n"
	.string "μένα, το {STR_VAR_1} ή το {STR_VAR_2};\p"
	.string "Μη ντρέπεσαι τώρα.\n"
	.string "Πες το χωρίς φόβο!$"

gText_ApprenticeMonThanks9::
	.string "Α-χα, ένα {STR_VAR_1} λοιπόν!\n"
	.string "ΟΚ, όλα καλά!\l"
	.string "Θα πιάσω ένα σε μια BALL, τσακ!\p"
	.string "Εντάξει, ευχαριστώ, όπως πάντα!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}, άκου! Μεγάλα νέα!\n"
	.string "Έπιασα ένα POKéMON-φάντασμα!\p"
	.string "Φυσικά και λέω ψέματα!\n"
	.string "Ουαχαχαχα!\p"
	.string "Αυτό όμως δεν είναι ψέμα.\n"
	.string "Δεν είμαι πολύ καλός στο να\n"
	.string "πιάνω POKéMON.\p"
	.string "Οπότε, τι λες να διαλέξεις ποιο\n"
	.string "είδος POKéMON πρέπει να πιάσω,\l"
	.string "master;\p"
	.string "Ποιο θα ήταν καλύτερο;\n"
	.string "Το {STR_VAR_1} ή το {STR_VAR_2};$"

gText_ApprenticeMonThanks10::
	.string "Οκ, το {STR_VAR_1} διάλεξες;\n"
	.string "Θα πιάσω το άλλο είδος τότε!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ, master!\n"
	.string "Ελπίζω να συνεχίσεις να με μαθαίνεις!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y!\n"
	.string "Που σημαίνει ahoy!\p"
	.string "Ο SAILOR που ραπάρει είμαι εγώ!\n"
	.string "Σίγουρα με θυμάσαι, έτσι δεν είναι;\p"
	.string "Σήμερα, έχω μια ερώτηση για\n"
	.string "POKéMON που θέλει συμβουλή!\p"
	.string "Έχω την επιλογή ανάμεσα στο\n"
	.string "{STR_VAR_1} και στο {STR_VAR_2}.\l"
	.string "Ποιο είναι αυτό που πρέπει να πιάσω;$"

gText_ApprenticeMonThanks11::
	.string "Το {STR_VAR_1}, ε; Έι, έι!\n"
	.string "Θα πάω να πιάσω ένα αμέσως!\p"
	.string "Αν χρειαστώ ποτέ συμβουλή,\n"
	.string "{PLAYER}, θα σε ακούσω πολύ!$"

gText_ApprenticeWhichMon12::
	.string "Ω, πω πω, ο {PLAYER}!\p"
	.string "Τι να κάνω; Να πάρω συμβουλή;\n"
	.string "Γιατί όχι; Ήδη σου μιλάω!\p"
	.string "Πέρασε καιρός. Ας σπάσω τον\n"
	.string "πάγο. Ψάχνω και εγώ συμβουλή!\l"
	.string "Με ακούς;\l"
	.string "Με ακούς!\p"
	.string "Τα POKéMON μου--ποιο να πάρω;\n"
	.string "Είναι το {STR_VAR_1} ή το {STR_VAR_2}.\l"
	.string "Ποιο διαλέγεις;$"

gText_ApprenticeMonThanks12::
	.string "Αν αυτό το {STR_VAR_1} είναι το best,\n"
	.string "θα το κάνω όπως λες!\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις.\p"
	.string "Θα σε ξαναδώ, έξυπνε φίλε μου!$"

gText_ApprenticeWhichMon13::
	.string "Α, γεια, {PLAYER}...\n"
	.string "Έχω αυτόν τον φρικτό πονοκέφαλο...\p"
	.string "Μάλλον αγχώθηκα πολύ για το τι\n"
	.string "είδος POKéMON να εκπαιδεύσω.\p"
	.string "Έτσι όπως είναι τα πράγματα,\n"
	.string "πρέπει να αποφασίσεις εσύ.\p"
	.string "{PLAYER}, αν έπρεπε να διαλέξω\n"
	.string "ανάμεσα στο {STR_VAR_1} και στο\l"
	.string "{STR_VAR_2}, ποιο θα ήταν;$"

gText_ApprenticeMonThanks13::
	.string "Χμμ, ένα {STR_VAR_1}, εντάξει.\n"
	.string "Θα ψάξω για ένα όταν γίνω καλά.\p"
	.string "Ελπίζω να συνεχίσω να σου ζητάω\n"
	.string "βοήθεια έτσι.$"

gText_ApprenticeWhichMon14::
	.string "Ε... εμμ...\n"
	.string "{PLAYER}...;\p"
	.string "Σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Νιώθω όλο και πιο άβολα...\l"
	.string "Ε... εγώ... θέλω τη συμβουλή σου.\p"
	.string "Ντρέπομαι πολύ, αλλά δεν μπορώ\n"
	.string "να αποφασίσω ποιο POKéMON να πάρω.\p"
	.string "Αν οι επιλογές ήταν {STR_VAR_1} ή\n"
	.string "{STR_VAR_2}, ποιο θα ήταν καλύτερο;$"

gText_ApprenticeMonThanks14::
	.string "Ω... Εντάξει!\n"
	.string "Θα προσπαθήσω με ένα {STR_VAR_1}.\p"
	.string "Ελπίζω να τα πάω καλά χωρίς\n"
	.string "να νιώσω άβολα.\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Αν ξαναβρεθούμε, ελπίζω να είσαι\l"
	.string "το ίδιο εξυπηρετικός/ή.$"

gText_ApprenticeWhichMon15::
	.string "Χμμ; Φαίνεσαι να είσαι ο {PLAYER}...\n"
	.string "Αλλά είσαι όντως αληθινός;\p"
	.string "Όχι, αν είσαι αληθινός, οκ.\n"
	.string "Παρεμπιπτόντως, θα ήθελα να\n"
	.string "έχω τη σοφή συμβουλή σου.\p"
	.string "Είναι για το POKéMON που θα πάρω.\p"
	.string "Αν οι επιλογές είναι το {STR_VAR_1}\n"
	.string "και το {STR_VAR_2}, ποιο είναι πιο\l"
	.string "άξιο για μένα;$"

gText_ApprenticeMonThanks15::
	.string "Το {STR_VAR_1};\n"
	.string "Είσαι σίγουρος/η;\p"
	.string "Καταλαβαίνω. Αν είναι έτσι, οκ.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Ελπίζω να είναι κάτι που ακόμα\n"
	.string "και εγώ μπορώ να χειριστώ άνετα.\p"
	.string "Ας ξανασυναντηθούμε!$"

gText_ApprenticeWhichMove0::
	.string "Ουάααα! Ω, {PLAYER}!\n"
	.string "Σνιφ... Χικ...\p"
	.string "Έχω ένα δίλημμα!\n"
	.string "Δεν μπορώ να διαλέξω κίνηση για\n"
	.string "το {STR_VAR_1} μου...\p"
	.string "Σε παρακαλώ, {PLAYER}.\n"
	.string "Μπορείς να διαλέξεις για μένα;\p"
	.string "Για το {STR_VAR_1} μου, ποια κίνηση\n"
	.string "θα ήταν καλύτερη: {STR_VAR_2}\l"
	.string "ή {STR_VAR_3};$"

gText_ApprenticeMoveThanks0::
	.string "Το {STR_VAR_1};\n"
	.string "Ουάαααα!\p"
	.string "Ω! Συγγνώμη, {PLAYER}!\n"
	.string "Με έκανες τόσο χαρούμενο/η με την\n"
	.string "κίνηση, που κλαίω...\p"
	.string "Σνιφ...\n"
	.string "Σε ευχαριστώ πάρα πολύ!$"

gText_ApprenticeWhichMove1::
	.string "Γιούπι! Γεια, {PLAYER}!\n"
	.string "Θέλω τη συμβουλή σου πάλι!\p"
	.string "Θέλω να μάθω στο {STR_VAR_1} μου\n"
	.string "μια cool κίνηση.\p"
	.string "Μου αρέσουν οι κινήσεις\n"
	.string "{STR_VAR_2} ή {STR_VAR_3}.\l"
	.string "Ποια είναι η πρότασή σου;$"

gText_ApprenticeMoveThanks1::
	.string "Η {STR_VAR_1} είναι καλύτερη; Έτσι\n"
	.string "φαίνεται! Θα διαλέξω αυτήν!\p"
	.string "Αν ξανασυναντηθούμε, σε παρακαλώ\n"
	.string "μάθε μου και κάτι άλλο, δάσκαλε!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, γεια σου!\n"
	.string "Είναι για το {STR_VAR_1} μου, αλλά\l"
	.string "ανησυχώ για τις κινήσεις του.\p"
	.string "Βλέπεις, είναι οι {STR_VAR_2}\n"
	.string "και {STR_VAR_3}.\p"
	.string "Ποια είναι πιο δυνατή και καλή\n"
	.string "για το {STR_VAR_1} μου;$"

gText_ApprenticeMoveThanks2::
	.string "Το {STR_VAR_1} είναι η επιλογή σου;\n"
	.string "Εντάξει, το έπιασα!\p"
	.string "Θα πάω να μάθω το {STR_VAR_1} στο\n"
	.string "POKéMON μου αμέσως!\p"
	.string "Τα λέμε ξανά!$"

gText_ApprenticeWhichMove3::
	.string "Ωωω, {PLAYER}...\n"
	.string "Είμαι απελπισμένος, αλήθεια!\p"
	.string "Αποφάσισα να εκπαιδεύσω ένα\n"
	.string "POKéMON, αλλά τώρα δεν μπορώ καν\n"
	.string "να διαλέξω τι κίνηση να μάθει...\p"
	.string "Ξέρω ότι δεν σημαίνει τίποτα\n"
	.string "για εσένα, {PLAYER}.\p"
	.string "Αλλά σημαίνει πολλά για μένα...\p"
	.string "Σε παρακαλώ, {PLAYER}, διάλεξε\n"
	.string "μια κίνηση για το {STR_VAR_1} μου.\p"
	.string "Αν μπορείς να διαλέξεις ανάμεσα\n"
	.string "σε {STR_VAR_2} και {STR_VAR_3}...$"

gText_ApprenticeMoveThanks3::
	.string "Κατάλαβα!\p"
	.string "Αλλά θα θέλει καν να μάθει το\n"
	.string "{STR_VAR_1} για μένα...\l"
	.string "Όχι! Θα βάλω τα δυνατά μου!\p"
	.string "Σε ευχαριστώ!$"

gText_ApprenticeWhichMove4::
	.string "Ω, {PLAYER}!\n"
	.string "Ήλπιζα να σε δω κι εγώ!\p"
	.string "Αναρωτιόμουν ποια κίνηση θα ήταν\n"
	.string "κατάλληλη για το {STR_VAR_1} μου.\p"
	.string "Δεν μπορώ να αποφασίσω, οπότε\n"
	.string "αποφασίζεις εσύ για μένα;\p"
	.string "Για παράδειγμα... Τι λες για τις\n"
	.string "κινήσεις {STR_VAR_2} και {STR_VAR_3};\l"
	.string "Ποια θα ήταν καλύτερη;$"

gText_ApprenticeMoveThanks4::
	.string "Η {STR_VAR_1}; Τέλεια!\p"
	.string "Ξέροντας ότι εσύ αποφάσισες,\n"
	.string "{PLAYER}, δεν θα στεναχωρηθώ και\l"
	.string "τόσο αν χάσω.\p"
	.string "Θα σε ξαναρωτήσω για συμβουλές.\n"
	.string "Γεια!$"

gText_ApprenticeWhichMove5::
	.string "Πώς μπορεί να είναι τόσο γεμάτη η μέρα;\n"
	.string "Έι, ο {PLAYER}! Πώς πάει;\p"
	.string "Από το πρωί που ξύπνησα, έκανα\n"
	.string "τζόκινγκ, κολύμπι και μαγείρεμα!\p"
	.string "Δεν φαντάζεσαι πόσο τρέχω!\p"
	.string "Δεν μπορώ καν να αποφασίσω ποια\n"
	.string "κίνηση να μάθει το {STR_VAR_1} μου!\p"
	.string "Η {STR_VAR_2} φαίνεται καλή, ε;\n"
	.string "Αλλά και η {STR_VAR_3} είναι εντάξει.\p"
	.string "{PLAYER}, δώσε μου τη συμβουλή σου!\n"
	.string "Ποια κίνηση θα ήταν καλή για μένα;$"

gText_ApprenticeMoveThanks5::
	.string "Εντάξει, το 'πιασα.\n"
	.string "Θα βρω χρόνο στο πρόγραμμά μου\n"
	.string "να τη μάθω.\p"
	.string "Χαίρομαι που βρήκα καλό μέντορα.\n"
	.string "Ευχαριστώ! Τα λέμε εκεί έξω!$"

gText_ApprenticeWhichMove6::
	.string "Ω! Τυχερός/ή!\n"
	.string "Σε πέτυχα πάλι, {PLAYER}!\l"
	.string "Χρειάζομαι τις γνώσεις σου πάλι.\p"
	.string "Τυμπανοκρουσίες, παρακαλώ!\n"
	.string "Η ερώτηση που έχω είναι...\p"
	.string "Για το {STR_VAR_1} μου, ποια κίνηση\n"
	.string "ταιριάζει καλύτερα, {STR_VAR_2} ή\l"
	.string "{STR_VAR_3};$"

gText_ApprenticeMoveThanks6::
	.string "Αααχ!\n"
	.string "Την {STR_VAR_1}, ε;\l"
	.string "Ευχαριστώ για την cool απάντηση!\p"
	.string "Νομίζω αυτά ήθελα να σε ρωτήσω\n"
	.string "για σήμερα.\p"
	.string "Ας βρεθούμε πάλι εδώ, εντάξει;\n"
	.string "Ευχαριστώ!$"

gText_ApprenticeWhichMove7::
	.string "Ω, γεια σου, {PLAYER}.\n"
	.string "Ελπίζω να είσαι καλά;\p"
	.string "Πρέπει να σε συμβουλευτώ πάλι.\n"
	.string "Είναι για το αγαπημένο μου {STR_VAR_1}.\p"
	.string "Ποια θα ήταν η ιδανική κίνηση για\n"
	.string "το αξιαγάπητο {STR_VAR_1} μου;\l"
	.string "{STR_VAR_2} ή {STR_VAR_3};$"

gText_ApprenticeMoveThanks7::
	.string "Την {STR_VAR_1} λοιπόν!\n"
	.string "Θα τη μάθω αμέσως!\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Ελπίζω να σε ξανασυμβουλευτώ.\l"
	.string "Να προσέχεις!$"

gText_ApprenticeWhichMove8::
	.string "Εκ! {PLAYER}! Σε ξαναβρήκα!\n"
	.string "Εγώ... είμαι πανευτυχής!\p"
	.string "Όποτε έχω ανάγκη, είσαι πάντα\n"
	.string "εκεί για μένα, {PLAYER}!\p"
	.string "Σήμερα, θέλω να μου προτείνεις\n"
	.string "μια κίνηση!\p"
	.string "Διάλεξε μια κίνηση για το\n"
	.string "{STR_VAR_1} μου!\p"
	.string "Ποια κίνηση θα ήταν καλύτερη,\n"
	.string "η {STR_VAR_2} ή η {STR_VAR_3};$"

gText_ApprenticeMoveThanks8::
	.string "Ω-ω-ω! Σε ευχαριστώ!\n"
	.string "Την {STR_VAR_1} λοιπόν!\l"
	.string "Κατανοητό απόλυτα!\p"
	.string "Ελπίζω να δεχτείς να με μάθεις\n"
	.string "κι άλλα κάποια άλλη στιγμή.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}, bueno!\n"
	.string "Ελπίζω σε λίγη ακόμα από τη\n"
	.string "σοφή συμβουλή σου σήμερα!\p"
	.string "Ποια θα ήταν η καλύτερη κίνηση\n"
	.string "για το {STR_VAR_1} μου;\p"
	.string "Θα πρέπει να είναι κάτι που θα με\n"
	.string "κάνει να νικήσω έτσι απλά!\p"
	.string "Θα ήταν η {STR_VAR_2};\n"
	.string "Ή η {STR_VAR_3};$"

gText_ApprenticeMoveThanks9::
	.string "Α-χα, την {STR_VAR_1} λοιπόν!\n"
	.string "Si, bueno!\l"
	.string "Θα τη μάθω έτσι απλά, μπαμ!\p"
	.string "Εντάξει, ευχαριστώ, όπως πάντα!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}, είναι απίστευτο!\p"
	.string "Το POKéMON μου!\n"
	.string "Έμαθε έξι κινήσεις!\p"
	.string "Φυσικά και λέω ψέματα!\n"
	.string "Ουαχαχαχα!\p"
	.string "Αυτό όμως δεν είναι ψέμα.\n"
	.string "Δεν είμαι καλός στο να διαλέγω\n"
	.string "κινήσεις για τα POKéMON μου.\p"
	.string "Οπότε, τι λες να διαλέξεις ποιο\n"
	.string "είδος κίνησης πρέπει να μάθω;\p"
	.string "{STR_VAR_2} ή {STR_VAR_3}--ποιο\n"
	.string "πάει καλύτερα στο {STR_VAR_1} μου;$"

gText_ApprenticeMoveThanks10::
	.string "Οκ, την {STR_VAR_1} διάλεξες;\n"
	.string "Θα διαλέξω άλλη κίνηση τότε!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ, master!\n"
	.string "Ελπίζω να συνεχίσεις να με μαθαίνεις!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "Που σημαίνει ahoy!\p"
	.string "Ο SAILOR που ραπάρει είμαι εγώ!\n"
	.string "Είμαι πάντα έτοιμος, μη ρωτάς γιατί.\p"
	.string "Σήμερα, έχω μια ερώτηση για\n"
	.string "κίνηση που θέλει συμβουλή!\p"
	.string "{STR_VAR_2} και {STR_VAR_3} είναι οι\n"
	.string "κινήσεις. Ποια θα ήταν η best\l"
	.string "για το {STR_VAR_1} μου, για να σαρώνει;$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, λες, έι, έι!\n"
	.string "Θα το μάθω αμέσως εκεί!\p"
	.string "Αν ποτέ συμβουλή χρειαστώ,\n"
	.string "{PLAYER}, πάντα θα σε ακούω!$"

gText_ApprenticeWhichMove12::
	.string "Ω, ναιιι, αν δεν είναι ο {PLAYER}!\p"
	.string "Τι να κάνω; Να πάρω συμβουλή;\n"
	.string "Γιατί όχι; Ήδη σου μιλάω!\p"
	.string "{PLAYER}, σε εκπλήσσω;\n"
	.string "Θέλω τη συμβουλή σου, δεν το βλέπεις;\p"
	.string "Με ακούς;\l"
	.string "Με ακούς!\p"
	.string "Το {STR_VAR_1} μου--ποιο να μάθει;\n"
	.string "Είναι η {STR_VAR_2} ή η {STR_VAR_3}.\l"
	.string "Τι διαλέγεις;$"

gText_ApprenticeMoveThanks12::
	.string "Αν η {STR_VAR_1} είναι η best,\n"
	.string "θα το κάνω όπως λες!\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις.\p"
	.string "Θα σε ξαναδώ, έξυπνε φίλε μου!$"

gText_ApprenticeWhichMove13::
	.string "Γκα-χάκ! Γκάα! Ω, {PLAYER}...\n"
	.string "Έχω αυτό το άθλιο κρύωμα...\p"
	.string "Θέλω να διαλέξω κίνηση για το\n"
	.string "POKéMON μου, αλλά δεν αντέχω...\p"
	.string "Έτσι όπως είναι τα πράγματα,\n"
	.string "πρέπει να αποφασίσεις εσύ.\p"
	.string "{PLAYER}, αν έπρεπε να διαλέξω\n"
	.string "ανάμεσα σε {STR_VAR_2} και {STR_VAR_3}\l"
	.string "για το {STR_VAR_1} μου, ποια θα ήταν;$"

gText_ApprenticeMoveThanks13::
	.string "Χμμ, την {STR_VAR_1}, οκ. *Βήχας*\n"
	.string "Θα τη μάθω όταν γίνω καλά.\p"
	.string "Ελπίζω να συνεχίσω να σου ζητάω\n"
	.string "βοήθεια έτσι.$"

gText_ApprenticeWhichMove14::
	.string "Ε... εμμ...\n"
	.string "{PLAYER}...;\p"
	.string "Σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Νιώθω όλο και πιο άβολα...\l"
	.string "Ε... εγώ... θέλω τη συμβουλή σου.\p"
	.string "Ντρέπομαι πολύ, αλλά δεν μπορώ να\n"
	.string "αποφασίσω ποια κίνηση να μάθω\l"
	.string "στο POKéMON μου.\p"
	.string "Είναι για το {STR_VAR_1} μου.\n"
	.string "Αν οι επιλογές ήταν {STR_VAR_2} ή\l"
	.string "{STR_VAR_3}, ποια θα ήταν καλύτερη;$"

gText_ApprenticeMoveThanks14::
	.string "Ω... Εντάξει!\n"
	.string "Θα δοκιμάσω την {STR_VAR_1}.\p"
	.string "Ελπίζω να μπορέσω να τη μάθω...\n"
	.string "Αυτό είναι τόσο αγχωτικό...\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Αν ξαναβρεθούμε, ελπίζω να είσαι\l"
	.string "το ίδιο εξυπηρετικός/ή.$"

gText_ApprenticeWhichMove15::
	.string "Χμμ; Φαίνεσαι να είσαι ο {PLAYER}...\n"
	.string "Αλλά είσαι όντως αληθινός;\p"
	.string "Μήπως είσαι ένας από αυτούς τους\n"
	.string "δημοφιλείς μίμους;\p"
	.string "Όχι, αν είσαι αληθινός, οκ.\n"
	.string "Δεν υπάρχει λόγος ανησυχίας!\p"
	.string "Παρεμπιπτόντως, θα ήθελα να\n"
	.string "έχω τη σοφή συμβουλή σου.\p"
	.string "Είναι για το {STR_VAR_1} μου.\p"
	.string "Ποια κίνηση θα ήταν καλύτερη,\n"
	.string "η {STR_VAR_2} ή η {STR_VAR_3};$"

gText_ApprenticeMoveThanks15::
	.string "Την {STR_VAR_1};\n"
	.string "Δεν υπάρχει αμφιβολία για αυτό;\p"
	.string "Καταλαβαίνω. Αν είναι έτσι, οκ.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Ελπίζω να είναι κάτι που ακόμα και\n"
	.string "το POKéMON μου μπορεί να μάθει.\p"
	.string "Ας ξανασυναντηθούμε!$"

gText_ApprenticePickWinSpeech0::
	.string "Ω... {PLAYER};\n"
	.string "Είναι ο {PLAYER}!\l"
	.string "Ω! Σνιφ... λυγμ... Άκου σε παρακαλώ!\p"
	.string "Εγώ... όταν μάχομαι αγχώνομαι,\n"
	.string "δεν μπορώ παρά να κλαίω και ας νικώ...\p"
	.string "Μακάρι να έλεγα κάτι cool όταν\n"
	.string "νικώ...\p"
	.string "Σε παρακαλώ, {PLAYER}!\n"
	.string "Μπορείς να μου μάθεις κάτι cool\n"
	.string "να λέω όταν νικώ για να μην κλαίω;$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Τέλεια! Απίστευτα! Αουυού!\n"
	.string "Είναι όντως cool!\p"
	.string "Ω... συγγνώμη...\n"
	.string "Είμαι τόσο χαρούμενος/η, κλαίω...\p"
	.string "Σνιφ... {PLAYER}!\n"
	.string "Σε ευχαριστώ πολύ για όλα!\p"
	.string "Θα μάχομαι όσο καλύτερα μπορώ για\n"
	.string "χάρη σου, {PLAYER}!\p"
	.string "{PLAYER}...\n"
	.string "Την επόμενη φορά... ας μονομαχήσουμε!$"

gText_ApprenticePickWinSpeech1::
	.string "Γιούπι! Είναι ο {PLAYER}! Γεια!\n"
	.string "Ήθελα να σε ρωτήσω κάτι!\p"
	.string "Θέλω να λέω κάτι cool όταν νικάω\n"
	.string "έναν αγώνα.\p"
	.string "Έχεις κάποια cool ατάκα να μου\n"
	.string "προτείνεις;$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Πω πω! Αυτό είναι πολύ cool!\n"
	.string "Οκ, αυτό θα λέω!\p"
	.string "Ευχαριστώ που με μάθαινες τόσο καιρό!\n"
	.string "Θα κάνω ό,τι καλύτερο μπορώ όπου\n"
	.string "κι αν πάω από εδώ και πέρα!\p"
	.string "Όταν ξαναβρεθούμε, θα είναι για\n"
	.string "μάχη!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, γεια σου!\p"
	.string "Το POKéMON μου κι εγώ είμαστε\n"
	.string "έτοιμοι για όλα, εκτός από ένα.\p"
	.string "Νομίζω θα ήταν καλό να έχω κάτι\n"
	.string "να φωνάζω όταν νικάω.\p"
	.string "Θα μπορούσες να σκεφτείς κάτι\n"
	.string "καλό να λέω;$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "...Cool!\n"
	.string "Αυτό θα χρησιμοποιήσω!\p"
	.string "Θα βγω έξω να μονομαχήσω παντού.\p"
	.string "Πού ξέρεις, μπορεί και να\n"
	.string "μονομαχήσω μαζί σου μια μέρα.\p"
	.string "Την επόμενη φορά, ας βρεθούμε στο\n"
	.string "πεδίο της μάχης!$"

gText_ApprenticePickWinSpeech3::
	.string "Γεια σου, {PLAYER}...\n"
	.string "Συγγνώμη που σε ενοχλώ, αλλά είμαι\n"
	.string "απελπισμένος/η...\p"
	.string "Ακόμα κι όταν...\n"
	.string "Ακόμα κι όταν νικώ, δεν έχω κάτι\n"
	.string "ιδιαίτερο να πω...\p"
	.string "Ξέρω ότι δεν σημαίνει τίποτα\n"
	.string "για εσένα, {PLAYER}.\p"
	.string "Αλλά σημαίνει πολλά για μένα...\p"
	.string "Σε παρακαλώ, {PLAYER}, τι να λέω\n"
	.string "αν νικήσω μια μάχη;$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Πολύ εμπνευσμένο...\p"
	.string "Ε... είναι οκ για κάποιον σαν εμένα\n"
	.string "να το λέει αυτό;\p"
	.string "Όχι! Θα βάλω τα δυνατά μου!\p"
	.string "{PLAYER}, σε ευχαριστώ τόσο πολύ\n"
	.string "που με ανέχτηκες τόσο καιρό...\p"
	.string "Υπόσχομαι να δώσω τον καλύτερο\n"
	.string "μου εαυτό από εδώ και πέρα.\p"
	.string "Σίγουρα θα ξεχάσεις γρήγορα\n"
	.string "κάποιον σαν εμένα, αλλά ας\l"
	.string "ξαναβρεθούμε κάπου!$"

gText_ApprenticePickWinSpeech4::
	.string "Ω, {PLAYER}.\n"
	.string "Είναι κάτι που θέλω να ακούσεις.\p"
	.string "Ξέρω ότι δεν ακούγομαι πάντα\n"
	.string "ευγενικός...\p"
	.string "Όταν νικάω μια μάχη, νομίζω ότι\n"
	.string "φαίνομαι αλαζονικός.\p"
	.string "Δεν θέλω να με αντιπαθούν,\n"
	.string "γι' αυτό θέλω να λέω κάτι καλό σε\l"
	.string "κάποιον που νίκησα.\p"
	.string "Αλλά δεν μπορώ να σκεφτώ τίποτα!\n"
	.string "Θα μπορούσες να σκεφτείς εσύ;$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Όχι άσχημα!\n"
	.string "Ναι, αυτό θα χρησιμοποιήσω!\p"
	.string "Θα βγω στον δρόμο και θα κάνω ό,τι\n"
	.string "μπορώ με όσα μου έμαθες.\p"
	.string "Συγγνώμη αν ήμουν τόσο\n"
	.string "πιεστικός μαζί σου!\p"
	.string "Την επόμενη φορά μονομαχούμε, οκ;\n"
	.string "Γεια!$"

gText_ApprenticePickWinSpeech5::
	.string "Ω, δεν φαντάζεσαι πόσο τρέχω!\n"
	.string "Έι, σε έψαχνα, {PLAYER}.\p"
	.string "Είσαι καλά όπως πάντα;\n"
	.string "Τίποτα δεν έχει αλλάξει για μένα.\p"
	.string "Τρέξιμο, μάχες, χαρτογράφηση...\n"
	.string "Γιατί είμαι τόσο απασχολημένος/η;\p"
	.string "Αλλά παρόλο που τρέχω, είναι αγένεια\n"
	.string "να φεύγω έτσι μετά από μια νίκη\l"
	.string "χωρίς να πω λέξη.\p"
	.string "Οπότε, ποια cool ατάκα θα\n"
	.string "τόνιζε το στυλ μου καθώς φεύγω;\n"
	.string "{PLAYER}, βοήθησέ με!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Εντάξει, το 'πιασα.\n"
	.string "Θα βρω χρόνο να το πω!\p"
	.string "Ειλικρινά, χαίρομαι που σε είχα\n"
	.string "για μέντορα.\p"
	.string "Θα βρω χρόνο κάπως για να\n"
	.string "αφοσιωθώ στις μάχες.\p"
	.string "Ευχαριστώ για όλα, {PLAYER}!\n"
	.string "Πρέπει να μονομαχήσουμε μια μέρα!$"

gText_ApprenticePickWinSpeech6::
	.string "Στάθηκα πάλι τυχερός/ή!\n"
	.string "{PLAYER}! Τι χαρά που σε βλέπω!\l"
	.string "Όπως πάντα, θέλω τη συμβουλή σου!\p"
	.string "Τυμπανοκρουσίες, παρακαλώ!\n"
	.string "Η τελευταία ερώτηση είναι...\p"
	.string "Αν νικήσω και θέλω να τελειώσω\n"
	.string "με μια cool ατάκα, τι\l"
	.string "πρέπει να πω;$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Αυτό... Αυτό είναι υπέροχο!\n"
	.string "Είναι σοβαρό και cool! Δικό μου!\p"
	.string "...Άκου, νομίζω γίνομαι καλός/ή\n"
	.string "σε αυτό, ε;\p"
	.string "Οπότε, σκέφτομαι να προκαλέσω\n"
	.string "άλλους TRAINERS από εδώ και πέρα.\p"
	.string "{PLAYER}, οι συμβουλές σου βοήθησαν.\p"
	.string "Ίσως μια μέρα έρθει η ώρα να\n"
	.string "μονομαχήσουμε!\p"
	.string "Σε ευχαριστώ για όλα!$"

gText_ApprenticePickWinSpeech7::
	.string "Ω, {PLAYER}.\n"
	.string "Χαίρομαι τόσο που σε γνώρισα!\p"
	.string "Δεν ανησυχώ πια για τα POKéMON μου.\p"
	.string "Ο εαυτός μου με ανησυχεί...\p"
	.string "Ξέρεις πώς ένας TRAINER λέει\n"
	.string "μερικά πράγματα όταν νικάει;\p"
	.string "Σίγουρα, θα ήθελα να το κάνω\n"
	.string "κι εγώ αυτό!\p"
	.string "Σε παρακαλώ, τι να λέω όταν\n"
	.string "νικάω μια μάχη;$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Α! Αυτή η ατάκα! Με ανανεώνει\n"
	.string "και με κάνει να νιώθω άλλος άνθρωπος!\p"
	.string "Πρέπει να τη χρησιμοποιήσω αμέσως!\p"
	.string "Και τώρα, πρέπει να σε αφήσω,\n"
	.string "{PLAYER}...\p"
	.string "Θα βγω να παλέψω με άλλους,\n"
	.string "αλλά δεν θα ξεχάσω όσα με έμαθες.\p"
	.string "Ίσως κάποια μέρα...\n"
	.string "Εις το επανιδείν!$"

gText_ApprenticePickWinSpeech8::
	.string "Εκ! Είδα τον/την {PLAYER}!\n"
	.string "Εγώ... πετάω από τη χαρά μου!\p"
	.string "Ω-ω-ω! Υπάρχει κάτι που έπρεπε\n"
	.string "να σε ρωτήσω!\p"
	.string "Πριν λίγο, νίκησα σε μια μάχη.\n"
	.string "Ήταν φανταστικά!\p"
	.string "Αλλά χάρηκα τόσο πολύ που\n"
	.string "πνίγηκα και δεν είπα λέξη!\p"
	.string "Τώρα, {PLAYER}, σε παρακαλώ, σκέψου\n"
	.string "μια ατάκα για όταν νικάω!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Ουάαααα!\n"
	.string "Θα το λέω αυτό;!\l"
	.string "Εγώ... τρελαίνομαι από τη χαρά μου!\p"
	.string "Σε ευ-ευ-ευχαριστώ!\n"
	.string "Δεν έχω μετανιώσει για τίποτα πια!\p"
	.string "Θα ταξιδέψω τώρα και θα παλέψω\n"
	.string "με κάθε λογής ανθρώπους.\p"
	.string "Όλα τα οφείλω σε εσένα, {PLAYER}.\n"
	.string "Πραγματικά, σε ευχαριστώ πολύ!\p"
	.string "Πρέπει να φύγω, ας μονομαχήσουμε\n"
	.string "μια μέρα!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}!\p"
	.string "Ξέρεις, θέλω πολύ να περιπλανηθώ\n"
	.string "και να μονομαχήσω όπου μπορώ.\p"
	.string "Πριν όμως, θέλω τη συμβουλή σου\n"
	.string "άλλη μια φορά, σε παρακαλώ!\p"
	.string "Αν νικούσα μια μάχη, ποιο θα ήταν\n"
	.string "ένα καλό καύχημα για τον\l"
	.string "ηττημένο αντίπαλο;$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Α-χα, αυτό είναι ωραίο!\n"
	.string "Si, bueno!\l"
	.string "Θα δοκιμάσω να το πω, έτσι, μπαμ!\p"
	.string "Και τώρα, ώρα να αποχαιρετιστούμε!\n"
	.string "Ευχαριστώ για όλα τα πράγματα!\p"
	.string "Δώσε μου μια μάχη μια μέρα, οκ;\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}, έχουμε πρόβλημα!\p"
	.string "Όταν νικάω, καυχιέμαι για αυτό\n"
	.string "τουλάχιστον για μια ώρα!\p"
	.string "Φυσικά και λέω ψέματα!\n"
	.string "Ουαχαχαχα!\p"
	.string "Αυτό όμως δεν είναι ψέμα.\n"
	.string "Δεν είμαι καλός στο να μιλάω.\p"
	.string "Οπότε, τι λες να αποφασίσεις εσύ\n"
	.string "τι να λέω μετά από μια νίκη,\l"
	.string "master;$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Αυτό πρέπει να λέω, ε;\n"
	.string "Τότε, θα μείνω μακριά από αυτό!\p"
	.string "Πλάκα κάνω!\n"
	.string "Θα ακούσω τις οδηγίες σου, master!\p"
	.string "Ευχαριστώ που με μάθαινες τόσο\n"
	.string "καιρό, master!\p"
	.string "Τελικά καταλαβαίνω τι σημαίνει\n"
	.string "να είσαι TRAINER.\p"
	.string "Θα βγω έξω και θα νικήσω μάχες\n"
	.string "κόντρα σε κάθε TRAINER.\p"
	.string "Ίσως να είσαι εσύ μια μέρα, master!\p"
	.string "Αυτά είναι όλα!\n"
	.string "Αντίο, master μου!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "Που σημαίνει ahoy!\p"
	.string "Ο SAILOR που ραπάρει είμαι εγώ!\n"
	.string "Αυτή είναι η τελευταία ερώτηση,\n"
	.string "μην κλάψεις!\p"
	.string "Είναι μια ερώτηση για ατάκα\n"
	.string "που θέλει τη συμβουλή σου!\p"
	.string "Αν νικήσω έναν αγώνα, τι να πω\n"
	.string "με έναν πραγματικά cool τρόπο;$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Τέλεια! Αυτό θα χρησιμοποιήσω.\n"
	.string "Είχα δίκιο που σε έβαλα να διαλέξεις!\p"
	.string "Και τώρα, νομίζω είναι καλύτερο,\n"
	.string "να ανοίξω τα φτερά μου!\p"
	.string "Ευχαριστώ για όσα με έμαθες.\n"
	.string "Θα ξεκινήσω ένα σερί από μάχες!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "Που σημαίνει bon voyage,\n"
	.string "για εσένα αυτός ο φόρος τιμής!$"

gText_ApprenticePickWinSpeech12::
	.string "Ω, ναι, {PLAYER}!\n"
	.string "Σε βρήκα πάλι σήμερα!\p"
	.string "Τι να κάνω; Να σε ρωτήσω πάλι;\n"
	.string "Γιατί όχι; Ήδη σε ρωτάω!\p"
	.string "Όπως και να 'χει, {PLAYER}...\n"
	.string "Με ακούς;\l"
	.string "Με ακούς!\l"
	.string "Θέλω λίγη ακόμα συμβουλή!\p"
	.string "Είναι για το τι πρέπει να φωνάξω.\n"
	.string "Κάτι cool να ουρλιάξω όταν\l"
	.string "μια μάχη τελειώσει καλά.\p"
	.string "Έλα, θέλω να σε ακούσω να το λες!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Εντάξει, εντάξει!\n"
	.string "Θα το πω γιατί είναι πολύ super!\p"
	.string "Δεν έχω άλλα να σε ρωτήσω.\n"
	.string "Έμεινε μόνο να σε αποχαιρετήσω.\p"
	.string "Αλλά ίσως μια μέρα βρεθούμε, και\n"
	.string "ένας από τους δυο θα ηττηθεί.\p"
	.string "Αλλά, είναι ώρα να πούμε αντίο.\p"
	.string "Λοιπόν, {PLAYER}, πρέπει να φύγω,\n"
	.string "αλλά μη με ξεχάσεις!\p"
	.string "Να προσέχεις, {PLAYER}!\n"
	.string "Σε αγαπώ!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}, τελείωσα...\n"
	.string "Η μύτη μου δεν σταματά να τρέχει...\p"
	.string "Προσπαθούσα να σκεφτώ κάτι cool\n"
	.string "να λέω όταν νικάω μια μάχη.\p"
	.string "Με ενέπνευσε τόσο, που με έκανε να\n"
	.string "κλάψω, και τώρα τρέχει η μύτη μου...\p"
	.string "Έτσι όπως είναι τα πράγματα,\n"
	.string "πρέπει να αποφασίσεις εσύ, {PLAYER}.\p"
	.string "Όταν νικάω μια μάχη,\n"
	.string "τι πρέπει να λέω;$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "... ... ...Καλό είναι.\n"
	.string "Όχι, είναι συγκλονιστικό!\l"
	.string "Φέρνει νέα δάκρυα στα μάτια μου!\p"
	.string "Αλλά παρά τα δάκρυα και τη μύτη\n"
	.string "μου, θα χρησιμοποιήσω αυτή την ατάκα!\p"
	.string "Δεν έχω άλλα να σε ρωτήσω,\n"
	.string "{PLAYER}.\p"
	.string "Από εδώ και πέρα, είμαστε αντίπαλοι!\n"
	.string "Ευχαριστώ για όλα!$"

gText_ApprenticePickWinSpeech14::
	.string "Ε... εμμ...\n"
	.string "{PLAYER}...\p"
	.string "Σε παρακαλώ, μη με κοιτάς έτσι.\n"
	.string "Με κάνεις να αγχώνομαι.\p"
	.string "Ε... εγώ... θέλω πάλι τη συμβουλή σου.\n"
	.string "Θα είναι η τελευταία, όμως...\p"
	.string "Είναι πολύ άβολο να ρωτάω, αλλά\n"
	.string "αν νικήσω μια μάχη;\l"
	.string "Τι πρέπει να λέω;$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Ω... Εντάξει!\n"
	.string "Θα προσπαθήσω να το πω!\l"
	.string "Μπορεί να αγχωθώ πολύ για να το πω...\p"
	.string "Σε ευχαριστώ, {PLAYER}.\n"
	.string "Πρέπει να σε αποχαιρετήσω τώρα.\p"
	.string "Θα ακολουθήσω όσα με έμαθες,\n"
	.string "{PLAYER}, και θα κάνω ό,τι καλύτερο.$"

gText_ApprenticePickWinSpeech15::
	.string "Χμμ; Φαίνεσαι να είσαι ο {PLAYER}...\n"
	.string "Αλλά είσαι όντως εσύ;\l"
	.string "Μήπως μια έξυπνη {PLAYER} DOLL;\p"
	.string "Ω, όχι, όχι, μη σε ανησυχεί!\n"
	.string "Αν είσαι όντως εσύ, σε παρακαλώ\l"
	.string "ξέχνα την αγένειά μου.\p"
	.string "Μη θυμώνεις. Το μόνο που θέλω\n"
	.string "είναι λίγη ακόμα συμβουλή.\p"
	.string "Αφορά μια ατάκα.\p"
	.string "Πιο συγκεκριμένα, τι να λέω όταν\n"
	.string "νικάω μια μάχη;$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "... ... ... ... ... ...\n"
	.string "Όταν νικάω έναν αγώνα...\p"
	.string "{STR_VAR_1}\p"
	.string "...Σοβαρολογείς;\p"
	.string "Κατάλαβα. Αν σοβαρολογείς, οκ.\n"
	.string "Σε ευχαριστώ για τον χρόνο σου.\p"
	.string "Ελπίζω ακόμα κι εγώ να μπορέσω\n"
	.string "να χρησιμοποιήσω αυτή την ατάκα.\p"
	.string "Φαίνεται ότι ξέμεινα από συμβουλές\n"
	.string "που χρειάζομαι.\p"
	.string "Πιστεύω είναι ώρα να σε\n"
	.string "αποχαιρετήσω και να πάρω τον δρόμο μου.\p"
	.string "Σε ευχαριστώ, μέντορά μου!\n"
	.string "Συγγνώμη για την αμφιβολία μου!$"
