FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Σε καλωσορίζω στο BATTLE TENT\n"
	.string "της FALLARBOR!\p"
	.string "Είμαι ο οδηγός σου για το\n"
	.string "Set KO Tourney!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Λοιπόν, θέλεις να πάρεις μέρος\n"
	.string "στο Set KO Tourney;$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Περιμένουμε την πρόκλησή σου\n"
	.string "μια άλλη φορά!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Στο FALLARBOR BATTLE TENT,\n"
	.string "διοργανώνουμε το Set KO Tourney.\p"
	.string "Όλοι οι συμμετέχοντες μπαίνουν με\n"
	.string "μια ομάδα τριών POKéMON.\p"
	.string "Τα τρία POKéMON πρέπει να είναι στη\n"
	.string "σειρά με την οποία θα εμφανιστούν.\p"
	.string "Κατά τη μάχη, τα POKéMON θα βγαίνουν\n"
	.string "ένα προς ένα με την προκαθορισμένη\l"
	.string "σειρά.\p"
	.string "Όταν ένα POKéMON μπει στη μάχη, πρέπει\n"
	.string "να μείνει μέχρι να κριθεί ο αγώνας.\p"
	.string "Αν ένας αγώνας δεν κριθεί σε\n"
	.string "τρεις γύρους, πάει σε βαθμολογία.\p"
	.string "Αν θες να διακόψεις την πρόκληση,\n"
	.string "παρακαλώ αποθήκευσε το παιχνίδι.\p"
	.string "Αν δεν αποθηκεύσεις, δεν θα μπορείς\n"
	.string "να συνεχίσεις την πρόκλησή σου.\p"
	.string "Αν καταφέρεις να νικήσεις τρεις\n"
	.string "TRAINERS στη σειρά, θα σου\l"
	.string "δώσουμε ένα ωραίο βραβείο.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Πριν σε οδηγήσω στο BATTLE TENT,\n"
	.string "πρέπει να αποθηκεύσω. Εντάξει;$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Προσφέρουμε δύο επίπεδα,\n"
	.string "Level 50 και Open Level.\l"
	.string "Ποιο διαλέγεις;$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Πολύ καλά, τώρα διάλεξε τα τρία\n"
	.string "POKéMON σου, παρακαλώ.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Γεια σου!\p"
	.string "Δεν έχεις τα τρία POKéMON που\n"
	.string "απαιτούνται για την είσοδο.\p"
	.string "Επίσης δεν πρέπει να κρατούν τα\n"
	.string "ίδια είδη αντικειμένων.\p"
	.string "Τα EGGS{STR_VAR_1} δεν γίνονται δεκτά.\p"
	.string "Όταν κάνεις τις προετοιμασίες σου,\n"
	.string "παρακαλώ επέστρεψε.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Γεια σου!\p"
	.string "Δεν έχεις τα τρία POKéMON που\n"
	.string "απαιτούνται για την είσοδο.\p"
	.string "Για να μπεις, πρέπει να φέρεις τρία\n"
	.string "διαφορετικά είδη POKéMON.\p"
	.string "Επίσης δεν πρέπει να κρατούν τα\n"
	.string "ίδια είδη αντικειμένων.\p"
	.string "Τα EGGS{STR_VAR_1} δεν γίνονται δεκτά.\p"
	.string "Όταν κάνεις τις προετοιμασίες σου,\n"
	.string "παρακαλώ επέστρεψε.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Θα σε οδηγήσω τώρα στο\n"
	.string "BATTLE TENT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Γεια σου!\p"
	.string "Δεν αποθήκευσες το παιχνίδι πριν\n"
	.string "κλείσεις τη συσκευή, έτσι δεν είναι;\p"
	.string "Είναι ατυχές, αλλά αυτό οδήγησε\n"
	.string "στον αποκλεισμό σου από την\l"
	.string "πρόκληση.\p"
	.string "Μπορείς, φυσικά, να ξεκινήσεις μια\n"
	.string "νέα πρόκληση.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Τι υπέροχο! Νίκησες τρεις\n"
	.string "TRAINERS στη σειρά!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Περίμενε όσο αποθηκεύω το παιχνίδι.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Σε ανάμνηση των 3 νικών σου, σου\n"
	.string "δίνουμε αυτό το βραβείο.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "Το βραβείο {STR_VAR_1}\n"
	.string "παραλήφθηκε.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Ω;\n"
	.string "Η BAG σου φαίνεται να είναι γεμάτη.\p"
	.string "Σε παροτρύνω να κάνεις χώρο και να\n"
	.string "επιστρέψεις για το βραβείο σου.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Σε ευχαριστώ πολύ για τη συμμετοχή!\p"
	.string "Περίμενε όσο αποθηκεύω το παιχνίδι.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Περιμένουμε την πρόκλησή σου\n"
	.string "μια άλλη φορά!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Περιμέναμε την άφιξή σου.\p"
	.string "Πριν σε οδηγήσω στο BATTLE TENT,\n"
	.string "πρέπει να αποθηκεύσω. Περίμενε.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Σε καλωσορίω στο BATTLE TENT\n"
	.string "της VERDANTURF!\p"
	.string "Εδώ, δοκιμάζεται η εμπιστοσύνη του\n"
	.string "TRAINER προς τα POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Θέλεις να πάρεις μέρος στην\n"
	.string "πρόκληση της VERDANTURF;$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Στο VERDANTURF BATTLE TENT,\n"
	.string "υπάρχει ένας κρίσιμος κανόνας που\l"
	.string "πρέπει να τηρείται.\p"
	.string "Οι TRAINERS επιτρέπεται μόνο να\n"
	.string "αλλάζουν τα POKéMON τους.\p"
	.string "Κατά τα άλλα, απαγορεύεται στους\n"
	.string "TRAINERS να δίνουν εντολές.\p"
	.string "Τα POKéMON θα συμπεριφέρονται\n"
	.string "σύμφωνα με τη φύση τους και θα\l"
	.string "μάχονται μόνα τους.\p"
	.string "Πρέπει να εμπιστευτείς τα\n"
	.string "POKéMON σου και να τα προσέχεις.\p"
	.string "Αν καταφέρεις να νικήσεις τρεις\n"
	.string "TRAINERS στη σειρά, θα σου\l"
	.string "δώσουμε ένα βραβείο.\p"
	.string "Αν θες να διακόψεις την πρόκληση,\n"
	.string "παρακαλώ αποθήκευσε το παιχνίδι.\p"
	.string "Αν δεν αποθηκεύσεις πριν διακόψεις,\n"
	.string "θα αποκλειστείς.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Όταν οχυρώσεις την καρδιά σου και\n"
	.string "τα POKéMON σου, πρέπει να γυρίσεις.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Υπάρχουν δύο επίπεδα δυσκολίας,\n"
	.string "Level 50 και Open Level.\l"
	.string "Ποια είναι η επιλογή σου;$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Αχ...\p"
	.string "Δεν έχεις τα τρία POKéMON που\n"
	.string "απαιτούνται για την πρόκληση.\p"
	.string "Για να μπεις, πρέπει να φέρεις τρία\n"
	.string "διαφορετικά είδη POKéMON.\p"
	.string "Επίσης δεν πρέπει να κρατούν τα\n"
	.string "ίδια είδη αντικειμένων.\p"
	.string "Τα EGGS{STR_VAR_1} δεν γίνονται δεκτά.\p"
	.string "Γύρισε όταν θα έχεις κάνει τις\n"
	.string "προετοιμασίες σου.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Αχ...\p"
	.string "Δεν έχεις τα τρία POKéMON που\n"
	.string "απαιτούνται για την πρόκληση.\p"
	.string "Για να μπεις, πρέπει να φέρεις τρία\n"
	.string "διαφορετικά είδη POKéMON.\p"
	.string "Επίσης δεν πρέπει να κρατούν τα\n"
	.string "ίδια είδη αντικειμένων.\p"
	.string "Τα EGGS{STR_VAR_1} δεν γίνονται δεκτά.\p"
	.string "Γύρισε όταν θα έχεις κάνει τις\n"
	.string "προετοιμασίες σου.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Ωραία. Τώρα, πρέπει να διαλέξεις\n"
	.string "τα τρία POKéMON σου.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Πρέπει να αποθηκεύσω πριν σε\n"
	.string "οδηγήσω στο BATTLE TENT. Εντάξει;$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Ωραία.\n"
	.string "Τώρα, ακολούθησέ με.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Νιώθω τιμή που είδα τα κατορθώματα\n"
	.string "των POKéMON σου.\p"
	.string "Τα αποτελέσματα θα καταγραφούν.\n"
	.string "Πρέπει να περιμένεις λίγο.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Το να κάνεις 3 νίκες στη σειρά...\p"
	.string "Οι δεσμοί που ενώνουν την καρδιά σου\n"
	.string "με τα POKéMON σου φαίνονται γεροί.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Το κατόρθωμά σου θα καταγραφεί.\n"
	.string "Πρέπει να περιμένεις λίγο.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Για το κατόρθωμα των 3 νικών σου,\n"
	.string "σου δίνουμε αυτό το βραβείο.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Καλώς ήρθες στο BATTLE TENT\n"
	.string "της SLATEPORT!\p"
	.string "Είμαι ο οδηγός σου για το\n"
	.string "Battle Swap Tournament.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Θέλεις να πάρεις μέρος στην\n"
	.string "πρόκληση Battle Swap;$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Εδώ στο SLATEPORT BATTLE TENT,\n"
	.string "διοργανώνουμε αγώνες Battle Swap\l"
	.string "χρησιμοποιώντας ενοικιαζόμενα POKéMON.\p"
	.string "Πρώτα, θα σου δανείσουμε τρία\n"
	.string "POKéMON ειδικά για αυτό το event.\p"
	.string "Χρησιμοποιώντας τα POKéMON αυτά,\n"
	.string "πρέπει να κάνεις μια SINGLE BATTLE.\p"
	.string "Αν νικήσεις, μπορείς να ανταλλάξεις\n"
	.string "ένα από τα ενοικιαζόμενα POKéMON.\p"
	.string "Επανάλαβε τον κύκλο μάχης και\n"
	.string "ανταλλαγής--αν νικήσεις τρεις\l"
	.string "φορές στη σειρά, θα κερδίσεις βραβείο.\p"
	.string "Αν θες να διακόψεις την πρόκληση,\n"
	.string "παρακαλώ αποθήκευσε το παιχνίδι.\p"
	.string "Αν δεν αποθηκεύσεις πριν διακόψεις,\n"
	.string "θα αποκλειστείς.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Περιμένουμε την επόμενη επίσκεψή σου.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Πριν ξεκινήσεις την πρόκληση,\n"
	.string "πρέπει να αποθηκεύσω. Εντάξει;$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Παρακαλώ, έλα από εδώ.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Σε ευχαριστώ για τη συμμετοχή!\p"
	.string "Θα σου επιστρέψω τα POKéMON σου και\n"
	.string "θα πάρω τα ενοικιαζόμενα.\p"
	.string "Πρέπει επίσης να αποθηκεύσω.\n"
	.string "Παρακαλώ περίμενε.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Συγχαρητήρια!\n"
	.string "Νίκησες σε τρεις συνεχόμενους αγώνες!\p"
	.string "Θα σου επιστρέψω τα POKéMON σου και\n"
	.string "θα πάρω τα ενοικιαζόμενα.\p"
	.string "Πρέπει επίσης να αποθηκεύσω.\n"
	.string "Παρακαλώ περίμενε.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Σε αναγνώριση των 3 νικών σου, σου\n"
	.string "δίνουμε αυτό το βραβείο.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Ω;\n"
	.string "Φαίνεται ότι δεν έχεις χώρο.\p"
	.string "Παρακαλώ άδειασε την BAG σου και\n"
	.string "πες μου το.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Σε περιμέναμε!\p"
	.string "Πριν συνεχίσουμε την πρόκληση,\n"
	.string "πρέπει να αποθηκεύσω το παιχνίδι.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Λυπάμαι που το λέω, αλλά δεν\n"
	.string "αποθήκευσες πριν κλείσεις την\l"
	.string "τελευταία φορά.\p"
	.string "Ως αποτέλεσμα, έχεις αποκλειστεί\n"
	.string "από την πρόκλησή σου.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We'll return your personal POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are listed.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Σε ένα event Battle Swap, μπορείς\n"
	.string "να χρησιμοποιήσεις μόνο τρία POKéMON.\p"
	.string "Είτε νοικιάζεις είτε ανταλλάσσεις,\n"
	.string "η ομάδα σου δεν μπορεί να έχει δύο\l"
	.string "ίδια POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Μπορείς να ανταλλάξεις POKéMON\n"
	.string "μόνο με τον TRAINER που μόλις νίκησες.\p"
	.string "Μπορείς να πάρεις μόνο τα POKéMON\n"
	.string "που χρησιμοποίησε ο TRAINER.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Μετά από κάθε μάχη που κερδίζεις,\n"
	.string "μπορείς να πάρεις ένα από τα\l"
	.string "POKéMON του αντιπάλου.\p"
	.string "Δεν θα μπορείς να ανταλλάξεις POKéMON\n"
	.string "με τον τρίτο TRAINER του event.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Υπάρχουν δύο βασικά σημεία που\n"
	.string "πρέπει να προσέξεις στις ανταλλαγές.\p"
	.string "Πρώτον, όταν ανταλλάσσεις, δεν\n"
	.string "μπορείς να δεις τα stats του\l"
	.string "POKéMON που πρόκειται να πάρεις.\p"
	.string "Δεύτερον, τα POKéMON στην ομάδα σου\n"
	.string "είναι στη σειρά με την οποία τα\l"
	.string "νοίκιασες.\p"
	.string "Αυτή η σειρά παραμένει ίδια ακόμη\n"
	.string "και μετά από ανταλλαγές.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Τα POKéMON του SLATEPORT BATTLE TENT\n"
	.string "είναι όλα ενοικιαζόμενα.\p"
	.string "Όλα τα ενοικιαζόμενα POKéMON είναι\n"
	.string "στο Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don't match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Σε αυτό το BATTLE TENT, τα επίπεδα\n"
	.string "των αντιπάλων θα προσαρμοστούν στο\l"
	.string "επίπεδο των δικών σου POKéMON.\p"
	.string "Ωστόσο, κανένας TRAINER δεν θα έχει\n"
	.string "POKéMON κάτω από Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Οι κανόνες του VERDANTURF\n"
	.string "BATTLE TENT είναι αναρτημένοι.$"
