BattleDome_Text_Potential1::
	.string "Ο καλύτερος υποψήφιος πρωταθλητής!$"

BattleDome_Text_Potential2::
	.string "Μια σίγουρη ομάδα για τον τελικό.$"

BattleDome_Text_Potential3::
	.string "Πιθανή ομάδα για την πρώτη τριάδα.$"

BattleDome_Text_Potential4::
	.string "Υποψήφια ομάδα για την πρώτη θέση.$"

BattleDome_Text_Potential5::
	.string "Ομάδα με κορυφαίες δυνατότητες.$"

BattleDome_Text_Potential6::
	.string "Το αουτσάιντερ του τουρνουά.$"

BattleDome_Text_Potential7::
	.string "Μια ομάδα καλύτερη από το μέσο όρο.$"

BattleDome_Text_Potential8::
	.string "Η μέση ομάδα αυτού του τουρνουά.$"

BattleDome_Text_Potential9::
	.string "Μια ομάδα με μέτριες δυνατότητες.$"

BattleDome_Text_Potential10::
	.string "Μια ομάδα χειρότερη από το μέσο όρο.$"

BattleDome_Text_Potential11::
	.string "Ομάδα που ψάχνει την πρώτη της νίκη.$"

BattleDome_Text_Potential12::
	.string "Μια νίκη θα κανει την ομάδα περήφανη.$"

BattleDome_Text_TakeChallenge::
	.string "Θέλεις να πάρεις μέρος στο\n"
	.string "Challenge Cup Tournament;$"

BattleDome_Text_Potential13::
	.string "Συνολικά, μια αδύναμη ομάδα.$"

BattleDome_Text_Potential14::
	.string "Ομάδα με πολύ χαμηλές δυνατότητες.$"

BattleDome_Text_Potential15::
	.string "Ομάδα απίθανο να νικήσει.$"

BattleDome_Text_Potential16::
	.string "Η ομάδα με τις λιγότερες ελπίδες.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "Ο τέλειος, ανίκητος superstar!$"

BattleDome_Text_SaveBeforeChallenge::
	.string "Πριν σε οδηγήσω στο BATTLE DOME,\n"
	.string "πρέπει να αποθηκεύσω. Εντάξει;$"

BattleDome_Text_StyleRiskDisaster::
	.string "Ρισκάρει την απόλυτη καταστροφή\n"
	.string "ανά πάσα στιγμή.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Εμπειρία στις μακρές μάχες.$"

BattleDome_Text_StyleVariesTactics::
	.string "Αλλάζει τακτικές ανάλογα με τον\n"
	.string "αντίπαλο.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Έχει μια σκληρή στρατηγική νίκης.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Πού και πού χρησιμοποιεί μια πολύ\n"
	.string "σπάνια κίνηση.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Χρησιμοποιεί κινήσεις που\n"
	.string "ξαφνιάζουν και αναστατώνουν.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Προσέχει συνεχώς τα HP στη μάχη.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Ικανότητα στη συγκέντρωση και\n"
	.string "απελευθέρωση δύναμης.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Ικανότητα στην αποδυνάμωση των\n"
	.string "αντιπάλων.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Προτιμά τακτικές που βασίζονται\n"
	.string "στην τύχη.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Επιτίθεται με βασιλικό αέρα.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Επιτίθεται με ισχυρές κινήσεις\n"
	.string "χαμηλού PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Αποδυναμώνει και μετά επιτίθεται.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Μάχεται ενώ αντέχει όλες τις\n"
	.string "επιθέσεις.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Αναστατώνει συναισθηματικά τους\n"
	.string "αντιπάλους.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Χρησιμοποιεί ισχυρές και άμεσες\n"
	.string "κινήσεις.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Χρησιμοποιεί επιθετικά ισχυρές\n"
	.string "κινήσεις.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Μάχεται αποφεύγοντας έξυπνα τις\n"
	.string "επιθέσεις.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Ικανότητα στη χρήση κινήσεων που\n"
	.string "αναστατώνουν.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Χρησιμοποιεί πολλές δημοφιλείς\n"
	.string "κινήσεις.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Έχει κινήσεις για ισχυρούς\n"
	.string "συνδυασμούς.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Χρησιμοποιεί επιθέσεις υψηλής\n"
	.string "πιθανότητας.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Χρησιμοποιεί επιθετικά\n"
	.string "φαντασμαγορικές κινήσεις.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Δίνει έμφαση στην επίθεση έναντι\n"
	.string "της άμυνας.$"

BattleDome_Text_NotEnoughValidMonsLvOpen::
	.string "Γεια σου!\p"
	.string "Δεν έχεις τα τρία POKéMON που\n"
	.string "απαιτούνται για την είσοδο.\p"
	.string "Για να μπεις, πρέπει να φέρεις τρία\n"
	.string "διαφορετικά είδη POKéMON.\p"
	.string "Επίσης δεν πρέπει να κρατούν τα\n"
	.string "ίδια είδη αντικειμένων.\p"
	.string "Τα EGGS δεν γίνονται δεκτά.\p"
	.string "Όταν κάνεις τις προετοιμασίες σου,\n"
	.string "παρακαλώ ξαναέλα.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Δίνει έμφαση στην άμυνα έναντι\n"
	.string "της επίθεσης.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Επιτίθεται γρήγορα με ισχυρές\n"
	.string "κινήσεις.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Συχνά χρησιμοποιεί κινήσεις με\n"
	.string "πρόσθετα εφέ.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Χρησιμοποιεί μια ισορροπημένη\n"
	.string "ποικιλία κινήσεων.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Αυτό είναι το δείγμα μηνύματος 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Αυτό είναι το δείγμα μηνύματος 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Αυτό είναι το δείγμα μηνύματος 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Αυτό είναι το δείγμα μηνύματος 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Δίνει έμφαση σε HP και ATTACK.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Δίνει έμφαση σε HP και DEFENSE.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Δίνει έμφαση σε HP και SPEED.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Δίνει έμφαση σε HP και SP. ATTACK.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Δίνει έμφαση σε HP και SP. DEFENSE.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Δίνει έμφαση σε ATTACK και DEFENSE.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Δίνει έμφαση σε ATTACK και SPEED.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Δίνει έμφαση σε ATTACK και SP. ATK.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Δίνει έμφαση σε ATTACK και SP. DEF.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Δίνει έμφαση σε DEFENSE και SPEED.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Δίνει έμφαση σε DEFENSE και SP. ATK.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Δίνει έμφαση σε DEFENSE και SP. DEF.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Δίνει έμφαση σε SPEED και SP. ATK.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Δίνει έμφαση σε SPEED και SP. DEF.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Δίνει έμφαση σε SP. ATK και SP. DEF.$"

BattleDome_Text_EmphasizesHP::
	.string "Δίνει έμφαση στα HP.$"

BattleDome_Text_EmphasizesAtk::
	.string "Δίνει έμφαση στην ATTACK.$"

BattleDome_Text_EmphasizesDef::
	.string "Δίνει έμφαση στην DEFENSE.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Δίνει έμφαση στην SPEED.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Δίνει έμφαση στην SP. ATTACK.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Δίνει έμφαση στην SP. DEFENSE.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Παραμελεί HP και ATTACK.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Παραμελεί HP και DEFENSE.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Παραμελεί HP και SPEED.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Παραμελεί HP και SP. ATTACK.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Παραμελεί HP και SP. DEFENSE.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Παραμελεί ATTACK και DEFENSE.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Παραμελεί ATTACK και SPEED.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Παραμελεί ATTACK και SP. ATK.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Παραμελεί ATTACK και SP. DEF.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Παραμελεί DEFENSE και SPEED.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Παραμελεί DEFENSE και SP. ATK.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Παραμελεί DEFENSE και SP. DEF.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Παραμελεί SPEED και SP. ATK.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Παραμελεί SPEED και SP. DEF.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Παραμελεί SP. ATK και SP. DEF.$"

BattleDome_Text_NeglectsHP::
	.string "Παραμελεί τα HP.$"

BattleDome_Text_NeglectsAtk::
	.string "Παραμελεί την ATTACK.$"

BattleDome_Text_NeglectsDef::
	.string "Παραμελεί την DEFENSE.$"

BattleDome_Text_NeglectsSpeed::
	.string "Παραμελεί την SPEED.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Παραμελεί την SP. ATTACK.$"

BattleDome_Text_NeglectsSpDef::
	.string "Παραμελεί την SP. DEFENSE.$"

BattleDome_Text_SelectThreeMons::
	.string "Πολύ καλά, τώρα διάλεξε τα τρία\n"
	.string "POKéMON σου, παρακαλώ.$"

BattleDome_Text_WelcomeToBattleDome::
	.string "Σε καλωσορίζω στο BATTLE DOME!\p"
	.string "Είμαι ο οδηγός σου για τους αγώνες\n"
	.string "Challenge Cup Tournament!$"

BattleDome_Text_WaitWhileSaveGame::
	.string "Περίμενε όσο αποθηκεύω το παιχνίδι.$"

BattleDome_Text_ExplainBattleDome::
	.string "Το BATTLE DOME διοργανώνει το\n"
	.string "Challenge Cup Tournament.\p"
	.string "Όλοι οι συμμετέχοντες μπαίνουν με\n"
	.string "μια ομάδα τριών POKéMON.\p"
	.string "Από αυτά τα τρία POKéMON, πρέπει να\n"
	.string "διαλέξεις δύο για κάθε μάχη.\p"
	.string "Το POKéMON που δεν διάλεξες θα\n"
	.string "κρατηθεί για σένα προσωρινά.\p"
	.string "Αν νικήσεις τέσσερις αγώνες στη\n"
	.string "σειρά, θα γίνεις πρωταθλητής και\l"
	.string "θα λάβεις Battle Points.\p"
	.string "Αν θες να διακόψεις την πρόκληση,\n"
	.string "παρακαλώ αποθήκευσε το παιχνίδι.\p"
	.string "Αν δεν αποθηκεύσεις πριν διακόψεις,\n"
	.string "θα αποκλειστείς.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Εκπαιδεύει POKéMON ισορροπημένα.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Ας ξεκινήσει η μάχη!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "Ο {STR_VAR_1} νίκησε με {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "Ο {STR_VAR_1} έγινε πρωταθλητής!$"

BattleDome_Text_TrainerWonByDefault::
	.string "Ο {STR_VAR_1} νίκησε άνευ αγώνα!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "Ο {STR_VAR_1} νίκησε άνευ αγώνα!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "Ο {STR_VAR_1} νίκησε χωρίς κινήσεις!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "Ο {STR_VAR_1} νίκησε χωρίς κινήσεις!$"

BattleDome_Text_Round1Match1::
	.string "Γύρος 1, Αγώνας 1$"

BattleDome_Text_Round1Match2::
	.string "Γύρος 1, Αγώνας 2$"

BattleDome_Text_Round1Match3::
	.string "Γύρος 1, Αγώνας 3$"

BattleDome_Text_Round1Match4::
	.string "Γύρος 1, Αγώνας 4$"

BattleDome_Text_Round1Match5::
	.string "Γύρος 1, Αγώνας 5$"

BattleDome_Text_Round1Match6::
	.string "Γύρος 1, Αγώνας 6$"

BattleDome_Text_Round1Match7::
	.string "Γύρος 1, Αγώνας 7$"

BattleDome_Text_Round1Match8::
	.string "Round 1, Match 8$"

BattleDome_Text_Round2Match1::
	.string "Round 2, Match 1$"

BattleDome_Text_Round2Match2::
	.string "Round 2, Match 2$"

BattleDome_Text_Round2Match3::
	.string "Round 2, Match 3$"

BattleDome_Text_Round2Match4::
	.string "Round 2, Match 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal Match 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal Match 2$"

BattleDome_Text_FinalMatch::
	.string "Final Match$"
