PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Γεια σου, {PLAYER}!\p"
	.string "Μόλις έλαβα ένα πολύ σπάνιο BERRY.\n"
	.string "Θα ήθελα να το έχεις εσύ.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Αν δεις BERRIES να φυτρώνουν σε \n"
	.string "αργιλώδες χώμα, μη διστάσεις \l"
	.string "να τα πάρεις.\p"
	.string "Αλλά φρόντισε να φυτέψεις ένα \n"
	.string "BERRY στο ίδιο σημείο.\l"
	.string "Αυτό λέει η κοινή λογική.\p"
	.string "Ορίστε, θα το μοιραστώ μαζί σου.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Από την εμφάνισή σου, πρέπει \n"
	.string "να είσαι TRAINER, σωστά;\p"
	.string "Οι TRAINERS συχνά δίνουν στα \n"
	.string "POKéMON να κρατούν BERRIES.\p"
	.string "Στο χέρι σου είναι αν θα \n"
	.string "καλλιεργήσεις BERRIES \l"
	.string "ή αν θα τα χρησιμοποιήσεις.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Πότιζα τα φυτά κάθε μέρα.\n"
	.string "Έβγαλαν πολλά λουλούδια.\p"
	.string "Και μου έδωσαν πολλά BERRIES, επίσης.\p"
	.string "Ορίστε!\n"
	.string "Μπορείς να το πάρεις!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Θα προσπαθήσω πολύ να φτιάξω\n"
	.string "BERRIES σε διάφορα χρώματα.\p"
	.string "Ελπίζω να προσπαθήσεις κι εσύ!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Αναρωτιέμαι τι χρώμα BERRIES να\n"
	.string "ψάξω σήμερα;$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Μου αρέσει να χρησιμοποιώ τη μηχανή\n"
	.string "BERRY CRUSH, γι' αυτό μαζεύω BERRIES.\p"
	.string "Θα μοιραστώ ένα μαζί σου, αν θες.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Θα πρέπει να δοκιμάσεις τη μηχανή\n"
	.string "BERRY CRUSH με τους φίλους σου.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Ποιο BERRY πρέπει να φυτευτεί;\n"
	.string "Να χρησιμοποιώ ή να μαζεύω BERRIES;\p"
	.string "Είναι διασκεδαστικό να το σκέφτεσαι.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Τα BERRIES μεγαλώνουν απορροφώντας\n"
	.string "το ηλιακό φως.\p"
	.string "Βοηθάμε τα BERRIES να μεγαλώσουν\n"
	.string "ποτίζοντάς τα τακτικά.\p"
	.string "Είναι μια έκφραση αγάπης, έτσι;$"

Route120_Text_YesYouUnderstand:
	.string "Ναι, ναι.\n"
	.string "Καταλαβαίνεις τι εννοώ.\p"
	.string "Πάρε αυτό.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Ω... Αλλά είναι σημαντικό να βγάζεις\n"
	.string "τις δικές σου εντυπώσεις, υποθέτω...\p"
	.string "Μπορείς να πάρεις αυτό.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Πιστεύω ότι αυτό το BERRY είναι σπάνιο.\n"
	.string "Ελπίζω να το μεγαλώσεις με αγάπη.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Θα πάρω κι άλλα BERRIES από τον\n"
	.string "BERRY MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Όταν το καλοσκεφτείς...\p"
	.string "Όπως το κοστούμι ταιριάζει σε μένα,\n"
	.string "έτσι και το αεράκι ταιριάζει στη θάλασσα.\p"
	.string "Και σε σένα, ένα BERRY σου ταιριάζει\n"
	.string "γάντι...\p"
	.string "Γιατί άραγε;$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Όταν το καλοσκεφτείς...\p"
	.string "Επειδή είσαι TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Όταν το καλοσκεφτείς...\p"
	.string "Όπως η αξιοπρεπής απλότητα ταιριάζει\n"
	.string "σε μένα, έτσι και τα {POKEBLOCK}S\l"
	.string "ταιριάζουν τέλεια στα POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Μπορείς να με φωνάζεις BERRY MASTER.\p"
	.string "Ονειρεύομαι να γεμίσω τον κόσμο με\n"
	.string "όμορφα λουλούδια, γι' αυτό καλλιεργώ\l"
	.string "BERRIES και τα μοιράζω σε όλους.\p"
	.string "Σου αξίζει ένα!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Γιατί να είμαστε τσιγκούνηδες;\n"
	.string "Πάρε άλλο ένα!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Να πας οπωσδήποτε στο ανθοπωλείο\n"
	.string "PRETTY PETAL κοντά στη RUSTBORO.\p"
	.string "Ας γεμίσει ο κόσμος λουλούδια!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Τελείωσα για σήμερα.\n"
	.string "Έλα πάλι μια άλλη μέρα.\p"
	.string "Ας γεμίσει ο κόσμος λουλούδια!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Ο τρόπος που ο άντρας μου καλλιεργεί\n"
	.string "BERRIES... είναι ο καλύτερος στον κόσμο.\p"
	.string "Με κάνει περήφανη, στ' αλήθεια.\p"
	.string "Παρεμπιπτόντως, παιδί μου, έχεις\n"
	.string "ακούσει καμιά καλή κουβέντα τελευταία;$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Α! Τι αξιοσημείωτη κουβέντα!\n"
	.string "Πραγματικά εμπνευσμένη!\p"
	.string "Θέλω να σου δώσω αυτό.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Ω! Μια πολύ καλή κουβέντα.\n"
	.string "Είσαι πραγματικά αξιοσημείωτο άτομο.\p"
	.string "Θέλω να σου δώσω αυτό.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Τα τέσσερα εγγόνια μας θα πρέπει να\n"
	.string "γίνουν πιο ικανά από τον άντρα μου.\p"
	.string "Η χαρά δεν λείπει ποτέ από τη ζωή μου!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Α...$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Γεια!\p"
	.string "Αυτό είναι το ανθοπωλείο\n"
	.string "PRETTY PETAL.\p"
	.string "Σκορπίζουμε λουλούδια σε \n"
	.string "όλο τον κόσμο!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, θα ήθελες να μάθεις \n"
	.string "για τα BERRIES;$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Πώς σε λένε;\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Είναι ένα ωραίο όνομα.\p"
	.string "{PLAYER}{KUN}, θα ήθελες να μάθεις \n"
	.string "για τα BERRIES;$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Τα BERRIES φυτρώνουν σε δέντρα που\n"
	.string "ευδοκιμούν μόνο σε μαλακό χώμα.\p"
	.string "Αν πάρεις μερικά BERRIES, φρόντισε \n"
	.string "να φυτέψεις ένα ξανά στο χώμα.\p"
	.string "Ένα φυτεμένο BERRY θα βλαστήσει \n"
	.string "σύντομα, θα γίνει φυτό, θα \l"
	.string "ανθίσει όμορφα, και μετά \l"
	.string "θα βγάλει ξανά BERRIES.\p"
	.string "Θέλω να δω όλο τον κόσμο γεμάτο \n"
	.string "με όμορφα λουλούδια.\l"
	.string "Αυτό είναι το όνειρό μου.\p"
	.string "Σε παρακαλώ βοήθησέ με, {PLAYER}{KUN}.\n"
	.string "Φύτεψε BERRIES και φέρε \l"
	.string "περισσότερα λουλούδια στον \l"
	.string "κόσμο.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Τα λουλούδια φέρνουν τόση χαρά \n"
	.string "στους ανθρώπους, δεν συμφωνείς;$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Γεια!\p"
	.string "Όσο περισσότερη προσοχή δίνεις στα \n"
	.string "λουλούδια, τόσο πιο όμορφα \l"
	.string "ανθίζουν.\p"
	.string "Θα σου αρέσει να φροντίζεις \n"
	.string "λουλούδια. Είμαι σίγουρη. \l"
	.string "Μπορείς να το έχεις αυτό.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Όσο μεγαλώνουν τα φυτά BERRY,\n"
	.string "πότιζέ τα με το WAILMER PAIL.\p"
	.string "Α, και κάτι ακόμα.\p"
	.string "Αν δεν μαζέψεις τα BERRIES για \n"
	.string "καιρό, θα πέσουν στο έδαφος.\l"
	.string "Αλλά θα φυτρώσουν ξανά.\p"
	.string "Δεν είναι φοβερό;\n"
	.string "Σαν να έχουν τη θέληση να ζήσουν.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Προσπαθώ να μοιάσω στις μεγάλες \n"
	.string "αδελφές μου.\n"
	.string "Καλλιεργώ κι εγώ λουλούδια!\p"
	.string "Ορίστε!\n"
	.string "Είναι για σένα!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Μπορείς να φυτέψεις ένα BERRY και \n"
	.string "να το μεγαλώσεις, ή μπορείς να \l"
	.string "βάλεις ένα POKéMON να το \l"
	.string "κρατήσει.\p"
	.string "Αλλά τώρα έχουν μια μηχανή που\n"
	.string "ανακατεύει διάφορα BERRIES και \l"
	.string "φτιάχνει καραμέλες για POKéMON.\p"
	.string "Θέλω κι εγώ καραμέλα.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Γεια, πώς σε λένε;\p"
	.string "... ... ... ... ... ... ... ... ...\n"
	.string "Ωραία. Πολύ όμορφα!\p"
	.string "Το όνομά μου είναι KIRI.\p"
	.string "Η μαμά και ο μπαμπάς μου με ονόμασαν\n"
	.string "έτσι για να μεγαλώσω υγιής και με\l"
	.string "ζεστή καρδιά. Αυτό ευχήθηκαν.\p"
	.string "Μπορείς να πάρεις ένα από αυτά.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "Η KIRI θα σου δώσει κι αυτό το BERRY!\n"
	.string "Μου αρέσει πάρα πολύ!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Αναρωτιέμαι τι είδους ευχή κρύβεται\n"
	.string "στο δικό σου όνομα.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Άνοιξη, καλοκαίρι, φθινόπωρο, χειμώνας.\p"
	.string "Αν γεννήθηκες την άνοιξη, σου αρέσει η\n"
	.string "άνοιξη; Και αν γεννήθηκες το καλοκαίρι,\n"
	.string "σου αρέσει το καλοκαίρι;$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Τότε η KIRI γεννήθηκε το φθινόπωρο,\n"
	.string "γι' αυτό λατρεύω το φθινόπωρο!\p"
	.string "Ποια εποχή σου αρέσει;$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Ω...\n"
	.string "Δεν έχει σημασία...\p"
	.string "Υπάρχουν τόσα πολλά που θέλω να μάθω...$"
