PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Hi, {PLAYER}!\p"
	.string "I just received a very rare BERRY.\n"
	.string "I'd like you to have it.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Αν δεις BERRIES να φυτρώνουν σε \n"
	.string "αργιλώδες χώμα, μη διστάσεις \l"
	.string "να τα πάρεις.\p"
	.string "Αλλά φρόντισε να φυτέψεις ένα \n"
	.string "BERRY στο ίδιο σημείο.\l"
	.string "Αυτό λέει η κοινή λογική.\p"
	.string "Ορίστε, θα το μοιραστώ μαζί σου.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Από την εμφάνισή σου, πρέπει \n"
	.string "να είσαι TRAINER, σωστά;\p"
	.string "Οι TRAINERS συχνά δίνουν στα \n"
	.string "POKéMON να κρατούν BERRIES.\p"
	.string "Στο χέρι σου είναι αν θα \n"
	.string "καλλιεργήσεις BERRIES \l"
	.string "ή αν θα τα χρησιμοποιήσεις.$

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "I watered the plants every day.\n"
	.string "They grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go!\n"
	.string "You can have it!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "I'm going to try really hard and make\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you try hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "You should try the BERRY CRUSH\n"
	.string "machine with your friends.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Which BERRY should be planted?\n"
	.string "Should you use or hoard BERRIES?\p"
	.string "It's fun to think about.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help the BERRIES grow by watering\n"
	.string "them regularly.\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_YesYouUnderstand:
	.string "Yes, yes.\n"
	.string "You understand what I mean.\p"
	.string "You should take this.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… But it is important to make your\n"
	.string "own impressions, I guess…\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "I think that BERRY is rare.\n"
	.string "I hope you raise it with loving care.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "I'll get more BERRIES from\n"
	.string "the BERRY MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "When it gets right down to it…\p"
	.string "The same way suits suit me perfectly,\n"
	.string "a crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”…\p"
	.string "Why should that be so?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "When it gets right down to it…\p"
	.string "It's because you're a TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "When it gets right down to it…\p"
	.string "The way dignified simplicity suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise BERRIES\l"
	.string "and hand them out to everyone.\p"
	.string "You're deserving of one!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Why be stingy?\n"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Be sure to visit the PRETTY PETAL\n"
	.string "flower shop near RUSTBORO.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "I'm done for today.\n"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "The way my husband grows BERRIES,\n"
	.string "oh, he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard\n"
	.string "a good saying lately?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! What a remarkable saying!\n"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! A good saying it is.\n"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Our four grandchildren should become\n"
	.string "more accomplished than my husband.\p"
	.string "Joy never goes out of my life!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Γεια!\p"
	.string "Αυτό είναι το ανθοπωλείο\n"
	.string "PRETTY PETAL.\p"
	.string "Σκορπίζουμε λουλούδια σε \n"
	.string "όλο τον κόσμο!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, θα ήθελες να μάθεις \n"
	.string "για τα BERRIES;$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Πώς σε λένε;\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Είναι ένα ωραίο όνομα.\p"
	.string "{PLAYER}{KUN}, θα ήθελες να μάθεις \n"
	.string "για τα BERRIES;$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Τα BERRIES φυτρώνουν σε δέντρα που\n"
	.string "ευδοκιμούν μόνο σε μαλακό χώμα.\p"
	.string "Αν πάρεις μερικά BERRIES, φρόντισε \n"
	.string "να φυτέψεις ένα ξανά στο χώμα.\p"
	.string "Ένα φυτεμένο BERRY θα βλαστήσει \n"
	.string "σύντομα, θα γίνει φυτό, θα \l"
	.string "ανθίσει όμορφα, και μετά \l"
	.string "θα βγάλει ξανά BERRIES.\p"
	.string "Θέλω να δω όλο τον κόσμο γεμάτο \n"
	.string "με όμορφα λουλούδια.\l"
	.string "Αυτό είναι το όνειρό μου.\p"
	.string "Σε παρακαλώ βοήθησέ με, {PLAYER}{KUN}.\n"
	.string "Φύτεψε BERRIES και φέρε \l"
	.string "περισσότερα λουλούδια στον \l"
	.string "κόσμο.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Τα λουλούδια φέρνουν τόση χαρά \n"
	.string "στους ανθρώπους, δεν συμφωνείς;$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Γεια!\p"
	.string "Όσο περισσότερη προσοχή δίνεις στα \n"
	.string "λουλούδια, τόσο πιο όμορφα \l"
	.string "ανθίζουν.\p"
	.string "Θα σου αρέσει να φροντίζεις \n"
	.string "λουλούδια. Είμαι σίγουρη. \l"
	.string "Μπορείς να το έχεις αυτό.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Όσο μεγαλώνουν τα φυτά BERRY,\n"
	.string "πότιζέ τα με το WAILMER PAIL.\p"
	.string "Α, και κάτι ακόμα.\p"
	.string "Αν δεν μαζέψεις τα BERRIES για \n"
	.string "καιρό, θα πέσουν στο έδαφος.\l"
	.string "Αλλά θα φυτρώσουν ξανά.\p"
	.string "Δεν είναι φοβερό;\n"
	.string "Σαν να έχουν τη θέληση να ζήσουν.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Προσπαθώ να μοιάσω στις μεγάλες \n"
	.string "αδελφές μου.\n"
	.string "Καλλιεργώ κι εγώ λουλούδια!\p"
	.string "Ορίστε!\n"
	.string "Είναι για σένα!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Μπορείς να φυτέψεις ένα BERRY και \n"
	.string "να το μεγαλώσεις, ή μπορείς να \l"
	.string "βάλεις ένα POKéMON να το \l"
	.string "κρατήσει.\p"
	.string "Αλλά τώρα έχουν μια μηχανή που\n"
	.string "ανακατεύει διάφορα BERRIES και \l"
	.string "φτιάχνει καραμέλες για POKéMON.\p"
	.string "Θέλω κι εγώ καραμέλα.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hi, what's your name?\p"
	.string "… … …  … … …  … … …\n"
	.string "Okay. That's nice!\p"
	.string "My name is KIRI.\p"
	.string "My mommy and daddy named me that so\n"
	.string "I would grow healthy and warmhearted.\l"
	.string "That's what they wished.\p"
	.string "You can have one of these.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI will give you this BERRY, too!\n"
	.string "I really like it lots!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "I wonder what kind of wish is included\n"
	.string "in your name.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you're born in springtime, do you like\n"
	.string "the spring, and if you're born in the\l"
	.string "summer, do you like the summer?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Then KIRI was born in the autumn,\n"
	.string "so I love the autumn!\p"
	.string "Which season do you like?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "It doesn't matter…\p"
	.string "There's so much that I want to know…$"
