gText_Birch_Welcome::
	.string "Γεια! Συγγνώμη που σε έκανα να\n"
	.string "περιμένεις!\p"
	.string "Καλώς ήρθες στον κόσμο των POKéMON!\p"
	.string "Το όνομά μου είναι BIRCH.\p"
	.string "Αλλά όλοι με φωνάζουν καθηγητή\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Αυτό το ονομάζουμε “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Αυτός ο κόσμος κατοικείται από\n"
	.string "πλάσματα γνωστά ως POKéMON.\p"
	.string "Εμείς οι άνθρωποι ζούμε μαζί τους,\n"
	.string "μερικές φορές ως φίλοι, \l"
	.string "και άλλες ως συνεργάτες στη δουλειά.\p"
	.string "Και μερικές φορές, ενωνόμαστε και\n"
	.string "μαχόμαστε άλλους σαν εμάς.\p"
	.string "Μα παρά την εγγύτητά μας, δεν ξέρουμε\n"
	.string "τα πάντα για τα POKéMON.\p"
	.string "Στην πραγματικότητα, υπάρχουν πολλά\n"
	.string "μυστικά γύρω από τα POKéMON.\p"
	.string "Για να λύσω τα μυστήριά τους,\n"
	.string "κάνω έρευνα.\l"
	.string "Αυτό κάνω.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Και εσύ είσαι;$"

gText_Birch_BoyOrGirl::
	.string "Είσαι αγόρι;\n"
	.string "Ή είσαι κορίτσι;$"

gText_Birch_WhatsYourName::
	.string "Μάλιστα.\n"
	.string "Πώς σε λένε;$"

gText_Birch_SoItsPlayer::
	.string "Οπότε σε λένε {PLAYER}{KUN};$"

gText_Birch_YourePlayer::
	.string "Α, εντάξει!\p"
	.string "Εσύ είσαι που μετακομίζεις στην\n"
	.string "πόλη μου, το LITTLEROOT.\l"
	.string "Τώρα κατάλαβα!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Εντάξει, όλα έτοιμα;\p"
	.string "Η περιπέτειά σου ξετυλίγεται εδώ\p"
	.string "Πάρε θάρρος και μπες στον κόσμο\n"
	.string "των POKéMON όπου όνειρα, περιπέτειες\l"
	.string "και φιλίες σε περιμένουν!\p"
	.string "Λοιπόν, θα σε περιμένω αργότερα.\n"
	.string "Έλα να με δεις στο POKéMON LAB μου.\p"
	.string "$"
