BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BLEND MASTER: Πράγματι, εγώ είμαι!\n"
	.string "Ο BLEND MASTER είμαι εγώ!\p"
	.string "Ανακάτεψε μαζί μου και θα δεις\n"
	.string "τι σημαίνει αυθεντία στο blend!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MASTER: Χμμμ! Θέλεις λοιπόν\n"
	.string "να δεις την τέχνη μου στην πράξη;$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Χμμμ!\p"
	.string "Είσαι πολυάσχολος/η τώρα, βλέπω!\p"
	.string "Αλλά μη φοβάσαι!\n"
	.string "Θα είμαι εδώ όλη μέρα!\l"
	.string "Γύρνα γρήγορα μόλις τελειώσεις!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Χμμμ!\p"
	.string "Δεν έχεις ούτε μία BERRY!\p"
	.string "Θα είμαι εδώ όλη μέρα!\n"
	.string "Γύρνα γρήγορα με μερικές BERRIES!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Φυσικά!\n"
	.string "Φυσικά!\p"
	.string "Παρεμπιπτόντως...\n"
	.string "Ξέρεις πώς να φτιάχνεις {POKEBLOCK}S\l"
	.string "από BERRIES;$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Χμμμ!\p"
	.string "Μα είναι μια απλή διαδικασία!\p"
	.string "Όταν το βέλος του BLENDER έρθει\n"
	.string "στον δείκτη σου, πάτα το κουμπί Α.\p"
	.string "Αυτό είναι όλο που πρέπει να κάνεις.\p"
	.string "Όταν δεις με τι ακρίβεια πατάω το\n"
	.string "κουμπί Α, θα καταλάβεις.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Ωραία!\p"
	.string "Ας ξεκινήσουμε, λοιπόν!\p"
	.string "Όλοι μαζί με τον BLEND MASTER,\n"
	.string "πάμε για BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Χμμμ!\p"
	.string "Φαίνεται πως δεν έχεις πάρει ακόμα\n"
	.string "τη {POKEBLOCK} CASE!\p"
	.string "Θα είμαι εδώ όλη μέρα!\n"
	.string "Πάρε τη {POKEBLOCK} CASE και έλα!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Χμμμ!\p"
	.string "Η {POKEBLOCK} CASE σου είναι γεμάτη!\p"
	.string "Θα είμαι εδώ όλη μέρα!\n"
	.string "Φάε μερικά {POKEBLOCK}S και έλα!$"

BerryBlender_Text_WhoaAwesome:
	.string "Ουάου!\n"
	.string "Απίστευτα!$"

BerryBlender_Text_WickedlyFast:
	.string "Τρελή ταχύτητα!$"

BerryBlender_Text_WhatAnExpert:
	.string "Τι ειδικός!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Όταν ανακάτεψα με τον MASTER,\n"
	.string "φτιάξαμε απίθανα {POKEBLOCK}S!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Μάτια που παρακολουθούν το βέλος\n"
	.string "με μηχανική ένταση...\p"
	.string "Ένα χέρι που πατάει το κουμπί Α\n"
	.string "με απόλυτη ακρίβεια...\p"
	.string "Αυτά τα χαρίσματα κάνουν τον\n"
	.string "BLEND MASTER πραγματικά σπουδαίο.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Λένε πως ο BLEND MASTER εξασκεί τις\n"
	.string "ικανότητές του βαθιά στα βουνά.\p"
	.string "Μερικές φορές έρχεται στη LILYCOVE\n"
	.string "να ανακατεύει BERRIES όλη μέρα.$"
