CableClub_Text_WelcomeWhichCableClubService:
	.string "Καλώς ήρθες στο POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Ποια από τις υπηρεσίες μας θέλεις\n"
	.string "να χρησιμοποιήσεις;$"

CableClub_Text_WhichService:
	.string "Ποια από τις υπηρεσίες μας θέλεις\n"
	.string "να χρησιμοποιήσεις;$"

CableClub_Text_TradeUsingLinkCable::
	.string "Αντάλλαξε POKéMON με άλλον παίκτη\n"
	.string "μέσω GBA Game Link cable.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Μπορείς να μονομαχήσεις με TRAINER\n"
	.string "μέσω GBA Game Link cable.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Μπορείς να πας στο RECORD CORNER\n"
	.string "με άλλους μέσω GBA Game Link cable.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Κλείσιμο αυτού του μενού.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Για DOUBLE BATTLE, πρέπει να\n"
	.string "έχεις τουλάχιστον δύο POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Για ανταλλαγή, πρέπει να έχεις\n"
	.string "τουλάχιστον δύο POKéMON μαζί σου.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Ένα POKéMON που κρατάει {STR_VAR_1}\n"
	.string "BERRY δεν μπορεί να ανταλλαγεί.$"

gText_PleaseWaitForLink::
	.string "Παρακαλώ περίμενε.\n"
	.string "… … B Button: Άκυρο$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Όταν όλοι οι παίκτες είναι έτοιμοι…\n"
	.string "A Button: Επιβεβαίωση\l"
	.string "B Button: Άκυρο$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Σύνδεση με {STR_VAR_1} παίκτες.\n"
	.string "A Button: Επιβεβαίωση\l"
	.string "B Button: Άκυρο$"

gText_AwaitingLinkup::
	.string "Αναμονή σύνδεσης…\n"
	.string "… … B Button: Άκυρο$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Πρέπει να αποθηκεύσεις πριν τη\n"
	.string "σύνδεση. Θέλεις να αποθηκεύσεις;$"

CableClub_Text_PleaseEnter:
	.string "Παρακαλώ περάστε.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Θα σε οδηγήσω στο δωμάτιό σου τώρα.$"

Text_SomeoneIsNotReadyToLink:
	.string "Κάποιος δεν είναι έτοιμος.\p"
	.string "Παρακαλώ έλα πάλι όταν όλοι\n"
	.string "έχουν ετοιμαστεί.$"

Text_LinkErrorPleaseReset:
	.string "Λυπάμαι, υπήρξε σφάλμα σύνδεσης…\n"
	.string "Κάνε reset και προσπάθησε πάλι.$"

Text_PlayersMadeDifferentSelections:
	.string "Οι άλλοι παίκτες φαίνεται πως\n"
	.string "έκαναν διαφορετικές επιλογές.$"

CableClub_Text_PleaseVisitAgain:
	.string "Σε παρακαλώ, έλα ξανά.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Ο αριθμός των συμμετεχόντων\n"
	.string "είναι λανθασμένος.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Το SINGLE BATTLE Mode δεν μπορεί\n"
	.string "να παιχτεί από {STR_VAR_1} παίκτες.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Το DOUBLE BATTLE Mode δεν μπορεί\n"
	.string "να παιχτεί από {STR_VAR_1} παίκτες.$"

CableClub_Text_NeedFourPlayers:
	.string "Πρέπει να υπάρχουν τέσσερις παίκτες\n"
	.string "για αυτό το Battle Mode.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Επιβεβαίωσε τον αριθμό των παικτών\n"
	.string "και προσπάθησε ξανά.$"

Text_TerminateLinkConfirmation:
	.string "Η σύνδεση θα τερματιστεί αν βγεις\n"
	.string "από το δωμάτιο. Είναι εντάξει;$"

Text_TerminateLinkPleaseWait:
	.string "Τερματισμός σύνδεσης…\n"
	.string "Θα σε συνοδεύσω έξω από\l"
	.string "το δωμάτιο. Περίμενε.$"

CableClub_Text_TooBusyToNotice:
	.string "Αυτός ο TRAINER έχει πολλή δουλειά\n"
	.string "και δεν σε προσέχει καν…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Τέλεια! Είδα την TRAINER CARD\n"
	.string "του/της {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Τέλεια! Είδα την TRAINER CARD\n"
	.string "του/της {STR_VAR_1}!\p"
	.string "Είναι μια {STR_VAR_2} κάρτα!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Παρακαλώ πάρτε θέση και\n"
	.string "ξεκινήστε τη μάχη σας.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Παρακαλώ καθίστε στη θέση σας\n"
	.string "και ξεκινήστε την ανταλλαγή.$"

RecordCorner_Text_ThanksForComing:
	.string "Ευχαριστώ που ήρθες.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Τα δεδομένα της TRAINER CARD\n"
	.string "θα αντικατασταθούν.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Ελπίζω να σε ξαναδώ!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Λυπάμαι πολύ.\p"
	.string "Δεν είμαστε έτοιμοι για ανταλλαγές\n"
	.string "με TRAINERS από άλλη περιοχή ακόμη…$"

CableClub_Text_OtherTrainerNotReady:
	.string "Ο άλλος TRAINER δεν είναι έτοιμος.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Έχεις τουλάχιστον ένα POKéMON\n"
	.string "που δεν μπορεί να εισέλθει.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Παρακαλώ καθίστε και περιμένετε.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "Ο/Η {STR_VAR_1} έστειλε ένα\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Σφάλμα μετάδοσης.\p"
	.string "Δεν μπορείς να αναμίξεις αρχεία με\n"
	.string "ιαπωνικές Ruby ή Sapphire.\p"
	.string "Επίσης, δεν μπορείς ταυτόχρονα με\n"
	.string "ιαπωνική Emerald και ξένες Ruby\l"
	.string "ή Sapphire.$"

CableClub_Text_AdapterNotConnected:
	.string "Ο Wireless Adapter δεν είναι\n"
	.string "συνδεδεμένος σωστά.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Οι συμμετέχοντες παρακαλούνται\n"
	.string "να προσέλθουν στη ρεσεψιόν.$"

@ Unused
CableClub_Text_Hello:
	.string "Γεια σου!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Παρακαλώ περίμενε.$"

CableClub_Text_YouMayTradeHere::
	.string "Μπορείς να ανταλλάξεις POKéMON\n"
	.string "εδώ με άλλον TRAINER.$"

CableClub_Text_YouMayBattleHere::
	.string "Μπορείς να μονομαχήσεις με τους\n"
	.string "φίλους σου εδώ.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Δύο έως πέντε TRAINERS μπορούν να\n"
	.string "φτιάξουν BERRY POWDER μαζί.$"

CableClub_Text_CanMixRecords::
	.string "Τα αρχεία δύο έως τεσσάρων παικτών\n"
	.string "μπορούν να αναμιχθούν μαζί.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Οδηγός για τις υπηρεσίες του\n"
	.string "WIRELESS CLUB.$"

CableClub_Text_CancelSelectedItem::
	.string "Ακυρώνει το επιλεγμένο MENU.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Ποιο battle mode προτιμάς;$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Επιστρέφει στο προηγούμενο βήμα.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Για το BERRY CRUSH, πρέπει να\n"
	.string "έχεις τουλάχιστον μία BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Για να μπεις στο UNION ROOM, πρέπει\n"
	.string "να έχεις τουλάχιστον δύο POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Κανένα POKéMON με {STR_VAR_1} BERRY\n"
	.string "δεν επιτρέπεται στο UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Αυτό είναι το UNION ROOM του\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Δυστυχώς, ο Wireless Adapter δεν\n"
	.string "είναι συνδεδεμένος σωστά.\p"
	.string "Παρακαλώ, έλα ξανά.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Ω…\n"
	.string "Με συγχωρείς!$"

CableClub_Text_PlayerIsWaiting:
	.string "Φαίνεται πως ο/η {STR_VAR_1} παίζει\n"
	.string "αυτή τη στιγμή.\l"
	.string "Δώσε τα όλα!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Μπορώ να σου εξηγήσω τους κανόνες,\n"
	.string "αν θέλεις.\p"
	.string "Ποιο παιχνίδι να σου περιγράψω;$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON JUMP”\p"
	.string "Κάνε το POKéMON σου να πηδήξει το\n"
	.string "VINE WHIP με το κουμπί A.\p"
	.string "Μόνο μικρά POKéMON έως 28 ίντσες\n"
	.string "μπορούν να συμμετάσχουν.\p"
	.string "POKéMON που μόνο κολυμπούν, σκάβουν\n"
	.string "ή πετούν, δεν πηδούν καλά.\p"
	.string "Έτσι, αυτά τα POKéMON δεν μπορούν\n"
	.string "να συμμετάσχουν.\p"
	.string "Κάτι καλό συμβαίνει αν όλοι\n"
	.string "πηδήξουν συγχρονισμένα.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Έλεγξε τα τρία κεφάλια του DODRIO\n"
	.string "για να πιάσεις τις BERRIES.\p"
	.string "Πάτα δεξιά, πάνω, ή αριστερά στο\n"
	.string "{PLUS} Control Pad για τα κεφάλια.\p"
	.string "Για να παίξεις, πρέπει να έχεις\n"
	.string "έναν DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Αν θέλεις να παίξεις παιχνίδι,\n"
	.string "μίλα στον παππού δίπλα μου.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Γεια, καλώς ήρθες!\n"
	.string "Ήρθες για παιχνίδια με\n"
	.string "Wireless Communication;\p"
	.string "Μπορείς να περιμένεις λίγο;$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Εντάξει, έλα ξανά!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "Ο Wireless Adapter δεν είναι εδώ.\n"
	.string "Έλα πάλι όταν συνδεθεί!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Ωραία, ποιο παιχνίδι ήθελες\n"
	.string "να παίξεις;$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Ποιο POKéMON θα ήθελες να\n"
	.string "δηλώσεις;$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Ωραία, είσαι έτοιμος/η.\n"
	.string "Μην αφήσεις τους άλλους να νικήσουν!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Φεύγεις ήδη;\n"
	.string "Να μας ξαναέρθεις!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Φαίνεται πως δεν έχεις κάποιο\n"
	.string "POKéMON που μπορεί να δηλωθεί…\p"
	.string "Θέλεις να σου εξηγήσω τι είδους\n"
	.string "POKéMON μπορούν να συμμετάσχουν;$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "Το “POKéMON JUMP” είναι για\n"
	.string "POKéMON έως 28 ίντσες.\p"
	.string "Αυτά που δεν μπαίνουν είναι\n"
	.string "POKéMON που δεν πηδούν.\p"
	.string "Ξέρεις, POKéMON που μόνο\n"
	.string "κολυμπούν, σκάβουν ή πετούν.\p"
	.string "Αυτά είναι όλα που πρέπει να ξέρεις.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "Το DODRIO BERRY-PICKING είναι\n"
	.string "μόνο για DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Μπορείς να το ξαναδοκιμάσεις\n"
	.string "από την αρχή, παρακαλώ;$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Καλώς ήρθες στο DIRECT CORNER του\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Εδώ μπορείς να αλληλεπιδράσεις\n"
	.string "απευθείας με τους φίλους σου.\p"
	.string "Σε ποιο δωμάτιο θέλεις να μπεις;$"

CableClub_Text_TradePokemon:
	.string "Θέλεις να ανταλλάξεις POKéMON;$"

CableClub_Text_PlayWhichBattleMode:
	.string "Ποιο Battle Mode θα ήθελες\n"
	.string "να παίξεις;$"

CableClub_Text_AccessRecordCorner:
	.string "Θέλεις πρόσβαση στο RECORD CORNER;$"

CableClub_Text_UseBerryCrush:
	.string "Θέλεις να χρησιμοποιήσεις το\n"
	.string "σύστημα BERRY CRUSH;$"

CableClub_Text_ExplainBattleModes:
	.string "Υπάρχουν τρία Battle Modes.\p"
	.string "Το SINGLE BATTLE είναι για δύο\n"
	.string "TRAINERS με ένα ή περισσότερα POKéMON.\p"
	.string "Κάθε TRAINER έχει ένα POKéMON\n"
	.string "στη μάχη κάθε φορά.\p"
	.string "Το DOUBLE BATTLE είναι για δύο\n"
	.string "TRAINERS με δύο ή περισσότερα POKéMON.\p"
	.string "Κάθε TRAINER στέλνει δύο POKéMON\n"
	.string "στη μάχη κάθε φορά.\p"
	.string "Το MULTI BATTLE είναι για τέσσερις\n"
	.string "TRAINERS με ένα ή περισσότερα POKéMON.\p"
	.string "Κάθε TRAINER έχει ένα POKéMON\n"
	.string "στη μάχη κάθε φορά.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Αποφασίστε ποιος από τους δύο\n"
	.string "θα γίνει ο LEADER.\p"
	.string "Ο άλλος παίκτης πρέπει να\n"
	.string "επιλέξει “JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Αποφασίστε ποιος από τους τέσσερις\n"
	.string "θα γίνει ο GROUP LEADER.\p"
	.string "Οι άλλοι παίκτες πρέπει να\n"
	.string "επιλέξουν “JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Αποφασίστε ποιος από εσάς\n"
	.string "θα γίνει ο GROUP LEADER.\p"
	.string "Οι άλλοι παίκτες πρέπει να\n"
	.string "επιλέξουν “JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Καλώς ήρθες στο UNION ROOM του\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Εδώ μπορείς να αλληλεπιδράσεις\n"
	.string "με άλλους TRAINERS, ακόμα και\l"
	.string "με κάποιους που δεν γνωρίζεις.\p"
	.string "Θέλεις να μπεις στο δωμάτιο;$"

CableClub_Text_UnionRoomInfo:
	.string "Οι TRAINERS στο UNION ROOM είναι\n"
	.string "οι παίκτες γύρω σου που έχουν\l"
	.string "μπει επίσης στο δωμάτιο.\p"
	.string "Μπορείς να κάνεις διάφορα πράγματα\n"
	.string "εδώ, όπως να χαιρετήσεις άλλους.\p"
	.string "Μπορείς να δηλώσεις δύο POKéMON\n"
	.string "έως Lv. 30 για μια γρήγορη μάχη.\p"
	.string "Μπορείς να συνομιλήσεις με δύο\n"
	.string "έως πέντε άτομα.\p"
	.string "Ή να δηλώσεις ένα POKéMON για\n"
	.string "ανταλλαγή.\p"
	.string "Θέλεις να μπεις στο δωμάτιο;$"

CableClub_Text_EnjoyUnionRoom:
	.string "Ελπίζω να περάσεις καλά στο\n"
	.string "UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Γεια σου!\n"
	.string "Το όνομά μου είναι TEALA.\p"
	.string "Πρέπει να είναι η πρώτη σου φορά\n"
	.string "εδώ πάνω.\p"
	.string "Θα σου δείξω πώς λειτουργεί το\n"
	.string "Wireless Communication System.\p"
	.string "Πρώτα, πρέπει να σου δείξω αυτόν\n"
	.string "τον όροφο του POKéMON CENTER.\p"
	.string "Από εδώ, παρακαλώ.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Στον επάνω όροφο, υπάρχουν δύο\n"
	.string "δωμάτια.\p"
	.string "Πρώτα, το δωμάτιο στα αριστερά.\n"
	.string "Είναι το UNION ROOM.\p"
	.string "Εκεί συνδέεσαι με TRAINERS γύρω\n"
	.string "σου που έχουν μπει επίσης στο\l"
	.string "UNION ROOM.\p"
	.string "Μαζί τους μπορείς να συζητήσεις,\n"
	.string "να μονομαχήσεις και να κάνεις\l"
	.string "ανταλλαγές.\p"
	.string "Δεύτερον, το δωμάτιο στα δεξιά\n"
	.string "είναι το DIRECT CORNER.\p"
	.string "Εκεί ανταλλάσσεις ή μάχεσαι με\n"
	.string "POKéMON με τους φίλους σου.\p"
	.string "Αν ο Wireless Adapter δεν είναι\n"
	.string "συνδεδεμένος, μπορείς ακόμα να\l"
	.string "συνδεθείς με GBA Game Link cable.\p"
	.string "Σε αυτή την περίπτωση, πρέπει να\n"
	.string "πας στο DIRECT CORNER.\p"
	.string "Ελπίζω να απολαύσεις το Wireless\n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking:
	.string "Γεια σου, {PLAYER}!\p"
	.string "Είμαι η TEALA, η υπάλληλος του\n"
	.string "2ου ορόφου του POKéMON CENTER.\p"
	.string "Υπάρχει κάτι που θα ήθελες να\n"
	.string "ρωτήσεις για τη σύνδεση;$"

CableClub_Text_ExplainWirelessClub:
	.string "Ας εξηγήσω πώς λειτουργεί το\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Σε αυτόν, τον επάνω όροφο, υπάρχουν\n"
	.string "δύο δωμάτια.\p"
	.string "Πρώτα, το δωμάτιο στα αριστερά.\n"
	.string "Είναι το UNION ROOM.\p"
	.string "Εκεί συνδέεσαι με TRAINERS γύρω\n"
	.string "σου που έχουν μπει επίσης στο\l"
	.string "UNION ROOM.\p"
	.string "Μαζί τους μπορείς να συζητήσεις,\n"
	.string "να μονομαχήσεις και να κάνεις\l"
	.string "ανταλλαγές.\p"
	.string "Δεύτερον, το δωμάτιο στα δεξιά\n"
	.string "είναι το DIRECT CORNER.\p"
	.string "Εκεί ανταλλάσσεις ή μάχεσαι με\n"
	.string "POKéMON με τους φίλους σου.\p"
	.string "Μερικές φορές, ίσως να μην μπορείς\n"
	.string "να βρεις τους φίλους σου στο\l"
	.string "UNION ROOM ή στο DIRECT CORNER.\p"
	.string "Σε αυτή την περίπτωση, πλησίασε\n"
	.string "πιο κοντά στους φίλους σου.\p"
	.string "Αν ο Wireless Adapter δεν είναι\n"
	.string "συνδεδεμένος, μπορείς ακόμα να\l"
	.string "συνδεθείς με GBA Game Link cable.\p"
	.string "Σε αυτή την περίπτωση, πρέπει να\n"
	.string "πας στο DIRECT CORNER.\p"
	.string "Ελπίζω να απολαύσεις το Wireless\n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Ελπίζω να απολαύσεις το Wireless\n"
	.string "Communication System.$"
