Text_PictureBookShelf:
	.string "Υπάρχουν εικονογραφημένα βιβλία\n"
	.string "POKéMON.$"

Text_BookShelf:
	.string "Είναι γεμάτη με κάθε είδους βιβλία.$"

Text_PokemonCenterBookShelf:
	.string "Περιοδικά POKéMON!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "Αυτό το βάζο φαίνεται ακριβό…\n"
	.string "Μια ματιά στο εσωτερικό…\p"
	.string "Όμως, ήταν άδειο.$"

Text_EmptyTrashCan:
	.string "Είναι άδειο.$"

Text_ShopShelf:
	.string "Τα ράφια είναι γεμάτα με κάθε\n"
	.string "είδους προϊόντα POKéMON.$"

Text_Blueprint:
	.string "Κάποιου είδους προσχέδιο;\n"
	.string "Είναι πολύ περίπλοκο!$"
