@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Μια κίνηση με μεγάλη απήχηση.$"

gText_UserMoreEasilyStartled::
	.string "Μετά από αυτή την κίνηση, ο χρήστης\n"
	.string "ξαφνιάζεται πιο εύκολα.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Μεγάλη απήχηση, αλλά δεν επιτρέπει\n"
	.string "άλλη κίνηση μέχρι το τέλος.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Μπορεί να χρησιμοποιηθεί επανειλημμένα\n"
	.string "χωρίς να βαρεθεί ο JUDGE.$"

gText_AvoidStartledByOthersOnce::
	.string "Αποφεύγει να ξαφνιαστεί από\n"
	.string "άλλους μία φορά.$"

gText_AvoidStartledByOthers::
	.string "Μπορεί να αποφύγει να ξαφνιαστεί\n"
	.string "από άλλους.$"

gText_AvoidStartledByOthersLittle::
	.string "Μπορεί να αποφύγει λίγο να\n"
	.string "ξαφνιαστεί από άλλους.$"

gText_UserLessLikelyStartled::
	.string "Μετά από αυτή την κίνηση, ο χρήστης\n"
	.string "ξαφνιάζεται λιγότερο εύκολα.$"

gText_SlightlyStartleFrontMon::
	.string "Ξαφνιάζει ελαφρώς το\n"
	.string "POKéMON που βρίσκεται μπροστά.$"

gText_SlightlyStartleAppealed::
	.string "Ξαφνιάζει ελαφρώς όσα έχουν\n"
	.string "κάνει ήδη απήχηση.$"

gText_StartleAppealedBeforeUser::
	.string "Ξαφνιάζει τα POKéMON που\n"
	.string "έκαναν απήχηση πριν τον χρήστη.$"

gText_StartleAllAppealed::
	.string "Ξαφνιάζει όλα τα POKéMON\n"
	.string "που έχουν κάνει την απήχησή τους.$"

gText_BadlyStartleFrontMon::
	.string "Ξαφνιάζει έντονα το\n"
	.string "POKéMON που βρίσκεται μπροστά.$"

gText_BadlyStartleAppealed::
	.string "Ξαφνιάζει έντονα όσα έχουν\n"
	.string "κάνει ήδη απήχηση.$"

gText_StartleAppealedBeforeUser2::
	.string "Ξαφνιάζει τα POKéMON που\n"
	.string "έκαναν απήχηση πριν τον χρήστη.$"

gText_StartleAllAppealed2::
	.string "Ξαφνιάζει όλα τα POKéMON\n"
	.string "που έχουν κάνει την απήχησή τους.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Αποσπά την προσοχή του JUDGE\n"
	.string "από τους άλλους.$"

gText_StartleMonHasJudgesAttention::
	.string "Ξαφνιάζει το POKéMON που έχει\n"
	.string "τραβήξει την προσοχή του JUDGE.$"

gText_JamOthersMissesTurn::
	.string "Εμποδίζει τους άλλους και χάνει\n"
	.string "μία σειρά απήχησης.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Ξαφνιάζει τα POKéMON που έκαναν\n"
	.string "απήχηση του ίδιου τύπου.$"

gText_BadlyStartleCoolAppeals::
	.string "Ξαφνιάζει έντονα τα POKéMON\n"
	.string "που έκαναν COOL απήχηση.$"

gText_BadlyStartleBeautyAppeals::
	.string "Ξαφνιάζει έντονα τα POKéMON\n"
	.string "που έκαναν BEAUTY απήχηση.$"

gText_BadlyStartleCuteAppeals::
	.string "Ξαφνιάζει έντονα τα POKéMON\n"
	.string "που έκαναν CUTE απήχηση.$"

gText_BadlyStartleSmartAppeals::
	.string "Ξαφνιάζει έντονα τα POKéMON\n"
	.string "που έκαναν SMART απήχηση.$"

gText_BadlyStartleToughAppeals::
	.string "Ξαφνιάζει έντονα τα POKéMON\n"
	.string "που έκαναν TOUGH απήχηση.$"

gText_MakeMonAfterUserNervous::
	.string "Κάνει νευρικό ένα POKéMON\n"
	.string "μετά τον χρήστη.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Κάνει νευρικά όλα τα POKéMON\n"
	.string "μετά τον χρήστη.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Χειροτερεύει την κατάσταση\n"
	.string "όσων έκαναν ήδη απήχηση.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Ξαφνιάζει έντονα τα POKéMON\n"
	.string "σε καλή κατάσταση.$"

gText_AppealGreatIfPerformedFirst::
	.string "Η απήχηση λειτουργεί τέλεια αν\n"
	.string "εκτελεστεί πρώτη.$"

gText_AppealGreatIfPerformedLast::
	.string "Η απήχηση λειτουργεί τέλεια αν\n"
	.string "εκτελεστεί τελευταία.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Κάνει την απήχηση εξίσου καλή\n"
	.string "με τις προηγούμενες.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Κάνει την απήχηση εξίσου καλή\n"
	.string "με την αμέσως προηγούμενη.$"

gText_AppealBetterLaterItsPerformed::
	.string "Η απήχηση πάει καλύτερα όσο\n"
	.string "πιο αργά εκτελεστεί.$"

gText_AppealVariesDependingOnTiming::
	.string "Η ποιότητα της απήχησης ποικίλλει\n"
	.string "ανάλογα με τον χρόνο της.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Λειτουργεί καλά αν είναι του ίδιου\n"
	.string "τύπου με την προηγούμενη.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Λειτουργεί καλά αν διαφέρει σε\n"
	.string "τύπο από την προηγούμενη.$"

gText_AffectedByAppealInFront::
	.string "Επηρεάζεται από το πόσο καλά\n"
	.string "πήγε η προηγούμενη απήχηση.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Βελτιώνει την κατάσταση του χρήστη.\n"
	.string "Βοηθά στην πρόληψη νευρικότητας.$"

gText_AppealWorksWellIfConditionGood::
	.string "Η απήχηση πετυχαίνει αν ο χρήστης\n"
	.string "είναι σε καλή κατάσταση.$"

gText_NextAppealMadeEarlier::
	.string "Η επόμενη απήχηση μπορεί να γίνει\n"
	.string "νωρίτερα στον επόμενο γύρο.$"

gText_NextAppealMadeLater::
	.string "Η επόμενη απήχηση μπορεί να γίνει\n"
	.string "αργότερα στον επόμενο γύρο.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Κάνει τη σειρά του επόμενου γύρου\n"
	.string "να ανακατεύεται πιο εύκολα.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Ανακατεύει τη σειρά των απηχήσεων\n"
	.string "στον επόμενο γύρο.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Μια απήχηση που ενθουσιάζει το\n"
	.string "κοινό σε κάθε CONTEST.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Ξαφνιάζει έντονα όλα τα POKéMON\n"
	.string "που έκαναν καλές απηχήσεις.$"

gText_AppealBestMoreCrowdExcited::
	.string "Η απήχηση πάει καλύτερα όσο πιο\n"
	.string "ενθουσιασμένο είναι το κοινό.$"

gText_TemporarilyStopCrowdExcited::
	.string "Σταματά προσωρινά το κοινό\n"
	.string "από το να ενθουσιάζεται.$"

@ Unused move names

gText_RainDance::
	.string "RAIN DANCE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "FOCUS ENERGY$"

gText_Hypnosis::
	.string "HYPNOSIS$"

gText_Softboiled::
	.string "SOFTBOILED$"

gText_HornAttack::
	.string "HORN ATTACK$"

gText_SwordsDance::
	.string "SWORDS DANCE$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "SUNNY DAY$"

gText_Rest2::
	.string "REST$"

gText_Vicegrip::
	.string "VICEGRIP$"

gText_DefenseCurl::
	.string "DEFENSE CURL$"

gText_LockOn::
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL$"

gContestMoveTypeBeautyText::
	.string "BEAUTY$"

gContestMoveTypeCuteText::
	.string "CUTE$"

gContestMoveTypeSmartText::
	.string "SMART$"

gContestMoveTypeToughText::
	.string "TOUGH$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Απήχηση αρ. {STR_VAR_1}!\n"
	.string "Ποια κίνηση θα παιχτεί;$"

gText_AppealNumButItCantParticipate::
	.string "Απήχηση αρ. {STR_VAR_1}!\n"
	.string "Αλλά δεν μπορεί να συμμετάσχει!$"

gText_MonAppealedWithMove::
	.string "Ο/Η {STR_VAR_1} έκανε απήχηση\n"
	.string "με {STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "Ο/Η {STR_VAR_1} παρακολουθούσε\n"
	.string "τους άλλους.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Τελείωσε ο χρόνος\n"
	.string "απήχησης!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Αλλά η απήχηση\n"
	.string "εμποδίστηκε.$"

gText_FollowedAnotherMonsLead::
	.string "Ακολούθησε το παράδειγμα\n"
	.string "άλλου POKéMON.$"

gText_ButItMessedUp::
	.string "Αλλά τα θαλάσσωσε.$"

gText_WentBetterThanUsual::
	.string "Πήγε καλύτερα από\n"
	.string "το συνηθισμένο.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Ο JUDGE κοίταξε αλλού\n"
	.string "για κάποιο λόγο.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Προσπάθησε σκληρά για να\n"
	.string "μάθει από τα λάθη του.$"

gText_CantMakeAnyMoreMoves::
	.string "Δεν μπορεί να κάνει\n"
	.string "άλλες κινήσεις.$"

gText_WorkedFrighteninglyWell::
	.string "Λειτούργησε τρομακτικά\n"
	.string "καλά.$"

gText_WorkedHardAsStandoutMon::
	.string "Προσπάθησε όσο και το\n"
	.string "κορυφαίο POKéMON.$"

gText_JudgedLookedOnExpectantly::
	.string "Ο JUDGE κοίταξε με\n"
	.string "προσδοκία.$"

gText_WorkedRatherWell::
	.string "Λειτούργησε αρκετά καλά.$"

gText_WorkedLittleBetterThanUsual::
	.string "Λειτούργησε λίγο καλύτερα\n"
	.string "από το συνηθισμένο.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "Ο/Η {STR_VAR_1} απέτυχε\n"
	.string "να ξεχωρίσει καθόλου…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "Ο/Η {STR_VAR_1} δεν ξεχώρισε\n"
	.string "και πολύ…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "Ο/Η {STR_VAR_1} τράβηξε\n"
	.string "λίγη προσοχή.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "Ο/Η {STR_VAR_1} τράβηξε\n"
	.string "πολλή προσοχή.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "Ο/Η {STR_VAR_1} τράβηξε την\n"
	.string "απόλυτη προσοχή.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "Ο/Η {STR_VAR_1} δεν έχει κάνει\n"
	.string "την απήχησή του.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Η προσδοκία μεγάλωσε για την\n"
	.string "επόμενη απήχηση του {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "Οι απόψεις του JUDGE για το\n"
	.string "{STR_VAR_1} παρέμειναν σταθερές.$"

gText_MonsXChangedPerceptions::
	.string "Το {STR_VAR_3} του/της {STR_VAR_1}\n"
	.string "άλλαξε τις εντυπώσεις.$"

gText_MonsAppealEffectWoreOff::
	.string "Η επίδραση της απήχησης\n"
	.string "του/της {STR_VAR_1} πέρασε.$"

gText_SpecialAppealsEffectWoreOff::
	.string "Η επίδραση της ειδικής\n"
	.string "απήχησης πέρασε.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Οι απηχήσεις όλων φάνηκαν\n"
	.string "να είναι οι ίδιες.$"

gText_CheapenedMonsAppeal::
	.string "Υποβάθμισε την απήχηση\n"
	.string "του {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Υποβάθμισε την απήχηση\n"
	.string "εκείνων που ήταν μπροστά.$"

gText_StoleAttentionAwayFromMon::
	.string "Έκλεψε την προσοχή από\n"
	.string "το {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Υποβάθμισε την απήχηση\n"
	.string "του {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Υποβάθμισε σοβαρά τις\n"
	.string "άλλες απηχήσεις.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Η προσδοκία μεγάλωσε για την\n"
	.string "επόμενη απήχηση του {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Υποβάθμισε την απήχηση\n"
	.string "εκείνων που ήταν μπροστά.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Υποβάθμισε την αγαπημένη\n"
	.string "απήχηση του JUDGE.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Οι απηχήσεις των άλλων\n"
	.string "υποβαθμίστηκαν στο μισό.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Ξεχώρισε για να αναπληρώσει\n"
	.string "το ότι εμποδίστηκε.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Δεν μπορεί να συμμετάσχει\n"
	.string "άλλο στις απηχήσεις.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Συγκίνησε τον JUDGE με μια\n"
	.string "φανταστική απήχηση.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Η προσδοκία αυξήθηκε για\n"
	.string "τις επόμενες απηχήσεις.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Ξεχώρισε όσο και οι\n"
	.string "ειδικές απηχήσεις.$"

gText_StoodOutAsMuchAsMon::
	.string "Ξεχώρισε όσο και το\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Οι εμποδισμένες απηχήσεις\n"
	.string "έγιναν ακόμα λιγότερο ορατές.$"

gText_EveryonesAppealsMadeSame::
	.string "Οι απηχήσεις όλων έγιναν\n"
	.string "οι ίδιες.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Έγινε πιο συνειδητό για\n"
	.string "τα άλλα POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "Ο/Η {STR_VAR_1} δεν μπορεί να\n"
	.string "κάνει απήχηση μετά από αυτό.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Ηρέμησε μόνο για\n"
	.string "λίγο.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Ξέχασε την ύπαρξη των\n"
	.string "άλλων POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Έδωσε λιγότερη προσοχή στα\n"
	.string "άλλα POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Σταμάτησε να νοιάζεται πολύ\n"
	.string "για τα άλλα POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Προσπάθησε να ξαφνιάσει\n"
	.string "τα άλλα POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Προσπάθησε να θαμπώσει\n"
	.string "τους άλλους.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Ο JUDGE κοίταξε μακριά\n"
	.string "από το {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Προσπάθησε να αγχώσει το\n"
	.string "επόμενο POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "Ο/Η {STR_VAR_1} έγινε\n"
	.string "νευρικός/ή.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Η απήχηση προσπάθησε να αγχώσει\n"
	.string "τα POKéMON που περιμένουν.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Προκάλεσε τα POKéMON\n"
	.string "που τα πήγαιναν καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "Ο/Η {STR_VAR_1} επανέκτησε τη\n"
	.string "φόρμα του.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Προσπάθησε να εμποδίσει\n"
	.string "τα POKéMON που πάνε καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "Το κορυφαίο {STR_VAR_1}\n"
	.string "προσπάθησε ακόμα περισσότερο.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Το απαρατήρητο {STR_VAR_1}\n"
	.string "προσπάθησε σκληρά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Προσπάθησε όσο και το\n"
	.string "προηγούμενο POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "δεν πήγε καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Προσπάθησε όσο και το\n"
	.string "προηγούμενο POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "δεν πήγε καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "δεν πήγε καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε ελαφρώς καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε αρκετά καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε εξαιρετικά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "ήταν μια αποτυχία.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "δεν λειτούργησε πολύ καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε ελαφρώς καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε αρκετά καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε πάρα πολύ καλά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "Η απήχηση του {STR_VAR_1}\n"
	.string "πήγε εξαιρετικά.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Είναι του ίδιου τύπου με το\n"
	.string "προηγούμενο POKéMON--καλό!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Δεν είναι του ίδιου τύπου με\n"
	.string "το προηγούμενο--καλό!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Ξεχώρισε πολύ περισσότερο\n"
	.string "από το προηγούμενο POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Δεν τα πήγε τόσο καλά όσο το\n"
	.string "προηγούμενο POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "Η κατάσταση του {STR_VAR_1}\n"
	.string "ανέβηκε πάνω από το συνηθισμένο.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Η εξαιρετική κατάσταση του\n"
	.string "{STR_VAR_1} έκανε σπουδαία απήχηση!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Ανέβηκε στη σειρά για την\n"
	.string "επόμενη απήχηση.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Κατέβηκε στη σειρά μία φορά\n"
	.string "για την επόμενη απήχηση.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Ανακάτεψε τη σειρά για τον\n"
	.string "επόμενο γύρο.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Ο JUDGE κοίταξε το {STR_VAR_1}\n"
	.string "με προσδοκία.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Ο συνδυασμός απήχησης πήγε\n"
	.string "πολύ καλά.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Ο συνδυασμός απήχησης πήγε\n"
	.string "πάρα πολύ καλά.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Ο συνδυασμός απήχησης πήγε\n"
	.string "εξαιρετικά.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "Ο/Η {STR_VAR_1} κατάφερε να\n"
	.string "αποστρέψει το βλέμμα του/της.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "Ο/Η {STR_VAR_1} κατάφερε να\n"
	.string "αποφύγει να το δει.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "Ο/Η {STR_VAR_1} δεν πτοείται\n"
	.string "από τέτοια πράγματα.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "Ο/Η {STR_VAR_1} αφαιρέθηκε\n"
	.string "λίγο.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Προσπάθησε να ξαφνιάσει\n"
	.string "τα άλλα POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "Ο/Η {STR_VAR_1} κοίταξε κάτω\n"
	.string "επειδή αφαιρέθηκε.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "Ο/Η {STR_VAR_1} γύρισε πίσω\n"
	.string "επειδή αφαιρέθηκε.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "Ο/Η {STR_VAR_1} δεν μπόρεσε να\n"
	.string "συγκρατήσει μια κραυγή.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "Ο/Η {STR_VAR_1} δεν μπόρεσε να\n"
	.string "αποφύγει ένα άλμα.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "Ο/Η {STR_VAR_1} παραπάτησε\n"
	.string "επειδή αφαιρέθηκε.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "Ο/Η {STR_VAR_1} ήταν πολύ\n"
	.string "νευρικός/ή για να κινηθεί.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Αλλά τα θαλάσσωσε.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Αλλά απέτυχε να αγχώσει\n"
	.string "τον στόχο.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Αλλά απέτυχε να αγχώσει\n"
	.string "κανέναν.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Αλλά αγνοήθηκε…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Αλλά δεν μπόρεσε να βελτιώσει\n"
	.string "την κατάστασή του…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Η κακή του κατάσταση οδήγησε\n"
	.string "σε μια αδύναμη απήχηση.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "Ο/Η {STR_VAR_1} δεν\n"
	.string "επηρεάστηκε.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "Ο/Η {STR_VAR_1} απογοήτευσε\n"
	.string "επαναλαμβάνοντας μια απήχηση.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "Το {STR_VAR_3} του/της {STR_VAR_1}\n"
	.string "πήγε εξαιρετικά.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "Το {STR_VAR_3} του/της {STR_VAR_1}\n"
	.string "δεν πήγε και πολύ καλά εδώ…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "Το {STR_VAR_3} του/της {STR_VAR_1}\n"
	.string "ξεσήκωσε το κοινό.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "Ο/Η {STR_VAR_1} δεν μπορεί να\n"
	.string "κάνει απήχηση στον επόμενο γύρο…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Τράβηξε την προσοχή\n"
	.string "του κοινού.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Το κοινό συνεχίζει να\n"
	.string "παρακολουθεί το {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "Η κίνηση {STR_VAR_2}\n"
	.string "του/της {STR_VAR_1} αγνοήθηκε.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "ντροπαλότητα$"

gText_Contest_Anxiety::
	.string "άγχος$"

gText_Contest_Laziness::
	.string "τεμπελιά$"

gText_Contest_Hesitancy::
	.string "διστακτικότητα$"

gText_Contest_Fear::
	.string "φόβος$"

gText_Contest_Coolness::
	.string "coolness$"

gText_Contest_Beauty::
	.string "beauty$"

gText_Contest_Cuteness::
	.string "cuteness$"

gText_Contest_Smartness::
	.string "smartness$"

gText_Contest_Toughness::
	.string "toughness$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "COOL Move$"

gText_BeautyMove::
	.string "BEAUTY Move$"

gText_CuteMove::
	.string "CUTE Move$"

gText_SmartMove::
	.string "SMART Move$"

gText_ToughMove::
	.string "TOUGH Move$"

gText_3QuestionMarks::
	.string "???$"
