gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} του/της {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "CONTEST$"

gContestRankNormal::
	.string "NORMAL RANK$"

gContestRankSuper::
	.string "SUPER RANK$"

gContestRankHyper::
	.string "HYPER RANK$"

gContestRankMaster::
	.string "MASTER RANK$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "COOLNESS$"

gContestBeauty::
	.string "BEAUTY$"

gContestCuteness::
	.string "CUTENESS$"

gContestSmartness::
	.string "SMARTNESS$"

gContestToughness::
	.string "TOUGHNESS$"

gContestPaintingCool1::
	.string "Ασταμάτητα cool--\n"
	.string "το ανεκτίμητο {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Γεια σου!\n"
	.string "Το πανέμορφο POKéMON {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Το θαυμάσιο, υπέροχο και\n"
	.string "πολύ σπουδαίο {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "Η τελευταία Αφροδίτη του αιώνα--\n"
	.string "το πανέμορφο {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "Το εκτυφλωτικό,\n"
	.string "λαμπερό χαμόγελο του {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "Super idol του POKéMON CENTER--\n"
	.string "το ασύγκριτο {STR_VAR_1}$"

gContestPaintingCute1::
	.string "Το αξιαγάπητο και γλυκό {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Το όμορφο πορτρέτο νίκης\n"
	.string "του {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Κλείσε μας το μάτι!\n"
	.string "Το χαριτωμένο POKéMON {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Ο μαέστρος της εξυπνάδας--\n"
	.string "το σοφό POKéMON {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--το εκλεκτό\n"
	.string "ανάμεσα σε όλα τα POKéMON$"

gContestPaintingSmart3::
	.string "Η στιγμή κομψότητας\n"
	.string "του εξαιρετικού {STR_VAR_1}$"

gContestPaintingTough1::
	.string "Ο πανίσχυρος και μυώδης\n"
	.string "δρομέας ταχύτητας {STR_VAR_1}$"

gContestPaintingTough2::
	.string "Το δυνατό, δυνατότερο και\n"
	.string "πανίσχυρο {STR_VAR_1}$"

gContestPaintingTough3::
	.string "Το πανίσχυρα σκληρό\n"
	.string "hyper POKéMON {STR_VAR_1}$"
