@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Χάθηκε η σειρά$"

gText_LinkStandby4::
	.string "Αναμονή σύνδεσης!$"

gText_WinnerIsPlayersMonCongrats::
	.string "Νικητής είναι το {STR_VAR_2}\n"
	.string "του/της {STR_VAR_1}! Συγχαρητήρια!$"

gText_WinnerIsPlayersMon::
	.string "Νικητής είναι το {STR_VAR_2} του/της {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Πρώτη κρίση: Αρ. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Δεύτερη κρίση: Αρ. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Ορισμός event: Αρ. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Κίνηση που χρησιμοποιήθηκε συχνά:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "Το πιο εντυπωσιακό POKéMON:\n"
	.string "το {STR_VAR_2} του/της {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Set event: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Η εκπομπή Link TV δεν θα γίνει\n"
	.string "επειδή ο TRAINER έχασε.{PAUSE_UNTIL_PRESS}$"
