EventTicket_Text_ShowOldSeaMap:
	.string "Το ferry για SLATEPORT είναι…\p"
	.string "Με συγχωρείτε;\n"
	.string "Μπορούμε να πλεύσουμε σε αυτό το\l"
	.string "μέρος στον χάρτη;\p"
	.string "Ξέρω κάποιον που θα σας βοηθήσει\n"
	.string "καλύτερα. Παρακαλώ περιμένετε.$"

EventTicket_Text_ThatPass:
	.string "Το ferry για SLATEPORT είναι…\p"
	.string "Ω;\n"
	.string "Αυτό το PASS…$"

EventTicket_Text_ShowEonTicket:
	.string "Αχόι, φίλε, εσύ είσαι αυτός που\n"
	.string "έφερε αυτό το περίεργο PASS;\p"
	.string "Σου λέω, προσπαθείς να φτάσεις σε\n"
	.string "ένα μικροσκοπικό νησάκι στον νότο.\p"
	.string "Ποιος ξέρει τι θα συναντήσουμε\n"
	.string "όταν φτάσουμε εκεί!\l"
	.string "Αυτό με κάνει να ανατριχιάζω!\p"
	.string "Όλοι επιβίβαση!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Αχόι, φίλε, δεν υπάρχει τίποτα να\n"
	.string "δεις ή να κάνεις σε αυτό το νησί.\p"
	.string "Τι λες να γυρίσουμε στο LILYCOVE;$"

EventTicket_Text_SailHome:
	.string "Ωραία, λοιπόν!\n"
	.string "Θα σαλπάρουμε για πίσω!$"

EventTicket_Text_AsYouLike:
	.string "Ωραία, όπως επιθυμείς, λοιπόν.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Όλα τα όνειρα είναι απλώς μια\n"
	.string "άλλη πραγματικότητα. Μην ξεχνάς…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Όσοι βλέπουν τις αναμνήσεις τους\n"
	.string "να σβήνουν, ζητούν να τις χαράξουν\l"
	.string "στις καρδιές τους…”$"
