EventTicket_Text_OldSeaMapTooFar:
	.string "Τι τρέχει, νεαρέ;\p"
	.string "Τι, εσύ είσαι αυτός που υποτίθεται \n"
	.string "ότι έχει έναν κουρελιασμένο \l"
	.string "παλιό χάρτη;\p"
	.string "Για να δούμε.\n"
	.string "… … … … … …\p"
	.string "Πω πω, αυτό είναι αρκετά μακριά. \n"
	.string "Φοβάμαι ότι δεν μπορώ να σε βοηθήσω…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Περίμενε μια στιγμή!\p"
	.string "Τι ιδέα είναι αυτή να απορρίπτεις \n"
	.string "κάποιον στον οποίο χρωστάω τόσα \l"
	.string "πολλά;$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}, λυπάμαι ειλικρινά.\p"
	.string "Ήρθες σε μένα ζητώντας τη βοήθειά \n"
	.string "μου, και παραλίγο να σε διώξουμε.\p"
	.string "Λοιπόν, άσε με να επανορθώ.\p"
	.string "Θα σαλπάρουμε αμέσως, φυσικά!\p"
	.string "Ας βρούμε αυτό το νησί σε αυτόν τον \n"
	.string "OLD SEA MAP!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Εσύ είσαι αυτός που έφερε αυτό το \n"
	.string "περίεργο εισιτήριο;\p"
	.string "Εκεί που προσπαθείς να πας είναι \n"
	.string "ένα νησί που είναι πολύ, πολύ \l"
	.string "μακριά.\p"
	.string "Κανείς δεν ξέρει τι περιμένει \n"
	.string "εκεί…\p"
	.string "Και μόνο η σκέψη ταράζει το αίμα \n"
	.string "μου ως ναυτικός!\p"
	.string "Επιβιβάσου, νεαρέ!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "O CAPT. BRINEY μπορεί να γίνει \n"
	.string "εξοργιστικά άστατος…\p"
	.string "Θέλεις να επιστρέψεις στο LILYCOVE;$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Τι περίεργο σχήμα που έχει το \n"
	.string "νησί, ε; Θέλεις να επιστρέψεις \l"
	.string "στο LILYCOVE;$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Εσύ είσαι αυτός που έφερε αυτά τα \n"
	.string "περίεργα εισιτήρια;\p"
	.string "… … …Χμ.\p"
	.string "Αυτά τα εισιτήρια θα σε πάνε σε \n"
	.string "νησιά που είναι πολύ, πολύ \l"
	.string "μακριά.\p"
	.string "Κανείς δεν ξέρει τι περιμένει \n"
	.string "εκεί, ή τι μπορεί να συμβεί εκεί.\p"
	.string "Και μόνο η σκέψη ταράζει το αίμα \n"
	.string "μου ως ναυτικός!\p"
	.string "Επιβιβάσου, νεαρέ!\n"
	.string "Πού θα σαλπάρουμε πρώτα;$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Άκουσες… Άκουσες αυτό;\n"
	.string "Αυτό το χαμηλό γρυλίσμα από \l"
	.string "βαθιά μέσα εκεί.\p"
	.string "Είσαι σίγουρος ότι είναι ασφαλές;\n"
	.string "Μήπως πρέπει να φύγουμε;$"

FarawayIsland_Entrance_Text_Sign:
	.string "Τα γράμματα ξεθωριάζουν σαν να έχουν \n"
	.string "γραφτεί πριν από πολύ καιρό…\p"
	.string "“…βριος, 6η μέρα\n"
	.string "Αν κάποιος άνθρωπος… πατήσει εδώ…\l"
	.string "ξανά… ας είναι καλόκαρδος άνθρω…\l"
	.string "…μ' αυτήν την ελπίδα, αναχωρω…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Μιού…$"
