EventTicket_Text_OldSeaMapTooFar:
	.string "What's up, youngster?\p"
	.string "What, it's you who's supposed to have\n"
	.string "a tattered old map?\p"
	.string "Let's have a look.\n"
	.string "… … … … … …\p"
	.string "Boy, this is quite a ways away.\n"
	.string "I'm afraid I can't help you…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Hold on a second!\p"
	.string "What's the idea of turning down\n"
	.string "someone that I owe so much to?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, I'm terribly sorry.\p"
	.string "You came to me seeking my help,\n"
	.string "and we almost turned you away.\p"
	.string "Well, let me make things right.\p"
	.string "We'll sail right away, of course!\p"
	.string "Let's find this island on\n"
	.string "this OLD SEA MAP!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Is it you who brought that odd\n"
	.string "ticket?\p"
	.string "Where you're trying to go is an island\n"
	.string "that's far, far away.\p"
	.string "No one knows what awaits there…\p"
	.string "The very thought excites my blood\n"
	.string "as a sailing man!\p"
	.string "Get on board, youngster!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "O CAPT. BRINEY μπορεί να γίνει \n"
	.string "εξοργιστικά άστατος…\p"
	.string "Θέλεις να επιστρέψεις στο LILYCOVE;$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "What an oddly shaped island, eh?\n"
	.string "Do you want to return to LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Is it you who brought those\n"
	.string "odd tickets?\p"
	.string "… … …Hm.\p"
	.string "These tickets will get you to islands\n"
	.string "that are far, far away.\p"
	.string "No one knows what awaits there,\n"
	.string "or what may happen there.\p"
	.string "The very thought excites my blood\n"
	.string "as a sailing man!\p"
	.string "Get on board, youngster!\n"
	.string "Where shall we sail first?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Did… Did you hear that?\n"
	.string "That low growling from deep in there.\p"
	.string "Are you sure it's safe?\n"
	.string "Do you think we should leave?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Τα γράμματα ξεθωριάζουν σαν να έχουν \n"
	.string "γραφτεί πριν από πολύ καιρό…\p"
	.string "“…βριος, 6η μέρα\n"
	.string "Αν κάποιος άνθρωπος… πατήσει εδώ…\l"
	.string "ξανά… ας είναι καλόκαρδος άνθρω…\l"
	.string "…μ' αυτήν την ελπίδα, αναχωρω…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Μιού…$"
