@ Battle Tower
gText_AnabelWonSilver::
	.string "Είναι πολύ απογοητευτικό…$"

gText_AnabelDefeatSilver::
	.string "Εντάξει, καταλαβαίνω…$"

gText_AnabelWonGold::
	.string "Λυπάμαι πάρα πολύ…$"

gText_AnabelDefeatGold::
	.string "Σε ευχαριστώ…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Αχαχαχα! Δεν ντρέπεσαι;\n"
	.string "Όλοι κοιτάζουν!$"

gText_TuckerDefeatSilver::
	.string "Γκρρ…\n"
	.string "Τι στο καλό…$"

gText_TuckerWonGold::
	.string "Ο τίτλος μου DOME ACE δεν είναι\n"
	.string "μόνο για επίδειξη!$"

gText_TuckerDefeatGold::
	.string "Αχαχαχα!\n"
	.string "Είσαι πηγή έμπνευσης!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Καλή προσπάθεια!\n"
	.string "Αυτό ήταν ένα καλό μάθημα, ε;$"

gText_NolandDefeatSilver::
	.string "Καλή δουλειά!\n"
	.string "Ξέρεις τι κάνεις!$"

gText_NolandWonGold::
	.string "Έι, έι, έι!\n"
	.string "Τελείωσες ήδη;$"

gText_NolandDefeatGold::
	.string "Τι συνέβη εδώ;$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Χμ…$"

gText_LucyDefeatSilver::
	.string "Ούρκι…$"

gText_LucyWonGold::
	.string "Χα!$"

gText_LucyDefeatGold::
	.string "Κρίμα!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Έλα τώρα!\n"
	.string "Πρέπει να προσπαθήσεις περισσότερο!$"

gText_GretaDefeatSilver::
	.string "Αποκλείεται!\n"
	.string "Καλή δουλειά!$"

gText_GretaWonGold::
	.string "Χεχέ!\n"
	.string "Τι περίμενες;$"

gText_GretaDefeatGold::
	.string "Ορίστε;\n"
	.string "Σοβαρολογείς;!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Τα POKéMON σου είναι αδύναμα\n"
	.string "επειδή είσαι αδύναμος TRAINER!$"

gText_SpenserDefeatSilver::
	.string "Αχ…\n"
	.string "Αυτό είναι κάτι άλλο…$"

gText_SpenserWonGold::
	.string "Γουαχαχαχα!\n"
	.string "Αδέρφια μου, δεν έχουμε να\n"
	.string "φοβηθούμε τίποτα!$"

gText_SpenserDefeatGold::
	.string "Γκουά!\n"
	.string "Χαχαχαχα!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Έι! Τι συμβαίνει με σένα;\n"
	.string "Δείξε λίγο ζήλο! Σήκω πάνω!$"

gText_BrandonDefeatSilver::
	.string "Αυτό είναι! Τα πήγες υπέροχα!\n"
	.string "Προσπάθησες πολύ γι' αυτό!$"

gText_BrandonWonGold::
	.string "Έι! Μην τα παρατάς τώρα!\n"
	.string "Σήκω! Μην χάνεις την πίστη σου!$"

gText_BrandonDefeatGold::
	.string "Αυτό είναι! Τα κατάφερες!\n"
	.string "Συνέχισες να παλεύεις γι' αυτό!$"
