LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Καλώς ήρθατε στο POKéMON LOTTERY\n"
	.string "CORNER.\p"
	.string "Όλοι οι αγοραστές του πολυκαταστήματος\n"
	.string "DEPARTMENT STORE μπορούν να\l"
	.string "τραβήξουν ένα POKéMON LOTO TICKET.\p"
	.string "Αν ο αριθμός του LOTO TICKET\n"
	.string "ταιριάζει με το ID κάποιου POKéMON\l"
	.string "σου, θα κερδίσεις ένα υπέροχο δώρο.\p"
	.string "Θέλεις να τραβήξεις ένα POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Παρακαλώ έλα ξανά αύριο.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Παρακαλώ επισκέψου μας ξανά.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Παρακαλώ διάλεξε ένα LOTO TICKET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Ο αριθμός του LOTO TICKET είναι\n"
	.string "{STR_VAR_1}.\p"
	.string "Πρέπει να ελέγξω αυτόν τον αριθμό\n"
	.string "για να δω αν ταιριάζει με το ID\l"
	.string "κάποιου POKéMON σου. Περίμενε.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Συγχαρητήρια!\p"
	.string "Ο αριθμός ID του {STR_VAR_1}\n"
	.string "της ομάδας σου ταιριάζει με τον\l"
	.string "αριθμό του LOTO TICKET σου!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Συγχαρητήρια!\p"
	.string "Ο αριθμός ID του {STR_VAR_1}\n"
	.string "στο PC σου ταιριάζει με τον\l"
	.string "αριθμό του LOTO TICKET σου!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Λυπάμαι.\n"
	.string "Κανένας αριθμός δεν ταιριάζει.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Ταιριάζουν δύο ψηφία, οπότε\n"
	.string "κερδίζεις το τρίτο βραβείο!\l"
	.string "Κέρδισες {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Ταιριάζουν τρία ψηφία, οπότε\n"
	.string "κερδίζεις το δεύτερο βραβείο!\l"
	.string "Κέρδισες {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Ταιριάζουν τέσσερα ψηφία, οπότε\n"
	.string "κερδίζεις το πρώτο βραβείο!\l"
	.string "Κέρδισες {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Ω, θεέ μου! Και τα πέντε ψηφία\n"
	.string "ταιριάζουν!\p"
	.string "Κέρδισες το μεγάλο βραβείο!\n"
	.string "Κέρδισες {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Ω?\n"
	.string "Φαίνεται πως δεν έχεις χώρο.\p"
	.string "Παρακαλώ κάνε χώρο στην BAG σου\n"
	.string "και έλα να μου πεις.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Ναι, σε περίμενα.\p"
	.string "Αυτό είναι το βραβείο που κρατούσαμε\n"
	.string "για σένα.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Παρακαλώ επισκέψου μας ξανά.$"
