MatchCall_WildBattleText1::
	.string "Γεια! {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Είδα ένα {STR_VAR_2} πριν λίγο\n"
	.string "αλλά δεν μπόρεσα να το πιάσω.\p"
	.string "Έφτασα τόσο κοντά!\n"
	.string "Λοιπόν, τα λέμε πάλι!$"

MatchCall_WildBattleText2::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Προσπάθησα να πιάσω ένα {STR_VAR_2}\n"
	.string "πριν από λίγο.\p"
	.string "Αλλά ξέφυγε.\n"
	.string "Απογοητεύτηκα πολύ!\p"
	.string "Εντάξει, γεια!$"

MatchCall_WildBattleText3::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Μόλις προσπάθησα να πιάσω\n"
	.string "αυτό το {STR_VAR_2}, αλλά έφυγε.\p"
	.string "Έφτασα πάρα πολύ κοντά!\p"
	.string "Μου χάλασε τη μέρα…\n"
	.string "Ωραία, τα λέμε!$"

MatchCall_WildBattleText4::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ξέρεις το POKéMON {STR_VAR_2};\n"
	.string "Έφτασα κοντά στο να πιάσω ένα.\p"
	.string "Πριν από λίγο ήταν.\n"
	.string "Νόμιζα ότι το είχα, αλλά ξέφυγε.\p"
	.string "Αν το ξαναδώ όμως, θα το πιάσω\n"
	.string "σίγουρα.\p"
	.string "Εντάξει, τα λέμε μετά.$"

MatchCall_WildBattleText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Έπιασες κανένα POKéMON πρόσφατα;\p"
	.string "Πριν λίγο έφτασα κοντά στο να\n"
	.string "πιάσω ένα, αλλά ξέφυγε.\p"
	.string "Λοιπόν, να προσέχεις!$"

MatchCall_WildBattleText6::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Έπιασες κανένα POKéMON πρόσφατα;\p"
	.string "Σχεδόν έπιασα ένα τις προάλλες.\n"
	.string "Αλλά μου ξέφυγε κάπως.\p"
	.string "Να προσέχεις.$"

MatchCall_WildBattleText7::
	.string "…Ε, {PLAYER};\n"
	.string "Είμαι {STR_VAR_1}.\p"
	.string "Ω, περίμενε! Περίμενε!\n"
	.string "Μπορώ να πιάσω αυτό το {STR_VAR_2}…\p"
	.string "Αααργκ! Ξέφυγε τελικά!\n"
	.string "Δεν ήταν απλά κοντά!$"

MatchCall_WildBattleText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Είχες επιτυχία στο να πιάνεις\n"
	.string "POKéMON πρόσφατα;\p"
	.string "Έφτασα πολύ κοντά πριν από λίγο,\n"
	.string "αλλά ο στόχος μου ξέφυγε.\p"
	.string "Πρέπει να προσπαθήσω περισσότερο!\n"
	.string "Θα τα ξαναπούμε!$"

MatchCall_WildBattleText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Λοιπόν; Μαζεύεις περισσότερα\n"
	.string "POKéMON;\p"
	.string "Εμένα μου πάνε όλα στραβά!\n"
	.string "Μου ξεφεύγουν όλα τους!\p"
	.string "Τα λέμε!$"

MatchCall_WildBattleText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Άκου, έφτασα μια ανάσα από το\n"
	.string "να πιάσω αυτό το {STR_VAR_2}…\p"
	.string "Αλλά μου ξέφυγε…\p"
	.string "Πρέπει να προσπαθήσω περισσότερο.\n"
	.string "Τα λέμε.$"

MatchCall_WildBattleText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πώς πάνε τα πράγματα;\p"
	.string "Προσπάθησα να πιάσω ένα άγριο\n"
	.string "{STR_VAR_2} νωρίτερα, αλλά έφυγε.\p"
	.string "Με πήρε από κάτω…$"

MatchCall_WildBattleText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ακόμα πιάνεις POKéMON;\p"
	.string "Προσπαθώ να πιάσω κι εγώ,\n"
	.string "αλλά δεν είναι τόσο εύκολο.\p"
	.string "Ο κόσμος των POKéMON είναι βαθύς!$"

MatchCall_WildBattleText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Πιάνεις καθόλου POKéMON;\p"
	.string "Προσπαθώ να πιάσω κι εγώ,\n"
	.string "αλλά με ελάχιστη επιτυχία.\p"
	.string "Ο κόσμος των POKéMON είναι βαθύς!$"

MatchCall_WildBattleText14::
	.string "Ω, γεια, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Μόλις τώρα προσπάθησα να πιάσω\n"
	.string "ένα χαριτωμένο {STR_VAR_2}.\p"
	.string "Αλλά μου ξέφυγε!\n"
	.string "Απογοητεύτηκα απίστευτα!\p"
	.string "Γεια-γεια!$"

MatchCall_WildBattleText15::
	.string "Γεια, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Σκεφτόμουν να προσπαθήσω να\n"
	.string "πιάσω μερικά POKéMON.\p"
	.string "Αλλά δεν μπορώ να βρω κανένα.\n"
	.string "Είναι πραγματικό μυστήριο!\p"
	.string "Έχω σηκώσει τα χέρια ψηλά!\n"
	.string "Τα λέμε εκεί έξω!$"

MatchCall_NegativeBattleText1::
	.string "Γεια! {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Προσπάθησα να παλέψω με TRAINER,\n"
	.string "αλλά έχασα.\p"
	.string "Ήταν πολύ απογοητευτικό.\n"
	.string "Λοιπόν, τα λέμε πάλι!$"

MatchCall_NegativeBattleText2::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Προκάλεσα κάποιον άλλον αφού\n"
	.string "παλέψαμε μαζί.\p"
	.string "Έφτασα κοντά, αλλά τελικά\n"
	.string "έχασα. Τι να κάνουμε!$"

MatchCall_NegativeBattleText3::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Με διέλυσαν σε μια μάχη.\p"
	.string "Μάλλον πρέπει να δυναμώσω\n"
	.string "την ομάδα μου κι άλλο!$"

MatchCall_NegativeBattleText4::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Δοκίμασα άλλη μια μάχη χθες,\n"
	.string "αλλά δεν μπόρεσα να νικήσω.\p"
	.string "Η ομάδα μου θέλει κι άλλη προπόνηση.\n"
	.string "Εντάξει, τα λέμε μετά.$"

MatchCall_NegativeBattleText5::
	.string "Γεια, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς πάνε τα πράγματα;\p"
	.string "Συνεχίζω να δίνω μάχες,\n"
	.string "αλλά δεν νικάω πολύ συχνά.\p"
	.string "Δεν μπορώ να τα καταφέρω.\n"
	.string "Λοιπόν, να προσέχεις!$"

MatchCall_NegativeBattleText6::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς σου πάει εσένα;\p"
	.string "Δίνω σκληρές μάχες τελευταία,\n"
	.string "αλλά με ελάχιστη επιτυχία.\p"
	.string "Δεν μπορώ να βρω ρυθμό.\n"
	.string "Να προσέχεις.$"

MatchCall_NegativeBattleText7::
	.string "Εδώ {STR_VAR_1}.\n"
	.string "Πώς πάνε τα πράγματα πρόσφατα;\p"
	.string "Έχασα μια μάχη χθες,\n"
	.string "και δεν μπορώ να το ξεχάσω.\p"
	.string "Πρέπει να βρω ένα σχέδιο…\n"
	.string "Τα λέμε.$"

MatchCall_NegativeBattleText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς πάνε τα POKéMON σου;\n"
	.string "Έχασα μια μάχη τις προάλλες.\p"
	.string "Πρέπει να προσπαθήσω περισσότερο!\n"
	.string "Θα τα ξαναπούμε!$"

MatchCall_NegativeBattleText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Άκου, άκου, πρέπει να το μάθεις!\p"
	.string "Έδωσα μια μάχη POKéMON πριν,\n"
	.string "αλλά έχασα το τελευταίο δευτερόλεπτο.\p"
	.string "Ω, έχω εκνευριστεί τόσο πολύ!$"

MatchCall_NegativeBattleText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Λίγο νωρίτερα, ήμουν σε μάχη.\n"
	.string "Όμως έχασα.\p"
	.string "Πρέπει να γυμνάσω τα POKéMON μου.\n"
	.string "Τα λέμε εκεί έξω.$"

MatchCall_NegativeBattleText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πώς είναι τα POKéMON σου;\p"
	.string "Μόλις έχασα άλλη μια μάχη.\p"
	.string "Λοιπόν, τα λέμε!$"

MatchCall_NegativeBattleText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ακόμα παλεύεις σκληρά;\p"
	.string "Εγώ έχασα πρόσφατα, οπότε\n"
	.string "προπονώ την ομάδα μου από την αρχή.\p"
	.string "Ας βρεθούμε πάλι.$"

MatchCall_NegativeBattleText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Ήμουν σε μάχη λίγο πριν από αυτό.\p"
	.string "{PLAYER}, προσπάθησε να κινείσαι\n"
	.string "συνεχώς σαν εμένα. Τα λέμε πάλι!$"

MatchCall_NegativeBattleText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Είσαι καλά;\p"
	.string "Πρέπει να πηγαίνεις σπίτι\n"
	.string "που και που, πάντως.\p"
	.string "Γεια-γεια!$"

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Έδωσα μάχη με έναν TRAINER πριν.\n"
	.string "Νίκησα! Νίκησα!\p"
	.string "Το {STR_VAR_2} μου προσπάθησε πολύ.\n"
	.string "Είναι φανταστικό!$"

MatchCall_PositiveBattleText2::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Έδωσα μια μάχη χθες και\n"
	.string "νίκησα! Είναι τέλειο!$"

MatchCall_PositiveBattleText3::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Πώς πάνε οι μάχες σου;\p"
	.string "Εγώ έδωσα μια μάχη τις προάλλες,\n"
	.string "και το {STR_VAR_2} μου ήταν απίστευτο!\p"
	.string "Την επόμενη φορά που θα παλέψουμε,\n"
	.string "{PLAYER}, δεν θα χάσω εγώ!$"

MatchCall_PositiveBattleText4::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έδωσα μια μάχη νωρίτερα.\n"
	.string "Κατάφερα να νικήσω, αλλά οριακά.\p"
	.string "Το {STR_VAR_2} μου έκανε μια\n"
	.string "εξαιρετική εμφάνιση.$"

MatchCall_PositiveBattleText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς πάνε τα πράγματα;\n"
	.string "Δίνεις πολλές μάχες;\p"
	.string "Μόλις νίκησα πριν από λίγο!\n"
	.string "Το {STR_VAR_2} μου ήταν φανταστικό!\p"
	.string "Περίμενε. Θα σε νικήσω την\n"
	.string "επόμενη φορά! Να προσέχεις!$"

MatchCall_PositiveBattleText6::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς πάνε τα πράγματα;\p"
	.string "Έχω ένα σερί νικών τελευταία.\n"
	.string "Μόλις κέρδισα μια μάχη.\p"
	.string "Στην επόμενη μάχη μας,\n"
	.string "σίγουρα δεν πρόκειται να χάσω!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER};\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Το {STR_VAR_2} μου είναι δύναμη!\n"
	.string "Μου χάρισε άλλη μια νίκη μόλις!\p"
	.string "Ανυπομονώ να κάνουμε ρεβάνς\n"
	.string "μαζί.$"

MatchCall_PositiveBattleText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ελπίζω να είσαι καλά.\n"
	.string "Ήθελα να σου πω ότι μόλις νίκησα.\p"
	.string "Το {STR_VAR_2} μου προσπάθησε πολύ\n"
	.string "για να πάρουμε τη νίκη.\p"
	.string "Θα τα ξαναπούμε!$"

MatchCall_PositiveBattleText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Πώς αντέχουν τα POKéMON σου;\n"
	.string "Τα δικά μου μόλις νίκησαν!\p"
	.string "Το {STR_VAR_2} μου ήταν φανταστικό,\n"
	.string "πρέπει να πω!\p"
	.string "Μακάρι να μπορούσα να σου δείξω!\n"
	.string "Θα τα ξαναπούμε!$"

MatchCall_PositiveBattleText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς σου φέρεται η ζωή;\p"
	.string "Τα POKéMON μου είναι γεμάτα\n"
	.string "ενέργεια.\p"
	.string "Μόλις κέρδισα μια μάχη μαζί τους.\n"
	.string "Τα λέμε.$"

MatchCall_PositiveBattleText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έδωσες καμιά μάχη πρόσφατα;\n"
	.string "Εγώ νίκησα άλλη μια σήμερα!\p"
	.string "Έχω πάρει φόρα! Γκαχαχαχα!\n"
	.string "Λοιπόν, τα λέμε!$"

MatchCall_PositiveBattleText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ελπίζω να είσαι καλά;\n"
	.string "Έχω ακόμα πολλή ενέργεια!\p"
	.string "Μόλις τώρα νίκησα σε άλλη μια μάχη.\n"
	.string "Δεν κάνω στην άκρη για εσάς\l"
	.string "τους νεότερους ακόμα!$"

MatchCall_PositiveBattleText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Ελπίζω να είσαι καλά.\n"
	.string "Έχω ακόμα ενέργεια στα βήματά μου!\p"
	.string "Μόλις τώρα νίκησα σε άλλη μια μάχη.\n"
	.string "Δεν χάνω από τους νέους\l"
	.string "ακόμα!\p"
	.string "Θα τα ξαναπούμε!$"

MatchCall_PositiveBattleText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ήμουν σε μάχη πρόσφατα, και το\n"
	.string "{STR_VAR_2} μου ήταν εξαιρετικό!\p"
	.string "Μακάρι να μπορούσες να το δεις,\n"
	.string "{PLAYER}. Γεια-γεια!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Γεια! {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ε; Μισό, είσαι κοντά στο\n"
	.string "{STR_VAR_2};\p"
	.string "Ω, τέλεια, πρέπει να παλέψουμε!\n"
	.string "Θα περιμένω! Τα λέμε!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ω; Τυχαίνει να είσαι κοντά στο\n"
	.string "{STR_VAR_2} τώρα;\p"
	.string "Θέλεις να παλέψουμε τώρα;\n"
	.string "Θα σε περιμένω! Τα λέμε!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ω, είσαι κοντά στο\n"
	.string "{STR_VAR_2} τώρα;\p"
	.string "Θα ήθελες να κάνουμε μια μάχη\n"
	.string "αυτή τη στιγμή;\p"
	.string "Δεν πρόκειται να ξαναχάσω!\n"
	.string "Θα περιμένω! Τα λέμε σύντομα!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πού βρίσκεσαι τώρα;\n"
	.string "Ε; Στο {STR_VAR_2};\p"
	.string "Θέλεις μάχη τώρα;\n"
	.string "Θα περιμένω. Τα λέμε!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πώς πάνε τα πράγματα;\p"
	.string "Πού είσαι τώρα;\n"
	.string "Στο {STR_VAR_2};\p"
	.string "Λοιπόν, τι λες για μια γρήγορη\n"
	.string "ρεβάνς αμέσως;\p"
	.string "Θα σε έχω το νου μου.\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πώς πάνε τα POKéMON σου;\p"
	.string "Αλήθεια; Είσαι κοντά στο\n"
	.string "{STR_VAR_2};\p"
	.string "Ε, τότε πρέπει οπωσδήποτε να\n"
	.string "κάνουμε ρεβάνς.\p"
	.string "Μπορώ να περιμένω, σίγουρα.\n"
	.string "Τα λέμε!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Ε, {PLAYER};\n"
	.string "Εδώ {STR_VAR_1}…\p"
	.string "Ω, είσαι κοντά στο\n"
	.string "{STR_VAR_2};\p"
	.string "Τότε, ας παλέψουμε.\n"
	.string "Αμέσως τώρα, εννοώ.\p"
	.string "Θα σου δείξω τα POKéMON μου.\n"
	.string "Θα σε περιμένω.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ελπίζω να είσαι καλά.\n"
	.string "Ω, είσαι κοντά στο {STR_VAR_2}.\p"
	.string "Θέλεις να κάνουμε μια μάχη\n"
	.string "τότε;\p"
	.string "Θα σε περιμένω.\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Τα καταφέρνεις;\n"
	.string "Ω, είσαι κοντά στο {STR_VAR_2};\p"
	.string "Ε, τότε δεν νομίζεις ότι\n"
	.string "πρέπει να παλέψουμε;\p"
	.string "Μην με στήσεις για πολύ!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς πάνε τα πράγματα;\n"
	.string "Ω, είσαι κοντά στο {STR_VAR_2}.\p"
	.string "Πρέπει να παλέψουμε τώρα, λοιπόν.\p"
	.string "Είμαι σε ετοιμότητα και περιμένω.\n"
	.string "Κάνε γρήγορα!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Α, οπότε εκεί που είσαι τώρα\n"
	.string "είναι το {STR_VAR_2};\p"
	.string "Ε, τότε πρέπει να παλέψουμε,\n"
	.string "δεν νομίζεις;\p"
	.string "Θα περιμένω εδώ γύρω!\n"
	.string "Τα λέμε γρήγορα!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πού να είσαι άραγε τώρα;\p"
	.string "{STR_VAR_2};\n"
	.string "Αυτό είναι πολύ κοντά!\p"
	.string "Τι λες να κάνουμε μια μάχη\n"
	.string "τώρα;\p"
	.string "Μπορώ να περιμένω.\n"
	.string "Τα λέμε!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Ελπίζω να είσαι καλά.\n"
	.string "Ω, είσαι κοντά στο {STR_VAR_2};\p"
	.string "Αφού δεν είναι πολύ μακριά,\n"
	.string "έλα να κάνουμε μια μάχη.\p"
	.string "Θα σε περιμένω.\n"
	.string "Γεια για την ώρα.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Είσαι πού; …Στο {STR_VAR_2};\n"
	.string "Αυτό είναι πάρα πολύ κοντά.\p"
	.string "Δεν νομίζεις ότι πρέπει να\n"
	.string "κάνουμε μια μάχη;\p"
	.string "Θα σε ψάξω!\n"
	.string "Γεια-γεια!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Γεια! {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Θέλεις να κάνουμε μια μάχη;\p"
	.string "Θα σε περιμένω κοντά στο\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Θα ήθελες να κάνουμε άλλη μια\n"
	.string "μάχη μαζί;\p"
	.string "Θα με βρεις κοντά στο\n"
	.string "{STR_VAR_2}. Θα περιμένω!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Τα POKéMON μου έχουν γίνει πολύ\n"
	.string "πιο δυνατά από την προηγούμενη φορά.\p"
	.string "Θέλω να δω πόσο δυνάμωσαν σε μάχη\n"
	.string "με τα δικά σου POKéMON, {PLAYER}.\p"
	.string "Λοιπόν, ας κάνουμε μια μάχη!\p"
	.string "Θα σε περιμένω κοντά στο\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πώς πάνε τα πράγματα;\p"
	.string "Τα POKéMON μου έχουν γίνει αρκετά\n"
	.string "δυνατά τελευταία.\p"
	.string "Ε, θα ήθελες να κάνουμε άλλη\n"
	.string "μία μάχη μαζί;\p"
	.string "Ας βρεθούμε κοντά στο\n"
	.string "{STR_VAR_2}, εντάξει;$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Τα POKéMON μου μεγαλώνουν πολύ\n"
	.string "καλά.\p"
	.string "Θα ήθελα πολύ να κάνουμε άλλη\n"
	.string "μία μάχη μαζί.\p"
	.string "Θα σε έχω το νου μου κοντά στο\n"
	.string "{STR_VAR_2}. Τα λέμε σύντομα!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να τα καταφέρνεις.\p"
	.string "Σκεφτόμουν ότι θα ήθελα άλλη μία\n"
	.string "μάχη μαζί σου. Τι λες;\p"
	.string "Αν έχεις όρεξη για μάχη,\n"
	.string "έλα στο {STR_VAR_2}.\p"
	.string "Τα λέμε!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Ε, {PLAYER};\n"
	.string "Εδώ {STR_VAR_1}…\l"
	.string "Λοιπόν; Μεγαλώνουν τα POKéMON σου;\p"
	.string "Τα δικά μου σίγουρα δυνάμωσαν.\n"
	.string "Θα ήθελα να σου δείξω.\p"
	.string "Θα είμαι κοντά στο {STR_VAR_2}.\n"
	.string "Έλα να κάνουμε μια μάχη.\p"
	.string "Τα λέμε.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ελπίζω να είσαι καλά.\n"
	.string "Τα POKéMON μου είναι πολύ ζωηρά.\p"
	.string "Αν βρεθείς ποτέ στην περιοχή,\n"
	.string "έλα να κάνουμε ρεβάνς.\p"
	.string "Θα είμαι κοντά στο {STR_VAR_2}.\n"
	.string "Μέχρι τότε, γεια χαρά!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Πώς πάνε τα POKéMON σου;\p"
	.string "Τα δικά μου γίνονται όλο και καλύτερα.\n"
	.string "Θα ήθελα να σου δείξω, {PLAYER}.\p"
	.string "Είμαι κοντά στο {STR_VAR_2} τώρα,\n"
	.string "οπότε ας παλέψουμε αν είσαι κοντά.\p"
	.string "Ελπίζω να σε δω σύντομα!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Λοιπόν, πώς πάνε τα πράγματα;\p"
	.string "Τα POKéMON μου έχουν γίνει πολύ\n"
	.string "πιο δυνατά από πριν.\p"
	.string "Θα ήθελα πολύ άλλη μια μάχη μαζί σου,\n"
	.string "{PLAYER}.\p"
	.string "Θα είμαι κοντά στο {STR_VAR_2}.\n"
	.string "Έλα να με βρεις αν είσαι κοντά.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Πού να είσαι άραγε τώρα;\p"
	.string "Τα POKéMON μου είναι γεμάτα ζωή.\n"
	.string "Φαίνεται να ανυπομονούν να\n"
	.string "δουν τα POKéMON σου, {PLAYER}.\p"
	.string "Είμαι κοντά στο {STR_VAR_2} τώρα.\n"
	.string "Ελπίζω να μας αναζητήσεις.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πρέπει να σου πω, τα POKéMON μου\n"
	.string "έχουν γίνει πολύ δυνατά τελευταία.\p"
	.string "Θα ήθελα να τα δω σε μάχη\n"
	.string "μαζί σου, {PLAYER}.\p"
	.string "Θα είμαστε κοντά στο {STR_VAR_2}.\n"
	.string "Έλα να μας βρεις όποτε θες!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Είναι καλά τα POKéMON σου;\p"
	.string "Τα δικά μου είναι τόσο υγιή,\n"
	.string "που δεν φαίνεται να μπορούν να χάσουν!\p"
	.string "Θα ήθελα οπωσδήποτε άλλη μία\n"
	.string "μάχη μαζί σου.\p"
	.string "Αν είσαι κοντά στο {STR_VAR_2},\n"
	.string "έλα να μας βρεις.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Ω, ναι! Τα POKéMON μου είναι\n"
	.string "πολύ πιο δυνατά από πριν.\p"
	.string "Δεν νομίζεις ότι πρέπει να\n"
	.string "κάνουμε μια μάχη, {PLAYER};\p"
	.string "Θα σε περιμένουμε κοντά στο\n"
	.string "{STR_VAR_2}.\p"
	.string "Έλα να μας βρεις όποτε θες, οκ;$"

MatchCall_PersonalizedText1::
	.string "Είμαι εγώ, ο λάτρης του βουνού\n"
	.string "{STR_VAR_1}!\p"
	.string "Λοιπόν, από τότε που βρεθήκαμε,\n"
	.string "άρχισες να εκτιμάς τα βουνά περισσότερο;\p"
	.string "Σπάνια σε βλέπω στα βουνά…\p"
	.string "Την επόμενη φορά, θα βρεθούμε κάπου\n"
	.string "κοντά στο {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Εδώ {STR_VAR_1}.\n"
	.string "Γεια σου.\p"
	.string "Μόλις έλεγα σε μια νέα TRAINER\n"
	.string "για εσένα.\p"
	.string "Της είπα για έναν δυνατό TRAINER\n"
	.string "που μεγαλώνει POKéMON με φροντίδα.\p"
	.string "Ελπίζω να γίνεις ένας TRAINER\n"
	.string "που όλοι θα θαυμάζουν.\p"
	.string "Ελπίζω να ανταμώσουμε ξανά!$"

MatchCall_PersonalizedText3::
	.string "Γεια! Εδώ {STR_VAR_1}.\p"
	.string "Μου αρέσει πολύ εδώ που είμαι τώρα.\n"
	.string "Είναι υπέροχα με γλυκά αρώματα!\p"
	.string "Νομίζω κάποιος φύτεψε BERRIES,\n"
	.string "και άνθισαν ξαφνικά.\p"
	.string "Τα λέμε πάλι κάποια στιγμή!$"

MatchCall_PersonalizedText4::
	.string "Γεια! Τριάντα χρόνια εξερεύνησης,\n"
	.string "ο {STR_VAR_1} στις υπηρεσίες σου!\p"
	.string "Φαίνεται ότι ταξιδεύεις με ενέργεια\n"
	.string "εδώ κι εκεί.\p"
	.string "Ανακάλυψες καθόλου νέα ερείπια;\p"
	.string "Πες μου σε παρακαλώ αν βρήκες!\n"
	.string "Τώρα, με συγχωρείς,\n"
	.string "έχω ερείπια να εξερευνήσω.$"

MatchCall_PersonalizedText5::
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Ξέρεις τι κάνω σήμερα;\n"
	.string "Κοιτάζω τα κύματα από την παραλία!\p"
	.string "Αχ… Τα κύματα είναι τόσο λαμπερά.\n"
	.string "Η θάλασσα είναι πανέμορφη από εδώ.\l"
	.string "Αρχίζω να πεινάω, οπότε γεια-γεια!$"

MatchCall_PersonalizedText6::
	.string "Μιαμ-μιαμ…\n"
	.string "Ω, γεια, εδώ {STR_VAR_1}.\l"
	.string "Μου αρέσει να τρώω στην παραλία.\p"
	.string "Τα POKéMON μου κι εγώ είμαστε μια\n"
	.string "χαρά. Γεμίσαμε ενέργεια!\l"
	.string "Πάω για κολύμπι. Γεια!$"

MatchCall_PersonalizedText7::
	.string "Γεια, εδώ {STR_VAR_1}…\p"
	.string "Έχω κουραστεί λίγο με όλο αυτό\n"
	.string "το θέμα του COOLTRAINER…\p"
	.string "Όλοι με θεωρούν τέλειο TRAINER,\n"
	.string "και αυτό με κάνει να\n"
	.string "προσπαθώ να ανταποκριθώ στις\l"
	.string "προσδοκίες τους.\p"
	.string "Αλλά φαντάζομαι αυτό συμβαίνει\n"
	.string "όταν είσαι COOLTRAINER.\p"
	.string "Πρέπει απλά να στρωθώ…\n"
	.string "και να κάνω υπομονή.\p"
	.string "Είσαι το μόνο άτομο που μπορώ\n"
	.string "να εμπιστευτώ έτσι.\p"
	.string "Αλλά όταν σε ξαναδώ,\n"
	.string "μην ανησυχείς, δεν θα γκρινιάξω!$"

MatchCall_PersonalizedText8::
	.string "Γιούχου, εδώ {STR_VAR_1}!\n"
	.string "Τι κάνεις;\p"
	.string "Εκπαιδεύω τα POKéMON μου έχοντας\n"
	.string "εσένα ως στόχο.\p"
	.string "Δεν σκοπεύω να χάσω όταν\n"
	.string "παλέψουμε ξανά.\p"
	.string "Δεν είναι τέλειο να έχεις φίλους\n"
	.string "TRAINERS; Ας βρεθούμε πάλι!$"

MatchCall_PersonalizedText9::
	.string "Εδώ {STR_VAR_1}…\n"
	.string "Αυτή τη στιγμή, πίσω σου…\l"
	.string "Δεν υπήρχε κάτι…;\p"
	.string "Η δύναμη των POKéMON που\n"
	.string "κοιμούνται εδώ στο MT. PYRE…\p"
	.string "Μου μιλάει για εσένα…\p"
	.string "Πρέπει να φύγεις γρήγορα και\n"
	.string "να μην κοιτάξεις πίσω…\p"
	.string "Χαχανητό…\n"
	.string "Αντίο…$"

MatchCall_PersonalizedText10::
	.string "Εδώ {STR_VAR_1}.\n"
	.string "Τι κάνεις;\p"
	.string "Δεν είναι βολικό που μπορούμε να\n"
	.string "μιλάμε έτσι από απόσταση;\p"
	.string "Παλαιότερα, αν ήθελα να μιλήσω\n"
	.string "με κάποιον, έπρεπε να με πάει ο\l"
	.string "πατέρας μου με το αμάξι…\p"
	.string "Πρέπει να πηγαίνω τώρα.\n"
	.string "Χαίρομαι που τα είπαμε.$"

MatchCall_PersonalizedText11::
	.string "Εδώ {STR_VAR_1}!\n"
	.string "Θέλεις να ακούσεις αυτό;\p"
	.string "Μου αρέσει πολύ η SAFARI ZONE,\n"
	.string "αλλά όποτε πηγαίνω, χάνομαι!\p"
	.string "Όλο αυτό το ψηλό γρασίδι!\n"
	.string "Και είναι τόσο απλωμένη!\p"
	.string "Νιώθω καλύτερα τώρα που το είπα!\p"
	.string "Φεύγω για τη SAFARI ZONE πάλι!\n"
	.string "Τα λέμε!$"

MatchCall_PersonalizedText12::
	.string "Γεια, {STR_VAR_1} εδώ.\n"
	.string "Ναι, σωστά, έχω πολλά πλούτη, ναι.\p"
	.string "Πρέπει να σου πω, τα πλούτη μου\n"
	.string "μεγάλωσαν από τότε που τα είπαμε.\p"
	.string "Επιπλέον, τα POKéMON μου έχουν\n"
	.string "γίνει επίσης πιο δυνατά.\p"
	.string "Δεν μπορώ να διώξω την αίσθηση\n"
	.string "ότι αυτός ο κόσμος υπάρχει για μένα!\p"
	.string "Ω, δεν χρειάζεται να πεις λέξη!\n"
	.string "Όλοι ξέρουν ότι είναι αλήθεια!\p"
	.string "Ω, με συγχωρείς, έχω να\n"
	.string "παρευρεθώ σε ένα επίσημο δείπνο.$"

MatchCall_PersonalizedText13::
	.string "Ουφουφουφου…\n"
	.string "Είμαι εγώ, {STR_VAR_1}…\p"
	.string "Μαντεύεις τι βλέπω;\n"
	.string "Ένα ζευγάρι {STR_VAR_2} σε μάχη.\p"
	.string "Ίσως προσπαθήσω να πιάσω\n"
	.string "το POKéMON που θα νικήσει…\n"
	.string "Ουφουφουφουφου…\p"
	.string "Έχω κάποιες δουλειές τώρα.\n"
	.string "Πρέπει να κλείσω.$"

MatchCall_PersonalizedText14::
	.string "Ω, εδώ {STR_VAR_1}!\p"
	.string "Μόλις σκεφτόμουν ότι άρχισα να\n"
	.string "βαριέμαι το ABANDONED SHIP.\p"
	.string "Αλλά αφού είμαι ήδη εδώ,\n"
	.string "και θέλω να σε νικήσω μια φορά,\l"
	.string "θα μείνω εδώ γύρω λίγο ακόμα.\p"
	.string "Αν το θέλεις, γιατί δεν\n"
	.string "έρχεσαι να με βρεις;\p"
	.string "Νομίζω σήμερα είναι η μέρα που\n"
	.string "θα προκαλέσω τον διπλανό\l"
	.string "σε μάχη.\p"
	.string "Θα σε δω!$"

MatchCall_PersonalizedText15::
	.string "Είμαι ο {STR_VAR_1}!\n"
	.string "Ο άνθρωπος της θάλασσας!\p"
	.string "Ξέρεις τι πιστεύω;\p"
	.string "Οι TRAINERS στη θάλασσα είναι\n"
	.string "οι πιο σκληροί από όλους!\p"
	.string "Πρέπει να μάθεις από μένα και να\n"
	.string "προπονείσαι στη θάλασσα…\p"
	.string "Ωχ, σηκώνεται μεγάλο κύμα!\p"
	.string "Είναι τέλεια ευκαιρία προπόνησης!\n"
	.string "Συγγνώμη, αλλά πρέπει να φύγω!$"

MatchCall_PersonalizedText16::
	.string "Εδώ {STR_VAR_1}! Άκου, μαθαίνω\n"
	.string "karate στα POKéMON μου.\p"
	.string "Αλλά τώρα είναι καλύτερα από μένα!\n"
	.string "Μόνο χάνω από αυτά!\p"
	.string "Όμως, παρόλο που μπορεί να χάνω από\n"
	.string "POKéMON, δεν θα χάσω από άλλον\l"
	.string "TRAINER, με τίποτα!\p"
	.string "Πρέπει να παλέψουμε ξανά!\n"
	.string "Ουγκουάαα!$"

MatchCall_PersonalizedText17::
	.string "Είμαι εγώ, {STR_VAR_1}.\n"
	.string "Πώς εξελίσσονται τα ταξίδια σου;\p"
	.string "…Ω, αλήθεια;\n"
	.string "Ακούγεται απίστευτα ενδιαφέρον!\p"
	.string "Νομίζω θα μπορούσα να γράψω ένα\n"
	.string "τραγούδι για μια περιπέτειά σου.\p"
	.string "…Ω, ναι, το νιώθω.\n"
	.string "Ακούω τη μελωδία στο κεφάλι μου.\p"
	.string "Πρέπει να γράψω αυτό το κομμάτι\n"
	.string "σωστά, οπότε φεύγω! Τα λέμε!$"

MatchCall_PersonalizedText18::
	.string "Εδώ {STR_VAR_1}…\n"
	.string "Άκου το νέο μου τραγούδι.\p"
	.string "Λαλαλα, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Γιατί είσαι έτσι {STR_VAR_2};\l"
	.string "Γιατί δεν μπορώ να είμαι σαν εσένα,\n"
	.string "{STR_VAR_2}; Λαλα, {STR_VAR_2}\n"
	.string "και {STR_VAR_1}, {STR_VAR_1} και\n"
	.string "{STR_VAR_2}…\p"
	.string "Επανάληψη ρεφρέν, σβήσιμο…$"

MatchCall_PersonalizedText19::
	.string "Είμαι ο {STR_VAR_1}, ξέρεις,\n"
	.string "ο ειδικός στο camping!\p"
	.string "Όταν παλέψαμε, δεν μπόρεσα\n"
	.string "παρά να χάσω από εσένα.\p"
	.string "Άλλωστε, η ειδικότητά μου είναι\n"
	.string "το camping.\p"
	.string "Αλλά είτε νικάω είτε χάνω, μου\n"
	.string "αρέσει η μάχη στο camping.\p"
	.string "Παίξε μαζί μας ξανά, εντάξει;\n"
	.string "Ω, και ας πάμε για camping επίσης!$"

MatchCall_PersonalizedText20::
	.string "Είμαι εγώ, {STR_VAR_1}!\p"
	.string "Θα ήθελες να ανέβω σε άλλα βουνά\n"
	.string "εκτός από αυτό, για να είμαι ειλικρινής.\p"
	.string "Αλλά δεν είμαι σίγουρος/η αν θα\n"
	.string "έχει κορίτσια όπως στο MT. CHIMNEY.\p"
	.string "Αν ξέρεις κανένα άλλο βουνό\n"
	.string "με κορίτσια εκεί γύρω, πες μου!\p"
	.string "Εχεχεχε, τα λέμε εκεί έξω!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Εδώ {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Αυτά για σήμερα…$"

MatchCall_PersonalizedText22::
	.string "Εδώ {STR_VAR_1}. Σήμερα, είχα\n"
	.string "αυτό το συναίσθημα ότι θα μιλούσαμε.\p"
	.string "Η επιθυμία μου να σε νικήσω\n"
	.string "μεγαλώνει μέρα με τη νύχτα.\p"
	.string "Έχεις κι εσύ έναν τέτοιο αντίπαλο;\n"
	.string "Μακάρι να ήμουν εγώ…\p"
	.string "Χαίρομαι που με άκουσες.\n"
	.string "Τα λέμε!$"

MatchCall_PersonalizedText23::
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Όταν υπάρχει ένας δυνατός TRAINER\n"
	.string "κοντά, μπορώ να το νιώσω κάπως.\p"
	.string "Πέρασες από εδώ κοντά, {PLAYER};\n"
	.string "Ίσως ήσουν εσύ.\p"
	.string "Θα περιμένω την επίσκεψή σου.\n"
	.string "Γεια!$"

MatchCall_PersonalizedText24::
	.string "Γεια σου, εδώ {STR_VAR_1}.\n"
	.string "Ακούγεσαι καλά, {PLAYER}.\p"
	.string "Έχω ταξιδέψει σε όλο τον κόσμο,\n"
	.string "αλλά πρέπει να πω ότι αγάπησα\l"
	.string "αυτή την περιοχή.\p"
	.string "Σκοπεύω να μείνω εδώ για λίγο.\n"
	.string "Ίσως μπορούμε να βρεθούμε ξανά;\p"
	.string "Δεν έχω ξεχάσει τις εκπληκτικές\n"
	.string "τεχνικές σου.\p"
	.string "Ελπίζω πραγματικά σε μια ρεβάνς.$"

MatchCall_PersonalizedText25::
	.string "Κλάμα… Είμαι… {STR_VAR_1}…\n"
	.string "…Λυγμός…\p"
	.string "Η ROXANNE με μάλωσε στην τάξη\n"
	.string "σήμερα.\p"
	.string "Αλλά δεν την αντιπαθώ.\p"
	.string "Η ROXANNE μου λέει ακριβώς τι\n"
	.string "έκανα λάθος για να μάθω.\p"
	.string "Σίγουρα θα πάω στο\n"
	.string "TRAINER'S SCHOOL αύριο!\p"
	.string "Τα λέμε μετά!$"

MatchCall_PersonalizedText26::
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Η ROXANNE με άφησε να παλέψω\n"
	.string "μαζί της χθες.\p"
	.string "Τα αποτελέσματα…\n"
	.string "Χάλια, σιγά που ρωτάς.\p"
	.string "Αλλά χάρηκα τόσο που η ROXANNE\n"
	.string "με άφησε έστω να την προκαλέσω!\p"
	.string "Δεν φαντάζεσαι πόσο\n"
	.string "περισσότερο τη θαυμάζω!\p"
	.string "Θα συγκεντρωθώ και θα δουλέψω!\n"
	.string "Πρέπει να πηγαίνω!$"

MatchCall_PersonalizedText27::
	.string "Γεια, είμαι η ANNA! Είμαι με τη\n"
	.string "συνεργάτιδά μου MEG πάλι σήμερα.\p"
	.string "Λατρεύω να προσέχω τη MEG και τα\n"
	.string "POKéMON. Είναι τόσο γλυκά!\p"
	.string "Μακάρι να τα πρόσεχα σαν να\n"
	.string "ήταν αδέρφια μου!\p"
	.string "Ω, γεια, MEG!\n"
	.string "Πήρες τα ψωμάκια;\p"
	.string "Ε; Όχι, όχι, δεν σε έχω σαν\n"
	.string "προσωπικό μου σκλάβο!\p"
	.string "Έχασες τη μάχη, οπότε πρέπει\n"
	.string "να πας να πάρεις ψωμί για τιμωρία!\p"
	.string "Δεν θα σε είχα ποτέ σαν σκλάβο,\n"
	.string "MEG! Είσαι πολύ ξεχωριστή για μένα!\p"
	.string "Πρέπει να πηγαίνω τώρα.\n"
	.string "Ώρα για το κολατσιό μας!$"

MatchCall_PersonalizedText28::
	.string "Λατρεύω τα POKéMON!\n"
	.string "Εδώ {STR_VAR_1} από το FAN CLUB!\p"
	.string "Πρέπει να το ακούσεις αυτό!\n"
	.string "Το γλυκό μου POKéMON…\p"
	.string "Χαχανητό! Βαχάχα!\n"
	.string "Δεν λέω άλλα! Είναι μυστικό!\l"
	.string "Είναι υπερβολικά γλυκό για λόγια!\p"
	.string "Ω, το γλυκό μου {STR_VAR_2} ζητάει\n"
	.string "ένα {POKEBLOCK}!\p"
	.string "Είναι η προσωποποίηση της γλύκας!\p"
	.string "Συγγνώμη, δεν μπορώ να μιλήσω τώρα!\n"
	.string "Θα το μάθεις την επόμενη φορά!$"

MatchCall_PersonalizedText29::
	.string "Ωχόχο!\p"
	.string "Εδώ {STR_VAR_1}! Ανυπομονώ να\n"
	.string "σου πω για το αγαπημένο μου POKéMON!\p"
	.string "Σε παρακαλώ, πρέπει να το ακούσεις.\n"
	.string "Είναι για το λατρεμένο μου {STR_VAR_2}.\p"
	.string "Όποτε πάει κάποιος να το σηκώσει,\n"
	.string "πηδάει κατευθείαν στην αγκαλιά μου!\p"
	.string "Ω… Ω… Θα μπορούσε να υπάρχει\n"
	.string "κάτι πιο ευτυχισμένο;\p"
	.string "Ω, είναι τόσο παραδεισένιο!\p"
	.string "Χαίρομαι που μοιράστηκα λίγη\n"
	.string "από την ευτυχία μου μαζί σου.\p"
	.string "Λοιπόν, πρέπει να πηγαίνω.\n"
	.string "Αντίο τώρα!$"

MatchCall_PersonalizedText30::
	.string "Είμαι… {STR_VAR_1}.\n"
	.string "Ο κόσμος με αποκαλεί EXPERT.\p"
	.string "Αλλά ένα πράγμα ξέρω.\n"
	.string "Δεν θα ήμουν EXPERT μόνο με τη\l"
	.string "δική μου δύναμη.\p"
	.string "Μόνο με τη βοήθεια των POKéMON\n"
	.string "μπορεί ένας TRAINER να γίνει EXPERT.\p"
	.string "Μπαχ! Νομίζω πως είπα κάτι\n"
	.string "πολύ βαθύ και σημαντικό!\p"
	.string "Σε αφήνω με καλή διάθεση!$"

MatchCall_PersonalizedText31::
	.string "Εδώ {STR_VAR_1}.\n"
	.string "Χαίρομαι που τα λέμε!\p"
	.string "Νιώθω τρομερή ευεξία και\n"
	.string "χαλάρωση σε αυτές τις θερμές πηγές.\p"
	.string "Παλεύω με νέους TRAINERS από\n"
	.string "τότε που βρεθήκαμε, αλλά είσαι\l"
	.string "ακόμα η κορυφή.\p"
	.string "Φαντάζομαι θα γίνεις EXPERT\n"
	.string "στα γεράματά σου! Οχοχοχο…$"

MatchCall_PersonalizedText32::
	.string "Γιούπι! Εδώ {STR_VAR_1}!\n"
	.string "Τι γίνεται;\p"
	.string "Μπορεί να είναι ιδέα μου, αλλά όταν\n"
	.string "νικάω, το σορτσάκι μου φαίνεται\l"
	.string "να έχει, ξέρεις, καλύτερη αίσθηση.\p"
	.string "Τι εννοώ με αυτό;\n"
	.string "Είναι κάπως δύσκολο να εξηγήσω…\l"
	.string "Πώς να το πω τώρα…\l"
	.string "Το σορτσάκι μου μοιάζει πιο απαλό!\p"
	.string "Και όταν παλέψαμε, {PLAYER},\n"
	.string "το σορτσάκι μου ήταν σκληρό.\p"
	.string "… … … … … …\n"
	.string "Δεν το πίστεψες στ' αλήθεια αυτό;\l"
	.string "Εχεχεχε, αυτά! Αντίο τώρα!$"

MatchCall_PersonalizedText33::
	.string "Έι!\n"
	.string "{STR_VAR_1} here!\p"
	.string "Όπως πάντα, ψαρεύω με μανία!\p"
	.string "Υπάρχουν άλλα μέρη να ψαρέψω\n"
	.string "εκτός από τη θάλασσα και τα ποτάμια;\p"
	.string "Μου έρχεται αυτή η τρομερή ανάγκη\n"
	.string "να ψαρέψω οπουδήποτε!\p"
	.string "Ω, να πάρει η ευχή!\n"
	.string "Η πετονιά μου μπερδεύτηκε!\p"
	.string "Πρέπει να φύγω!\n"
	.string "Βρες μου νέα μέρη για ψάρεμα!$"

MatchCall_PersonalizedText34::
	.string "Έι! Εδώ {STR_VAR_1}.\n"
	.string "Το παίρνεις χαλαρά;\p"
	.string "Από παιδί, ξέρεις,\n"
	.string "ήμουν πάντα της ηρεμίας, ε;\p"
	.string "Δεν μου άρεσε ποτέ το άγχος\n"
	.string "ή να βιάζομαι.\p"
	.string "Αλλά δες πώς τα φέρνει η ζωή,\n"
	.string "τώρα είμαι TRIATHLETE.\p"
	.string "Δεν ξέρεις ποτέ πού θα σε βγάλει\n"
	.string "ο δρόμος, αν με καταλαβαίνεις.\p"
	.string "Τώρα είσαι TRAINER, αλλά ποιος\n"
	.string "ξέρει τι φέρνει το μέλλον;\p"
	.string "Φαντάσου τον εαυτό σου δάσκαλο\n"
	.string "ή ίσως καλλιτέχνη. Τέλειο, ε;\p"
	.string "Αλλά, έι, χαλάρωσε. Πάρ' το χαλαρά.\n"
	.string "Τα λέμε εκεί έξω.$"

MatchCall_PersonalizedText35::
	.string "Εδώ {STR_VAR_1}!\n"
	.string "Κάνω ποδήλατο τώρα.\p"
	.string "Μου αρέσει το κολύμπι και το τρέξιμο,\n"
	.string "αλλά το ποδήλατο είναι η αγάπη μου!\p"
	.string "Κάνει όλο μου το σώμα να νιώθει\n"
	.string "ένα με τον άνεμο.\p"
	.string "Με συναρπάζει σαν να\n"
	.string "πετάω!\p"
	.string "Ωραία! Σήμερα θα κάνω νέο ρεκόρ\n"
	.string "στο CYCLING ROAD!\p"
	.string "Πρέπει να δοκιμάσεις κι εσύ!\n"
	.string "Τα λέμε!$"

MatchCall_PersonalizedText36::
	.string "Έι, εδώ {STR_VAR_1}! Είμαι ακριβώς\n"
	.string "στη μέση ενός τριάθλου!\p"
	.string "Αλλά πάντα έχω χρόνο για\n"
	.string "κουβεντούλα!\p"
	.string "Η γυμναστική με POKéMON είναι\n"
	.string "τρομερή!\p"
	.string "Χωρίς λόγια, συντονιζόμαστε σαν\n"
	.string "να μοιραζόμαστε την ίδια καρδιά.\p"
	.string "Είναι συναρπαστικό!\p"
	.string "Λαχάνιασμα… Μιλώντας τρέχοντας…\n"
	.string "Κουράζομαι πολύ…\l"
	.string "Λαχάνιασμα… Πρέπει… να… κλείσω…$"

MatchCall_PersonalizedText37::
	.string "Γεια, εδώ {STR_VAR_1}.\n"
	.string "Αν θες να βελτιώσεις την αντοχή,\l"
	.string "η προπόνηση σε υψόμετρο είναι ό,τι πρέπει!\p"
	.string "Δοκίμασε να τρέξεις σε βουνοκορφή.\n"
	.string "Θα λαχανιάσεις αμέσως!\p"
	.string "Ξεμένω κι εγώ από οξυγόνο!\n"
	.string "Τα λέμε!$"

MatchCall_PersonalizedText38::
	.string "Ω, εδώ {STR_VAR_1}, γεια σου.\p"
	.string "Κολυμπάω πολύ αλλά ακόμα δεν\n"
	.string "μπορώ να φτάσω στην EVERGRANDE.\p"
	.string "Ίσως απλά πηγαίνω γύρω-γύρω.\p"
	.string "Όχι, όχι, αυτό αποκλείεται.\n"
	.string "Βαχάχαχα.\l"
	.string "Να προσέχεις!$"

MatchCall_PersonalizedText39::
	.string "Έι, εδώ {STR_VAR_1}…\n"
	.string "Ωχ!\p"
	.string "Μπαμ!\p"
	.string "Γκλουγκ-γκλουγκ-γκλουγκ…\p"
	.string "Πλουφ!\p"
	.string "Φου-φου! Φου-φου!\p"
	.string "Έι! Συγγνώμη για αυτό!\n"
	.string "Μόλις έβαζα αντηλιακό λάδι.\p"
	.string "Και το POKéNAV μου γλίστρησε\n"
	.string "από το χέρι κατευθείαν στο νερό!\p"
	.string "Αλλά το POKéNAV της DEVON είναι\n"
	.string "σκληρό. Επιβίωσε από τη βουτιά!\p"
	.string "Τέλος πάντων, κάνω ηλιοθεραπεία,\n"
	.string "οπότε τα λέμε άλλη φορά.$"

MatchCall_PersonalizedText40::
	.string "Γεια σου, εδώ {STR_VAR_1}.\p"
	.string "Από τα τρία αθλήματα του τριάθλου,\n"
	.string "μου αρέσει περισσότερο το κολύμπι.\p"
	.string "Αλλά αν μείνω στη θάλασσα πολύ,\n"
	.string "δεν θα γίνω σαν σταφίδα;\p"
	.string "Ωχ, το τρίαθλο είναι εξαντλητική\n"
	.string "δοκιμασία αντοχής! Αντίο!$"

MatchCall_PersonalizedText41::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πώς πάνε τα POKéMON σου;\p"
	.string "Τα DRAGON POKéMON μου φαίνεται να\n"
	.string "είναι σε τέλεια φόρμα. Γεια για τώρα.$"

MatchCall_PersonalizedText42::
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Το {STR_VAR_2} μου έχει γίνει ακόμα\n"
	.string "πιο δυνατό από την προηγούμενη φορά.\p"
	.string "Δεν πρόκειται να ξαναχάσω από σένα.\n"
	.string "Περίμενε μέχρι την επόμενη φορά!\p"
	.string "Τα λέμε εκεί έξω!$"

MatchCall_PersonalizedText43::
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Συνέχισα τις μελέτες μου στην\n"
	.string "τέχνη της απόκρυψης.\p"
	.string "Αλλά είχα υπερβολική επιτυχία.\n"
	.string "Κανείς δεν μπορεί να με βρει.\l"
	.string "Η επιτυχία μου φέρνει μοναξιά…\p"
	.string "Σαν καπνός εξαφανίζομαι!\n"
	.string "Αντίο!$"

MatchCall_PersonalizedText44::
	.string "Εδώ {STR_VAR_1}.\n"
	.string "Συνέχισα την προπόνηση από τότε.\p"
	.string "Το {STR_VAR_2} μου έχει γίνει πολύ\n"
	.string "δυνατό.\p"
	.string "Η προπόνηση στην παραλία είναι\n"
	.string "αποτελεσματική, όπως ακριβώς\l"
	.string "νόμιζα. Αντίο τώρα!$"

MatchCall_PersonalizedText45::
	.string "Τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Αναρωτιέμαι πότε θα σταματήσει\n"
	.string "να πέφτει αυτή η ηφαιστειακή στάχτη;\p"
	.string "Αν μαζευτεί πολύ, θα καλύψει\n"
	.string "το σχέδιο στην ομπρέλα μου…\p"
	.string "Ας υποσχεθούμε να τα ξαναπούμε!$"

MatchCall_PersonalizedText46::
	.string "Γεια, {STR_VAR_1} εδώ.\p"
	.string "Ήξερες ότι είναι πιο εύκολο να\n"
	.string "επιπλέεις στη θάλασσα παρά σε πισίνα;\p"
	.string "Αν ξαπλώσεις ακίνητα, το σώμα σου\n"
	.string "θα επιπλεύσει από μόνο του.\p"
	.string "Αλλά αν επιπλέεις για πολύ ώρα,\n"
	.string "πρόσεχε μην παρασυρθείς πολύ\l"
	.string "μακριά στα ανοιχτά.\p"
	.string "…Πού είμαι, αλήθεια;\p"
	.string "Πρέπει να πηγαίνω!$"

MatchCall_PersonalizedText47::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Είμαι πάνω στα βουνά τώρα.\p"
	.string "Αλλά το έδαφος είναι πολύ ανώμαλο.\n"
	.string "Δεν μπορώ να στήσω τη σκηνή μου…\p"
	.string "Ω, είχα μια φανταστική ιδέα!\p"
	.string "Ίσως μπορώ να βάλω τα POKéMON μου\n"
	.string "να ισιώσουν το έδαφος εδώ!\p"
	.string "Θα το δοκιμάσω αυτό!\n"
	.string "Γεια-γεια!$"

MatchCall_PersonalizedText48::
	.string "Ω, γεια, γεια, εδώ {STR_VAR_1}!\p"
	.string "Εκπαιδεύω POKéMON με τη LIV!\n"
	.string "Προσπαθούμε πάρα πολύ!\p"
	.string "Αν προσπαθήσουμε περισσότερο, λες\n"
	.string "να γίνουμε νούμερο ένα; Γεια-γεια!$"

MatchCall_PersonalizedText49::
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Είμαι SAILOR, αλλά δεν είμαι σε\n"
	.string "πλοίο τώρα.\p"
	.string "Αναρωτιέμαι--πώς πρέπει να λέγεται\n"
	.string "ένας SAILOR στη στεριά;\p"
	.string "Αυτό σκεφτόμουν καθώς κοιτούσα\n"
	.string "πέρα από τα κύματα.\p"
	.string "Εντάξει, την επόμενη φορά!$"

MatchCall_PersonalizedText50::
	.string "Εδώ {STR_VAR_1}.\n"
	.string "Λοιπόν; Πήρες άλλα POKéMON;\p"
	.string "Αν πιάσεις κάποιο νέο POKéMON,\n"
	.string "πρέπει να έρθεις να μου το δείξεις.\p"
	.string "Δεν θα σου γκρινιάξω, αλήθεια.\n"
	.string "Θα περιμένω. Τα λέμε.$"

MatchCall_PersonalizedText51::
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Εκπαιδεύεις τα POKéMON σου\n"
	.string "με τον καλύτερο τρόπο;\p"
	.string "Ο αέρας είναι καθαρός εδώ που είμαι.\n"
	.string "Είναι το τέλειο περιβάλλον για\l"
	.string "την εκπαίδευση POKéMON.\p"
	.string "Αν σκοπεύεις να συγκεντρωθείς σε\n"
	.string "αυτό, πρέπει να έρθεις στο\l"
	.string "{STR_VAR_2}. Να προσέχεις.$"

MatchCall_PersonalizedText52::
	.string "Γεια, εδώ {STR_VAR_1}.\p"
	.string "Έδωσα ένα {POKEBLOCK} στο {STR_VAR_2} μου.\n"
	.string "Φάνηκε να του αρέσει πάρα πολύ.\p"
	.string "Φαίνεται ότι τα POKéMON έχουν τις\n"
	.string "προτιμήσεις τους στα {POKEBLOCK}S.\p"
	.string "Το βρίσκω αρκετά ενδιαφέρον.\n"
	.string "Να προσέχεις.$"

MatchCall_PersonalizedText53::
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Αν συνεργάζεσαι με τα POKéMON,\n"
	.string "μπορείς να ζήσεις άνετα στη φύση.\p"
	.string "Όλοι πρέπει να το καταλάβουν και να\n"
	.string "συνεργάζονται περισσότερο μαζί τους.\p"
	.string "Αυτό θα ήταν το ιδανικό.\n"
	.string "Πραγματικά το πιστεύω.\p"
	.string "Νομίζω ότι είσαι σε καλό δρόμο!\n"
	.string "Τα λέμε μετά!$"

MatchCall_PersonalizedText54::
	.string "Γεια, εδώ {STR_VAR_1}. Ξέρεις,\n"
	.string "ο/η TRAINER που είναι πάντα\n"
	.string "σε ετοιμότητα!\p"
	.string "{PLAYER}, έχεις αρκετά αντικείμενα;\n"
	.string "Είναι τα POKéMON σου έτοιμα για μάχη;\p"
	.string "Το να έχεις τα πάντα τέλεια γύρω\n"
	.string "σου είναι το μυστικό για να\l"
	.string "συνεχίσεις το ταξίδι σου.\p"
	.string "Πάω να ελέγξω τα δικά μου\n"
	.string "εφόδια! Να είσαι σε εγρήγορση!$"

MatchCall_PersonalizedText55::
	.string "Εδώ {STR_VAR_1}!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Το {STR_VAR_2} είναι πολυσύχναστος\n"
	.string "δρόμος, οπότε με προκαλούν κάθε\l"
	.string "λογής TRAINERS κάθε μέρα.\p"
	.string "Σήμερα κέρδισα πέντε μάχες και\n"
	.string "έχασα μόνο τρεις!\p"
	.string "Πώς τα πήγες εσύ σήμερα;\n"
	.string "Πες μου την επόμενη φορά, οκ;$"

MatchCall_PersonalizedText56::
	.string "Είμαι εγώ, ο {STR_VAR_1}.\p"
	.string "Είμαι δημοφιλής επειδή έχω πολλά\n"
	.string "BUG POKéMON, σωστά;\p"
	.string "Λοιπόν, πήρα μια παρέα από τα\n"
	.string "αγαπημένα μου έντομα στο σχολείο.\p"
	.string "Ένα κορίτσι που μου αρέσει έκλαψε!\n"
	.string "Γέλα αν θες.\p"
	.string "Πρέπει να προσπαθήσω να της δείξω\n"
	.string "τι κάνει τα BUG POKéMON ελκυστικά.\p"
	.string "Κλάμα…\n"
	.string "Τα λέμε!$"

MatchCall_PersonalizedText57::
	.string "Χα! Χα! Χα! Χα!\p"
	.string "Γεια! Εδώ {STR_VAR_1}! Χα! Χα!\p"
	.string "Το να μιλάς…\n"
	.string "Καθώς σκαρφαλώνεις…\l"
	.string "Είναι σκληρή άσκηση… Χα! Χα!\p"
	.string "Ουχ! Ωχ…\n"
	.string "Έγινε πιο απότομο τώρα…\l"
	.string "Θα τα πούμε… άλλη φορά…\l"
	.string "Χα! Χα! Χα!$"

MatchCall_PersonalizedText58::
	.string "Ω, γεια!\p"
	.string "Ψάχνω ακόμα για θησαυρούς\n"
	.string "με την KIRA!\p"
	.string "Ίσως να μην υπάρχει κανένας\n"
	.string "θησαυρός εδώ γύρω τελικά…\p"
	.string "Αλλά το σημαντικό είναι ότι\n"
	.string "ψάχνω μαζί με την KIRA.\p"
	.string "Ω, έι, KIRA!\n"
	.string "Για-γιατί είσαι θυμωμένη;\p"
	.string "Δεν σε αγνοώ, αγάπη μου!\n"
	.string "Είσαι η μοναδική μου!\p"
	.string "…{PLAYER}, πρέπει να κλείσω, γεια!$"

MatchCall_PersonalizedText59::
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Πήγα στο GYM της DEWFORD πάλι\n"
	.string "για προπόνηση.\p"
	.string "Ο BRAWLY, ο GYM LEADER, φαίνεται\n"
	.string "να έχει γίνει πιο δυνατός.\p"
	.string "Κάτι για το ότι σκληραγωγήθηκε\n"
	.string "από τα άγρια κύματα…\p"
	.string "Αλλά είναι ακόμα τόσο κουλ.\n"
	.string "Τα κορίτσια τον λατρεύουν!\l"
	.string "Ζηλεύω, για να είμαι ειλικρινής.\p"
	.string "Αναρωτιέμαι… Είναι ο φίλος του ο\n"
	.string "BRUNO ίδιος με τον BRAWLY;\p"
	.string "Ξέρεις, όλο ιδρωμένος, μυρωδάτος,\n"
	.string "και να φωνάζει “μεγάλο κύμα”;\p"
	.string "Αλλά, έι, αυτή η ζήλεια δεν είναι\n"
	.string "πολύ κομψή, έτσι;\p"
	.string "Ξέχνα ότι έγινε αυτή η κουβέντα,\n"
	.string "τι λες; Τα λέμε!$"

MatchCall_PersonalizedText60::
	.string "Είναι χαρά να μιλάω με έναν\n"
	.string "νεαρό TRAINER σαν εσένα.\p"
	.string "Φαντάζομαι ότι θα συνεχίσεις να\n"
	.string "απολαμβάνεις τα POKéMON σε κάθε ηλικία.\p"
	.string "Δεν θα ήταν ωραίο να είχες μια\n"
	.string "σχέση σαν τη δική μας;\p"
	.string "Φυσικά, {PLAYER}, απολαμβάνεις ήδη\n"
	.string "την εμπιστοσύνη και συντροφιά\l"
	.string "των POKéMON σου τώρα.\p"
	.string "Έχεις ήδη τα φόντα για μακροχρόνιες\n"
	.string "και σταθερές σχέσεις!\p"
	.string "Χαχαχα!\n"
	.string "Ποτέ μην αποθαρρύνεσαι!$"

MatchCall_PersonalizedText61::
	.string "Γεια, εδώ {STR_VAR_1}!\n"
	.string "Μόλις κερδίσαμε μια μάχη!\p"
	.string "Δεν νικάμε συχνά, αλλά ήταν ένας\n"
	.string "κουλ SWIMMER.\p"
	.string "Η αδερφή μου είχε γίνει έξαλλη!\p"
	.string "Ήθελε να προσποιηθεί ότι είναι\n"
	.string "αδύναμη για να κάνει εντύπωση!\p"
	.string "Με μαλώνει πάντα, είτε\n"
	.string "κερδίζουμε είτε χάνουμε!\p"
	.string "{PLAYER}, μπορείς να της πεις κάτι\n"
	.string "την επόμενη φορά;\p"
	.string "Εντάξει, τα λέμε!$"

MatchCall_PersonalizedText62::
	.string "Εδώ {STR_VAR_1}, ναι.\n"
	.string "Βγήκα στη θάλασσα χθες.\p"
	.string "Ήλπιζα να βρω κάποιο νέο\n"
	.string "ερείπιο να εξερευνήσω.\p"
	.string "Αλλά τα ρεύματα κάπως με\n"
	.string "έφεραν πίσω από εκεί που ξεκίνησα.\p"
	.string "Υστερώ ακόμα στις μάχες…\n"
	.string "Μπορείς ελεύθερα να με κοροϊδέψεις…\l"
	.string "Αλλά δεν θα τα παρατήσω.\p"
	.string "Θα έρθει η μέρα που θα ανακαλύψω\n"
	.string "ένα νέο ερείπιο!\p"
	.string "Αυτά είχα να πω!\n"
	.string "Αντίο προς το παρόν!$"

MatchCall_PersonalizedText63::
	.string "Έι εκεί!\n"
	.string "Είμαι εγώ, ο {STR_VAR_1}!\l"
	.string "Είμαι έξω στο ROUTE 108 τώρα!\l"
	.string "Δηλαδή, εκεί που είμαι πάντα!\p"
	.string "Σήμερα, μια πανέμορφη SWIMMER\n"
	.string "πέρασε κολυμπώντας από δίπλα μου!\p"
	.string "Οπότε την ξάφνιασα με μια φωνή!\p"
	.string "Και μου έριξε ένα άγριο βλέμμα!\p"
	.string "Αυτά από το ROUTE 108!\n"
	.string "Από τον {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Έχω κάποιες δουλειές, αλλά\n"
	.string "ήθελα να σου πω ότι νίκησα\l"
	.string "πέντε TRAINERS πάλι σήμερα.\p"
	.string "Αν συνεχίσω έτσι, μάλλον θα σε\n"
	.string "νικήσω την επόμενη φορά.\p"
	.string "Πιστεύω θα γίνουμε καλοί αντίπαλοι,\n"
	.string "εσύ κι εγώ. Αντίο προς το παρόν!$"

MatchCall_BattleFrontierStreakText1::
	.string "Γεια! Εδώ {STR_VAR_1}.\n"
	.string "Έμαθα τα νέα!\p"
	.string "Λένε ότι τα πήγες περίφημα στο\n"
	.string "{STR_VAR_2}.\p"
	.string "Είναι τρομερό, {STR_VAR_3} συνεχόμενες νίκες;\n"
	.string "Τα λέμε!$"

MatchCall_BattleFrontierStreakText2::
	.string "Γεια, εδώ {STR_VAR_1}!\n"
	.string "Έμαθα για εσένα!\p"
	.string "Είπαν ότι κέρδισες {STR_VAR_3} σερί\n"
	.string "μάχες στο {STR_VAR_2}.\p"
	.string "Αυτό είναι ξεχωριστό! Πρέπει να\n"
	.string "προσπαθήσω κι εγώ! Τα λέμε!$"

MatchCall_BattleFrontierStreakText3::
	.string "Έι, {PLAYER}!\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\p"
	.string "Έμαθα ότι σάρωσες στο\n"
	.string "{STR_VAR_2}!\p"
	.string "Ένα μεγάλο σερί {STR_VAR_3} νικών…\n"
	.string "Αυτό είναι μεγάλο ρεκόρ, έτσι;\p"
	.string "Πρέπει να στρωθώ κι εγώ!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleFrontierStreakText4::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}. Τι γίνεται;\p"
	.string "Κυκλοφορεί μια φήμη ότι\n"
	.string "έκανες {STR_VAR_3} συνεχόμενες\l"
	.string "νίκες στο {STR_VAR_2}.\p"
	.string "Πρέπει να ανεβάσω ρυθμούς κι εγώ.\n"
	.string "Τα λέμε!$"

MatchCall_BattleFrontierStreakText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ήσουν στο {STR_VAR_2}\n"
	.string "και κέρδισες {STR_VAR_3} μάχες στη σειρά;\l"
	.string "Αυτό κι αν είναι εντυπωσιακό!\p"
	.string "Πρέπει να προπονήσω τα POKéMON μου.\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleFrontierStreakText6::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}. Πώς είσαι;\p"
	.string "Παρεμπιπτόντως, έμαθα ότι πέτυχες\n"
	.string "το κατόρθωμα των {STR_VAR_3} σερί νικών στο\l"
	.string "{STR_VAR_2}.\p"
	.string "Αυτό με εμπνέει να αφοσιωθώ\n"
	.string "στην ομάδα μου.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Ε, {PLAYER}?\n"
	.string "Εδώ {STR_VAR_1}…\p"
	.string "Ω, ναι, ήσουν στο\n"
	.string "{STR_VAR_2}, σωστά;\p"
	.string "Και κέρδισες {STR_VAR_3} μάχες στη σειρά.\p"
	.string "Ω, ορίστε ένα σπάνιο POKéMON!\n"
	.string "Πρέπει να φύγω!$"

MatchCall_BattleFrontierStreakText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Ω, αλλά είσαι. Έμαθα ότι\n"
	.string "κέρδισες {STR_VAR_3} μάχες στη σειρά στο\l"
	.string "{STR_VAR_2}.\p"
	.string "Αυτό είναι πολύ εντυπωσιακό!\n"
	.string "Σου εύχομαι πάντα επιτυχίες.$"

MatchCall_BattleFrontierStreakText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Το έμαθα! Το σερί {STR_VAR_3} νικών σου\n"
	.string "στο {STR_VAR_2}!\p"
	.string "Αυτό είναι τόσο τέλειο!\n"
	.string "Πρέπει να προσπαθήσω κι εγώ!$"

MatchCall_BattleFrontierStreakText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Κέρδισες {STR_VAR_3} σερί μάχες στο\n"
	.string "{STR_VAR_2};\p"
	.string "Αυτό είναι σπουδαίο επίτευγμα.\n"
	.string "Πρέπει να δουλέψω σκληρότερα.$"

MatchCall_BattleFrontierStreakText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι είσαι ο φόβος και\n"
	.string "ο τρόμος του {STR_VAR_2};\p"
	.string "Κέρδισες, τι, {STR_VAR_3} μάχες στη\n"
	.string "σειρά;\p"
	.string "Έχεις πολλή ικανότητα, εσύ.\n"
	.string "Αναρωτιέμαι πόσες μπορώ να νικήσω;$"

MatchCall_BattleFrontierStreakText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Είσαι καλά;\p"
	.string "Κάποιος μου μετέφερε τα νέα για σένα.\n"
	.string "Ότι κέρδισες {STR_VAR_3} σερί μάχες\l"
	.string "σε ένα μέρος που λέγεται {STR_VAR_2};\p"
	.string "Αυτή κι αν είναι ιστορία.\n"
	.string "Τα λέμε!$"

MatchCall_BattleFrontierStreakText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Λένε ότι κέρδισες {STR_VAR_3} σερί\n"
	.string "μάχες στο {STR_VAR_2}.\p"
	.string "Θαυμάζω την ενέργειά σου!\n"
	.string "Αντίο τώρα.$"

MatchCall_BattleFrontierStreakText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα για εσένα!\n"
	.string "Δεν κέρδισες μόλις {STR_VAR_3} μάχες στη\l"
	.string "σειρά στο {STR_VAR_2};\p"
	.string "Αποτελείς έμπνευση!\n"
	.string "Γεια-γεια!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Γεια! Εδώ {STR_VAR_1}.\n"
	.string "Έμαθα τα νέα!\p"
	.string "Λένε ότι τα πήγες περίφημα στο\n"
	.string "{STR_VAR_2}.\p"
	.string "Είναι τρομερό--{STR_VAR_3} σερί νίκες;\n"
	.string "Τα λέμε!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Γεια, εδώ {STR_VAR_1}!\n"
	.string "Έμαθα για εσένα!\p"
	.string "Είπαν ότι κέρδισες {STR_VAR_3} σερί\n"
	.string "μάχες στο {STR_VAR_2}.\p"
	.string "Αυτό είναι ξεχωριστό! Πρέπει να\n"
	.string "προσπαθήσω κι εγώ! Τα λέμε!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Έι, {PLAYER}!\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\p"
	.string "Έμαθα ότι σάρωσες στο\n"
	.string "{STR_VAR_2}!\p"
	.string "Ένα μεγάλο σερί {STR_VAR_3} νικών…\n"
	.string "Αυτό είναι μεγάλο ρεκόρ, έτσι;\p"
	.string "Πρέπει να στρωθώ κι εγώ!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}. Τι γίνεται;\p"
	.string "Κυκλοφορεί μια φήμη ότι\n"
	.string "έκανες {STR_VAR_3} συνεχόμενες\l"
	.string "νίκες στο {STR_VAR_2}.\p"
	.string "Πρέπει να ανεβάσω ρυθμούς κι εγώ.\n"
	.string "Τα λέμε!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ήσουν στο {STR_VAR_2}\n"
	.string "και κέρδισες {STR_VAR_3} μάχες στη σειρά;\l"
	.string "Αυτό κι αν είναι εντυπωσιακό!\p"
	.string "Εγώ; Θα έλεγα ότι τα πάω καλά.\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}. Πώς είσαι;\p"
	.string "Παρεμπιπτόντως, έμαθα ότι πέτυχες\n"
	.string "το κατόρθωμα των {STR_VAR_3} σερί νικών στο\l"
	.string "{STR_VAR_2}.\p"
	.string "Πρέπει να προσπαθήσω κι εγώ!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Ε, {PLAYER}?\n"
	.string "Εδώ {STR_VAR_1}…\p"
	.string "Ω, ναι, ήσουν στο\n"
	.string "{STR_VAR_2}, σωστά;\p"
	.string "Και κέρδισες {STR_VAR_3} μάχες στη σειρά.\p"
	.string "Ω, ορίστε ένα σπάνιο POKéMON!\n"
	.string "Πρέπει να φύγω!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Ω, αλλά είσαι. Έμαθα ότι\n"
	.string "κέρδισες {STR_VAR_3} μάχες στη σειρά στο\l"
	.string "{STR_VAR_2}.\p"
	.string "Αυτό είναι πολύ εντυπωσιακό!\n"
	.string "Πρέπει να εκπαιδεύσω κι εγώ!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Το έμαθα! Το σερί {STR_VAR_3} νικών σου\n"
	.string "στο {STR_VAR_2}!\p"
	.string "Αυτό είναι τόσο τέλειο!\n"
	.string "Πρέπει να προσπαθήσω κι εγώ!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Κέρδισες {STR_VAR_3} σερί μάχες στο\n"
	.string "{STR_VAR_2};\p"
	.string "Αυτό είναι σπουδαίο επίτευγμα.\n"
	.string "Πρέπει να δουλέψω σκληρότερα.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι είσαι ο φόβος και\n"
	.string "ο τρόμος του {STR_VAR_2};\p"
	.string "Κέρδισες, τι, {STR_VAR_3} μάχες στη\n"
	.string "σειρά;\p"
	.string "Έχεις πολλή ικανότητα, εσύ.\n"
	.string "Αναρωτιέμαι πόσες μπορώ να νικήσω;$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Είσαι καλά;\p"
	.string "Κάποιος μου μετέφερε τα νέα για σένα.\n"
	.string "Ότι κέρδισες {STR_VAR_3} σερί μάχες\l"
	.string "σε ένα μέρος που λέγεται {STR_VAR_2};\p"
	.string "Αυτή κι αν είναι ιστορία.\n"
	.string "Τα λέμε!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Λένε ότι κέρδισες {STR_VAR_3} σερί\n"
	.string "μάχες στο {STR_VAR_2}.\p"
	.string "Θαυμάζω την ενέργειά σου!\n"
	.string "Αντίο τώρα.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Έμαθα για εσένα!\p"
	.string "Δεν κέρδισες μόλις {STR_VAR_3} μάχες στη\n"
	.string "σειρά στο {STR_VAR_2};\p"
	.string "Αποτελείς έμπνευση!\n"
	.string "Γεια-γεια!$"

MatchCall_BattleDomeText1::
	.string "Γεια! {PLAYER};\n"
	.string "Γεια σου, εδώ {STR_VAR_1}!\l"
	.string "Έμαθα τα νέα!\p"
	.string "Έγινες champion στο\n"
	.string "{STR_VAR_2} {STR_VAR_3} φορές;\p"
	.string "Είναι τρομερό! Πρέπει να\n"
	.string "προσπαθήσω περισσότερο! Τα λέμε!$"

MatchCall_BattleDomeText2::
	.string "Γεια, εδώ {STR_VAR_1}!\n"
	.string "Έμαθα για εσένα!\p"
	.string "Είπαν ότι κέρδισες {STR_VAR_3} τίτλους\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Αυτό είναι σούπερ! Αναρωτιέμαι αν\n"
	.string "μπορώ να γίνω κι εγώ champion;$"

MatchCall_BattleDomeText3::
	.string "Έι, {PLAYER}!\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Πώς πάει;\p"
	.string "Έμαθα ότι κέρδισες διοργανώσεις\n"
	.string "{STR_VAR_3} φορές στο {STR_VAR_2}!\p"
	.string "Κάν' τες μία ακόμα την επόμενη φορά!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleDomeText4::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι έγινες champion\n"
	.string "στο {STR_VAR_2} {STR_VAR_3} φορές.\p"
	.string "Φαίνεται ότι προσπαθείς πολύ.\n"
	.string "Θα προσπαθήσω να σε φτάσω!$"

MatchCall_BattleDomeText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι κέρδισες {STR_VAR_3} φορές\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Πρέπει να στρωθώ κι εγώ στη δουλειά!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattleDomeText6::
	.string "Έι, {PLAYER};\n"
	.string "Εδώ {STR_VAR_1}. Πώς είσαι;\p"
	.string "Παρεμπιπτόντως, έμαθα ότι έγινες\n"
	.string "champion {STR_VAR_3} φορές στο\l"
	.string "{STR_VAR_2}.\p"
	.string "Πρέπει να δυναμώσω τα POKéMON μου\n"
	.string "προτού ξεφύγεις κι άλλο.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER};\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ήσουν στο {STR_VAR_2}\n"
	.string "κι έγινες champion {STR_VAR_3} φορές;\p"
	.string "Τέλειο. Παρεμπιπτόντως, έπιασες\n"
	.string "κανένα σπάνιο POKéMON τελευταία;\p"
	.string "Α, αλήθεια;\n"
	.string "Εντάξει, γεια.$"

MatchCall_BattleDomeText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να είσαι καλά.\l"
	.string "Ω, αλλά είσαι.\p"
	.string "Έμαθα ότι κέρδισες {STR_VAR_3} τίτλους\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Πρέπει να προπονώ τα POKéMON μου\n"
	.string "όπως εσύ. Τα λέμε πάλι.$"

MatchCall_BattleDomeText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Το έμαθα! Πήρες τον τίτλο\n"
	.string "{STR_VAR_3} φορές στο {STR_VAR_2}!\p"
	.string "Αυτό είναι τόσο τέλειο!\n"
	.string "Πρέπει να προσπαθήσω κι εγώ!$"

MatchCall_BattleDomeText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Κέρδισες {STR_VAR_3} σερί φορές στο\n"
	.string "{STR_VAR_2};\p"
	.string "Αυτό είναι σπουδαίο επίτευγμα.\n"
	.string "Πρέπει να δουλέψω σκληρότερα.$"

MatchCall_BattleDomeText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι είσαι ο φόβος και\n"
	.string "ο τρόμος του {STR_VAR_2};\p"
	.string "Κέρδισες, τι, {STR_VAR_3} σερί φορές\n"
	.string "τώρα;\p"
	.string "Αναρωτιέμαι αν θα γίνω ποτέ\n"
	.string "champion;\p"
	.string "…Μάλλον απίθανο;\n"
	.string "Λοιπόν, τα λέμε!$"

MatchCall_BattleDomeText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Είσαι καλά;\p"
	.string "Κέρδισες {STR_VAR_3} διοργανώσεις σε\n"
	.string "ένα μέρος που λέγεται {STR_VAR_2};\p"
	.string "Αυτή κι αν είναι ιστορία.\n"
	.string "Τα λέμε!$"

MatchCall_BattleDomeText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Έμαθα για εσένα!\p"
	.string "Δεν κέρδισες {STR_VAR_3} τίτλους\n"
	.string "στο {STR_VAR_2};\p"
	.string "Αποτελείς έμπνευση!\n"
	.string "Τα λέμε πάλι!$"

MatchCall_BattlePikeText1::
	.string "Γεια! {PLAYER};\n"
	.string "Γεια σου, εδώ {STR_VAR_1}!\l"
	.string "Έμαθα τα νέα!\p"
	.string "Πέρασες από {STR_VAR_3} δωμάτια\n"
	.string "στο {STR_VAR_2}!\p"
	.string "Είναι τρομερό!\n"
	.string "Τα λέμε!$"

MatchCall_BattlePikeText2::
	.string "Γεια, εδώ {STR_VAR_1}!\n"
	.string "Έμαθα για εσένα!\p"
	.string "Είπαν ότι πέρασες από\n"
	.string "{STR_VAR_3} δωμάτια στο {STR_VAR_2}.\p"
	.string "Πρέπει να προσπαθήσω πολύ περισσότερο!\n"
	.string "Γεια!$"

MatchCall_BattlePikeText3::
	.string "Έι, {PLAYER}!\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Πώς πάει;\p"
	.string "Έμαθα ότι πέρασες από {STR_VAR_3} δωμάτια\n"
	.string "στο {STR_VAR_2}!\p"
	.string "Προσπάθησε ακόμα καλύτερα μετά!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattlePikeText4::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι πέρασες από {STR_VAR_3} δωμάτια\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Πρέπει να προπονήσω τα POKéMON μου\n"
	.string "και να προσπαθήσω να σε φτάσω!$"

MatchCall_BattlePikeText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι πέρασες {STR_VAR_3} δωμάτια\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Πρέπει να στρωθώ κι εγώ στη δουλειά!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattlePikeText6::
	.string "Έι, {PLAYER};\n"
	.string "Εδώ {STR_VAR_1}. Πώς είσαι;\p"
	.string "Παρεμπιπτόντως, έμαθα ότι πέρασες\n"
	.string "από {STR_VAR_3} δωμάτια στο {STR_VAR_2}.\p"
	.string "Πρέπει να δυναμώσω τα POKéMON μου\n"
	.string "προτού ξεφύγεις κι άλλο.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER};\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ήσουν στο {STR_VAR_2}\n"
	.string "και πέρασες {STR_VAR_3} δωμάτια;\p"
	.string "Αυτό είναι φοβερό.\p"
	.string "Ω, ορίστε ένα σπάνιο POKéMON!\n"
	.string "Εντάξει, γεια.$"

MatchCall_BattlePikeText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να είσαι καλά.\l"
	.string "Ω, αλλά είσαι.\p"
	.string "Έμαθα ότι πέρασες από\n"
	.string "{STR_VAR_3} δωμάτια στο {STR_VAR_2}.\p"
	.string "Αυτό είναι πολύ εντυπωσιακό!\n"
	.string "Πρέπει να προπονώ τα POKéMON μου\l"
	.string "όπως εσύ. Τα λέμε πάλι.$"

MatchCall_BattlePikeText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Το έμαθα! Πέρασες από\n"
	.string "{STR_VAR_3} δωμάτια στο {STR_VAR_2}!\p"
	.string "Αυτό είναι τόσο τέλειο!\n"
	.string "Πρέπει να προσπαθήσω κι εγώ!$"

MatchCall_BattlePikeText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Πέρασες {STR_VAR_3} δωμάτια στο\n"
	.string "{STR_VAR_2};\p"
	.string "Αυτό είναι σπουδαίο επίτευγμα.\n"
	.string "Πρέπει να δουλέψω σκληρότερα.$"

MatchCall_BattlePikeText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι είσαι ο φόβος και\n"
	.string "ο τρόμος του {STR_VAR_2};\p"
	.string "Πέρασες, τι, {STR_VAR_3} δωμάτια;\n"
	.string "Αυτό σίγουρα μετράει.\p"
	.string "Αναρωτιέμαι αν θα γίνω ποτέ\n"
	.string "champion;\p"
	.string "…Μάλλον απίθανο;\n"
	.string "Λοιπόν, τα λέμε!$"

MatchCall_BattlePikeText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Είσαι καλά;\p"
	.string "Πέρασες {STR_VAR_3} δωμάτια σε\n"
	.string "ένα μέρος που λέγεται {STR_VAR_2};\p"
	.string "Αυτή κι αν είναι ιστορία.\n"
	.string "Τα λέμε!$"

MatchCall_BattlePikeText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Λένε ότι νίκησες σε {STR_VAR_3} δωμάτια\n"
	.string "στο {STR_VAR_2};\p"
	.string "Θαυμάζω την ενέργειά σου!\n"
	.string "Αντίο τώρα.$"

MatchCall_BattlePikeText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Έμαθα για εσένα!\p"
	.string "Δεν πέρασες {STR_VAR_3} δωμάτια\n"
	.string "στο {STR_VAR_2};\p"
	.string "Αποτελείς έμπνευση!\n"
	.string "Τα λέμε πάλι!$"

MatchCall_BattlePyramidText1::
	.string "Γεια! {PLAYER};\n"
	.string "Γεια σου, εδώ {STR_VAR_1}!\l"
	.string "Έμαθα τα νέα!\p"
	.string "Ανέβηκες {STR_VAR_3} ορόφους στο\n"
	.string "{STR_VAR_2}, σωστά;\p"
	.string "Είναι τρομερό!\n"
	.string "Πρέπει να δοκιμάσω αυτή την πρόκληση.$"

MatchCall_BattlePyramidText2::
	.string "Γεια, εδώ {STR_VAR_1}!\n"
	.string "Έμαθα για εσένα!\p"
	.string "Είπαν ότι πέρασες από {STR_VAR_3}\n"
	.string "ορόφους στο {STR_VAR_2}.\p"
	.string "Ωχ, αυτό είναι φανταστικό!\n"
	.string "Πρέπει να δυναμώσω τα POKéMON μου!$"

MatchCall_BattlePyramidText3::
	.string "Έι, {PLAYER}!\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Πώς πάει;\p"
	.string "Έμαθα ότι ανέβηκες {STR_VAR_3} ορόφους\n"
	.string "στο {STR_VAR_2}!\p"
	.string "Προσπάθησε ακόμα καλύτερα μετά!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattlePyramidText4::
	.string "Έι, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι ανέβηκες {STR_VAR_3} ορόφους\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Πρέπει να προσπαθήσω σκληρά\n"
	.string "για να σε φτάσω!$"

MatchCall_BattlePyramidText5::
	.string "Γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι ανέβηκες {STR_VAR_3} ορόφους\n"
	.string "στο {STR_VAR_2}.\p"
	.string "Πρέπει να στρωθώ κι εγώ στη δουλειά!\n"
	.string "Τα λέμε σύντομα!$"

MatchCall_BattlePyramidText6::
	.string "Έι, {PLAYER};\n"
	.string "Εδώ {STR_VAR_1}. Πώς είσαι;\p"
	.string "Παρεμπιπτόντως, έμαθα ότι πέρασες\n"
	.string "από {STR_VAR_3} ορόφους στο {STR_VAR_2}.\p"
	.string "Πρέπει να δυναμώσω τα POKéMON μου\n"
	.string "προτού ξεφύγεις κι άλλο.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER};\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ήσουν στο {STR_VAR_2}\n"
	.string "κι ανέβηκες {STR_VAR_3} ορόφους;\p"
	.string "Ωραία. Υπήρχαν σπάνια POKéMON\n"
	.string "εκεί πέρα;\p"
	.string "Όχι, ε;\n"
	.string "Εντάξει, γεια.$"

MatchCall_BattlePyramidText8::
	.string "Ω, {PLAYER}, τι κάνεις;\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Ελπίζω να είσαι καλά.\l"
	.string "Ω, αλλά είσαι.\p"
	.string "Έμαθα ότι πέρασες από\n"
	.string "{STR_VAR_3} ορόφους στο {STR_VAR_2}.\p"
	.string "Αυτό είναι πολύ εντυπωσιακό!\n"
	.string "Πρέπει να προπονώ τα POKéMON μου\l"
	.string "όπως εσύ. Τα λέμε πάλι.$"

MatchCall_BattlePyramidText9::
	.string "Ω, {PLAYER}, γεια σου!\n"
	.string "Εδώ {STR_VAR_1}!\p"
	.string "Το έμαθα! Πέρασες από\n"
	.string "{STR_VAR_3} ορόφους στο {STR_VAR_2}!\p"
	.string "Αυτό είναι τόσο τέλειο!\n"
	.string "Πρέπει να προσπαθήσω κι εγώ!$"

MatchCall_BattlePyramidText10::
	.string "Ω, {PLAYER}, γεια σου…\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Ανέβηκες {STR_VAR_3} ορόφους στο\n"
	.string "{STR_VAR_2};\p"
	.string "Αυτό είναι σπουδαίο επίτευγμα.\n"
	.string "Πρέπει να δουλέψω σκληρότερα.$"

MatchCall_BattlePyramidText11::
	.string "Αχ, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\p"
	.string "Έμαθα ότι είσαι ο φόβος και\n"
	.string "ο τρόμος του {STR_VAR_2};\p"
	.string "Ανέβηκες, τι, {STR_VAR_3} ορόφους;\n"
	.string "Αυτό σίγουρα μετράει.\p"
	.string "Αναρωτιέμαι αν θα γίνω ποτέ\n"
	.string "champion;\p"
	.string "…Μάλλον απίθανο;\n"
	.string "Λοιπόν, τα λέμε!$"

MatchCall_BattlePyramidText12::
	.string "Γεια σου, {PLAYER}.\n"
	.string "Είμαι εγώ, {STR_VAR_1}.\l"
	.string "Είσαι καλά;\p"
	.string "Πέρασες {STR_VAR_3} ορόφους σε\n"
	.string "ένα μέρος που λέγεται {STR_VAR_2};\p"
	.string "Αυτή κι αν είναι ιστορία.\n"
	.string "Τα λέμε!$"

MatchCall_BattlePyramidText13::
	.string "Αχ, γεια σου, {PLAYER}!\n"
	.string "Εδώ {STR_VAR_1}!\l"
	.string "Ελπίζω να είσαι καλά.\p"
	.string "Λένε ότι ανέβηκες {STR_VAR_3} ορόφους\n"
	.string "στο {STR_VAR_2};\p"
	.string "Θαυμάζω την ενέργειά σου!\n"
	.string "Αντίο τώρα.$"

MatchCall_BattlePyramidText14::
	.string "Ω, γεια, {PLAYER}.\n"
	.string "Εδώ {STR_VAR_1}.\l"
	.string "Έμαθα για εσένα!\p"
	.string "Δεν ανέβηκες {STR_VAR_3} ορόφους\n"
	.string "στο {STR_VAR_2};\p"
	.string "Αποτελείς έμπνευση!\n"
	.string "Τα λέμε πάλι!$"

MatchCall_Text_Mom1::
	.string "MOM: Ο πατέρας σου κι εσύ…\n"
	.string "Όλοι έχουν μαγευτεί από τα POKéMON.\p"
	.string "Ποια είναι η χάρη των POKéMON;\p"
	.string "Εγώ;\n"
	.string "Λατρεύω τα POKéMON που με βοηθούν\l"
	.string "στις καθημερινές μου δουλειές.$"

MatchCall_Text_Mom2::
	.string "MOM: Γεια σου, {PLAYER}!\n"
	.string "Ο πατέρας σου είναι κλεισμένος\l"
	.string "στο PETALBURG GYM.\p"
	.string "Έρχεται σπίτι πού και πού.\n"
	.string "Αλλά επιστρέφει στο GYM όταν\l"
	.string "έχει φάει ό,τι βρει.\p"
	.string "Φαντάζομαι ότι η ήττα από εσένα\n"
	.string "ήταν μεγάλο πλήγμα για τον εγωισμό του!$"

MatchCall_Text_Mom3::
	.string "MOM: {PLAYER}…\n"
	.string "Μην ανησυχείς για μένα ή το σπίτι.\p"
	.string "Φόρα εκείνα τα RUNNING SHOES\n"
	.string "μέχρι να λιώσουν, παιδί μου!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Ω, γεια σου, {PLAYER}!\p"
	.string "Προπονούμαι σκληρά από τότε\n"
	.string "που συναντηθήκαμε.\p"
	.string "Θα χρειαστώ ακόμα λίγο χρόνο\n"
	.string "προτού ανοίξω ξανά το GYM.\p"
	.string "Αλλά όταν το κάνω, σε παρακαλώ\n"
	.string "έλα για μια ρεβάνς!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: {PLAYER} εσύ είσαι;\n"
	.string "Συγχαρητήρια!\l"
	.string "Μαθαίνω νέα για σένα!\p"
	.string "Όσο για μένα, χρειάζομαι χρόνο\n"
	.string "προτού ανοίξω ξανά το GYM.\p"
	.string "Αλλά όταν το κάνω, σε παρακαλώ\n"
	.string "έλα για μια ρεβάνς!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "Το GYM μου είναι έτοιμο!\p"
	.string "Έλα στη RUSTBORO όποτε\n"
	.string "μπορέσεις!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: Στο RUSTBORO GYM,\n"
	.string "το ότι παλέψαμε, {PLAYER},\l"
	.string "είναι θέμα περηφάνιας.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Έι, {PLAYER}!\p"
	.string "Έμαθα πολλά από τη μάχη που\n"
	.string "δώσαμε μαζί.\p"
	.string "Σκοπεύω να ξανακάνω προπόνηση,\n"
	.string "κι έπειτα να ανοίξω το GYM.\p"
	.string "Θα πάρει λίγο χρόνο προτού\n"
	.string "είμαι έτοιμος να το λειτουργήσω.\p"
	.string "Αλλά όταν το ανοίξω ξανά,\n"
	.string "θέλω να μας προκαλέσεις πάλι.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Έι, {PLAYER}!\n"
	.string "Συγχαρητήρια!\p"
	.string "Τα νέα για τα κατορθώματά σου\n"
	.string "έφτασαν με τον άνεμο!\p"
	.string "Φαίνεται πως πρέπει να δουλέψω\n"
	.string "λίγο ακόμα στην προπόνησή μου.\p"
	.string "Θα πάρει λίγο χρόνο προτού\n"
	.string "είμαι έτοιμος να το λειτουργήσω.\p"
	.string "Αλλά όταν το ανοίξω ξανά,\n"
	.string "θέλω να μας προκαλέσεις πάλι.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Έι, {PLAYER}!\n"
	.string "Το GYM μου είναι έτοιμο!\p"
	.string "Έλα πίσω στη DEWFORD όποτε θες\n"
	.string "για μια νέα πρόκληση!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}, δεν νομίζω να\n"
	.string "βαρεθώ ποτέ να σε αντιμετωπίζω!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Ω, εσύ είσαι!\p"
	.string "Αφού έφυγες, ξαναξεκίνησα την\n"
	.string "προπόνησή μου από το μηδέν.\p"
	.string "Θα έλεγα ότι χρειάζομαι λίγο\n"
	.string "χρόνο ακόμα για να ανοίξω το GYM.\p"
	.string "Θα πρέπει να περιμένεις ως τότε!\n"
	.string "Ουαχαχαχαχα!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Ουαχαχαχαχα!\p"
	.string "Τα κατάφερες πραγματικά, έτσι;\n"
	.string "Μαθαίνω συνεχώς νέα σου!\p"
	.string "Φαίνεται πως πρέπει να\n"
	.string "προπονηθώ κι άλλο ακόμα.\p"
	.string "Θα έλεγα ότι χρειάζομαι λίγο\n"
	.string "χρόνο ακόμα για να ανοίξω το GYM.\p"
	.string "Θα πρέπει να περιμένεις ως τότε!\n"
	.string "Ουαχαχαχαχα!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Ω, εσύ είσαι!\n"
	.string "Το GYM μου είναι έτοιμο!\p"
	.string "Έλα στη MAUVILLE όποτε θες!\n"
	.string "Ουαχαχαχαχα!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Ουαχαχαχα!\p"
	.string "Μια μάχη μαζί σου είναι πάντα\n"
	.string "γεμάτη με ηλεκτρισμένη ενέργεια!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "Όναν παλέψαμε, κατάλαβα ακριβώς\n"
	.string "πόσο ανώριμη ήμουν.\p"
	.string "Αλλά δεν τελείωσα ακόμα!\p"
	.string "Θα ξανακάνω προπόνηση και θα\n"
	.string "ανοίξω ξανά το GYM.\p"
	.string "Όταν έρθει η ώρα, {PLAYER},\n"
	.string "σε παρακαλώ προκάλεσέ μας πάλι.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Γεια, {PLAYER};\n"
	.string "Συγχαρητήρια!\p"
	.string "Τα νέα της επιτυχίας σου έφτασαν\n"
	.string "σαν τη λάβα ηφαιστείου!\p"
	.string "Η προπόνησή μας πηγαίνει πάρα\n"
	.string "καλά εδώ πέρα.\p"
	.string "Όταν το GYM είναι έτοιμο, ένα\n"
	.string "σημάδι θα εμφανιστεί δίπλα στο\l"
	.string "όνομά μου στη λίστα MATCH CALL.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Ω, {PLAYER};\n"
	.string "Το GYM μας είναι έτοιμο!\p"
	.string "Έλα στη LAVARIDGE για ένα μπάνιο\n"
	.string "στις θερμές πηγές και μια μάχη!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "Είμαι σίγουρη πως βελτιώνεσαι\l"
	.string "συνεχώς στην προπόνηση.$"

MatchCall_Text_Winona1::
	.string "WINONA: Γεια σου, {PLAYER}!\p"
	.string "Χάρη στη μάχη μας, κατάφερα να\n"
	.string "καταλάβω τα αδύναμα σημεία μου!\p"
	.string "Όταν ανοίξω ξανά το GYM, δεν θα\n"
	.string "ηττηθώ ξανά έτσι εύκολα!$"

MatchCall_Text_Winona2::
	.string "WINONA: Τα κατάφερες, {PLAYER}!\p"
	.string "Τα νέα για τον νέο CHAMPION\n"
	.string "έφτασαν σε εμάς στη FORTREE!\p"
	.string "Όμως… Την επόμενη φορά που θα\n"
	.string "παλέψουμε, δεν θα λήξει έτσι.$"

MatchCall_Text_Winona3::
	.string "WINONA: {PLAYER} εσύ είσαι;\n"
	.string "Το GYM μας λειτουργεί ξανά!\p"
	.string "Σε περιμένουμε στη FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Αν και έχασα, τα φτερά μου δεν\l"
	.string "πρόκειται να σπάσουν ποτέ.\p"
	.string "Ναι, με τον ίδιο ακριβώς τρόπο που\n"
	.string "δεν έχασες ποτέ το όνειρό σου.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Ω! Είσαι…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Προπονούμαστε ξανά…\n"
	.string "LIZA: Για να ανοίξουμε το GYM!\p"
	.string "TATE: Όταν το GYM μας είναι έτοιμο…\n"
	.string "LIZA: Όταν το GYM μας είναι έτοιμο…\p"
	.string "TATE: Ένα σημάδι θα μπει στο όνομα…\n"
	.string "LIZA: Στη λίστα MATCH CALL.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, συγχαρητήρια!\n"
	.string "LIZA: {PLAYER}, συγχαρητήρια!\p"
	.string "TATE: Οι δυο μας είμαστε…\n"
	.string "LIZA: Ακόμα στην προπόνηση!\p"
	.string "TATE: Χρειαζόμαστε χρόνο, αλλά…\n"
	.string "LIZA: Όταν το GYM μας είναι έτοιμο…\p"
	.string "TATE: Ένα σημάδι θα μπει στο όνομα…\n"
	.string "LIZA: Στη λίστα MATCH CALL.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Το GYM μας είναι έτοιμο!\n"
	.string "LIZA: Το GYM μας είναι έτοιμο!\p"
	.string "TATE: Σε παρακαλώ έλα…\n"
	.string "LIZA: Στη MOSSDEEP όποτε θες!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, η μάχη που δώσαμε…\n"
	.string "LIZA: Ήταν πολύτιμη εμπειρία.\p"
	.string "TATE: Θα ήταν τέλειο αν…\n"
	.string "LIZA: Παλεύαμε όλοι μαζί ξανά!$"

MatchCall_Text_Juan1::
	.string "JUAN: Χμμ…\n"
	.string "{PLAYER}… Έτσι δεν είναι;\p"
	.string "Η μάχη μας--μου έφερε\n"
	.string "αναμνήσεις από τότε που πρωτο-\l"
	.string "συνάντησα τον WALLACE.\p"
	.string "Ίσως είσαι μια ιδιοφυΐα που\n"
	.string "θα ξεπεράσει και τον WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Φούφου… {PLAYER}…\n"
	.string "Πέτυχες επιτέλους τον στόχο σου.\p"
	.string "Το μάτι μου για ταλέντα δεν\n"
	.string "έκανε λάθος…\p"
	.string "Εύχομαι να ξανασυναντηθούμε,\n"
	.string "αφού ανέβηκες στην κορυφή της\l"
	.string "δύναμης και του κύρους.$"

MatchCall_Text_Juan3::
	.string "JUAN: Χοχο… {PLAYER}…\p"
	.string "Το SOOTOPOLIS GYM άνοιξε\n"
	.string "επιτέλους ξανά.\p"
	.string "Αν θες να με δεις, είσαι\n"
	.string "πάντα ευπρόσδεκτος όποτε θες.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}…\p"
	.string "Σαν την πιο φίνα μουσική, οι μάχες\n"
	.string "μας αγγίζουν χορδές έμπνευσης\l"
	.string "στην καρδιά μου…\p"
	.string "Όταν κλείνω τα μάτια, σε βλέπω\n"
	.string "να πετάς μαζί με τη μελωδία…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Έι, {PLAYER}!\p"
	.string "Αν θες να παλέψουμε ξανά,\n"
	.string "έλα πίσω όποτε θέλεις στο\l"
	.string "POKéMON LEAGUE.\p"
	.string "Θα είμαι πάντα εδώ!\n"
	.string "Θα σε περιμένω!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Γεια, {PLAYER}!\p"
	.string "Τι θα έλεγες να ξαναέρθεις\n"
	.string "εδώ πέρα κάποια στιγμή;\p"
	.string "Θέλω να δω πόσο πιο δυνατός\n"
	.string "έγινε ο δεσμός σου με τα\l"
	.string "POKéMON σου.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Γεια σου, {PLAYER}.\p"
	.string "Ελπίζω να μην επαναπαύτηκες\n"
	.string "με τη δύναμή σου;\p"
	.string "Αν νιώθεις την ανάγκη να ηρεμήσεις\n"
	.string "τα θερμά σου συναισθήματα,\l"
	.string "έλα στο POKéMON LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: Αυτή η φωνή… {PLAYER};\n"
	.string "Ακούγεσαι καλά…\p"
	.string "Έμαθα ότι υπάρχει τώρα μια\n"
	.string "εγκατάσταση που λέγεται BATTLE\l"
	.string "FRONTIER για δοκιμή ικανοτήτων.\p"
	.string "Όμως, αν θες αληθινές μάχες,\n"
	.string "δεν υπάρχει υποκατάστατο\l"
	.string "για το POKéMON LEAGUE!\p"
	.string "Δεν συμφωνείς, {PLAYER};$"

MatchCall_Text_Wallace::
	.string "WALLACE: Γεια σου, {PLAYER}.\n"
	.string "Συνάντησες τον STEVEN;\p"
	.string "Είναι…\n"
	.string "Πραγματικά απίστευτα ικανός.\p"
	.string "Όμως, είναι περίεργη ψυχή που\n"
	.string "σπάνια μάχεται.\p"
	.string "Αντ' αυτού, προτιμά να ψάχνει\n"
	.string "για σπάνιες πέτρες.\p"
	.string "Σίγουρα θα σκάβει σε κάποια σπηλιά\n"
	.string "ή σε κανένα κακοτράχαλο βουνό.\p"
	.string "Αλλά τι είναι μια σπάνια πέτρα;\n"
	.string "Το μόνο που σκέφτομαι είναι METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Μπιπ!\p"
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Ήμουν στην PACIFIDLOG πριν από\n"
	.string "λίγη ώρα.\p"
	.string "Είδα ένα γιγάντιο πράσινο POKéMON\n"
	.string "να πετάει ψηλά στον ουρανό.\p"
	.string "Εγώ…\n"
	.string "Δεν έχω ξαναδεί κάτι τέτοιο.\p"
	.string "Αναρωτιέμαι τι ήταν.\n"
	.string "Μήπως είναι μια σπουδαία ανακάλυψη;\p"
	.string "… … … … … …\n"
	.string "… … … … … Κλικ!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Μπιπ!\p"
	.string "BRENDAN: Έι, {PLAYER}!\n"
	.string "Ήμουν στην PACIFIDLOG μόλις τώρα.\p"
	.string "Είδα ένα τεράστιο πράσινο POKéMON\n"
	.string "να πετάει στον ουρανό.\p"
	.string "Δεν έχω ξαναδεί ποτέ κάτι τόσο\n"
	.string "εντυπωσιακό.\p"
	.string "Μακάρι να το έβλεπες κι εσύ,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Κλικ!$"

MatchCall_Text_May1::
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Ο MR. BRINEY αποσύρθηκε από ναύτης,\n"
	.string "αλλά τον βλέπω ακόμα στη θάλασσα\l"
	.string "με την αγαπημένη του PEEKO.\p"
	.string "Πρέπει να λατρεύει ακόμα τη θάλασσα.$"

MatchCall_Text_May2::
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Ξέρεις πώς μικρές πόλεις όπως η\n"
	.string "PETALBURG και η DEWFORD έχουν GYMS;\p"
	.string "Για κάποιο λόγο, το μεγάλο λιμάνι\n"
	.string "της SLATEPORT δεν έχει GYM.\p"
	.string "Όταν χτίσουν επιτέλους ένα GYM εκεί,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3::
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Θυμάσαι έναν άνθρωπο που τον\n"
	.string "έλεγαν CUTTER στη RUSTBORO;\l"
	.string "Είχε ένα σπίτι εκεί, θυμάσαι;\p"
	.string "Λοιπόν, έμαθα ότι ο μικρός του\n"
	.string "αδερφός μένει στη MAUVILLE.\p"
	.string "Μαντεύεις το όνομά του;\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Ο ROCK SMASH GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER};\p"
	.string "Το RUSTURF TUNNEL…\n"
	.string "Το ονόμασαν έτσι επειδή\l"
	.string "ενώνει τη RUSTBORO με τη VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}, πώς είσαι;\p"
	.string "Είμαι έξω στο ROUTE 111 τώρα.\p"
	.string "Θα ξεκουραστώ στο σπίτι μιας\n"
	.string "ηλικιωμένης κυρίας.\p"
	.string "Μένει ακριβώς βόρεια από\n"
	.string "την έρημο.$"

MatchCall_Text_May6::
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Ήξερες για το MIRAGE TOWER\n"
	.string "στην έρημο;\p"
	.string "Λένε πως, σαν οφθαλμαπάτη,\n"
	.string "εμφανίζεται και χάνεται μυστηριωδώς.\p"
	.string "Μακάρι να μπορούσα να το δω.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}, γιούχου!\n"
	.string "Είμαι στο ROUTE 119 τώρα.\p"
	.string "Έχει ένα μεγάλο ποτάμι εδώ,\n"
	.string "και βρέχει συχνά.\p"
	.string "Έγινα μούσκεμα!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}, γεια.\p"
	.string "Το MT. PYRE είναι μνημείο για τα\n"
	.string "POKéMON που έχουν πεθάνει.\p"
	.string "Ίσως γι' αυτό, είναι γεμάτο\n"
	.string "με πολλά POKéMON τύπου GHOST!$"

MatchCall_Text_May9::
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Σκεφτόμουν να πάω στις θερμές\n"
	.string "πηγές στη LAVARIDGE.\p"
	.string "Αλλά στον δρόμο, γύρω από το\n"
	.string "JAGGED PASS, έπεσα πάνω σε κάποιους\l"
	.string "περίεργους τύπους. Το κλίμα ήταν άγριο!$"

MatchCall_Text_May10::
	.string "MAY: Γεια σου, {PLAYER}!\n"
	.string "Είδες τα νέα;\p"
	.string "Λένε ότι ο CAPT. STERN ανακάλυψε\n"
	.string "το SEAFLOOR CAVERN κατά την\l"
	.string "υποβρύχια αποστολή του.$"

MatchCall_Text_May11::
	.string "MAY: Γεια σου, {PLAYER}!\n"
	.string "Δεν νομίζεις ότι είναι τέλειο;\p"
	.string "Ακόμα κι αν δεν έχεις βάρκα,\n"
	.string "μπορείς να περάσεις τη θάλασσα\l"
	.string "με μια κίνηση POKéMON.\p"
	.string "Ήξερες ότι υπάρχει κι άλλο;\p"
	.string "Υπάρχει κίνηση POKéMON που σε\n"
	.string "στέλνει στον βυθό της θάλασσας.$"

MatchCall_Text_May12::
	.string "MAY: Γεια σου, {PLAYER}!\n"
	.string "Ελπίζω να είσαι καλά!\p"
	.string "Ήσουν ποτέ στη θάλασσα και\n"
	.string "βρήκες τον δρόμο σου κλειστό;\p"
	.string "Δοκίμασε να βουτήξεις βαθιά και\n"
	.string "να ακολουθήσεις τα υποθαλάσσια ρήγματα.\p"
	.string "Όταν φτάσεις στην άλλη πλευρά,\n"
	.string "ανέβα στην επιφάνεια. Εύκολο!$"

MatchCall_Text_May13::
	.string "MAY: Γεια σου, {PLAYER}!\p"
	.string "Πώς πάει;\n"
	.string "Γεμίζεις το POKéDEX σου;\p"
	.string "Έμαθα μια φήμη ότι υπάρχουν\n"
	.string "υπέρ-αρχαία POKéMON εκεί έξω.\l"
	.string "And there are three of them!\p"
	.string "Θα ήθελα πολύ να δω έστω ένα…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}!\n"
	.string "Έμαθα τις φήμες!\p"
	.string "Νίκησες τον LEADER του\n"
	.string "SOOTOPOLIS GYM;\p"
	.string "Αυτό σημαίνει ότι δεν σου μένει\n"
	.string "πολύς δρόμος ακόμα, έτσι;$"

MatchCall_Text_May15::
	.string "MAY: Δεν έχει μείνει ούτε ένας\n"
	.string "TRAINER στο HOENN που να μην ξέρει\l"
	.string "ποιος είσαι, {PLAYER}!\p"
	.string "Όταν λέω στον κόσμο ότι είμαστε\n"
	.string "φίλοι, {PLAYER}, όλοι\l"
	.string "ξαφνιάζονται!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Έι, {PLAYER}!\p"
	.string "Ο MR. BRINEY αποσύρθηκε από ναύτης,\n"
	.string "αλλά τον βλέπω ακόμα στη θάλασσα\l"
	.string "με την αγαπημένη του PEEKO.\p"
	.string "Φαντάζομαι πως λατρεύει ακόμα\n"
	.string "τη θάλασσα.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Έι, {PLAYER}!\p"
	.string "Δεν καταλαβαίνω γιατί μικρές πόλεις\n"
	.string "όπως η PETALBURG και η DEWFORD\l"
	.string "έχουν GYMS.\p"
	.string "Δηλαδή, γιατί το μεγάλο λιμάνι\n"
	.string "της SLATEPORT δεν έχει GYM.\p"
	.string "Όταν χτίσουν επιτέλους ένα GYM εκεί,\n"
	.string "πρέπει να κάνω αίτηση για LEADER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Έι, {PLAYER}!\p"
	.string "Θυμάσαι έναν τύπο που τον\n"
	.string "έλεγαν CUTTER στη RUSTBORO;\l"
	.string "Είχε ένα σπίτι εκεί, σωστά;\p"
	.string "Λοιπόν, ο μικρός του αδερφός\n"
	.string "μένει στη MAUVILLE.\p"
	.string "Μαντεύεις το όνομά του;\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Ο ROCK SMASH GUY!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Αυτή η φωνή… {PLAYER};\p"
	.string "Ονόμασαν το RUSTURF TUNNEL έτσι\n"
	.string "επειδή ενώνει τη RUSTBORO με τη\l"
	.string "VERDANTURF.\p"
	.string "Το ήξερες αυτό;$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, τι γίνεται;\p"
	.string "Έι, είμαι έξω στο ROUTE 111 τώρα.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Έι, {PLAYER}!\p"
	.string "Ήξερες για το MIRAGE TOWER\n"
	.string "στην έρημο;\p"
	.string "Λένε πως, σαν οφθαλμαπάτη,\n"
	.string "εμφανίζεται μόνο πού και πού.\p"
	.string "Θα ήθελα πολύ να το δω αυτό!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Ποιος είναι; Ω, {PLAYER};\n"
	.string "Μάντεψε! Είμαι στο ROUTE 119 τώρα.\p"
	.string "Έχει ένα μεγάλο ποτάμι εδώ,\n"
	.string "και βρέχει συνέχεια.\p"
	.string "Έγινα μούσκεμα ως το κόκαλο!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "Το MT. PYRE είναι μνημείο για τα\n"
	.string "POKéMON που έχουν πεθάνει.\p"
	.string "Μάλλον γι' αυτό είναι γεμάτο\n"
	.string "με πολλά POKéMON τύπου GHOST!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Έι, {PLAYER}.\p"
	.string "Πήγαινα πίσω στις θερμές\n"
	.string "πηγές στη LAVARIDGE.\p"
	.string "Αλλά γύρω από το JAGGED PASS,\n"
	.string "έπεσα πάνω σε περίεργους τύπους.\p"
	.string "Αυτοί οι άθλιοι…\n"
	.string "Νομίζω πως ήταν της TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Γεια, {PLAYER}!\n"
	.string "Έμαθες τα νέα;\p"
	.string "Λένε ότι ο CAPT. STERN ανακάλυψε\n"
	.string "το SEAFLOOR CAVERN κατά την\l"
	.string "υποβρύχια αποστολή του.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Έι, {PLAYER}!\n"
	.string "Δεν νομίζεις ότι είναι φοβερό;\p"
	.string "Ακόμα κι αν δεν έχεις βάρκα,\n"
	.string "μπορείς να περάσεις τη θάλασσα\l"
	.string "με μια κίνηση POKéMON.\p"
	.string "Και υπάρχει μια κίνηση που σε\n"
	.string "αφήνει να ταξιδέψεις στον βυθό.\p"
	.string "Φίλε, τα POKéMON κάνουν τα πάντα!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Γεια σου, {PLAYER}!\n"
	.string "Πώς τα πας;\p"
	.string "Βρήκες ποτέ τον δρόμο σου κλειστό\n"
	.string "ενώ ήσουν στη θάλασσα;\p"
	.string "Δοκίμασε να βουτήξεις βαθιά και\n"
	.string "να ακολουθήσεις τα ρήγματα στον βυθό.\p"
	.string "Όταν φτάσεις στην άλλη πλευρά,\n"
	.string "βγες στην επιφάνεια. Απλό!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Έι, {PLAYER}!\p"
	.string "Πώς πάει; Γεμίζεις το POKéDEX\n"
	.string "σου με επιτυχία;\p"
	.string "Έμαθα μια φήμη ότι υπάρχουν\n"
	.string "υπέρ-αρχαία POKéMON εκεί έξω.\l"
	.string "Και όχι μόνο ένα--τρία!\p"
	.string "Θα ήθελα πολύ να πιάσω έστω ένα…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "Έμαθα τις φήμες!\p"
	.string "Νίκησες τον LEADER του\n"
	.string "SOOTOPOLIS GYM; Τέλεια!\p"
	.string "Πλησιάζεις πάρα πολύ τώρα!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: Δεν υπάρχει TRAINER σε\n"
	.string "όλο το HOENN που να μην ξέρει\l"
	.string "ποιος είσαι, {PLAYER}!\p"
	.string "Όταν λέω στον κόσμο ότι είμαστε\n"
	.string "φίλοι, {PLAYER}, όλοι\l"
	.string "ζηλεύουν πολύ!$"

MatchCall_Text_Wally1::
	.string "WALLY: Ω, {PLAYER}!\p"
	.string "Έγινα πιο υγιής και\n"
	.string "έχω καλύτερη φυσική κατάσταση.\p"
	.string "Ελπίζω να γίνω TRAINER σαν\n"
	.string "εσένα σύντομα, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, γεια σου!\p"
	.string "Αφότου άνοιξε το RUSTURF TUNNEL,\n"
	.string "η WANDA είναι πολύ χαρούμενη!$"

MatchCall_Text_Wally3::
	.string "WALLY: Ω, {PLAYER}!\p"
	.string "Εγώ… έφυγα από τον θείο μου στη\n"
	.string "VERDANTURF χωρίς να πω τίποτα.\p"
	.string "Αναρωτιέμαι αν είναι έξαλλος μαζί μου…\p"
	.string "{PLAYER}, με καταλαβαίνεις,\n"
	.string "έτσι δεν είναι;$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER};\n"
	.string "Είμαι εγώ, ο WALLY!\p"
	.string "Ο κόσμος των TRAINERS είναι τέλειος!\p"
	.string "Όταν έχω τα POKéMON μαζί μου,\n"
	.string "κάθε είδους άνθρωποι με χαιρετούν!\p"
	.string "Είναι λες και όλοι συνδέονται\n"
	.string "μέσω των POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}; Είναι φοβερό!\n"
	.string "Εκείνο το RALTS που πιάσαμε μαζί;\l"
	.string "Εξελίχθηκε, {PLAYER}!\p"
	.string "Ίσως έχω ταλέντο…\p"
	.string "Ω, αλλά δεν πρέπει να παίρνουν τα\n"
	.string "μυαλά μου αέρα!\p"
	.string "Στο κάτω-κάτω, το POKéMON είναι\n"
	.string "αυτό που αξίζει τον έπαινο!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Ο WALLY φαίνεται να είναι εκτός\n"
	.string "περιοχής κάλυψης του POKéNAV…$"

MatchCall_Text_Wally7::
	.string "WALLY: Ω, {PLAYER}!\p"
	.string "Προτού σε γνωρίσω, σχεδόν ποτέ\n"
	.string "δεν έβγαινα από το σπίτι…\p"
	.string "Αλλά τώρα, είμαι σε περιπέτεια με\n"
	.string "το δικό μου POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Σε ευχαριστώ…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Γεια σου, {PLAYER}!\p"
	.string "Ξέρεις πώς τα POKéMON μπορούν\n"
	.string "να βρεθούν παντού;\p"
	.string "Όπως στα βουνά, στη θάλασσα,\n"
	.string "στο ψηλό γρασίδι παντού;\p"
	.string "Όπως ακριβώς τα POKéMON, βρίσκεις\n"
	.string "TRAINERS παντού, επίσης.\p"
	.string "Γι' αυτό πρέπει να βιάζομαι\n"
	.string "κι εγώ παντού. Πολύ τρέξιμο!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Είμαι στο ROUTE 119 τώρα.\n"
	.string "Είναι γεμάτο με TRAINERS!\p"
	.string "Είναι επίσης πνιγμένο στο ψηλό\n"
	.string "γρασίδι παντού, έτσι φαίνεται.\p"
	.string "Το να περπατάω με σορτσάκι εδώ\n"
	.string "με κάνει να γαργαλιέμαι!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Γεια, γεια, {PLAYER}!\p"
	.string "Είχες την ευκαιρία να ανέβεις\n"
	.string "στο MT. PYRE;\p"
	.string "Το μέρος είναι ένα μνημείο για\n"
	.string "τα POKéMON που έχουν πεθάνει.\p"
	.string "Κάθε TRAINER πρέπει να ανέβει\n"
	.string "στην κορυφή του έστω μια φορά.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Γεια, {PLAYER}!\p"
	.string "Ακούω ότι αυτές οι περίεργες\n"
	.string "συμμορίες προκαλούν προβλήματα.\p"
	.string "TEAM MAGMA και TEAM AQUA,\n"
	.string "νομίζω πως τις έλεγαν.\p"
	.string "Θα περίμενα να υπάρχουν ικανοί\n"
	.string "TRAINERS ανάμεσά τους.\p"
	.string "…Αλλά αν είναι απλοί αλήτες…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Ω, γεια, {PLAYER}.\p"
	.string "Άραγε να υπάρχουν δυνατοί\n"
	.string "TRAINERS στον βυθό της θάλασσας;\p"
	.string "Δεν μπορώ να πάω να το ελέγξω.\n"
	.string "Πρώτον, δεν ξέρω κολύμπι.\l"
	.string "Και δεύτερον, δεν εκτρέφω POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Γεια, γεια, {PLAYER}!\p"
	.string "Ξέρεις ότι προκαλείς το POKéMON\n"
	.string "LEAGUE όταν μαζέψεις όλα τα GYM\l"
	.string "BADGES;\p"
	.string "Με το ταλέντο σου, το να γίνεις\n"
	.string "CHAMPION δεν είναι άπιαστο όνειρο.\p"
	.string "Αλλά το ήξερες;\n"
	.string "Υπάρχει ένα μέρος ακόμα καλύτερο.\p"
	.string "Αλλά αυτά είναι όλα όσα θα πω\n"
	.string "προς το παρόν.\p"
	.string "Είναι κάτι που μπορείς να\n"
	.string "περιμένεις με ανυπομονησία.\p"
	.string "Όταν νικήσεις στο POKéMON\n"
	.string "LEAGUE και μπεις στο HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Ο SCOTT φαίνεται να είναι εκτός\n"
	.string "περιοχής κάλυψης του POKéNAV…$"

MatchCall_Text_Norman1::
	.string "DAD: Στη RUSTBORO, υπάρχει ένας\n"
	.string "άνθρωπος με το περίεργο όνομα\l"
	.string "CUTTER.\p"
	.string "Αν είσαι στην περιοχή, πρέπει\n"
	.string "να του κάνεις μια επίσκεψη.$"

MatchCall_Text_Norman2::
	.string "DAD: Χμ… Σιγά-σιγά, αλλά και\n"
	.string "πολύ σταθερά, δυναμώνεις\l"
	.string "συνεχώς, {PLAYER}.\p"
	.string "Όσο περισσότερο δυναμώνεις, τόσο πιο\n"
	.string "μακριά και ψηλά πετάς από τη\n"
	.string "μητέρα σου κι εμένα…\p"
	.string "Αυτό το συναίσθημα είναι δύσκολο\n"
	.string "να εξηγηθεί.$"

MatchCall_Text_Norman3::
	.string "DAD: Βλέπω…\n"
	.string "Μάζεψες τέσσερα GYM BADGES…\p"
	.string "Δεν μπορούμε να το αποφύγουμε.\n"
	.string "Θα παλέψουμε όπως υποσχέθηκα.\p"
	.string "Έλα όποτε θες.\n"
	.string "Θα σε περιμένουμε όλοι!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! Καλό θα ήταν να\n"
	.string "επισκέπτεσαι τη μητέρα σου συχνά.\p"
	.string "Εγώ θα παραμείνω εδώ και θα\n"
	.string "διπλασιάσω την προπόνησή μου.\p"
	.string "Ο δρόμος της μάχης είναι βαθύς\n"
	.string "και ασυγχώρητος!$"

MatchCall_Text_Norman5::
	.string "DAD: Ω, γεια σου, {PLAYER}!\p"
	.string "Τι είναι αυτό; MAGMA EMBLEM?\n"
	.string "Δεν ξέρω τι ακριβώς είναι.\p"
	.string "Αλλά με τέτοιο όνομα, ίσως\n"
	.string "συνδέεται κάπως με ηφαίστειο!$"

MatchCall_Text_Norman6::
	.string "DAD: Ίαχ! Αάχ! Ντουάχ!\p"
	.string "…Ω; {PLAYER}!\p"
	.string "Με πέτυχες ακριβώς στη μέση μιας\n"
	.string "προπόνησης POKéMON!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Ποιος να το φανταζόταν ότι θα\n"
	.string "γινόσουν CHAMPION στο POKéMON LEAGUE…\p"
	.string "Εντάξει!\n"
	.string "Δεν θα μείνω πίσω!$"

MatchCall_Text_Norman8::
	.string "DAD: Χμ; {PLAYER};\n"
	.string "Τι καλή συγκυρία!\p"
	.string "Αυτή τη φορά, θα σε προκαλέσω\n"
	.string "εγώ σε μάχη.\p"
	.string "Περιμένω στο PETALBURG GYM.\n"
	.string "Δέξου την πρόκλησή μου όποτε θες!$"

MatchCall_Text_Norman9::
	.string "DAD: …Με εκπλήσσεις, {PLAYER}.\n"
	.string "Πόσο ψηλότερα θα πετάξεις ακόμα;$"

MatchCall_Text_Steven1::
	.string "STEVEN: Γεια σου, {PLAYER}!\p"
	.string "Έχεις πάει ήδη στη MAUVILLE;\p"
	.string "Πρέπει να πας στο BIKE SHOP\n"
	.string "και να πάρεις ένα MACH BIKE.\p"
	.string "Μετά, δοκίμασε να εξερευνήσεις\n"
	.string "το GRANITE CAVE εξονυχιστικά.\p"
	.string "Ίσως κάνεις μια νέα ανακάλυψη\n"
	.string "εκεί.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Γεια σου, {PLAYER}!\p"
	.string "Έχω συναντήσει πολλούς\n"
	.string "διαφορετικούς TRAINERS ως τώρα.\p"
	.string "Αλλά εσύ ξεχωρίζεις.\n"
	.string "Δεν μοιάζεις με κανέναν άλλον.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Γεια σου, {PLAYER}!\p"
	.string "Όταν είσαι σε περιπέτεια με τα\n"
	.string "POKéMON σου, τι σκέφτεσαι;\p"
	.string "Τα θεωρείς ισχυρούς συνεργάτες;\p"
	.string "Τα βλέπεις σαν διασκεδαστικούς\n"
	.string "συντρόφους;\p"
	.string "Ανάλογα με το πώς σκέφτεσαι, η\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Παρακαλώ;\n"
	.string "{PLAYER};\p"
	.string "Έχω μπλέξει σε ένα πρόβλημα\n"
	.string "στο SPACE CENTER.\p"
	.string "Λυπάμαι, αλλά δεν μπορώ να μιλήσω.\n"
	.string "Γεια!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Ω!\n"
	.string "{PLAYER}!\p"
	.string "Δεν χρειάζεται να μιλάμε.\n"
	.string "Η ώρα για λόγια πέρασε.\p"
	.string "Πρέπει να πιστέψεις στον εαυτό σου\n"
	.string "και να κάνεις το σωστό.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "Ο STEVEN φαίνεται να μην απαντάει\n"
	.string "στην κλήση…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}… Συγχαρητήρια\n"
	.string "για την είσοδο στο HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Ελπίζω να ξανασυναντηθούμε\n"
	.string "κάπου!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Ω, {PLAYER}!\n"
	.string "Έχω ήδη ακούσει νέα για σένα!\p"
	.string "Φαίνεται πως το POKéNAV σου\n"
	.string "αναβαθμίστηκε με MATCH CALL.\p"
	.string "Λοιπόν, πρέπει να εγγραφώ κι εγώ!\p"
	.string "Έτσι, θα μπορώ να εξετάζω το\n"
	.string "POKéDEX σου ακόμα κι όταν είσαι\l"
	.string "έξω στον δρόμο.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Έγινε εγγραφή του PROF. BIRCH\n"
	.string "στο POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: Όταν έχεις POKéDEX\n"
	.string "και POKéNAV, η μελέτη των POKéMON\l"
	.string "γίνεται πιο διασκεδαστική, ε;$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Ω; {PLAYER}!\p"
	.string "Αφού με κάλεσες, το POKéNAV\n"
	.string "πρέπει να δουλεύει σωστά!\p"
	.string "Και άλλοι θα εγγραφούν,\n"
	.string "οπότε δοκίμασε να τους καλέσεις!\p"
	.string "Ωραία! Ωραία!\n"
	.string "Δείχνεις να χαίρεσαι πολύ!\p"
	.string "Χμ…\n"
	.string "Πώς το ξέρω αυτό;\p"
	.string "Επειδή σε κοιτάζω από το\n"
	.string "παράθυρο του γραφείου μου!\p"
	.string "Ουαχαχαχα!\n"
	.string "Τα λέμε!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Ω; {PLAYER}!\p"
	.string "Τι τρέχει; Ξέχασες εκείνο\n"
	.string "το μικρό μου θεληματάκι;\p"
	.string "Πρέπει να παραδώσεις το γράμμα μου\n"
	.string "στον STEVEN στη DEWFORD.\p"
	.string "Μετά, παράδωσε το δέμα μας στον\n"
	.string "CAPT. STERN στη SLATEPORT.\p"
	.string "Το θυμάσαι, έτσι δεν είναι;\p"
	.string "Τώρα, ως απασχολημένος PRESIDENT,\n"
	.string "πρέπει να φύγω! Αντίο!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Ω! {PLAYER}!\p"
	.string "Α, συνάντησες τον STEVEN!\n"
	.string "Πρέπει να σε ανταμείψω, λοιπόν!\p"
	.string "Όταν επισκεφτείς τη RUSTBORO,\n"
	.string "έλα να με βρεις στο γραφείο μου.\p"
	.string "Θα σε περιμένω!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Ω! {PLAYER}!\p"
	.string "Ήξερες ότι η DEVON έσκαβε\n"
	.string "το RUSTURF TUNNEL;\p"
	.string "Αλλά σταματήσαμε τις εργασίες για\n"
	.string "να προστατέψουμε τα POKéMON εκεί.\p"
	.string "Είναι αυτονόητο, πραγματικά.\p"
	.string "Είναι πιο σημαντικό να ζουν τα\n"
	.string "POKéMON ήσυχα παρά η δική μας\l"
	.string "ευκολία.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Γεια, γεια, {PLAYER}!\p"
	.string "Έμαθα από κάποιον στην PETALBURG\n"
	.string "ότι είσαι το παιδί του NORMAN!\p"
	.string "Δεν απορώ που είσαι τόσο ικανό\n"
	.string "άτομο!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: Τι πράγμα;\p"
	.string "Πάλεψες με τον ίδιο σου τον πατέρα\n"
	.string "και τον νίκησες;\p"
	.string "Αυτό είναι εκπληκτικό!\p"
	.string "Δεν είχα ιδέα ότι έκανα φιλία\n"
	.string "με κάποιον τόσο ξεχωριστό! Ουαχάχα!$"

MatchCall_Text_MrStone7::
	.string "Γεια σας!\n"
	.string "Εδώ DEVON CORPORATI…\l"
	.string "Ω, γεια σου, {PLAYER}!\p"
	.string "Ο PRESIDENT μας ήταν εδώ πριν από\n"
	.string "λίγο, αλλά βγήκε έξω.\p"
	.string "Ο PRESIDENT μας είναι απασχολημένος,\n"
	.string "αλλά κι εσύ τρέχεις πολύ, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Ε; …Τι είναι αυτό;\p"
	.string "GROU… Ναι; …DON;\p"
	.string "Κόβεται η γραμμή…\n"
	.string "…δεν ακούω…\p"
	.string "ΜΠΖΖΖΖ…$"

MatchCall_Text_MrStone9::
	.string "…Ε; …Τι είναι αυτό;\p"
	.string "Seaflo… Ναι; …Caver…;\p"
	.string "Κόβεται η γραμμή…\n"
	.string "…δεν ακούω…\p"
	.string "ΜΠΖΖΖΖ…$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}! Εγώ είμαι!\p"
	.string "Φαίνεται πως ενεπλάκης σε κάθε\n"
	.string "λογής πράγματα, αλλά εγώ, όντας\l"
	.string "απασχολημένος, δεν έχω ιδέα!\p"
	.string "Όπως και να 'χει, σε προτρέπω\n"
	.string "να ακολουθήσεις τον δρόμο που\l"
	.string "πιστεύεις.\p"
	.string "Θα είμαι πάντα στο πλευρό σου!\n"
	.string "Να προσέχεις!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Μήπως είναι {PLAYER} εσύ;\p"
	.string "Η φωνή σου έχει τόση σιγουριά,\n"
	.string "που δεν σε γνώρισα αμέσως!\p"
	.string "Χμ! Πρέπει να έρθεις να μας\n"
	.string "επισκεφτείς στη DEVON κάποια στιγμή!$"
