@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " τόσο όμορφο!$"

GiddyText_SoDarling::
	.string " τόσο αξιαγάπητο!$"

GiddyText_SoRelaxed::
	.string " τόσο χαλαρό!$"

GiddyText_SoSunny::
	.string " τόσο ηλιόλουστο!$"

GiddyText_SoDesirable::
	.string " τόσο επιθυμητό!$"

GiddyText_SoExciting::
	.string " τόσο συναρπαστικό!$"

GiddyText_SoAmusing::
	.string " τόσο διασκεδαστικό!$"

GiddyText_SoMagical::
	.string " τόσο μαγικό!$"

GiddyText_Is::
	.string " είναι$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Δεν συμφωνείς;$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Θέλω τόσο πολύ να πάω διακοπές.\n"
	.string "Μήπως ξέρεις κανένα καλό μέρος;$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Αγόρασα κηρομπογιές με 120 χρώματα!\n"
	.string "Δεν νομίζεις ότι είναι ωραίο;$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Δεν θα ήταν ωραίο να πετούσαμε\n"
	.string "μακριά πάνω σε ένα σύννεφο φυσαλίδων;$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Όταν γράφεις σε μια αμμουδιά,\n"
	.string "σβήνονται. Αυτό με στεναχωρεί.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Πώς να είναι ο βυθός της θάλασσας;\n"
	.string "Μια φορά μόνο θα ήθελα να πάω!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Όταν βλέπεις το ηλιοβασίλεμα, σε\n"
	.string "κάνει να θέλεις να πας σπίτι;$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Το να ξαπλώνεις στο πράσινο γρασίδι…\n"
	.string "Ω, είναι τόσο, τόσο ωραία!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Οι SECRET BASES είναι υπέροχες!\n"
	.string "Δεν νιώθεις τον ενθουσιασμό;$"
