MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Αυτή η κίνηση μπορεί να μαθευτεί\n"
	.string "μόνο μία φορά. Είναι εντάξει;$"

MoveTutor_Text_SwaggerTeach:
	.string "Χε! Το POKéMON μου κυριαρχεί!\n"
	.string "Είναι πιο κουλ από κάθε POKéMON!\p"
	.string "Μιλούσα με μεγάλη υπεροψία και\n"
	.string "καμάρι, όταν ο CHAIRMAN\l"
	.string "μου έκανε αυστηρή παρατήρηση.\p"
	.string "Αυτό μου έκοψε τελείως τη φόρα.\p"
	.string "Αν θες, μπορώ να διδάξω την κίνηση\n"
	.string "SWAGGER σε ένα POKéMON σου.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Τι, όχι; Δεν μπορείς να μπεις\n"
	.string "στο πνεύμα;$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Ωραία, ποιο POKéMON θέλει να\n"
	.string "μάθει να κάνει SWAGGER;$"

MoveTutor_Text_SwaggerTaught:
	.string "Από εδώ και πέρα θα επαινώ το\n"
	.string "POKéMON μου χωρίς καμάρι.$"

MoveTutor_Text_RolloutTeach:
	.string "Ήξερες ότι μπορείς να πας από\n"
	.string "εδώ πολύ μακριά προς τα εκεί\l"
	.string "χωρίς να αλλάξεις κατεύθυνση;\p"
	.string "Ίσως να μπορώ ακόμη και να\n"
	.string "κυλήσω προς τα εκεί.\p"
	.string "Πιστεύεις ότι το POKéMON σου\n"
	.string "θα ήθελε να κυλήσει επίσης;\p"
	.string "Μπορώ να του μάθω το ROLLOUT\n"
	.string "αν θέλεις.$"

MoveTutor_Text_RolloutDeclined:
	.string "Δεν χρειάζεται να ντρέπεσαι.\n"
	.string "Ας κυλήσουμε!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Εχεχέ, σίγουρα! Θα ήταν τέλειο\n"
	.string "αν το POKéMON μου έμοιαζε.$"

MoveTutor_Text_RolloutTaught:
	.string "Το να κυλάω στο γρασίδι με κάνει\n"
	.string "χαρούμενο. Έλα, ας κυλήσουμε!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Υπάρχει μια κίνηση που δυναμώνει\n"
	.string "όταν τη χρησιμοποιείς συνεχόμενα.\p"
	.string "Είναι κίνηση τύπου BUG και είναι\n"
	.string "απίστευτα κουλ.\p"
	.string "Λέγεται FURY CUTTER.\n"
	.string "Θες να τη μάθω σε ένα POKéMON;$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Δεν είμαστε στο ίδιο μήκος κύματος.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Γιούπι!\n"
	.string "Δείξε μου σε ποιο POKéMON να τη μάθω.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Είναι συναρπαστικό να βλέπεις αν\n"
	.string "η κίνηση πετυχαίνει συνεχόμενα!$"

MoveTutor_MimicTeach:
	.string "Αχ, νεαρό μου παιδί!\p"
	.string "Κι εγώ νέος είμαι, αλλά μιμούμαι\n"
	.string "το στυλ και την ομιλία των ηλικιωμένων\l"
	.string "αυτής της πόλης.\p"
	.string "Τι λες, νεαρό μου παιδί;\n"
	.string "Θα δεχόσουν αν σου πρότεινα να\l"
	.string "διδάξω την κίνηση MIMIC;$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach MIMIC\n"
	.string "στο POKéMON σου!$"

MoveTutor_Text_MimicWhichMon:
	.string "Φουοφουό! Έτσι θα γίνει λοιπόν!\n"
	.string "Δείξε μου το POKéMON που\l"
	.string "θέλεις να του τη μάθω.$"

MoveTutor_Text_MimicTaught:
	.string "Το MIMIC είναι μια βαθιά κίνηση.\p"
	.string "Θα μπορούσες να την εκτελέσεις\n"
	.string "τέλεια όσο κι εγώ…;$"

MoveTutor_Text_MetronomeTeach:
	.string "Θέλω κάθε λογής πράγματα!\n"
	.string "Αλλά ξόδεψα όλο το χαρτζιλίκι μου…\p"
	.string "Δεν θα ήταν τέλειο αν υπήρχε ένα\n"
	.string "ξόρκι που θα έφερνε χρήματα όταν\l"
	.string "κούναγες το δάχτυλό σου;\p"
	.string "Αν θες, μπορώ να μάθω στο POKéMON\n"
	.string "σου την κίνηση METRONOME.\p"
	.string "Χρήματα δεν θα εμφανιστούν, αλλά\n"
	.string "το POKéMON σου θα κουνάει\l"
	.string "το δάχτυλο. Ναι;$"

MoveTutor_Text_MetronomeDeclined:
	.string "Εντάξει. Θα είμαι εδώ αν αλλάξεις\n"
	.string "γνώμη.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Ωραία! Θα τη διδάξω!\n"
	.string "Σε ποιο POKéMON να τη μάθω;$"

MoveTutor_Text_MetronomeTaught:
	.string "Όταν ένα POKéMON κουνάει το δάχτυλο\n"
	.string "σαν METRONOME, συμβαίνουν κάθε\l"
	.string "λογής ωραία πράγματα.\p"
	.string "Δεν θα ήταν ωραίο να μπορούσαμε\n"
	.string "να το κάνουμε κι εμείς;$"

MoveTutor_Text_SleepTalkTeach:
	.string "Χμφ! Η γυναίκα μου βασίζεται στο\n"
	.string "HIDDEN POWER για να μένει ξύπνια.\p"
	.string "Θα έπρεπε απλώς να κοιμάται σαν εμένα\n"
	.string "και να μιλάει στον ύπνο της.\p"
	.string "Μπορώ να μάθω στο POKéMON σου το\n"
	.string "SLEEP TALK αντί γι' αυτό. Θέλεις;$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Α, καλά, καλά. Θέλεις κι εσύ να\n"
	.string "μην κοιμάσαι με το HIDDEN POWER…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Αχ, ένα παιδί που εκτιμάει!\n"
	.string "Σε ποιο POKéMON να τη μάθω;$"

MoveTutor_Text_SleepTalkTaught:
	.string "Δεν έχω πετύχει ούτε μία φορά το\n"
	.string "κόλπο της γυναίκας μου με το νόμισμα.\p"
	.string "Θα ήμουν χαρούμενος αν το πετύχαινα\n"
	.string "ακόμα και όταν μιλάω στον ύπνο μου…$"

MoveTutor_Text_SubstituteTeach:
	.string "Όταν βλέπω τον απέραντο κόσμο από\n"
	.string "εδώ ψηλά στην οροφή…\p"
	.string "Σκέφτομαι πόσο ωραίο θα ήταν να\n"
	.string "υπήρχαν περισσότεροι από εμένα,\l"
	.string "για να ζούσα κάθε είδους ζωή.\p"
	.string "Φυσικά αυτό δεν είναι δυνατόν.\n"
	.string "Χεχε…\p"
	.string "Το βρήκα! Θα σε ενδιέφερε να μάθει\n"
	.string "ένα POKéMON σου το SUBSTITUTE;$"

MoveTutor_Text_SubstituteDeclined:
	.string "Όχι;\p"
	.string "Ένα POKéMON μπορεί να φτιάξει ένα\n"
	.string "αντίγραφο του εαυτού του με αυτό.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Χεχε…\n"
	.string "Σε ποιο POKéMON θέλεις να μάθω\l"
	.string "το SUBSTITUTE;$"

MoveTutor_Text_SubstituteTaught:
	.string "Εμείς οι άνθρωποι πρέπει να ζούμε\n"
	.string "τη ζωή μας στο έπακρο!\p"
	.string "Ελπίζω να το κάνεις κι εσύ αυτό!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Δεν αντέχω άλλο!\p"
	.string "Είναι τελείως απελπιστικό!\p"
	.string "Είμαι FIGHTING-type TRAINER,\n"
	.string "οπότε δεν μπορώ να νικήσω στο\l"
	.string "MOSSDEEP GYM όσο κι αν προσπαθώ!\p"
	.string "Αργκ! Μπουνιά! Μπουνιά! Μπουνιά!\n"
	.string "Μπουνιά! Μπουνιά! Μπουνιά!\p"
	.string "Τι, μη με κοιτάς έτσι!\n"
	.string "Μόνο το έδαφος χτυπάω!\p"
	.string "Ή μήπως θες να μάθω στο POKéMON\n"
	.string "σου το DYNAMICPUNCH;$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Κρίμα! Με κοροϊδεύεις κιόλας;\n"
	.string "Μπουνιά! Μπουνιά! Μπουνιά!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Τι; Αλήθεια; Είσαι καλός άνθρωπος!\n"
	.string "Σε ποιο POKéMON να τη μάθω;$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Θέλω να νικήσεις στο MOSSDEEP GYM\n"
	.string "χρησιμοποιώντας το DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Αχ…\p"
	.string "Ο GYM LEADER της SOOTOPOLIS είναι\n"
	.string "πραγματικά αξιοθαύμαστος.\p"
	.string "Αλλά αυτό σημαίνει επίσης ότι έχω\n"
	.string "πολλούς ανταγωνιστές.\p"
	.string "Έχει μια γοητεία σαν DOUBLE-EDGE.\n"
	.string "Δεν μπόρεσα καν να του\n"
	.string "τραβήξω την προσοχή.\p"
	.string "Σε παρακαλώ, άσε με να μάθω στο\n"
	.string "POKéMON σου το DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Αχ…\n"
	.string "Ακόμα κι εσύ με απέρριψες…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Ωραία, σε ποιο POKéMON να μάθω\n"
	.string "το DOUBLE-EDGE;$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Δεν θα ζω πια για την αγάπη!\n"
	.string "Θα γίνω σκληρός!$"

MoveTutor_Text_ExplosionTeach:
	.string "Δεν σκοπεύω να μείνω σε αυτήν την\n"
	.string "επαρχία για πάντα.\p"
	.string "Θα δεις, θα πάω στην πόλη\n"
	.string "και θα γίνω τεράστια επιτυχία.\p"
	.string "Σοβαρά, θα προκαλέσω μια\n"
	.string "τεράστια EXPLOSION δημοτικότητας!\p"
	.string "Αν το άκουσες αυτό, ευχαρίστως να\n"
	.string "μάθω το EXPLOSION στο POKéMON σου!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Γκάαχ! Με απορρίπτεις επειδή\n"
	.string "μένω στην επαρχία;$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Καλά! EXPLOSION λοιπόν!\n"
	.string "Ποιο POKéMON θέλει να ανατιναχτεί;$"

MoveTutor_Text_ExplosionTaught:
	.string "Εδώ και πολύ καιρό διδάσκω POKéMON\n"
	.string "πώς να χρησιμοποιούν το EXPLOSION,\l"
	.string "αλλά δεν έχω εκραγεί ακόμα ο ίδιος…\p"
	.string "Ίσως επειδή, βαθιά μέσα μου,\n"
	.string "θα προτιμούσα να μείνω εδώ…$"
