gText_ObtainedTheItem::
	.string "Έλαβες {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Η BAG είναι γεμάτη…$"

gText_PutItemInPocket::
	.string "Το {STR_VAR_2} τοποθετήθηκε\n"
	.string "στην {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "Βρέθηκε ένα {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Κρίμα!\n"
	.string "Η BAG είναι γεμάτη…$"

gText_PlayerPutItemInBag::
	.string "Το {STR_VAR_2} τοποθετήθηκε\n"
	.string "στην BAG.$"

gText_ObtainedTheDecor::
	.string "Έλαβες {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Κρίμα! Δεν υπάρχει χώρος για\n"
	.string "άλλο {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Το {STR_VAR_2} μεταφέρθηκε\n"
	.string "στο PC.$"
