gText_WouldYouLikeToRestYourPkmn::
	.string "Γεια σου, καλώς ήρθες στο\n"
	.string "POKéMON CENTER.\p"
	.string "Εδώ θεραπεύουμε τα κουρασμένα\n"
	.string "σου POKéMON.\p"
	.string "Θέλεις να ξεκουράσεις τα POKéMON;$"

gText_IllTakeYourPkmn::
	.string "Εντάξει, θα πάρω τα POKéMON σου\n"
	.string "για λίγα δευτερόλεπτα.$"

gText_RestoredPkmnToFullHealth::
	.string "Σε ευχαριστώ για την αναμονή.\p"
	.string "Τα POKéMON σου είναι πλέον\n"
	.string "σε πλήρη υγεία.$"

gText_WeHopeToSeeYouAgain::
	.string "Ελπίζουμε να σε ξαναδούμε!$"

gText_WelcomeCutShort::
	.string "Γεια σου, καλώς ήρθες στο\n"
	.string "POKéMON CENTER.\p"
	.string "Εδώ θεραπεύουμε τα κουρασμένα\n"
	.string "σου POKéMON.\p"
	.string "Θέλεις να...$"

gText_NoticesGoldCard::
	.string "Α-αυτή η κάρτα...\n"
	.string "Μήπως είναι... η GOLD CARD;!\p"
	.string "Ω, το χρυσό χρώμα αστράφτει!\n"
	.string "Τα τέσσερα αστέρια λάμπουν!\p"
	.string "Έχω δει TRAINERS με SILVER CARD\n"
	.string "πριν, αλλά εσύ, {PLAYER},\l"
	.string "είναι η πρώτη φορά που βλέπω\l"
	.string "κάποιον με GOLD CARD!\p"
	.string "Λοιπόν, {PLAYER}, μου επιτρέπεις\n"
	.string "να θεραπεύσω τα POKéMON σου;$"

gText_YouWantTheUsual::
	.string "Χαίρομαι που σε βλέπω, {PLAYER}!\n"
	.string "Θέλεις τα συνηθισμένα, έτσι;$"

gText_IllTakeYourPkmn2::
	.string "Εντάξει, θα πάρω τα POKéMON σου\n"
	.string "για λίγα δευτερόλεπτα.$"

gText_ThankYouForWaiting::
	.string "Σε ευχαριστώ για την αναμονή.$"

gText_WeHopeToSeeYouAgain2::
	.string "Ελπίζουμε να σε ξαναδούμε!$"
