gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Α, {PLAYER}{KUN}!\p"
	.string "Θέλεις να μάθεις πώς τα πάει\n"
	.string "το POKéDEX σου;$"

gBirchDexRatingText_Cancel::
	.string "Χμ; Ω, δεν έχεις πιάσει αρκετά\n"
	.string "POKéMON ώστε να αξίζει.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Χμχμ…\p"
	.string "Λοιπόν, έχεις δει {STR_VAR_1} POKéMON,\n"
	.string "και έχεις πιάσει {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Πήγαινε πιο πολύ στα χόρτα και\n"
	.string "ψάξε για POKéMON πιο προσεκτικά.$"

gBirchDexRatingText_LessThan20::
	.string "Φαίνεται να παίρνεις τον αέρα\n"
	.string "του. Μα τα δύσκολα αρχίζουν τώρα.$"

gBirchDexRatingText_LessThan30::
	.string "Μερικά POKéMON εμφανίζονται\n"
	.string "μόνο σε συγκεκριμένες περιοχές.\l"
	.string "Πρέπει να έχεις επιμονή.$"

gBirchDexRatingText_LessThan40::
	.string "Θέλει ακόμα δουλειά στην ποσότητα,\n"
	.string "αλλά πλέον αρχίζει να μοιάζει\l"
	.string "με ένα πραγματικό POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Πηγαίνει αρκετά καλά.\n"
	.string "Συνέχισε την προσπάθεια.$"

gBirchDexRatingText_LessThan60::
	.string "Χρησιμοποιείς καθόλου RODS;\n"
	.string "Έχει πολλά POKéMON στη θάλασσα.$"

gBirchDexRatingText_LessThan70::
	.string "Αντί να πιάνεις μόνο POKéMON,\n"
	.string "τι θα έλεγες να τα εξελίξεις κιόλας;$"

gBirchDexRatingText_LessThan80::
	.string "Αυτό θα γίνει ένα φανταστικό\n"
	.string "POKéDEX.\l"
	.string "Αυτό το συναίσθημα έχω.$"

gBirchDexRatingText_LessThan90::
	.string "Έχεις μαζέψει τόσα πολλά…\n"
	.string "Το ταλέντο σου είναι αξιοσημείωτο!$"

gBirchDexRatingText_LessThan100::
	.string "Έχεις πάει στο SAFARI ZONE;\p"
	.string "Ακούω πως υπάρχουν POKéMON που\n"
	.string "μπορούν να πιαστούν μόνο εκεί.$"

gBirchDexRatingText_LessThan110::
	.string "Έφτασες επιτέλους στο ορόσημο\n"
	.string "των 100 ειδών POKéMON.\p"
	.string "Αυτό είναι ένα εντυπωσιακό POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "Ίσως βρεις κάποια POKéMON\n"
	.string "χρησιμοποιώντας ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Θα πρέπει να αποκτήσεις κι άλλα\n"
	.string "POKéMON μέσω ανταλλαγών.$"

gBirchDexRatingText_LessThan140::
	.string "Έχω ακούσει για POKéMON που\n"
	.string "εξελίσσονται όταν αγαπήσουν πολύ\l"
	.string "τους TRAINERS τους.$"

gBirchDexRatingText_LessThan150::
	.string "Δεν είχα ιδέα ότι υπήρχαν τόσα\n"
	.string "πολλά είδη POKéMON στην περιοχή\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Μερικές φορές, κάποια POKéMON\n"
	.string "εμφανίζονται μαζικά ως επιδημία.\p"
	.string "Μη χάνεις τέτοιες ευκαιρίες\n"
	.string "για να τα πιάσεις.$"

gBirchDexRatingText_LessThan170::
	.string "Μπορεί κανείς να πάρει μια καλή\n"
	.string "ιδέα για τα POKéMON του HOENN\l"
	.string "ρίχνοντας μια ματιά στο POKéDEX σου.$"

gBirchDexRatingText_LessThan180::
	.string "Θα έλεγα ότι ήδη έχεις τις βάσεις\n"
	.string "για POKéMON PROFESSOR, και μάλιστα\l"
	.string "πολύ καλού!$"

gBirchDexRatingText_LessThan190::
	.string "Με ένα POKéDEX τόσο ολοκληρωμένο,\n"
	.string "είσαι πραγματικός επαγγελματίας!$"

gBirchDexRatingText_LessThan200::
	.string "Είσαι πολύ κοντά στην ολοκλήρωση\n"
	.string "αυτού του POKéDEX.\l"
	.string "Το νιώθω βαθιά μέσα μου!$"

gBirchDexRatingText_DexCompleted::
	.string "Συγχαρητήρια!\n"
	.string "Το POKéDEX σου ολοκληρώθηκε!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Χμχμ…\n"
	.string "Σε εθνικό επίπεδο…\p"
	.string "Έχεις δει {STR_VAR_1} POKéMON,\n"
	.string "και έχεις πιάσει {STR_VAR_2} POKéMON…$"

