Questionnaire_Text_FillOut::
	.string "Υπάρχει ένα ερωτηματολόγιο.\n"
	.string "Θέλεις να το συμπληρώσεις;$"

Questionnaire_Text_ThankYou::
	.string "Ευχαριστούμε που αφιέρωσες χρόνο\n"
	.string "για το ερωτηματολόγιό μας.\p"
	.string "Οι απαντήσεις σου θα βοηθήσουν\n"
	.string "μελλοντικά.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Ω, γεια σου!\n"
	.string "Γνωρίζεις αυτές τις λέξεις;\p"
	.string "Αυτό σημαίνει πως γνωρίζεις το\n"
	.string "MYSTERY GIFT.\p"
	.string "Από εδώ και πέρα, θα μπορείς\n"
	.string "να λαμβάνεις MYSTERY GIFTS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Αφού αποθηκεύσεις το παιχνίδι,\n"
	.string "θα έχεις πρόσβαση στο MYSTERY GIFT.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Ω, γεια σου!\n"
	.string "Γνωρίζεις αυτές τις λέξεις;\p"
	.string "Αυτό σημαίνει πως γνωρίζεις το\n"
	.string "MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Αφού αποθηκεύσεις το παιχνίδι,\n"
	.string "θα έχεις πρόσβαση στο MYSTERY EVENT.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Ευχαριστούμε για τη χρήση του\n"
	.string "MYSTERY EVENT System.\p"
	.string "Πρέπει να είσαι {PLAYER}.\n"
	.string "Υπάρχει ένα εισιτήριο για σένα.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Φαίνεται πως είναι για χρήση στο\n"
	.string "λιμάνι της LILYCOVE CITY.\p"
	.string "Γιατί δεν το δοκιμάζεις να δεις\n"
	.string "περί τίνος πρόκειται;$"

