	.align 2
gText_ConfirmSave::
	.string "Θέλεις να αποθηκεύσεις το παιχνίδι;$"

gText_AlreadySavedFile::
	.string "Υπάρχει ήδη ένα αρχείο.\n"
	.string "Να γίνει αντικατάσταση;$"

gText_SavingDontTurnOff::
	.string "ΑΠΟΘΗΚΕΥΣΗ...\n"
	.string "ΜΗΝ ΚΛΕΙΣΕΙΣ ΤΗ ΣΥΣΚΕΥΗ.$"

gText_PlayerSavedGame::
	.string "Το παιχνίδι αποθηκεύτηκε.$"

gText_DifferentSaveFile::
	.string "ΠΡΟΣΟΧΗ!\p"
	.string "Υπάρχει ήδη αποθηκευμένο ένα\n"
	.string "διαφορετικό αρχείο.\p"
	.string "Αν αποθηκεύσεις τώρα, η πρόοδος\n"
	.string "στο άλλο αρχείο, μαζί με τα\l"
	.string "items και τα POKéMON, θα χαθεί.\p"
	.string "Θέλεις σίγουρα να αποθηκεύσεις\n"
	.string "και να διαγράψεις το άλλο αρχείο;$"

gText_SaveError::
	.string "Σφάλμα αποθήκευσης.\p"
	.string "Παρακαλώ άλλαξε τη\n"
	.string "μνήμη backup.$"

gText_SavingDontTurnOffPower::
	.string "ΑΠΟΘΗΚΕΥΣΗ...\n"
	.string "ΜΗΝ ΚΛΕΙΣΕΙΣ ΤΗ ΣΥΣΚΕΥΗ.$"
