SecretBase_Text_Trainer0Intro:
	.string "Έφτιαξες ήδη SECRET BASE;\p"
	.string "Πήγα εδώ, εκεί, παντού πριν\n"
	.string "επιλέξω αυτό το μέρος.\p"
	.string "Μιας και είσαι ήδη εδώ, τι θα\n"
	.string "έλεγες για μια μάχη;$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Ωραία!\n"
	.string "Ξεκινάμε!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Ε;\n"
	.string "Α, δεν μπορείς τώρα…$"

SecretBase_Text_Trainer0Defeated::
	.string "Ουάαα! Έχεις πολλή δύναμη!\n"
	.string "Για την ήττα μου… Κράτα το μυστικό!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Πώς σου φαίνεται η SECRET BASE μου;\n"
	.string "Έλα να με επισκεφτείς πάλι αύριο.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Έφτιαξες ήδη SECRET BASE;\p"
	.string "Πήγα εδώ, εκεί, παντού πριν\n"
	.string "επιλέξω αυτό το μέρος.\p"
	.string "Νιώσε άνετα να χαλαρώσεις εδώ!$"

SecretBase_Text_Trainer5Intro:
	.string "Υπάρχουν πολλά μέρη όπου\n"
	.string "μπορείς να φτιάξεις SECRET BASE.\p"
	.string "Αλλά αυτό το μέρος μού αρέσει πολύ.\n"
	.string "Δεν νομίζεις ότι είναι ωραίο;\p"
	.string "Ω, θα ήθελες να μονομαχήσουμε;$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Ωραία, ξεκινάμε!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Ω…\n"
	.string "Δεν μπορείς τώρα, εντάξει.$"

SecretBase_Text_Trainer5Defeated::
	.string "Χμμμ… Ήταν ήττα μας…\n"
	.string "Αλλά μην το πεις σε κανέναν!\l"
	.string "Είναι εμπιστευτικό μυστικό!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Αν βρεθείς ξανά σε αυτή την περιοχή,\n"
	.string "ελπίζω να με επισκεφτείς.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Υπάρχουν πολλά μέρη όπου μπορείς\n"
	.string "να φτιάξεις SECRET BASE.\p"
	.string "Αλλά αυτό το μέρος μού αρέσει πολύ.\n"
	.string "Δεν νομίζεις ότι είναι ωραίο;$"

SecretBase_Text_Trainer1Intro:
	.string "Αυτό είναι ένα δημοφιλές μέρος.\n"
	.string "Είναι πάντα πιασμένο.\p"
	.string "Ω! Μήπως σκεφτόσουν να\n"
	.string "πάρεις κι εσύ αυτό το μέρος;\p"
	.string "Σου προτείνω το εξής: θα το πάρεις\n"
	.string "αν καταφέρεις να με νικήσεις.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Ωραία!\n"
	.string "Θα υπερασπιστώ τη SECRET BASE μου!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Ε; Αλήθεια;\n"
	.string "Δεν σε ενδιαφέρει αυτό το μέρος;$"

SecretBase_Text_Trainer1Defeated::
	.string "Δεν αντέχω άλλο!\n"
	.string "Παραδίνομαι!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Εντάξει, όταν μετακομίσω μια μέρα,\n"
	.string "αυτό το μέρος θα γίνει δικό σου!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Αυτό είναι ένα δημοφιλές μέρος.\n"
	.string "Είναι πάντα πιασμένο.\p"
	.string "Περίμενα πολύ καιρό να αδειάσει.\n"
	.string "Επιτέλους κατάφερα να το πάρω!$"

SecretBase_Text_Trainer6Intro:
	.string "Καλώς ήρθες στο POKéMON LAB μου.\p"
	.string "Κάνω έρευνα πάνω στις μάχες στα\n"
	.string "κρυφά.\p"
	.string "Θέλεις να δεις πόσο δυνατός είμαι;$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Θα τα δώσω όλα!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Α.\n"
	.string "Μια άλλη φορά τότε!$"

SecretBase_Text_Trainer6Defeated::
	.string "Χμμ… Έχω ακόμα πολλά να μάθω.\n"
	.string "Πρέπει να μελετήσω κι άλλο.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Ευχαριστώ για τη μάχη μαζί μου.\n"
	.string "Σε παρακαλώ, έλα πάλι αύριο.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Καλώς ήρθες στο POKéMON LAB μου.\p"
	.string "Κάνω έρευνα πάνω στις μάχες στα\n"
	.string "κρυφά.$"

SecretBase_Text_Trainer2Intro:
	.string "Μια μεγάλη έπαυλη είναι ωραία,\n"
	.string "αλλά μου αρέσουν περισσότερο αυτά.\p"
	.string "Μου αρέσει γιατί κάθε είδους κόσμος\n"
	.string "έρχεται να με επισκεφτεί.\p"
	.string "Λοιπόν, πώς θα σου φαινόταν μια μάχη;$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Έτσι μπράβο!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Όταν ετοιμαστείς, πες μου!$"

SecretBase_Text_Trainer2Defeated::
	.string "Ωχ! Έχασα!\n"
	.string "Αλλά έχει ακόμα πλάκα η μάχη!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Τέλος πάντων, πρέπει να αγοράσω\n"
	.string "διακοσμητικά και έπιπλα.\p"
	.string "Θέλω η SECRET BASE μου να είναι μέρος\n"
	.string "που θα απολαμβάνουν οι άλλοι.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Μια μεγάλη έπαυλη είναι ωραία,\n"
	.string "αλλά μου αρέσουν περισσότερο αυτά.\p"
	.string "Μου αρέσει γιατί κάθε είδους κόσμος\n"
	.string "έρχεται να με επισκεφτεί.$"

SecretBase_Text_Trainer7Intro:
	.string "Απλά λατρεύω να ψωνίζω διακοσμητικά\n"
	.string "και έπιπλα.\p"
	.string "Επίσης λατρεύω να εκτρέφω POKéMON\n"
	.string "το ίδιο πολύ.\p"
	.string "Αν έχεις την καλοσύνη, μονομαχείς\n"
	.string "με τα POKéMON μου;$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Ευχαριστώ.\n"
	.string "Να ξεκινήσουμε;$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Ω.\n"
	.string "Τι απογοήτευση…$"

SecretBase_Text_Trainer7Defeated::
	.string "Παραδίνομαι…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Ήταν πολύ διασκεδαστικό!\n"
	.string "Πάω να απολαύσω τα ψώνια μου τώρα.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Απλά λατρεύω να ψωνίζω διακοσμητικά\n"
	.string "και έπιπλα.\p"
	.string "Επίσης λατρεύω να εκτρέφω POKéMON\n"
	.string "το ίδιο πολύ.$"

SecretBase_Text_Trainer3Intro:
	.string "Κάποιοι φτιάχνουν τις SECRET BASES\n"
	.string "τους σε δυσπρόσιτα μέρη.\l"
	.string "Θέλουν απλά να μην δίνουν στόχο;\p"
	.string "Μιας και με βρήκες όμως, τι λες\n"
	.string "να κάνουμε μια μάχη;$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Δεν θα πέσω εύκολα!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Ωχ… Μήπως κουράστηκες να ψάχνεις\n"
	.string "αυτό το μέρος;$"

SecretBase_Text_Trainer3Defeated::
	.string "Έπεσα…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Πού είναι η δική σου SECRET BASE;\n"
	.string "Θα έπρεπε να σε επισκεφτώ εκεί.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Κάποιοι φτιάχνουν τις SECRET BASES\n"
	.string "τους σε δυσπρόσιτα μέρη.\l"
	.string "Θέλουν απλά να μην δίνουν στόχο;$"

SecretBase_Text_Trainer8Intro:
	.string "Μου είπαν ότι μπορείς να βρεις\n"
	.string "διακοσμητικά με διάφορους τρόπους.\p"
	.string "Να κάνουμε αγώνα για το ποιος θα\n"
	.string "βρει τα καλύτερα έπιπλα!\p"
	.string "Στο μεταξύ, θέλεις μια μάχη;$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Αυτή είναι η SECRET BASE μου.\n"
	.string "Δεν μπορώ να χάσω!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Μονομαχώ μαζί σου ανά πάσα στιγμή.$"

SecretBase_Text_Trainer8Defeated::
	.string "Ε;\n"
	.string "Μόλις έχασα;$"

SecretBase_Text_Trainer8PostBattle:
	.string "Δεν θα χάσω στη συλλογή επίπλων.\n"
	.string "Έλα να με επισκεφτείς ξανά!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Μου είπαν ότι μπορείς να βρεις\n"
	.string "διακοσμητικά με διάφορους τρόπους.\p"
	.string "Να κάνουμε αγώνα για το ποιος θα\n"
	.string "βρει τα καλύτερα έπιπλα!$"

SecretBase_Text_Trainer4Intro:
	.string "Βρήκα ένα μέρος που μου άρεσε και\n"
	.string "το στόλισα με τα αγαπημένα μου.\p"
	.string "Εκτρέφω το αγαπημένο μου POKéMON\n"
	.string "και αποκτώ περισσότερη δύναμη.\p"
	.string "Αυτό ακριβώς κάνω.\n"
	.string "Θέλεις να μονομαχήσουμε;$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Δείξε μου τι αξίζεις!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Φαντάζομαι υπάρχουν στιγμές που\n"
	.string "δεν έχεις όρεξη.$"

SecretBase_Text_Trainer4Defeated::
	.string "Τώρα ξέρω ακριβώς τι αξίζεις.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Μπορούμε και οι δύο να δυναμώσουμε.\n"
	.string "Ας συνεχίσουμε έτσι!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Βρήκα ένα μέρος που μου άρεσε και\n"
	.string "το στόλισα με τα αγαπημένα μου.\p"
	.string "Εκτρέφω το αγαπημένο μου POKéMON\n"
	.string "και αποκτώ περισσότερη δύναμη.\p"
	.string "Κάθε μέρα είναι μια υπέροχη μέρα.$"

SecretBase_Text_Trainer9Intro:
	.string "Μαθαίνεις πολλά για το γούστο των\n"
	.string "ανθρώπων από τα διακοσμητικά που\l"
	.string "έχουν και πώς τα τοποθετούν.\p"
	.string "Πώς σου φαίνεται το γούστο μου;\n"
	.string "Έχασες τα λόγια σου;\p"
	.string "Θέλεις να δεις το γούστο μου στη μάχη;$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Δεν κρατιέμαι καθόλου!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Θα χαρώ να δείξω το στυλ μου\n"
	.string "οποτεδήποτε.$"

SecretBase_Text_Trainer9Defeated::
	.string "Έχεις απίστευτο ταλέντο!\n"
	.string "Η δύναμή σου φαίνεται απεριόριστη…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Πώς σου φάνηκε το στυλ μου;\n"
	.string "Θα συνεχίσω να το βελτιώνω!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Μαθαίνεις πολλά για το γούστο των\n"
	.string "ανθρώπων από τα διακοσμητικά που\l"
	.string "έχουν και πώς τα τοποθετούν.\p"
	.string "Πώς σου φαίνεται το γούστο μου;\n"
	.string "Έχασες τα λόγια σου;$"

