ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Σκοπεύεις να μπεις βαθιά\n"
	.string "εκεί μέσα;\p"
	.string "Τι θα έλεγες να μου φέρεις\n"
	.string "SHOAL SALT και SHOAL SHELLS;\p"
	.string "Μπορώ να σου φτιάξω κάτι καλό\n"
	.string "αν μου φέρεις τα υλικά.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Αν μου φέρεις τέσσερα από το\n"
	.string "καθένα, SHOAL SALT και SHOAL\l"
	.string "SHELLS, μπορώ να σου φτιάξω\l"
	.string "ένα SHELL BELL…\p"
	.string "Μπορείς να βρίσκεις αυτά τα\n"
	.string "υλικά κάθε μέρα.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Ω, κοίτα! SHOAL SALT και SHOAL\n"
	.string "SHELLS! Και αρκετά από αυτά!\p"
	.string "Θέλεις να σου φτιάξω ένα\n"
	.string "SHELL BELL με αυτά;$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Μια χαρά τότε! Θα σου φτιάξω\n"
	.string "ένα SHELL BELL αμέσως.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Ορίστε! Έτοιμο!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Δώσε το σε ένα POKéMON να το\n"
	.string "κρατάει. Θα του αρέσει σίγουρα.\p"
	.string "Ο ήχος του SHELL BELL…\n"
	.string "Είναι απλά υπέροχος!\p"
	.string "Μπορείς να βρίσκεις τα υλικά\n"
	.string "κάθε μέρα, ώστε να σου φτιάξω κι άλλα.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Ω… Έτσι είν' ε…\n"
	.string "Ήθελα να φτιάξω ένα SHELL BELL…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Δεν έχεις χώρο στην BAG σου\n"
	.string "για να στο φτιάξω τώρα.\p"
	.string "Κάνε λίγο χώρο και έλα ξανά\n"
	.string "για το SHELL BELL.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Υπήρχε λίγο SHOAL SALT εδώ.\n"
	.string "Αλλά δεν υπάρχει τίποτα τώρα.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Υπήρχε ένα SHOAL SHELL εδώ.\n"
	.string "Αλλά δεν υπάρχει τίποτα τώρα.$"
