LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Ω, γεια! Ήσουν σε ένα POKéMON\n"
	.string "CONTEST, έτσι δεν είναι;\l"
	.string "Είναι εύκολο να το καταλάβω.\p"
	.string "Είμαι ρεπόρτερ. Γράφω ένα άρθρο\n"
	.string "σχετικά με τα POKéMON CONTESTS.\p"
	.string "Αν επιτρέπεται, θα ήθελες να\n"
	.string "απαντήσεις σε μερικές ερωτήσεις;$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Ω, αλήθεια;\n"
	.string "Σε ευχαριστώ.\p"
	.string "Σύντομα, πώς θα περιέγραφες το\n"
	.string "CONTEST στο οποίο συμμετείχες;$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Α, μάλιστα.\n"
	.string "Πολύ ενδιαφέρον σχόλιο.\p"
	.string "Μας δίνει μια καλή εικόνα για το\n"
	.string "πώς ήταν το CONTEST.\p"
	.string "Έχω μια τελευταία ερώτηση.\p"
	.string "Όταν ακούς τη λέξη “{STR_VAR_2}”,\n"
	.string "ποια εικόνα σου έρχεται στο μυαλό;$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Καταλαβαίνω!\p"
	.string "Έτσι φαντάζεσαι λοιπόν την\n"
	.string "έννοια του/της “{STR_VAR_2}”.\p"
	.string "Σε ευχαριστώ!\n"
	.string "Μου έδωσες μερικές πολύ καλές ιδέες.\p"
	.string "Νομίζω πως μπορώ να γράψω ένα καλό\n"
	.string "άρθρο για τα POKéMON CONTESTS.\p"
	.string "Ίσως αυτό το άρθρο να βγει ακόμη\n"
	.string "και στην τηλεόραση.\l"
	.string "Ελπίζω να το παρακολουθήσεις!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Ω, κρίμα…\p"
	.string "Αν βρεις κάποια καλή ιστορία,\n"
	.string "μοιράσου τη μαζί μου.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Θα περιμένω το επόμενο POKéMON\n"
	.string "CONTEST σου.$"

gTVBravoTrainerText00::
	.string "Ναι!\n"
	.string "Ώρα για το BRAVO TRAINER!\p"
	.string "Σήμερα θα παρουσιάσουμε ένα POKéMON\n"
	.string "που ανήκει στον/στην {STR_VAR_1}.\p"
	.string "Αυτό το POKéMON έχει {STR_VAR_3}\n"
	.string "Rank στην Κατηγορία {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Παρουσιάζουμε το {STR_VAR_2},\n"
	.string "το {STR_VAR_1}!\p"
	.string "Το όνομα {STR_VAR_2}…\p"
	.string "Ακόμη και το όνομα εκπέμπει έναν\n"
	.string "αέρα που δηλώνει “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Όταν ο/η TRAINER {STR_VAR_1}\n"
	.string "έβαλε το POKéMON σε ένα CONTEST,\l"
	.string "μαζέψαμε μερικές ενθουσιώδεις\l"
	.string "δηλώσεις για τον έμπιστο συνεργάτη.$"

gTVBravoTrainerText03::
	.string "Όταν ρωτήθηκε μετά το CONTEST,\n"
	.string "ο/η {STR_VAR_1} απάντησε χαρούμενα\l"
	.string "με ένα μεγάλο χαμόγελο, “{STR_VAR_2}!”\p"
	.string "Το POKéMON του/της {STR_VAR_1} βγήκε\n"
	.string "νούμερο {STR_VAR_3} στο CONTEST.\p"
	.string "Αυτή η φράση ταιριάζει τέλεια\n"
	.string "στον/στην {STR_VAR_1} αυτή τη στιγμή!$"

gTVBravoTrainerText04::
	.string "Όταν ρωτήθηκε μετά το CONTEST,\n"
	.string "ο/η {STR_VAR_1} απάντησε με μια δόση\l"
	.string "πικρίας, “{STR_VAR_2}.”\p"
	.string "Το POKéMON του/της {STR_VAR_1} βγήκε\n"
	.string "νούμερο {STR_VAR_3} στο CONTEST.\p"
	.string "Η απογοήτευση του/της {STR_VAR_1}\n"
	.string "είναι ολοφάνερη, θα έλεγα!$"

gTVBravoTrainerText05::
	.string "Θέλετε να μάθετε τι φαντάζεται\n"
	.string "ο/η {STR_VAR_1} πως είναι το {STR_VAR_2};\p"
	.string "Φυσικά και θέλαμε!\n"
	.string "Γι' αυτό και ρωτήσαμε!\p"
	.string "Η απάντηση είναι σύντομη:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Αυτό σημαίνει το {STR_VAR_2}\n"
	.string "για τον/την {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "Η τελευταία κίνηση {STR_VAR_2}\n"
	.string "του {STR_VAR_1} έχει να κάνει\l"
	.string "εξολοκλήρου με “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Μπράβο, {STR_VAR_1}!\n"
	.string "Μπράβο, {STR_VAR_2}!\p"
	.string "Ελπίζουμε να δούμε τον/την {STR_VAR_1}\n"
	.string "να φτάνει σε ακόμη μεγαλύτερα ύψη!\p"
	.string "Αυτός ήταν ο χρόνος μας!\n"
	.string "Τα λέμε την επόμενη φορά!$"

gTVBravoTrainerText08::
	.string "Παρουσιάζουμε το {STR_VAR_1} του/της TRAINER!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Γεια! Είσαι ο/η TRAINER που μόλις\n"
	.string "έκανε μια μάχη, έτσι δεν είναι;\p"
	.string "Συλλέγω συνεντεύξεις από TRAINERS\n"
	.string "σε όλη την περιοχή.\p"
	.string "Μπορώ να έχω λίγα λόγια για τις\n"
	.string "εντυπώσεις σου από τη μάχη;$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Θα το κάνεις; Αλήθεια;\n"
	.string "Σε ευχαριστώ πολύ!\l"
	.string "Λοιπόν, ε…\p"
	.string "Πώς πήγαν τα πράγματα στο\n"
	.string "BATTLE TOWER σήμερα;\p"
	.string "Ήσουν ευχαριστημένος/η από τη\n"
	.string "μάχη ή μήπως όχι;$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Ω…\n"
	.string "Συγγνώμη για την ενόχληση.\p"
	.string "Δώσε μας μια συνέντευξη την επόμενη\n"
	.string "φορά που θα έρθεις στο BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Μα φυσικά!\p"
	.string "Αυτό το αναμφισβήτητο βλέμμα\n"
	.string "ικανοποίησης στο πρόσωπό σου…\p"
	.string "Είναι φανερό πως είχες μια\n"
	.string "εξαιρετική μάχη.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Ω, καταλαβαίνω…\p"
	.string "Είναι σίγουρα δύσκολο να πάνε\n"
	.string "όλα στη μάχη όπως τα σχεδίασες.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Ω, μπορώ να κάνω άλλη μια ερώτηση;\p"
	.string "Αν περιέγραφες τις εντυπώσεις σου\n"
	.string "για αυτή τη μάχη με μία φράση,\l"
	.string "ποια θα ήταν αυτή;$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Ω, αυτό είναι απίστευτα τέλειο!\p"
	.string "Είναι μια υπέροχη φράση!\n"
	.string "Ελπίζω να πας εξαιρετικά και μετά.\p"
	.string "Ελπίζω να σε ξαναδώ σύντομα!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Ω, καταλαβαίνω…\p"
	.string "Πάντως, το να είσαι σιωπηλός τύπος\n"
	.string "έχει επίσης φάση, έτσι δεν είναι;\p"
	.string "Ελπίζω να μου δώσεις την ευκαιρία\n"
	.string "να ακούσω τις σκέψεις σου ξανά!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Θα περιμένω με ανυπομονησία την\n"
	.string "επόμενη μάχη σου!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ναι!\n"
	.string "Ώρα για το BRAVO TRAINER!\p"
	.string "Σήμερα παρουσιάζουμε τον/την {STR_VAR_1},\n"
	.string "που δοκίμασε το BATTLE TOWER!\p"
	.string "Για την πρόκληση, ο/η {STR_VAR_1}\n"
	.string "κατέβασε ένα φοβερό {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Έκαναν νέο ρεκόρ με {STR_VAR_2} νίκες\n"
	.string "στη σειρά στην κατηγορία {STR_VAR_1}!\l"
	.string "Μπράβο, TRAINER!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Οι δυο τους τελικά λύγισαν από\n"
	.string "τον/την {STR_VAR_1} στον αγώνα {STR_VAR_2}.\l"
	.string "Καλή προσπάθεια, TRAINER!\p"
	.string "Αλλά ήταν κακή τύχη να πέσεις πάνω\n"
	.string "στον/στην {STR_VAR_1} τόσο νωρίς.\p"
	.string "Ρωτήσαμε τον/την TRAINER για τις\n"
	.string "εντυπώσεις από τον αγώνα.$"

BravoTrainerBattleTower_Text_Won::
	.string "Οι δυο τους νίκησαν ολοκληρωτικά\n"
	.string "το {STR_VAR_2} του/της {STR_VAR_1}.\l"
	.string "Μπράβο, TRAINER!\p"
	.string "Το να νικήσεις ακόμη και τον/την\n"
	.string "{STR_VAR_1}… Είναι απίστευτο!\p"
	.string "Ρωτήσαμε τον/την TRAINER για τις\n"
	.string "εντυπώσεις από τη στιγμή δόξας.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Μετά από σερί νικών, λύγισαν\n"
	.string "στο τέλος από το {STR_VAR_2} του {STR_VAR_1}.\l"
	.string "Καλή προσπάθεια, TRAINER!\p"
	.string "Ωστόσο, πρέπει να τους αναγνωρίσουμε\n"
	.string "την αξία. Δεν βλέπεις συχνά τέτοιους\l"
	.string "συνδυασμούς όπως {STR_VAR_1} και {STR_VAR_2}.\p"
	.string "Ρωτήσαμε τον/την TRAINER για τις\n"
	.string "εντυπώσεις από τη μάχη μαζί τους.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Αυτό δήλωσε ο/η TRAINER:\n"
	.string "“Είμαι ικανοποιημένος/η!”\p"
	.string "Δεν είναι μια αναζωογονητική απάντηση;\n"
	.string "Μπράβο, TRAINER!\p"
	.string "Δεν είναι τέλειο να μάχεσαι με\n"
	.string "απόλυτη ικανοποίηση;\p"
	.string "Κατάλαβα πόσο ευχαριστημένος/η ήταν\n"
	.string "όταν τον/την άκουσα να λέει αυτό:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Αυτό δήλωσε ο/η TRAINER:\n"
	.string "“Δεν είμαι ικανοποιημένος/η…”\p"
	.string "Ήταν φανερά λίγο πεσμένος/η\n"
	.string "όταν το ξεστόμισε αυτό.\p"
	.string "Δεν είναι εύκολο να μάχεσαι με\n"
	.string "απόλυτη ικανοποίηση, σωστά;\p"
	.string "Κατάλαβα πόσο απογοητευμένος/η ήταν\n"
	.string "όταν τον/την άκουσα να λέει αυτό:$"

BravoTrainerBattleTower_Text_None1::
	.string "None$"

BravoTrainerBattleTower_Text_None2::
	.string "None$"

BravoTrainerBattleTower_Text_None3::
	.string "None$"

BravoTrainerBattleTower_Text_None4::
	.string "None$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Δεν είναι υπέροχο;\p"
	.string "Εκφράζει τη χαρά του/της {STR_VAR_2},\n"
	.string "θα έλεγα.\p"
	.string "Αυτή η μάχη με τον/την {STR_VAR_3} στο\n"
	.string "τέλος… Ήταν πραγματικά αυτό που\l"
	.string "θα λέγαμε “{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Δεν είναι ταιριαστό;\p"
	.string "Αυτή η μάχη με τον/την {STR_VAR_3} στο\n"
	.string "τέλος… Δεν περιγράφεται αλλιώς\l"
	.string "παρά μόνο ως “{STR_VAR_1}”!\p"
	.string "Η απογοήτευση του/της {STR_VAR_2}\n"
	.string "είναι ολοφάνερη, θα έλεγα!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Μπράβο, {STR_VAR_1}!\n"
	.string "Μπράβο, {STR_VAR_2}!\p"
	.string "Ελπίζουμε να δούμε τον/την {STR_VAR_1}\n"
	.string "να φτάνει σε ακόμη μεγαλύτερα ύψη!\p"
	.string "Αυτός ήταν ο χρόνος μας!\n"
	.string "Τα λέμε την επόμενη φορά!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Ουάου!\p"
	.string "Είναι φανερό πως δίνεις όλη σου\n"
	.string "την αγάπη στο {STR_VAR_1} σου.\p"
	.string "Μάλιστα, το όνομά του είναι {STR_VAR_2}.\p"
	.string "Μπορώ να σου ζητήσω μια χάρη;\p"
	.string "Είμαι ρεπόρτερ και κάνω μια\n"
	.string "έρευνα σχετικά με τα POKéMON.\p"
	.string "Θα ήθελες να απαντήσεις σε μερικές\n"
	.string "απλές ερωτήσεις για μένα;$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Τέλεια! Σε ευχαριστώ!\p"
	.string "Λοιπόν, ξεκινάμε.\n"
	.string "Θέλω μόνο γρήγορες απαντήσεις, οκ;$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Όταν πρωτοσυνάντησες το {STR_VAR_1},\n"
	.string "τι ένιωσες;\p"
	.string "Πώς θα περιέγραφες τα συναισθήματά\n"
	.string "σου εκείνη τη στιγμή;$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Φροντίζεις το {STR_VAR_1} με πολλή αγάπη.\p"
	.string "Αν το παρομοίαζες με κάτι\n"
	.string "που σου αρέσει, τι θα ήταν αυτό;$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Αυτή η ερώτηση αφορά επίσης το\n"
	.string "αγαπημένο σου {STR_VAR_1}.\p"
	.string "Τι ήταν αυτό στο {STR_VAR_1} που\n"
	.string "σε προσέλκυσε;$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Μάλιστα, βγάζει νόημα.\p"
	.string "Η επόμενη ερώτηση ίσως είναι\n"
	.string "λίγο πιο δύσκολη.\p"
	.string "Ορίστε…\p"
	.string "Τι σημαίνουν τα POKéMON για σένα;$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Καταλαβαίνω!\p"
	.string "Χμχμ…\p"
	.string "Ωραία!\n"
	.string "Σε ευχαριστώ για τη βοήθεια.\p"
	.string "Ήταν ευχάριστη και διαφωτιστική\n"
	.string "η κουβέντα μαζί σου.\p"
	.string "Ίσως η συνέντευξή μας να βγει\n"
	.string "στην TV. Συντονίσου να δεις!\p"
	.string "Αυτά λοιπόν.\n"
	.string "Γεια σας!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Ω, εντάξει…\p"
	.string "Αν νιώσεις την ανάγκη να μου πεις\n"
	.string "για τα POKéMON, θα είμαι εδώ!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Μου αρέσει αυτή η δουλειά--μαθαίνεις\n"
	.string "για τα POKéMON παίρνοντας συνεντεύξεις.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Γεια! Φαίνεται πως είστε πολύ\n"
	.string "δεμένοι με το {STR_VAR_1} σου.\p"
	.string "Ξέρεις τι;\n"
	.string "Είμαι ρεπόρτερ.\p"
	.string "Ταξιδεύω και παίρνω συνεντεύξεις\n"
	.string "από κόσμο για τα POKéMON.\p"
	.string "Αναρωτιέμαι αν θα ήθελες να μου\n"
	.string "πεις λίγα λόγια για το {STR_VAR_1} σου;$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Ουάου, σε ευχαριστώ!\p"
	.string "Λοιπόν, πες μου ό,τι θέλεις\n"
	.string "για το {STR_VAR_1} σου.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Ουάου…\n"
	.string "Πολύ ενδιαφέρουσα ιστορία.\p"
	.string "Είστε πραγματικά δεμένοι με το\n"
	.string "{STR_VAR_1}, έτσι δεν είναι;\p"
	.string "Έχω την αίσθηση πως η ιστορία σου\n"
	.string "θα γίνει ένα τέλειο θέμα στην TV.\p"
	.string "Υπόσχομαι να τη μετατρέψω σε μια\n"
	.string "άκρως διασκεδαστική εκπομπή.\l"
	.string "Έχε το νου σου για να τη δεις.\p"
	.string "Λοιπόν, αυτά για την ώρα.\n"
	.string "Γεια σας!$"

gTVFanClubOpinionsText00::
	.string "ΕΙΜΑΣΤΕ ΤΟ POKéMON FAN CLUB!\p"
	.string "Είμαστε στον αέρα!\p"
	.string "Σε αυτή την εκπομπή, ακούμε γνώμες\n"
	.string "και τις μεταδίδω εκ μέρους σας!\l"
	.string "Δεν είναι φανταστική ιδέα εκπομπής;\p"
	.string "Σήμερα, σας φέρνουμε αυτό το θέμα\n"
	.string "από το POKéMON FAN CLUB.\p"
	.string "Λοιπόν, ποιος είναι ο σημερινός\n"
	.string "φανατικός θαυμαστής POKéMON;\p"
	.string "… … … … … … … …\p"
	.string "Ο/η {STR_VAR_1}!\p"
	.string "Ας ακούσουμε τι έχει να πει ο/η\n"
	.string "{STR_VAR_1} για το {STR_VAR_3} το {STR_VAR_2}.\p"
	.string "Και εγώ θα μεταδώσω αυτά τα λόγια\n"
	.string "αγάπης δυνατά στην τηλεόραση!\p"
	.string "Χου-χα!\p"
	.string "Ας φωνάξουμε!$"

gTVFanClubOpinionsText01::
	.string "Ρωτήσαμε τον/την {STR_VAR_1}: “Όταν\n"
	.string "πρωτοείδες το {STR_VAR_2} σου, ποια\l"
	.string "ήταν η πρώτη σου σκέψη;”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ναι! Αυτό είναι μια δυνατή κραυγή!\p"
	.string "Δεν φέρνει πίσω αναμνήσεις από\n"
	.string "εκείνες τις παλιές καλές μέρες;$"

gTVFanClubOpinionsText02::
	.string "Ρωτήσαμε τον/την {STR_VAR_1}: “Αν\n"
	.string "παρομοίαζες το {STR_VAR_2} σου με κάτι,\l"
	.string "αυτό θα ήταν…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ωχ, αυτή κι αν είναι πρωτότυπη ιδέα!\p"
	.string "Μπορείς σίγουρα να νιώσεις την\n"
	.string "αγάπη που έχει ο/η TRAINER για\l"
	.string "το {STR_VAR_2} του/της.$"

gTVFanClubOpinionsText03::
	.string "Και ας δούμε…\n"
	.string "Τι ήταν αυτό στο {STR_VAR_2}\l"
	.string "που τράβηξε τόσο τον/την {STR_VAR_1};\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ουάου! Τι θεαματική δήλωση!\p"
	.string "Η αγάπη του/της TRAINER για το\n"
	.string "{STR_VAR_2} είναι ολοφάνερη!$"

gTVFanClubOpinionsText04::
	.string "Χμ; Έχει κι άλλο ακόμη.\n"
	.string "Ας το δούμε!\p"
	.string "Για να δω τώρα…\p"
	.string "Ρωτήσαμε τον/την {STR_VAR_1}: “Τι\n"
	.string "σημαίνουν τα POKéMON για σένα;”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Μπράβο!\p"
	.string "Αυτή είναι η καλύτερη ατάκα σήμερα!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Σε κάνει να θέλεις να το φωνάζεις\n"
	.string "ξανά και ξανά!\p"
	.string "Τώρα που φωνάξαμε, ήρθε η ώρα να\n"
	.string "πούμε αντίο μέχρι την επόμενη φορά!\p"
	.string "Ας φωνάξουμε όλοι μαζί μια φορά…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "ΕΙΜΑΣΤΕ ΤΟ POKéMON FAN CLUB!\p"
	.string "Είμαστε στον αέρα!\p"
	.string "Σήμερα θα ξεκινήσουμε με τη\n"
	.string "ΓΩΝΙΑ ΕΡΕΥΝΑΣ POKéMON.\p"
	.string "Από όλες τις ιστορίες POKéMON\n"
	.string "και TRAINERS, ποιο νέο δράμα θα\l"
	.string "τραβήξει την προσοχή μας σήμερα;\p"
	.string "Για να δω…\p"
	.string "Αυτό εδώ!\p"
	.string "Θα αρχίσουμε με αυτό το γράμμα!\p"
	.string "Είναι ένα γράμμα από τον/την\n"
	.string "{STR_VAR_1} για ένα αγαμημένο {STR_VAR_2}.\p"
	.string "Ας δούμε με πόσο πάθος εκφράζει\n"
	.string "την αγάπη του/της για το {STR_VAR_2}!\l"
	.string "Χμχμ…$"

gTVFanClubText01::
	.string "Ουάου!\n"
	.string "Τι φανταστικό γράμμα!$"

gTVFanClubText02::
	.string "Μου άρεσε τόσο, ας το δούμε ξανά!$"

gTVFanClubText03::
	.string "Ένα καλό γράμμα αξίζει να το\n"
	.string "διαβάζεις ξανά και ξανά!$"

gTVFanClubText04::
	.string "Το κομμάτι “{STR_VAR_3}” τονίζει\n"
	.string "πραγματικά το συναίσθημα!\p"
	.string "Είναι ένα υπέροχο γράμμα με\n"
	.string "πραγματικό βάθος συναισθημάτων!$"

gTVFanClubText05::
	.string "Ειδικά αυτό το μέρος “{STR_VAR_3}”!\p"
	.string "Λατρεύω πώς χρησιμοποιείται το\n"
	.string "“{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "Παρεμπιπτόντως, αν και δεν έχει\n"
	.string "σημασία, το “{STR_VAR_3}” είναι τέλειο.\p"
	.string "Χρησιμοποιώ το “{STR_VAR_3}” πολύ\n"
	.string "στις συζητήσεις μου τελευταία.$"

gTVFanClubText07::
	.string "Αν έπρεπε να βαθμολογήσω αυτό το\n"
	.string "γράμμα, θα έδινα {STR_VAR_3} βαθμούς.\p"
	.string "Την επόμενη φορά περιμένω ένα ακόμη\n"
	.string "καλύτερο γράμμα, {STR_VAR_1}!\p"
	.string "Ωχ, κοιτάξτε πώς πέρασε η ώρα!\n"
	.string "Ώρα να αποχαιρετιστούμε τώρα!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Ω;\n"
	.string "Μήπως σου αρέσουν τα POKéMON;\p"
	.string "Είμαι σε αποστολή για την TV.\p"
	.string "Μαζεύω πρόσφατες ιστορίες για\n"
	.string "POKéMON και TRAINERS.\p"
	.string "Αν δεν σε πειράζει, θα μπορούσες να\n"
	.string "μου πεις κάτι για τον εαυτό σου;$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Μαζεύω πρόσφατες ιστορίες για\n"
	.string "POKéMON και TRAINERS.\p"
	.string "Αν δεν σε πειράζει, θα μπορούσες να\n"
	.string "μου πεις κάτι για τον εαυτό σου;$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Ω, αλήθεια;\n"
	.string "Σε ευχαριστώ!\p"
	.string "Τότε, πες μου ό,τι ενδιαφέρον\n"
	.string "έζησες πρόσφατα με POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Ω, καταλαβαίνω…\p"
	.string "Αν έχεις κάποια ενδιαφέρουσα\n"
	.string "ιστορία να πεις, ενημέρωσέ με.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Ω, τι όμορφη ιστορία!\p"
	.string "Θα φροντίσω σίγουρα να ακουστεί\n"
	.string "η ιστορία σου στην τηλεόραση.\p"
	.string "Θα προβληθεί κάποια στιγμή, οπότε\n"
	.string "να την περιμένεις.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Χμ…\n"
	.string "Έχω μια καλή ιστορία για την TV.\p"
	.string "Καλύτερα να τη γράψω γρήγορα!$"

gTVRecentHappeningsText00::
	.string "Γεια σας, ώρα για RECENT HAPPENINGS.\p"
	.string "Για τους POKéMON TRAINERS, κάθε μέρα\n"
	.string "είναι σαν παραμύθι.\p"
	.string "Αυτό που θέλουμε είναι να σας\n"
	.string "παρουσιάσουμε μερικές ιστορίες.\p"
	.string "Σήμερα, σας φέρνουμε την ιστορία\n"
	.string "του/της TRAINER {STR_VAR_1}.\p"
	.string "Τι έζησε ο/η {STR_VAR_1} πρόσφατα;\n"
	.string "Ας το ανακαλύψουμε.\p"
	.string "Για να δούμε…$"

gTVRecentHappeningsText01::
	.string "Δεν ήταν διαφωτιστικό;\p"
	.string "Η ιστορία δείχνει ξεκάθαρα τι\n"
	.string "έζησε ο/η {STR_VAR_1} πρόσφατα.\l"
	.string "Σαν να ήμασταν εκεί μάρτυρες!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Αυτό\n"
	.string "τονίζει την ιστορία και δίνει βάθος.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Αυτό δίνει μια αίσθηση τοποθεσίας.\l"
	.string "Μας βοηθά να δούμε το σκηνικό.$"

gTVRecentHappeningsText04::
	.string "Το μέρος “{STR_VAR_3}”\n"
	.string "της ιστορίας είναι πολύ εκφραστικό.$"

gTVRecentHappeningsText05::
	.string "Ο/η {STR_VAR_1} διηγήθηκε μια\n"
	.string "υπέροχη ιστορία με POKéMON.\p"
	.string "Και τώρα η ιστορία του/της\n"
	.string "έχει αποτυπωθεί και στη δική σας ψυχή.\p"
	.string "Αυτά για σήμερα.\n"
	.string "Συντονιστείτε την επόμενη φορά.$"

gTVMassOutbreakText00::
	.string "Χαιρετίσματα!\n"
	.string "Ώρα για το POKéMON NEWS.\p"
	.string "Μόλις λάβαμε νέα για ένα πολύ\n"
	.string "σπάνιο συμβάν.\p"
	.string "Υπάρχουν αναφορές για μαζική\n"
	.string "εμφάνιση {STR_VAR_2} κοντά\l"
	.string "στην περιοχή {STR_VAR_1}.\p"
	.string "Το {STR_VAR_2}, όπως ίσως γνωρίζετε,\n"
	.string "είναι ένα σπάνιο POKéMON\l"
	.string "που δύσκολα εντοπίζεται.\p"
	.string "Ακούγεται ως σπάνια ευκαιρία να\n"
	.string "δείτε αυτή την έξαρση {STR_VAR_2}\l"
	.string "στην άγρια φύση.\p"
	.string "Αυτά ήταν τα POKéMON NEWS.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Ελπίζω να είστε χαρούμενοι,\n"
	.string "το “3 CHEERS FOR {POKEBLOCK}S” ξεκινά!\p"
	.string "Σήμερα εξετάζουμε τα {POKEBLOCK}\n"
	.string "που έφτιαξε ο/η {STR_VAR_1} με την παρέα.\p"
	.string "Χαιρίς καθυστέρηση, ας τα δώσω\n"
	.string "στο λαίμαργο POKéMON μου, GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Και το αποτέλεσμα είναι πολύ {STR_VAR_1}!\n"
	.string "Το GULPIN λέει πως είναι “{STR_VAR_2}!”\p"
	.string "Σε ευχαριστούμε πολύ, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Η προσπάθεια του/της {STR_VAR_1}\n"
	.string "άφησε μερικά πράγματα επιθυμητά.\p"
	.string "Αν ο/η TRAINER ανακάτευε καλύτερα,\n"
	.string "τα {POKEBLOCK} θα ήταν πιο νόστιμα.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Χμ… Είναι πολύ {STR_VAR_1}.\n"
	.string "Το GULPIN λέει πως είναι “{STR_VAR_2}!”\p"
	.string "Φαίνεται πως τα λάθη του/της {STR_VAR_3}\n"
	.string "χάλασαν την ποιότητα ανάμειξης…$"

gTV3CheersForPokeblocksText04::
	.string "Κρίμα που η προσπάθεια\n"
	.string "του/της {STR_VAR_1} πήγε χαμένη.\p"
	.string "Ελπίζουμε ο/η {STR_VAR_2} να τα πάει\n"
	.string "καλύτερα την επόμενη φορά!$"

gTV3CheersForPokeblocksText05::
	.string "Συντονιστείτε την επόμενη φορά!\n"
	.string "Το σλόγκαν μας: “3 CHEERS FOR {POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Γεια χαρά!\p"
	.string "Είμαι μεγάλος θαυμαστής του/της {STR_VAR_1}.\n"
	.string "Ποια είναι η γνώμη σου για {STR_VAR_1};$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Μάλιστα, μάλιστα. Αυτό πιστεύεις\n"
	.string "για τον/την TRAINER.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Έχεις ξεχάσει τελείως\n"
	.string "τον/την {STR_VAR_1};$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Είμαι μεγάλος θαυμαστής του/της {STR_VAR_1}.\n"
	.string "Ποια είναι η γνώμη σου για {STR_VAR_1};$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Πόσο δυνατό θα βαθμολογούσες\n"
	.string "τον/την {STR_VAR_1} με άριστα το 100;$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Έχεις ξεχάσει τελείως\n"
	.string "τον/την {STR_VAR_1};$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Ω, καταλαβαίνω!\n"
	.string "Πρέπει να συναντήσεις τον/την {STR_VAR_1}.\l"
	.string "Σίγουρα θα γίνεις θαυμαστής κι εσύ!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Μάλιστα, μάλιστα.\p"
	.string "Σε ευχαριστώ!\n"
	.string "Αυτή είναι πολύ χρήσιμη πληροφορία.\p"
	.string "Θα τη μοιραστώ με άλλους θαυμαστές\n"
	.string "του/της {STR_VAR_1} για να τη συζητήσουμε.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Θα βγει ένα αφιέρωμα στην TV\n"
	.string "για τον/την {STR_VAR_1} πολύ σύντομα.\p"
	.string "Ελπίζω να το προλάβεις!$"

gTVTrainerFanClubSpecialText00::
	.string "ΑΦΙΕΡΩΜΑ TRAINER FAN CLUB\n"
	.string "ΕΙΔΙΚΟ {STR_VAR_1}!\p"
	.string "Αυτό είναι ένα ειδικό αφιέρωμα για\n"
	.string "τους θαυμαστές του/της {STR_VAR_1}\l"
	.string "σε ολόκληρη τη HOENN!\p"
	.string "Σήμερα θέτουμε το ερώτημα: “Τι\n"
	.string "πιστεύει ο κόσμος για {STR_VAR_1};”\p"
	.string "Θέσαμε την ερώτηση στον/στην {STR_VAR_2}\n"
	.string "ως εκπρόσωπο των TRAINERS.\p"
	.string "Ρωτήσαμε: “Με μια λέξη, πώς θα\n"
	.string "περιέγραφες τον/την {STR_VAR_1};”\p"
	.string "Η απάντηση: “{STR_VAR_3}.”\p"
	.string "Μπράβο στον/στην {STR_VAR_2}!\n"
	.string "Τι διορατική άποψη!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Ακούγεται τόσο όμορφα!\p"
	.string "Ο/η {STR_VAR_2} βαθμολόγησε επίσης\n"
	.string "τη δύναμη του/της {STR_VAR_1} από 0 έως 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Η βαθμολογία ήταν {STR_VAR_3} βαθμοί!\n"
	.string "Πρόκειται για μια πολύ υψηλή βαθμολογία!\p"
	.string "Ο/η {STR_VAR_2} σίγουρα εκτιμά\n"
	.string "πάρα πολύ τον/την {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText02::
	.string "Η βαθμολογία ήταν {STR_VAR_3} βαθμοί!\n"
	.string "Αυτή είναι μια αρκετά καλή βαθμολογία.\p"
	.string "Ο/η {STR_VAR_2} μάλλον θεωρεί\n"
	.string "τον/την {STR_VAR_1} ως αντίπαλο.$"

gTVTrainerFanClubSpecialText03::
	.string "Η βαθμολογία ήταν {STR_VAR_3} βαθμοί!\n"
	.string "Αυτή είναι μια μάλλον χαμηλή βαθμολογία.\p"
	.string "Ο/η {STR_VAR_2} μάλλον θεωρεί\n"
	.string "τον/την {STR_VAR_1} απλό βοηθό.$"

gTVTrainerFanClubSpecialText04::
	.string "Η βαθμολογία ήταν {STR_VAR_3} βαθμοί!\n"
	.string "Αυτή είναι μια πολύ κακή βαθμολογία.\p"
	.string "Ο/η {STR_VAR_2} μάλλον θεωρεί\n"
	.string "τον/την {STR_VAR_1} ως κατώτερο.$"

gTVTrainerFanClubSpecialText05::
	.string "Αυτά ήταν λοιπόν, φίλοι μου!\p"
	.string "Νομίζω πως όλοι μάθαμε κάτι\n"
	.string "καινούριο για τον/την {STR_VAR_1}.\p"
	.string "Κλείνοντας, σας αφήνω με τα\n"
	.string "λόγια του/της {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Και τώρα, ήρθε η ώρα για…\n"
	.string "THE NAME RATER SHOW.\p"
	.string "Λέω τη μοίρα των POKéMON σας από\n"
	.string "το όνομα που τους έχετε δώσει.\p"
	.string "Μοιράζομαι χρήσιμες συμβουλές,\n"
	.string "αυτό είναι το έργο μου.\p"
	.string "Σήμερα, θα αναλύσω το όνομα\n"
	.string "{STR_VAR_3} του POKéMON {STR_VAR_2}\l"
	.string "που ανήκει στον/στην {STR_VAR_1}.\p"
	.string "Χμχμ…\p"
	.string "Χμ…\n"
	.string "Αυτό το όνομα είναι…$"

gTVNameRaterText01::
	.string "Ένα όνομα που δείχνει ταλέντο\n"
	.string "με πολλούς διαφορετικούς τρόπους.\p"
	.string "Προτρέπω τον/την TRAINER να πάρει\n"
	.string "θάρρος για πολλές προκλήσεις.$"

gTVNameRaterText02::
	.string "Ένα όνομα που ταιριάζει απόλυτα\n"
	.string "με το {STR_VAR_1}, το όνομα του/της TRAINER.\p"
	.string "Δείχνει πως θα αναπτύξετε μια\n"
	.string "υπέροχη σχέση με τέλειο χρονισμό.$"

gTVNameRaterText03::
	.string "Ένα όνομα κατάλληλο για ένα\n"
	.string "μοναδικό POKéMON!\p"
	.string "Με σωστή εκπαίδευση, αυτή η\n"
	.string "μοναδικότητα θα ανθίσει θεαματικά!$"

gTVNameRaterText04::
	.string "Ένα όνομα που θα καλλιεργήσει τη\n"
	.string "στοργική πλευρά του POKéMON.\p"
	.string "Αν εκπαιδευτεί σωστά, αυτό το\n"
	.string "POKéMON θα δείξει αληθινή ζεστασιά!$"

gTVNameRaterText05::
	.string "Ένα πολύ ωραίο όνομα που αφήνει\n"
	.string "υποσχέσεις για μελλοντικό μεγαλείο.\p"
	.string "Αναρωτιέμαι τι επιφυλάσσει το\n"
	.string "μέλλον για αυτό το POKéMON.$"

gTVNameRaterText06::
	.string "Ένα καλό όνομα που θα κάνει το\n"
	.string "POKéMON υγιές και δυνατό!\p"
	.string "Αυτό το POKéMON θα παραμείνει\n"
	.string "ακμαίο για πολύ καιρό.$"

gTVNameRaterText07::
	.string "Ένα καλό όνομα που θα κάνει το\n"
	.string "POKéMON πολύ δραστήριο!\p"
	.string "Πιστεύω πως αυτό το POKéMON θα έχει\n"
	.string "εξαιρετική απόδοση στις μάχες.$"

gTVNameRaterText08::
	.string "Ένα ελκυστικό όνομα που κάνει το\n"
	.string "POKéMON εξαιρετικά γοητευτικό!\p"
	.string "Δεν έχω αμφιβολία πως θα λάμψει\n"
	.string "στα POKéMON CONTESTS.$"

gTVNameRaterText09::
	.string "Το όνομα {STR_VAR_1} έχει ως ρίζα\n"
	.string "το γράμμα “{STR_VAR_3}.”\p"
	.string "Αυτό στηρίζεται από το πρώτο\n"
	.string "γράμμα “{STR_VAR_2}”, δίνοντάς του\l"
	.string "μια στιβαρή παρουσία ως όνομα.$"

gTVNameRaterText10::
	.string "Το όνομα {STR_VAR_1} έχει πολύ\n"
	.string "κομψό και ευχάριστο σχήμα.\p"
	.string "Η παρουσία των γραμμάτων “{STR_VAR_2}” και\n"
	.string "“{STR_VAR_3}” είναι απίστευτα καλή!$"

gTVNameRaterText11::
	.string "Το όνομα {STR_VAR_1}--έχει μια\n"
	.string "υπέροχη, ρέουσα αίσθηση.\p"
	.string "Η ροή από το αρχικό γράμμα “{STR_VAR_2}”\n"
	.string "στο “{STR_VAR_3}” είναι φανταστική.$"

gTVNameRaterText12::
	.string "Ας δούμε μερικά ακόμη παραδείγματα\n"
	.string "ωραίων ονομάτων, θέλετε;$"

gTVNameRaterText13::
	.string "Δοκιμάστε αυτό: Πάρτε ένα μέρος από\n"
	.string "το όνομα {STR_VAR_1} του/της TRAINER\l"
	.string "και φτιάξτε το όνομα {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Το όνομα {STR_VAR_2}{STR_VAR_3} θα λειτουργούσε\n"
	.string "επίσης πολύ καλά.$"

gTVNameRaterText15::
	.string "Το όνομα είδους του POKéMON {STR_VAR_2}\n"
	.string "μπορεί να χρησιμοποιηθεί ως βάση\l"
	.string "για τη δημιουργία του ονόματος {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "Το {STR_VAR_1}{STR_VAR_3} θα ήταν επίσης ένα\n"
	.string "αποτελεσματικό όνομα.$"

gTVNameRaterText17::
	.string "Αυτό που πρέπει να αποφεύγεται είναι\n"
	.string "το όνομα ενός άλλου POKéMON.\p"
	.string "Για παράδειγμα, μην πάρετε το όνομα\n"
	.string "του {STR_VAR_2} για να βγάλετε το {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Αυτό είναι απαράδεκτο.$"

gTVNameRaterText18::
	.string "Πρέπει να πω πως το {STR_VAR_1}\n"
	.string "είναι ένα αρκετά καλό όνομα.\p"
	.string "Ελπίζω ο/η TRAINER να συνεχίσει\n"
	.string "να φέρεται στο {STR_VAR_1} με αγάπη.\p"
	.string "Αυτά για τη σημερινή εκπομπή.\n"
	.string "Εις το επανιδείν.$"

gTVPokemonAnglerText00::
	.string "ΨΑΡΕΜΑ {STR_VAR_2}\p"
	.string "ΠΑΡΟΥΣΙΑΣΤΗΣ: Γεια σας! Σήμερα θα\n"
	.string "δούμε συμβουλές ψαρέματος {STR_VAR_2}.\p"
	.string "GURU, τι συμβουλή έχετε για να\n"
	.string "πιάσουμε {STR_VAR_2};\p"
	.string "GURU: Χμ; Ψάρεμα {STR_VAR_2};\n"
	.string "Λοιπόν, να είστε υπομονετικοί και\l"
	.string "να περιμένετε. Αυτό είναι όλο.\p"
	.string "Βλέπετε τον/την {STR_VAR_1} εκεί πέρα;\n"
	.string "Ο/η TRAINER είναι καλό παράδειγμα.\p"
	.string "Έχει ήδη χάσει {STR_VAR_3} POKéMON\n"
	.string "που του/της ξέφυγαν.\p"
	.string "Αλλά ο/η {STR_VAR_1} περιμένει. Δεν τα παρατά.\n"
	.string "Αυτός είναι ο νόμος για {STR_VAR_2}.\p"
	.string "ΠΑΡΟΥΣΙΑΣΤΗΣ: Μάλιστα…\p"
	.string "Ω! Ο/η {STR_VAR_1} επιτέλους έπιασε\n"
	.string "ένα ακριβοθώρητο {STR_VAR_2}!\p"
	.string "Ο/η TRAINER κοντεύει να κλάψει\n"
	.string "από τη μεγάλη του/της χαρά!\p"
	.string "Βλέποντας αυτή τη χαρά, θέλω κι εγώ\n"
	.string "να πάω για ψάρεμα τώρα!\p"
	.string "Τηλεθεατές, ευκαιρία να\n"
	.string "δοκιμάσετε το ψάρεμα {STR_VAR_2}!\p"
	.string "Μέχρι την επόμενη φορά, αντίο\n"
	.string "και καλό ψάρεμα σε όλους!$"

gTVPokemonAnglerText01::
	.string "ΨΑΡΕΜΑ {STR_VAR_2}\p"
	.string "ΠΑΡΟΥΣΙΑΣΤΗΣ: Γεια σας! Σήμερα θα\n"
	.string "δούμε συμβουλές ψαρέματος {STR_VAR_2}.\p"
	.string "GURU, τι συμβουλή έχετε για να\n"
	.string "πιάσουμε {STR_VAR_2};\p"
	.string "GURU: Χμ; Ψάρεμα {STR_VAR_2};\n"
	.string "Λοιπόν, κουνήστε το ΚΑΛΑΜΙ σας\l"
	.string "με περίσσια ενέργεια!\p"
	.string "Βλέπετε τον/την {STR_VAR_1} εκεί πέρα;\n"
	.string "Βλέπετε πώς χειρίζεται το ΚΑΛΑΜΙ;\p"
	.string "Έχει ήδη πιάσει {STR_VAR_3}\n"
	.string "POKéMON στη σειρά.\p"
	.string "ΠΑΡΟΥΣΙΑΣΤΗΣ: Απίστευτο!\n"
	.string "Μοιάζει με καταιγίδα…\p"
	.string "Βλέποντας τέτοια τεχνική, με\n"
	.string "πιάνει κι εμένα επιθυμία για ψάρεμα.\p"
	.string "Τηλεθεατές, ευκαιρία να\n"
	.string "δοκιμάσετε το ψάρεμα {STR_VAR_2}!\p"
	.string "Μέχρι την επόμενη φορά, αντίο\n"
	.string "και καλό ψάρεμα σε όλους!$"

gTVPokemonTodayFailedText00::
	.string "Γεια σας!\p"
	.string "Ώρα για το POKéMON TODAY!\p"
	.string "BIG SIS: Γεια! Είστε όλοι χαρούμενοι\n"
	.string "και ορεξάτοι σήμερα;\p"
	.string "Σήμερα θα δούμε το POKéMON\n"
	.string "{STR_VAR_2} του/της {STR_VAR_1}!\p"
	.string "BIG BRO: Ναι! Αυτό ακριβώς θα κάνουμε!$"

gTVPokemonTodayFailedText01::
	.string "Ω!\n"
	.string "Μιας και μιλάμε για τον/την {STR_VAR_1}…\p"
	.string "BIG SIS, είδα τον/την TRAINER με τα ίδια\n"
	.string "μου τα μάτια!\p"
	.string "BIG SIS: Ω, τι είδες;\p"
	.string "BIG BRO: Λοιπόν, έπρεπε να πάω\n"
	.string "ένα ταξίδι στο/στη {STR_VAR_2}.\p"
	.string "Τότε πέτυχα τον/την {STR_VAR_1},\n"
	.string "που προσπαθούσε να πιάσει το\l"
	.string "POKéMON {STR_VAR_3}, αλλά…$"

gTVPokemonTodayFailedText02::
	.string "Το POKéMON κατάφερε να ξεφύγει!\p"
	.string "Και σπατάλησε τόσες POKé BALLS: {STR_VAR_2}!\p"
	.string "Έπρεπε να δεις την απογοήτευση\n"
	.string "στο πρόσωπο του/της {STR_VAR_1}\l"
	.string "όταν το POKéMON έγινε άφαντο!$"

gTVPokemonTodayFailedText03::
	.string "Αλλά ο/η {STR_VAR_1} έκανε λάθος\n"
	.string "και το POKéMON λιποθύμησε!\p"
	.string "Και σπατάλησε τόσες POKé BALLS: {STR_VAR_2}!\p"
	.string "Έπρεπε να δεις το ξαφνιασμένο\n"
	.string "πρόσωπο του/της {STR_VAR_1}\l"
	.string "όταν το POKéMON λιποθύμησε!$"

gTVPokemonTodayFailedText04::
	.string "BIG SIS: Ε, εσύ εκεί!\n"
	.string "Αυτό δεν είναι ωραίο!\p"
	.string "Δεν πρέπει να γελάς με τη\n"
	.string "δυστυχία των άλλων!\p"
	.string "Ω, καημένε/η {STR_VAR_1}.\n"
	.string "Τι κρίμα!\p"
	.string "BIG BRO: Αλήθεια είναι!\n"
	.string "Συγγνώμη που γέλασα.$"

gTVPokemonTodayFailedText05::
	.string "BIG SIS: Μπουφουφού…\p"
	.string "BIG BRO: Ε!\n"
	.string "Κι εσύ μόλις γέλασες!\p"
	.string "BIG SIS: Ορίστε;!\p"
	.string "Δεν γέλασα!\n"
	.string "Ειλικρινά, δεν γέλασα!\p"
	.string "Ω, καημένε/η {STR_VAR_1}.\n"
	.string "Τι κρίμα!\p"
	.string "BIG BRO: …$"

gTVPokemonTodayFailedText06::
	.string "BIG SIS: Αρκετά με τις τρέλες!\n"
	.string "Ας δούμε το σημερινό POKéMON…\p"
	.string "Ε;\n"
	.string "Τέλειωσε ήδη ο χρόνος μας;\p"
	.string "Αχ!\n"
	.string "Δεν προλάβαμε POKéMON σήμερα!\p"
	.string "BIG BRO: Τα λέμε την επόμενη φορά!\p"
	.string "BIG SIS: Ε, μην κλείνεις την εκπομπή\n"
	.string "χωρίς εμένα!$"

gTVPokemonTodaySuccessfulText00::
	.string "Γεια σας!\p"
	.string "Ώρα για το POKéMON TODAY!\p"
	.string "BIG SIS: Γεια! Είστε όλοι χαρούμενοι\n"
	.string "και ορεξάτοι σήμερα;\p"
	.string "Σήμερα θα δούμε το POKéMON\n"
	.string "{STR_VAR_2} του/της {STR_VAR_1}!\p"
	.string "BIG BRO: Ναι! Αυτό ακριβώς θα κάνουμε!$"

gTVPokemonTodaySuccessfulText01::
	.string "BIG SIS: Ο/η {STR_VAR_1} έδωσε το όνομα\n"
	.string "{STR_VAR_3} στο {STR_VAR_2}!\p"
	.string "Απ' ό,τι φαίνεται το {STR_VAR_3} δέχεται\n"
	.string "πολλή αγάπη και φροντίδα!$"

gTVPokemonTodaySuccessfulText02::
	.string "BIG BRO: Ο/η TRAINER χρειάστηκε να\n"
	.string "ρίξει τόσες POKé BALLS: {STR_VAR_3}!\p"
	.string "Τελικά χρειάστηκε μόνο μία {STR_VAR_2}\n"
	.string "για να το πιάσει!$"

gTVPokemonTodaySuccessfulText03::
	.string "BIG SIS: Αφού ήταν τόσο εύκολο,\n"
	.string "θα ήταν γραφτό να συναντηθούν\l"
	.string "ο/η {STR_VAR_1} και το {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "BIG SIS: Ουάου! Αυτό είναι τέλειο!\p"
	.string "Αλλά όπως λένε, ένα POKéMON\n"
	.string "που θέλει κόπο για να πιαστεί\l"
	.string "κερδίζει την αγάπη του/της TRAINER!$"

gTVPokemonTodaySuccessfulText05::
	.string "BIG SIS: Το {STR_VAR_2} του/της {STR_VAR_1}\n"
	.string "είναι αξέχαστο POKéMON καθώς\l"
	.string "χρειάστηκε μια σπάνια MASTER BALL!\p"
	.string "BIG BRO: Ουάου! Αυτό είναι απίθανο!\p"
	.string "BIG SIS: Ο/η {STR_VAR_1} σίγουρα θα\n"
	.string "ήθελε πολύ αυτό το {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText06::
	.string "BIG BRO: Και το να δώσει το όνομα\n"
	.string "{STR_VAR_3} σε αυτό το {STR_VAR_2}…\p"
	.string "Δείχνει πολλά για το ένστικτο\n"
	.string "του/της {STR_VAR_1} ως TRAINER.\p"
	.string "BIG SIS: Συμφωνώ απόλυτα με αυτό!$"

gTVPokemonTodaySuccessfulText07::
	.string "Αν ήμουν εγώ, θα έδινα αυτό το όνομα\n"
	.string "σε κάτι σαν αυτό το {STR_VAR_3}!\p"
	.string "BIG BRO: Ουάου! Αυτό θα μπορούσε να\n"
	.string "είναι η αρχή για κάτι νέο!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} το {STR_VAR_1};\n"
	.string "Δεν ακούγεται τέλειο;\p"
	.string "Τα γράμματα και όλα--ακούγονται\n"
	.string "ακριβώς σωστά για το POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: Ναι, αλήθεια είναι αυτό!$"

gTVPokemonTodaySuccessfulText09::
	.string "Απ' όσο ξέρω, κανένας TRAINER δεν\n"
	.string "έχει δώσει το όνομα {STR_VAR_2} στο\l"
	.string "{STR_VAR_1} του/της!\p"
	.string "BIG BRO: Αυτό δείχνει το υπέροχο\n"
	.string "γούστο που έχει στην επιλογή ονομάτων!$"

gTVPokemonTodaySuccessfulText10::
	.string "Την επόμενη φορά που θα πιάσω POKéMON,\n"
	.string "μάλλον θα του δώσω το όνομα {STR_VAR_2}.\p"
	.string "BIG BRO: Ε; Κι εγώ επίσης!\n"
	.string "Θα χρησιμοποιήσω το όνομα {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "BIG SIS: Ω, όχι!\n"
	.string "Κοιτάξτε την ώρα!\p"
	.string "Λοιπόν, παιδιά, αυτά για σήμερα.\n"
	.string "Τα λέμε την επόμενη φορά!\p"
	.string "BIG BRO: Να θυμάστε, ίσως το δικό σας\n"
	.string "POKéMON να είναι στο προσκήνιο!$"

SmartShopper_Text_Intro::
	.string "Γεια σας!\p"
	.string "Ώρα για το TODAY'S SMART SHOPPER.\p"
	.string "ΡΕΠΟΡΤΕΡ: Πώς είστε, τηλεθεατές;\p"
	.string "Σήμερα επισκεπτόμαστε ένα μαγαζί\n"
	.string "στο/στη {STR_VAR_2}.\p"
	.string "Ας δούμε ποια προϊόντα είχαν\n"
	.string "τη μεγαλύτερη ζήτηση πρόσφατα.$"

SmartShopper_Text_ClerkNormal::
	.string "Ας μιλήσουμε με τον υπάλληλο.\p"
	.string "Γεια σας! Πώς πάνε οι δουλειές;\p"
	.string "ΥΠΑΛΛΗΛΟΣ: Ω, πάμε εξαιρετικά.\p"
	.string "Πρόσφατα, το {STR_VAR_2} είχε\n"
	.string "ιδιαίτερα μεγάλες πωλήσεις.\p"
	.string "Μάλιστα, τις προάλλες ένας TRAINER\n"
	.string "ονόματι {STR_VAR_1} αγόρασε {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "ΡΕΠΟΡΤΕΡ: Ο/η TRAINER αγόρασε\n"
	.string "{STR_VAR_3} {STR_VAR_2}; Αυτό είναι πολύ!\p"
	.string "Αν μου επιτρέπεται, ο/η {STR_VAR_1}\n"
	.string "μάλλον ετοιμάζεται για μεγάλο\l"
	.string "ταξίδι σε μακρινά μέρη.\p"
	.string "Για τα ταξίδια, το {STR_VAR_2} είναι\n"
	.string "τόσο σημαντικό!$"

SmartShopper_Text_RandomComment2::
	.string "ΡΕΠΟΡΤΕΡ: Μιλώντας για το αντικείμενο\n"
	.string "{STR_VAR_2}, κι εγώ αγόρασα {STR_VAR_3}\l"
	.string "από αυτά πρόσφατα.\p"
	.string "Άλλωστε, το {STR_VAR_2} είναι τέλειο!$"

SmartShopper_Text_RandomComment3::
	.string "ΡΕΠΟΡΤΕΡ: {STR_VAR_2}!;\n"
	.string "Και μάλιστα {STR_VAR_3} κομμάτια!;\p"
	.string "Δεν πίστευα πως θα υπήρχε κανείς\n"
	.string "να αγοράσει τόσα πολλά.\p"
	.string "Θεέ μου, εγώ μετά βίας μπορώ\n"
	.string "να πάρω ένα ή δύο τη φορά…$"

SmartShopper_Text_RandomComment4::
	.string "ΡΕΠΟΡΤΕΡ: Μια φορά αγόρασα\n"
	.string "τεράστια ποσότητα από {STR_VAR_2}.\p"
	.string "Αλλά αποδείχτηκαν πάρα πολλά.\n"
	.string "Στο τέλος το μετάνιωσα…\p"
	.string "Από τότε, αγοράζω αυστηρά μόνο\n"
	.string "ό,τι έχω πραγματικά ανάγκη…\p"
	.string "Ωχ!\p"
	.string "Δεν έχει νόημα να μιλάω για μένα!$"

SmartShopper_Text_SecondItem::
	.string "ΥΠΑΛΛΗΛΟΣ: Ο/η {STR_VAR_1} αγόρασε επίσης\n"
	.string "το αντικείμενο {STR_VAR_2} χονδρικώς, {STR_VAR_3} κομμάτια.\p"
	.string "ΡΕΠΟΡΤΕΡ: Ω, αυτό είναι έξυπνο.\n"
	.string "Το {STR_VAR_2} είναι επίσης πολύ καλό.$"

SmartShopper_Text_ThirdItem::
	.string "ΥΠΑΛΛΗΛΟΣ: Και ο/η TRAINER αγόρασε\n"
	.string "επίσης {STR_VAR_3} από το {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "ΥΠΑΛΛΗΛΟΣ: Επιπλέον, είχε έκπτωση.\n"
	.string "Αυτό θα πει έξυπνες αγορές.$"

SmartShopper_Text_OutroNormal::
	.string "ΡΕΠΟΡΤΕΡ: Χμ… Ο/η {STR_VAR_1} φαίνεται\n"
	.string "πολύ ικανός/ή στο να βρίσκει ευκαιρίες!\p"
	.string "Συνολικά, οι αγορές του/της ήταν…\p"
	.string "¥{STR_VAR_2}!;\n"
	.string "Τι απίστευτο ποσό!\p"
	.string "Ωχ! Τελείωσε ο χρόνος μας!\n"
	.string "Τα λέμε στην επόμενη εκπομπή!$"

SmartShopper_Text_IsVIP::
	.string "ΥΠΑΛΛΗΛΟΣ: Ο/η {STR_VAR_1} είναι VIP πελάτης,\n"
	.string "χωρίς καμία αμφιβολία.$"

SmartShopper_Text_ClerkMax::
	.string "Ας μιλήσουμε με τον υπάλληλο.\p"
	.string "Γεια σας! Πώς πάνε οι δουλειές;\p"
	.string "ΥΠΑΛΛΗΛΟΣ: Ω, κάνουμε απίστευτο\n"
	.string "τζίρο. Σχεδόν εξωπραγματικό.\p"
	.string "Πρόσφατα, ένας/μια TRAINER {STR_VAR_1}\n"
	.string "αγόρασε το {STR_VAR_2} σε τεράστια ποσότητα.\p"
	.string "Σχεδόν άδειασε όλο μας το\n"
	.string "απόθεμα σε {STR_VAR_2}.\p"
	.string "Ποτέ δεν φανταζόμουν πως κάποιος\n"
	.string "θα χρειαζόταν τόσα πολλά {STR_VAR_2}.\l"
	.string "Είναι απλά πρωτάκουστο!\p"
	.string "ΡΕΠΟΡΤΕΡ: Δηλαδή μιλάμε για\n"
	.string "100 ή 200 κομμάτια;\p"
	.string "ΥΠΑΛΛΗΛΟΣ: Ω, όχι, πολύ περισσότερα!\p"
	.string "ΡΕΠΟΡΤΕΡ: Θεέ μου!\n"
	.string "Ο/η {STR_VAR_1} πρέπει να είναι ειδικός πελάτης!\p"
	.string "ΥΠΑΛΛΗΛΟΣ: Ο/η {STR_VAR_1} είναι VIP πελάτης,\n"
	.string "χωρίς καμία αμφιβολία.$"

SmartShopper_Text_OutroMax::
	.string "ΡΕΠΟΡΤΕΡ: Χμ…\n"
	.string "Αυτό είναι εκπληκτικό.\p"
	.string "Αλλά γιατί να χρειάζεται ο/η TRAINER\n"
	.string "να αγοράσει τόσα πολλά;\p"
	.string "… …\p"
	.string "Το μυστήριο μεγαλώνει, αλλά αυτός\n"
	.string "είναι όλος ο χρόνος που έχουμε σήμερα.\l"
	.string "Τα λέμε στην επόμενη εκπομπή!\p"
	.string "Πάντως, ο/η {STR_VAR_1} είναι ένα αίνιγμα…$"

gTVWorldOfMastersText00::
	.string "Ο ΚΟΣΜΟΣ ΤΩΝ MASTERS\p"
	.string "Γεια σας, τηλεθεατές.\p"
	.string "Ίσως γνωρίζετε έναν/μια TRAINER\n"
	.string "ονόματι {STR_VAR_1}.\p"
	.string "Ο/η {STR_VAR_1} είναι διάσημος/η ως\n"
	.string "μάστερ στο να πιάνει POKéMON.\p"
	.string "Η αναζήτηση του/της βασίζεται\n"
	.string "εξολοκλήρου σε πεζοπορία.\p"
	.string "Σε μια αξέχαστη μέρα, έκανε\n"
	.string "περίπου {STR_VAR_2} βήματα.\p"
	.string "Τα POKéMON που πιάστηκαν εκείνη\n"
	.string "τη μέρα έφτασαν τα {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Αυτό το απίστευτο κατόρθωμα έγινε\n"
	.string "δυνατό λόγω της εμπιστοσύνης μεταξύ\l"
	.string "του/της TRAINER και του {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Ο/η μάστερ έπιασε το τελευταίο\n"
	.string "{STR_VAR_3} της μέρας κοντά στο {STR_VAR_2}.\p"
	.string "Αυτό το POKéMON προφανώς απολαμβάνει\n"
	.string "μια ειδική θέση ως κάτοχος ρεκόρ.\p"
	.string "Οι έμπειροι TRAINERS ας προσπαθήσουν\n"
	.string "να καταρρίψουν αυτό το ρεκόρ.\p"
	.string "Αυτά για σήμερα.\n"
	.string "Συντονιστείτε την επόμενη φορά.$"

gTVTodaysRivalTrainerText00::
	.string "Ο ΣΗΜΕΡΙΝΟΣ ΑΝΤΙΠΑΛΟΣ TRAINER!\p"
	.string "Γεια σας, συνάδελφοι POKéMON TRAINERS!\n"
	.string "Πώς είμαστε όλοι σήμερα;\p"
	.string "Σήμερα, όπως και κάθε άλλη μέρα,\n"
	.string "θα εξετάσουμε έναν από τους αντιπάλους!$"

gTVTodaysRivalTrainerText07::
	.string "Σήμερα ο αντίπαλος είναι ο/η {STR_VAR_1},\n"
	.string "που βρίσκεται κοντά στο/στη {STR_VAR_3}.\p"
	.string "Ο/η {STR_VAR_1} έχει καταγράψει μέχρι\n"
	.string "στιγμής {STR_VAR_2} POKéMON στο POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "Σήμερα ο αντίπαλος είναι ο/η {STR_VAR_1},\n"
	.string "που είναι στη SECRET BASE τώρα.\p"
	.string "Ο/η {STR_VAR_1} έχει καταγράψει μέχρι\n"
	.string "στιγμής {STR_VAR_2} POKéMON στο POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "Σήμερα ο αντίπαλος είναι ο/η {STR_VAR_1}.\p"
	.string "Μέχρι στιγμής, ο/η {STR_VAR_1} έχει\n"
	.string "καταγράψει {STR_VAR_2} POKéMON στο POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "Σήμερα ο αντίπαλος είναι ο/η {STR_VAR_1},\n"
	.string "που βρίσκεται στο φέρι μποτ τώρα.\p"
	.string "Ο/η {STR_VAR_1} έχει καταγράψει μέχρι\n"
	.string "στιγμής {STR_VAR_2} POKéMON στο POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Και πόσα BADGES έχει ο αντίπαλός μας;\n"
	.string "Ο αριθμός είναι {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Αλλά ο αντίπαλός μας δεν έχει\n"
	.string "αποκτήσει ούτε ένα BADGE ακόμη!$"

gTVTodaysRivalTrainerText03::
	.string "Ο αντίπαλός μας δεν έχει πάρει\n"
	.string "ούτε ένα BATTLE FRONTIER Symbol.$"

gTVTodaysRivalTrainerText04::
	.string "Ας δούμε πόσα BATTLE FRONTIER\n"
	.string "Symbols έχει ο αντίπαλός μας.\p"
	.string "Gold Symbols: {STR_VAR_1}!\n"
	.string "Silver Symbols: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Ο αντίπαλός μας έχει μαζέψει\n"
	.string "{STR_VAR_1} Battle Points στο FRONTIER.$"

gTVTodaysRivalTrainerText06::
	.string "Λοιπόν, πώς τα πάτε σε σύγκριση\n"
	.string "με τον/την {STR_VAR_1};\p"
	.string "Η περιπέτεια συνεχίζεται!\p"
	.string "Συνάδελφοι TRAINERS!\p"
	.string "Ας συνεχίσουμε όλοι μπροστά\n"
	.string "και ας προσπεράσουμε τους αντιπάλους!$"

TrendWatcher_Text_Intro::
	.string "DEWFORD TREND-WATCHER NETWORK!\p"
	.string "MC: Τι γίνεται;\n"
	.string "Θα μιλήσουμε ειλικρινά για ό,τι\l"
	.string "είναι στη μόδα στη DEWFORD.\p"
	.string "Καλεσμένος μας είναι αυτός ο παππούς\n"
	.string "που θεωρείται αυθεντία σε ό,τι\l"
	.string "έχει να κάνει με τη DEWFORD.\p"
	.string "Παππούς: Χαρά μου που είμαι εδώ.\p"
	.string "MC: Ας μπούμε κατευθείαν στο θέμα.\p"
	.string "Τι είναι αυτό που ξετρελαίνει\n"
	.string "τον κόσμο στη DEWFORD;\p"
	.string "Παππούς: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "λέτε;\p"
	.string "Παππούς: Όχι.\p"
	.string "Το {STR_VAR_1} {STR_VAR_2} δεν έγινε\n"
	.string "ποτέ της μόδας.\p"
	.string "Θέλετε να ακούσετε γι' αυτό;\p"
	.string "MC: Ε, όχι. Αυτό που θέλουμε να\n"
	.string "μάθουμε είναι τι είναι στη μόδα τώρα…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Παππούς: Το {STR_VAR_1} {STR_VAR_2}\n"
	.string "μου το έμαθε ο/η {STR_VAR_3}\l"
	.string "από τη LITTLEROOT ως μοντέρνο…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Παππούς: Το {STR_VAR_1} {STR_VAR_2}\n"
	.string "μου το έμαθε ο/η {STR_VAR_3}\l"
	.string "από τη LITTLEROOT ως μοντέρνο…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Αλλά ήταν εντελώς μάταιο.\p"
	.string "Φεστιβάλ {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Διαγωνισμός {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Προσπάθησα να το μάθω σε όλους\n"
	.string "όσο καλύτερα μπορούσα, αλλά…\p"
	.string "Ίσως το μέρος {STR_VAR_1} να μην\n"
	.string "ήταν το σωστό…\p"
	.string "MC: Ε, με συγχωρείτε, φίλε μου,\n"
	.string "πρέπει να μάθω τι είναι στη μόδα τώρα…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Παππούς: {STR_VAR_3}!\n"
	.string "Σε παρακαλώ, πες μου κάτι μεγαλύτερο\l"
	.string "από αυτό το {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Παππούς: {STR_VAR_3}!\n"
	.string "Σε παρακαλώ, πες μου κάτι μεγαλύτερο\l"
	.string "από αυτό το {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: …Ε… Αυτά είχαμε λοιπόν\n"
	.string "για όλους εσάς τους μοντέρνους εκεί έξω!\p"
	.string "Το {STR_VAR_1} {STR_VAR_2}… ε…\n"
	.string "Δεν έγινε ποτέ μόδα στη DEWFORD!\p"
	.string "Ο χρόνος μου τελείωσε. Τα λέμε!\p"
	.string "Παππούς: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "HOENN TREASURE INVESTIGATORS!\p"
	.string "Γεια σας, παρέα!\n"
	.string "Βρήκατε κανένα κρυφό αντικείμενο;\p"
	.string "Όπως πάντα, θα εξετάσουμε μαρτυρίες\n"
	.string "για κρυφά μυστικά από παντού!\p"
	.string "Ας αρχίσουμε με ένα γράμμα.\n"
	.string "Λέει: “Βρέθηκε {STR_VAR_1}!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Ουάου, πρέπει να το ψάξουμε αυτό!\n"
	.string "Ας σας το διαβάσω.\p"
	.string "…Αγαπητοί INVESTIGATORS,\n"
	.string "ελπίζω να είστε καλά.\p"
	.string "Πρόσφατα είδα τον/την {STR_VAR_2}\n"
	.string "κάπου κοντά στο/στη {STR_VAR_3}.\p"
	.string "Ο/η TRAINER βρήκε το αντικείμενο\n"
	.string "{STR_VAR_1}. Ζήλεψα πολύ.\p"
	.string "…Μπράβο, {STR_VAR_2}!\p"
	.string "Τηλεθεατές, ας σας παρακινήσει αυτό\n"
	.string "να ψάξετε με τα ITEMFINDERS σας!\p"
	.string "Θα περιμένω συναρπαστικά νέα\n"
	.string "από όλους σας!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Ουάου, πρέπει να το ψάξουμε αυτό!\n"
	.string "Ας σας το διαβάσω.\p"
	.string "…Αγαπητοί INVESTIGATORS,\n"
	.string "ελπίζω να είστε καλά.\p"
	.string "Πρόσφατα είδα τον/την {STR_VAR_2}\n"
	.string "σε ένα φέρι μποτ.\p"
	.string "Ο/η TRAINER βρήκε το αντικείμενο\n"
	.string "{STR_VAR_1}. Ζήλεψα πολύ.\p"
	.string "…Μπράβο, {STR_VAR_2}!\p"
	.string "Τηλεθεατές, ας σας παρακινήσει αυτό\n"
	.string "να ψάξετε με τα ITEMFINDERS σας!\p"
	.string "Θα περιμένω συναρπαστικά νέα\n"
	.string "από όλους σας!$"

gTVFindThatGamerText00::
	.string "FIND THAT GAMER!\p"
	.string "Γεια χαρά, gamers!\n"
	.string "Πώς πάνε τα slots για {STR_VAR_2};\p"
	.string "Όπως πάντα, ρίχνουμε το φως σε έναν\n"
	.string "σπάνιο TRAINER που επισκέφτηκε το\l"
	.string "GAME CORNER!\p"
	.string "Σήμερα, ο κορυφαίος παίκτης είναι…\n"
	.string "ο/η {STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "Ο/η {STR_VAR_1} έπαιξε {STR_VAR_2}\n"
	.string "κι έπιασε το σπάνιο {STR_VAR_3} COINS.\p"
	.string "“Όταν έρχεται ο/η {STR_VAR_1},\n"
	.string "πρέπει να έχουμε αρκετά COINS.”\p"
	.string "Αυτό ψιθυρίζουν οι υπάλληλοι του\n"
	.string "GAME CORNER όταν παίζει ο παίκτης μας!\p"
	.string "Τηλεθεατές, προσέξτε τα COINS σας\n"
	.string "όπως ο/η {STR_VAR_1} αν πάτε στο GAME\l"
	.string "CORNER για να παίξετε {STR_VAR_2}.\p"
	.string "Απευθείας από το GAME CORNER--\n"
	.string "εκεί που χτυπά η καρδιά της δράσης!\p"
	.string "Αυτά για σήμερα!$"

gTVFindThatGamerText02::
	.string "Ο/η {STR_VAR_1} έπαιξε {STR_VAR_2}\n"
	.string "και έχασε {STR_VAR_3} COINS.\p"
	.string "“Όταν έρχεται ο/η {STR_VAR_1},\n"
	.string "οι πωλήσεις COINS ανεβαίνουν.”\p"
	.string "Αυτό λένε οι υπάλληλοι του\n"
	.string "GAME CORNER όταν παίζει ο παίκτης μας!$"

gTVFindThatGamerText03::
	.string "Τηλεθεατές, προσέξτε τα COINS σας\n"
	.string "όπως ο/η {STR_VAR_1} αν πάτε στο GAME\l"
	.string "CORNER για να παίξετε {STR_VAR_2}.\p"
	.string "Απευθείας από το GAME CORNER--\n"
	.string "εκεί που χτυπά η καρδιά της δράσης!\p"
	.string "Αυτά για σήμερα!$"

gTVBreakingNewsText00::
	.string "BREAKING NEWS TV!$"

gTVBreakingNewsText01::
	.string "Σπάνιο {STR_VAR_2} πιάστηκε\n"
	.string "από τον/την {STR_VAR_1}!\p"
	.string "Είμαστε ζωντανά από την περιοχή\n"
	.string "γύρω από το/στη {STR_VAR_3}!\p"
	.string "Ο/η {STR_VAR_1} έπιασε με επιτυχία\n"
	.string "ένα σπάνιο {STR_VAR_2} νωρίτερα εδώ!$"

gTVBreakingNewsText02::
	.string "Όταν ο/η {STR_VAR_1} αντιμετώπισε το\n"
	.string "σπάνιο {STR_VAR_2}, έστειλε στη\l"
	.string "μάχη το POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Στη μάχη, ο αριθμός των POKé\n"
	.string "BALLS που έριξε ήταν {STR_VAR_1}.\p"
	.string "Τελικά, το σπάνιο POKéMON\n"
	.string "πιάστηκε με τη {STR_VAR_2} στο τέλος.$"

gTVBreakingNewsText04::
	.string "Εκείνη τη στιγμή, το/η {STR_VAR_2}\n"
	.string "αντηχούσε από τις κραυγές\l"
	.string "θριάμβου του/της {STR_VAR_1}.\p"
	.string "Ζηλεύω λίγο τον/την {STR_VAR_1}.\n"
	.string "Θα ήθελα να πανηγυρίσω κι εγώ.\p"
	.string "…Αυτά από την απευθείας σύνδεση\n"
	.string "με το χαρούμενο σκηνικό!$"

gTVBreakingNewsText05::
	.string "Αποτυχία του/της {STR_VAR_1} να\n"
	.string "πιάσει ένα σπάνιο {STR_VAR_2}!\p"
	.string "Είμαστε ζωντανά από την περιοχή\n"
	.string "γύρω από το/στη {STR_VAR_3}!\p"
	.string "Ήταν εδώ που ο/η {STR_VAR_1} απέτυχε\n"
	.string "να πιάσει ένα σπάνιο {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Όταν ο/η {STR_VAR_1} αντιμετώπισε το\n"
	.string "σπάνιο {STR_VAR_2}, έστειλε στη\l"
	.string "μάχη το POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "Ο/η TRAINER έβαλε το {STR_VAR_2}\n"
	.string "να χρησιμοποιήσει {STR_VAR_1}.\p"
	.string "Χωρίς να το θέλει όμως, έκανε\n"
	.string "το σπάνιο POKéMON να λιποθυμήσει…$"

gTVBreakingNewsText12::
	.string "Όμως, ο/η {STR_VAR_1} πανικοβλήθηκε\n"
	.string "στη θέα του σπάνιου {STR_VAR_2}.\p"
	.string "Μέσα στη σύγχυση, διέταξε το\n"
	.string "{STR_VAR_3} να επιτεθεί.\p"
	.string "Χωρίς να το θέλει όμως, έκανε\n"
	.string "το σπάνιο POKéMON να λιποθυμήσει.$"

gTVBreakingNewsText08::
	.string "Εκείνη τη στιγμή, το/η {STR_VAR_2}\n"
	.string "αντηχούσε από τις κραυγές\l"
	.string "απογοήτευσης του/της {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "Όμως, ο/η {STR_VAR_1} ξέμεινε από\n"
	.string "POKé BALLS.\p"
	.string "Έπρεπε να διακόψει τη μάχη\n"
	.string "με το σπάνιο {STR_VAR_2}.\p"
	.string "Εκείνη τη στιγμή, το/η {STR_VAR_3}\n"
	.string "αντηχούσε από τις κραυγές\l"
	.string "απογοήτευσης του/της {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "Όμως, το {STR_VAR_2} τράπηκε σε φυγή\n"
	.string "χωρίς καμία προειδοποίηση.\p"
	.string "Εκείνη τη στιγμή, το/η {STR_VAR_3}\n"
	.string "αντηχούσε από τις κραυγές\l"
	.string "απογοήτευσης του/της {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "Συμπονώ πραγματικά τον/την {STR_VAR_1}.\n"
	.string "Με κάνει να θέλω να φωνάξω κι εγώ.\p"
	.string "…Αυτά από την απευθείας σύνδεση\n"
	.string "με το μελαγχολικό σκηνικό!$"

gTVSecretBaseVisitText00::
	.string "Γεια σας, τηλεθεατές!\n"
	.string "Ώρα για άλλη μια\l"
	.string "ΕΠΙΣΚΕΨΗ ΣΕ SECRET BASE.\p"
	.string "Σήμερα, επισκεπτόμαστε τη SECRET\n"
	.string "BASE του/της {STR_VAR_1}.\p"
	.string "Πώς διακόσμησε ο/η {STR_VAR_1}\n"
	.string "τη SECRET BASE;\p"
	.string "Ας το ανακαλύψουμε!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Ω!\n"
	.string "Τι υπέροχο!\p"
	.string "Αυτό το/η {STR_VAR_2}…\n"
	.string "Δεν είναι αυτό που θα περίμενε\l"
	.string "κανείς να βρει εδώ!$"

gTVSecretBaseVisitText02::
	.string "Ω!\n"
	.string "Τι αξιοσημείωτο!\p"
	.string "Δεν υπάρχει ούτε ένα έπιπλο\n"
	.string "ή διακοσμητικό αντικείμενο!\p"
	.string "Οι κοινοί θνητοί δεν θα μπορούσαν\n"
	.string "να μιμηθούν αυτή τη δήλωση!\p"
	.string "Είναι απλό, αλλά ξεχειλίζει,\n"
	.string "ναι, ξεχειλίζει από αγριάδα!\p"
	.string "Σου βγάζω το καπέλο, {STR_VAR_1}.\n"
	.string "Μόνο εσύ θα το έκανες αυτό!$"

gTVSecretBaseVisitText03::
	.string "Ω! Κατάλαβα!\n"
	.string "Με απόλυτη σαφήνεια, το βλέπω!\p"
	.string "Αυτό το/η {STR_VAR_2} εδώ…\n"
	.string "Στέλνει ένα πολύ δυνατό μήνυμα!$"

gTVSecretBaseVisitText04::
	.string "Ω! Κατάλαβα!\n"
	.string "Με απόλυτη σαφήνεια, το βλέπω!\p"
	.string "Αυτός ο χώρος διατηρείται σκόπιμα\n"
	.string "άδειος από αντικείμενα!\p"
	.string "Στέλνει ένα πολύ δυνατό μήνυμα!$"

gTVSecretBaseVisitText05::
	.string "Ουάου!\p"
	.string "Ο συνδυασμός του/της {STR_VAR_2}\n"
	.string "με το/τη {STR_VAR_3}!\p"
	.string "Είναι ένας ονειρεμένος συνδυασμός\n"
	.string "αν υπήρξε ποτέ κάποιος!$"

gTVSecretBaseVisitText06::
	.string "Ουάου!\p"
	.string "Η τοποθέτηση αυτού του {STR_VAR_2}\n"
	.string "ακριβώς εδώ…\p"
	.string "Έχει μια παρουσία που γεμίζει\n"
	.string "ολόκληρη τη SECRET BASE!$"

gTVSecretBaseVisitText07::
	.string "Ουάου!\p"
	.string "Δεν υπάρχει τίποτα στημένο εδώ.\p"
	.string "Αυτός ο άδειος χώρος επηρεάζει\n"
	.string "ολόκληρη τη SECRET BASE.$"

gTVSecretBaseVisitText08::
	.string "Ω!\n"
	.string "Να ο/η {STR_VAR_1}!\l"
	.string "Ας προκαλέσουμε τον/την TRAINER!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Αχ…\n"
	.string "Πρέπει να το αναγνωρίσω στον/στη {STR_VAR_1}.\p"
	.string "Τα POKéMON του/της ήταν άξια\n"
	.string "για τον τίτλο του CHAMPION.\p"
	.string "Έδωσαν τρανή απόδειξη για το πόσο\n"
	.string "σκληρός TRAINER είναι ο/η {STR_VAR_1}.\p"
	.string "Το ότι το/η {STR_VAR_2} ήξερε\n"
	.string "την κίνηση {STR_VAR_3}…\p"
	.string "Δείχνει τι είδους TRAINER είναι\n"
	.string "ο/η {STR_VAR_1}.\p"
	.string "Σίγουρα, ήταν ένα καλό μάθημα!$"

gTVSecretBaseVisitText10::
	.string "Αμάν!\n"
	.string "Πρέπει να το αναγνωρίσω στον/στη {STR_VAR_1}.\p"
	.string "Τα POKéMON του/της ήταν\n"
	.string "τρομερά δυνατά!\p"
	.string "Έδωσαν τρανή απόδειξη της\n"
	.string "επιμονής του/της {STR_VAR_1} ως TRAINER.\p"
	.string "Το ότι το/η {STR_VAR_2} ήξερε\n"
	.string "την κίνηση {STR_VAR_3}…\p"
	.string "Δείχνει τι είδους TRAINER είναι\n"
	.string "ο/η {STR_VAR_1}.\p"
	.string "Σίγουρα, ήταν ένα καλό μάθημα!$"

gTVSecretBaseVisitText11::
	.string "Ουάου!\n"
	.string "Πρέπει να το αναγνωρίσω στον/στη {STR_VAR_1}.\p"
	.string "Τα POKéMON του/της ανατράφηκαν\n"
	.string "με πολύ ισορροπημένο τρόπο.\p"
	.string "Έδωσαν τρανή απόδειξη της\n"
	.string "προσοχής του/της {STR_VAR_1} ως TRAINER.\p"
	.string "Το ότι το/η {STR_VAR_2} ήξερε\n"
	.string "την κίνηση {STR_VAR_3}…\p"
	.string "Δείχνει τι είδους TRAINER είναι\n"
	.string "ο/η {STR_VAR_1}.\p"
	.string "Σίγουρα, ήταν ένα καλό μάθημα!$"

gTVSecretBaseVisitText12::
	.string "Μάλιστα!\n"
	.string "Πρέπει να το αναγνωρίσω στον/στη {STR_VAR_1}.\p"
	.string "Τα POKéMON του/της έδειξαν\n"
	.string "μεγάλη υπόσχεση για το μέλλον.\p"
	.string "Αντιπροσώπευαν τις ελπίδες\n"
	.string "και τα όνειρα του/της {STR_VAR_1}.\p"
	.string "Το ότι το/η {STR_VAR_2} ήξερε\n"
	.string "την κίνηση {STR_VAR_3}…\p"
	.string "Δείχνει τι είδους TRAINER είναι\n"
	.string "ο/η {STR_VAR_1}.\p"
	.string "Σίγουρα, ήταν ένα καλό μάθημα!$"

gTVSecretBaseVisitText13::
	.string "Πρέπει να πω, τι υπέροχη SECRET BASE\n"
	.string "που ήταν!\p"
	.string "Τηλεθεατές, αν έχετε την ευκαιρία,\n"
	.string "επισκεφτείτε τη SECRET BASE του/της {STR_VAR_1}.\p"
	.string "Μέχρι την επόμενη φορά, αντίο σας!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Είναι συναρπαστικό!\n"
	.string "Είναι δραματικό!\p"
	.string "Είναι το POKéMON LOTTERY\n"
	.string "WINNER FLASH REPORT!\p"
	.string "Γεια σας! Είμαστε ζωντανά από τη\n"
	.string "γωνιά του POKéMON LOTTERY στο\l"
	.string "ισόγειο του LILYCOVE\l"
	.string "DEPARTMENT STORE!\p"
	.string "Όπως πάντα συμβαίνει, άλλος ένας\n"
	.string "τυχερός TRAINER εμφανίστηκε σήμερα!\p"
	.string "Το όνομα αυτού του TRAINER…\n"
	.string "{STR_VAR_1}!\p"
	.string "Ο/η {STR_VAR_1} κέρδισε το {STR_VAR_2} βραβείο\n"
	.string "και πήρε σπίτι το/τη {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Συγχαρητήρια!\p"
	.string "Τηλεθεατές, μην κοιτάτε απλώς,\n"
	.string "μπείτε κι εσείς στη δράση!\p"
	.string "Όλοι εμείς στο LILYCOVE DEPARTMENT\n"
	.string "STORE ανυπομονούμε για την επίσκεψή σας!\p"
	.string "Αυτή ήταν μια ζωντανή εκπομπή από\n"
	.string "το LILYCOVE DEPARTMENT STORE, με τη\l"
	.string "μεγαλύτερη ποικιλία σε όλη τη HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "THE POKéMON BATTLE SEMINAR!\p"
	.string "Εξετάζουμε μάχες για να δούμε τι\n"
	.string "μαθήματα παίρνουμε από άλλους.\p"
	.string "Η σημερινή μελέτη είναι για τη\n"
	.string "μάχη του/της {STR_VAR_1}.\p"
	.string "Το {STR_VAR_2} του/της {STR_VAR_1}\n"
	.string "μονομαχούσε με ένα {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Και χρησιμοποίησε την κίνηση\n"
	.string "{STR_VAR_3} στο {STR_VAR_2}…\p"
	.string "Χμμ… {STR_VAR_1}!\n"
	.string "Αυτό είναι λάθος επιλογή!$"

gTVThePokemonBattleSeminarText02::
	.string "Εκτός από την καταδικασμένη κίνηση,\n"
	.string "το POKéMON του/της {STR_VAR_1} ήξερε$"

gTVThePokemonBattleSeminarText03::
	.string "τις κινήσεις {STR_VAR_1}, {STR_VAR_2},\n"
	.string "και {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "τις κινήσεις {STR_VAR_1} και\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "την κίνηση {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Λοιπόν, σε αυτή την κατάσταση,\n"
	.string "τι θα έπρεπε να χρησιμοποιήσει;\p"
	.string "… … … … … …\n"
	.string "Την κίνηση {STR_VAR_1}!\p"
	.string "Η κίνηση {STR_VAR_1} θα ήταν\n"
	.string "σαφώς καλύτερη από τη {STR_VAR_2}.\p"
	.string "Τηλεθεατές, σας προτρέπω να μάθετε\n"
	.string "από αυτό και να μάχεστε έξυπνα!\p"
	.string "Μέχρι την επόμενη φορά, αντίο!$"

gTVTrainerFanClubText00::
	.string "Όλοι μαζί τώρα!\n"
	.string "TRAINER FAN CLUB!\p"
	.string "MC: Πώς περνάτε όλοι;\n"
	.string "Σήμερα μαζέψαμε τους fans του/της\l"
	.string "υπέρ-δημοφιλούς TRAINER {STR_VAR_1}!\p"
	.string "FANS: Ουάααααααααα!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "MC: Λοιπόν όλοι!\n"
	.string "Πόσο σας αρέσει ο/η {STR_VAR_1};\p"
	.string "FANS: Αγαπάμε τον/την {STR_VAR_1}!\p"
	.string "MC: Τι αγαπάτε περισσότερο\n"
	.string "στον/στην {STR_VAR_1};$"

gTVTrainerFanClubText01::
	.string "FANS: Τον φοβερό τρόπο που πετάει\n"
	.string "POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: Το αξιολάτρευτο τρέξιμό του/της!$"

gTVTrainerFanClubText03::
	.string "FANS: Πώς γίνεται τόσο σκληρός/ή\n"
	.string "όταν τα πράγματα δυσκολεύουν!$"

gTVTrainerFanClubText04::
	.string "FANS: Τις γνώσεις του/της για\n"
	.string "τα POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: Την καλοσύνη του/της προς\n"
	.string "όλα τα POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: Την απίστευτη τεχνική του/της\n"
	.string "στην οδήγηση ποδηλάτου!$"

gTVTrainerFanClubText07::
	.string "FANS: Το εντυπωσιακό στυλ αγορών\n"
	.string "του/της!$"

gTVTrainerFanClubText08::
	.string "FANS: Το γοητευτικό στυλ ονοματοδοσίας\n"
	.string "POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: Το κομψό στυλ διακόσμησης\n"
	.string "της SECRET BASE!$"

gTVTrainerFanClubText10::
	.string "FANS: Τον τολμηρό τρόπο χρήσης TMs!$"

gTVTrainerFanClubText11::
	.string "MC: Όπως μόλις είδατε, ο/η {STR_VAR_1}\n"
	.string "είναι “φωτιά”! Πολύ καυτός/ή!\p"
	.string "Ανάμεσα στους FANS του/της {STR_VAR_1}\n"
	.string "υπάρχει ένα ειδικό σύνθημα!\p"
	.string "MC: Όταν λέω {STR_VAR_1},\n"
	.string "εσείς λέτε…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Σωστά, όταν κάποιος λέει,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Απαντήστε με, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Αυτό ακούγεται τόσο μοναδικά!\n"
	.string "Καταλαβαίνω γιατί γίνονται FANS\l"
	.string "του/της {STR_VAR_1}!\p"
	.string "Εσείς, μπροστά στην TV, ελάτε μαζί μας!\n"
	.string "Όλοι μαζί τώρα!\p"
	.string "MC: Όταν λέω {STR_VAR_1},\n"
	.string "εσείς λέτε…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Ευχαριστούμε που ήσασταν μαζί μας,\n"
	.string "όλοι εσείς οι τρελοί FANS του/της {STR_VAR_1}!\l"
	.string "Αυτή ήταν η εκπομπή! Τα λέμε!\p"
	.string "MC: Όταν λέω {STR_VAR_1},\n"
	.string "εσείς λέτε…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "SPOT THE CUTIES!\n"
	.string "POKéMON ME RIBBONS!\p"
	.string "Γεια σας, γλυκοί μου τηλεθεατές!\p"
	.string "Ξέρω πως θα συμφωνήσετε, αλλά ένα\n"
	.string "POKéMON με RIBBONS είναι θεϊκό!\p"
	.string "Σήμερα, θέλω να μοιραστώ μαζί σας\n"
	.string "ένα υπέροχο POKéMON που εντόπισα\l"
	.string "καθώς έκανα μια βόλτα στην πόλη.\p"
	.string "Το σημερινό πανέμορφο POKéMON\n"
	.string "είναι το {STR_VAR_2} του/της {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Ο αριθμός των RIBBONS που φοράει\n"
	.string "το {STR_VAR_2} είναι {STR_VAR_3}.\p"
	.string "Αυτό δείχνει πόσο πολύ ο/η {STR_VAR_1}\n"
	.string "λατρεύει αυτό το POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "Το {STR_VAR_2} φοράει ένα εκπληκτικό\n"
	.string "νούμερο {STR_VAR_3} RIBBONS!\p"
	.string "Αυτό λέει πολλά για την αφοσίωση\n"
	.string "του/της {STR_VAR_1} στο POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "Το {STR_VAR_2} φοράει το απίστευτο\n"
	.string "νούμερο {STR_VAR_3} RIBBONS!\p"
	.string "Δείχνει την απόλυτη αφοσίωση\n"
	.string "του/της {STR_VAR_1} ως συλλέκτη!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Ας ρίξουμε μια ματιά στα πολλά\n"
	.string "RIBBONS που φοράει το {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Το CHAMPION RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε μπαίνοντας\n"
	.string "στο HALL OF FAME.\p"
	.string "Αναδεικνύει πραγματικά τη γενναιότητα\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το CHAMP RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Το COOL RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε κερδίζοντας\n"
	.string "σε COOL CONTEST.\p"
	.string "Αναδεικνύει πραγματικά τη γοητεία\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το COOL RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Το BEAUTY RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε κερδίζοντας\n"
	.string "σε BEAUTY CONTEST.\p"
	.string "Αναδεικνύει πραγματικά την ομορφιά\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το BEAUTY RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Το CUTE RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε κερδίζοντας\n"
	.string "σε CUTE CONTEST.\p"
	.string "Αναδεικνύει πραγματικά τη χαριτωμενιά\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το CUTE RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Το SMART RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε κερδίζοντας\n"
	.string "σε SMART CONTEST.\p"
	.string "Αναδεικνύει πραγματικά την εξυπνάδα\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το SMART RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Το TOUGH RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε κερδίζοντας\n"
	.string "σε TOUGH CONTEST.\p"
	.string "Αναδεικνύει πραγματικά τη δυναμικότητα\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το TOUGH RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Το WINNING RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε για τα κατορθώματά\n"
	.string "του στο BATTLE TOWER.\p"
	.string "Αναδεικνύει πραγματικά τη δύναμη\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το WINNING RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Το VICTORY RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε για τα κατορθώματά\n"
	.string "του στο BATTLE TOWER.\p"
	.string "Αναδεικνύει την απίστευτη δύναμη\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το VICTORY RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Το ARTIST RIBBON είναι ιδιαίτερα\n"
	.string "ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε όταν έγινε\n"
	.string "το μοντέλο για έναν καλλιτέχνη.\p"
	.string "Αναδεικνύει τη γοητεία σταρ\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το ARTIST RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Το Hard Worker RIBBON είναι\n"
	.string "ιδιαίτερα ελκυστικό.\p"
	.string "Το {STR_VAR_2} το έλαβε επειδή είναι\n"
	.string "ένας εξαιρετικά εργατικός βοηθός.\p"
	.string "Αναδεικνύει την αποφασιστικότητα\n"
	.string "του {STR_VAR_2}.\p"
	.string "Το {STR_VAR_2} με το Hard Worker RIBBON!\n"
	.string "Ο συνδυασμός φυσάει!$"

TVSpotTheCuties_Text_Outro::
	.string "…Αχ…\p"
	.string "RIBBONS και POKéMON…\n"
	.string "Ταιριάζουν τόσο υπέροχα μαζί!\p"
	.string "Πριν λιποθυμήσω,\n"
	.string "σας αποχαιρετώ όλους!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Χαίρετε!\n"
	.string "Ώρα για το POKéMON NEWS.\p"
	.string "Έχουμε μερικά ευχάριστα νέα από\n"
	.string "το BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "SINGLE BATTLE ROOM\l"
	.string "του BATTLE TOWER.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "DOUBLE BATTLE ROOM\l"
	.string "του BATTLE TOWER.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "MULTI BATTLE ROOM\l"
	.string "του BATTLE TOWER.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "LINK MULTI BATTLE ROOM\l"
	.string "του BATTLE TOWER.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων πρωταθλημάτων\l"
	.string "στα SINGLE BATTLE Tournaments\l"
	.string "του BATTLE DOME.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων πρωταθλημάτων\l"
	.string "στα DOUBLE BATTLE Tournaments\l"
	.string "του BATTLE DOME.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "Battle Swap Single\l"
	.string "του BATTLE FACTORY.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "Battle Swap Double\l"
	.string "του BATTLE FACTORY.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε νέο\n"
	.string "ρεκόρ ολοκληρώνοντας {STR_VAR_2} δωμάτια\l"
	.string "στο Battle Choice\l"
	.string "του BATTLE PIKE.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στα\l"
	.string "Set KO Tournaments\l"
	.string "του BATTLE ARENA.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "SINGLE BATTLE HALL\l"
	.string "του BATTLE PALACE.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε ρεκόρ\n"
	.string "{STR_VAR_2} συνεχόμενων νικών στο\l"
	.string "DOUBLE BATTLE HALL\l"
	.string "του BATTLE PALACE.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Ο/η TRAINER {STR_VAR_1} έκανε νέο\n"
	.string "ρεκόρ ολοκληρώνοντας {STR_VAR_2} ορόφους\l"
	.string "στο Battle Quest\l"
	.string "του BATTLE PYRAMID.\p"
	.string "Συγχαρητήρια στον/στη {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Και στα τρία POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, και {STR_VAR_3}!\p"
	.string "Συγχαρητήρια για την κορυφαία\n"
	.string "επίδοσή σας!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Και στα δύο POKéMON, {STR_VAR_1}\n"
	.string "και {STR_VAR_2}!\p"
	.string "Συγχαρητήρια για την κορυφαία\n"
	.string "επίδοσή σας!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Και στα τέσσερα POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Και {STR_VAR_1}!\p"
	.string "Συγχαρητήρια για την κορυφαία\n"
	.string "επίδοσή σας!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Ας ελπίσουμε για περισσότερα ρεκόρ\n"
	.string "από τον/την {STR_VAR_1} και τα πιστά\l"
	.string "POKéMON του/της!\p"
	.string "Αυτά ήταν τα νέα στο POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "WHAT'S NO. 1 IN HOENN TODAY?\n"
	.string "Ναι, ήρθε πάλι αυτή η ώρα!\p"
	.string "Γεια σας! Δίνετε τον καλύτερό σας\n"
	.string "εαυτό σε ό,τι κι αν κάνετε;\p"
	.string "Ας ρίξουμε μια ματιά στον TRAINER\n"
	.string "που τα πήγε καλύτερα από όλους!\p"
	.string "Ο κορυφαίος TRAINER σήμερα είναι\n"
	.string "ο/η {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Σε μία μέρα, ο/η {STR_VAR_1} έπαιξε\n"
	.string "στα SLOTS του GAME CORNER {STR_VAR_2} φορές.\p"
	.string "Καθώς έπαιζε, ο/η {STR_VAR_1} ακούστηκε\n"
	.string "να ψιθυρίζει: “Για μένα, οι κύλινδροι\l"
	.string "ούτε καν γυρίζουν…”\l"
	.string "Δεν είναι πολύ ενδιαφέρον;$"

gTVWhatsNo1InHoennTodayText02::
	.string "Σε μία μέρα, ο/η {STR_VAR_1} έπαιξε\n"
	.string "ROULETTE στο GAME CORNER {STR_VAR_2} φορές.\p"
	.string "Καθώς έπαιζε, ο/η {STR_VAR_1} φώναξε:\n"
	.string "“Ας αποφασίσουν οι μπίλιες!”\p"
	.string "Τα μάτια του/της ήταν καρφωμένα\n"
	.string "και το πρόσωπο έδειχνε συγκέντρωση.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Σε μία μέρα, ο/η {STR_VAR_1} μονομάχησε\n"
	.string "με άγρια POKéMON {STR_VAR_2} φορές!\p"
	.string "Προφανώς, τα POKéMON του/της\n"
	.string "έχουν γίνει ασύγκριτα πιο δυνατά.\p"
	.string "Ανυπομονούν να παλέψουν παντού,\n"
	.string "οποτεδήποτε και με κάθε τρόπο!$"

gTVWhatsNo1InHoennTodayText04::
	.string "Σε μία μόνο μέρα, ο/η {STR_VAR_1}\n"
	.string "γύρισε το BERRY BLENDER {STR_VAR_2} φορές!\p"
	.string "Προς το τέλος, ακόμα και ο/η {STR_VAR_1}\n"
	.string "φαινόταν να ζαλίζεται.\p"
	.string "Ο/η TRAINER φαινόταν να παραπατάει\n"
	.string "σαν ένα SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "Σε μία μόνο μέρα, ο/η {STR_VAR_1}\n"
	.string "φύτεψε {STR_VAR_2} BERRIES!\p"
	.string "Ως αποτέλεσμα, τα ρούχα του/της\n"
	.string "έγιναν γεμάτα λάσπες.\p"
	.string "Εκεί που φύτεψε, αμέτρητα\n"
	.string "λουλούδια έχουν ανθίσει.\p"
	.string "Λένε πως αυτά τα λουλούδια ηρεμούν\n"
	.string "τις ψυχές των ανθρώπων.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Σε μία μόνο μέρα, ο/η {STR_VAR_1}\n"
	.string "μάζεψε {STR_VAR_2} BERRIES!\p"
	.string "Η τσάντα του/της γέμισε τόσο πολύ\n"
	.string "με BERRIES, που μετά ο/η TRAINER\l"
	.string "δυσκολευόταν να περπατήσει!$"

gTVWhatsNo1InHoennTodayText07::
	.string "Σε μία μόνο μέρα, ο/η {STR_VAR_1}\n"
	.string "συγκέντρωσε {STR_VAR_2} Battle Points!\p"
	.string "Αργότερα εθεάθη να παλεύει\n"
	.string "με την απόφαση να τα ανταλλάξει\l"
	.string "με ένα ωραίο αντικείμενο ή με μια\l"
	.string "κομψή διακόσμηση.\p"
	.string "Λέγεται πως χαμογελούσε πλατιά\n"
	.string "ενώ σκεφτόταν τις επιλογές.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Ω, αυτό κι αν είναι σπουδαίο!\p"
	.string "{STR_VAR_1}!\n"
	.string "Είσαι ο κορυφαίος TRAINER σήμερα!\p"
	.string "Τηλεθεατές, πάρτε κουράγιο από τον/την\n"
	.string "{STR_VAR_1}! Μπορείτε κι εσείς να είστε\l"
	.string "στο νούμερο 1 κάθε μέρα!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRET BASE SECRETS!\p"
	.string "Τι κάνουν οι TRAINERS στη μυστικότητα\n"
	.string "των SECRET BASES;\p"
	.string "Σήμερα ερευνούμε τη SECRET BASE\n"
	.string "του/της {STR_VAR_1}.\p"
	.string "Ωχ; Φαίνεται πως ο/η {STR_VAR_2}\n"
	.string "ήρθε για επίσκεψη.\p"
	.string "Ας ρίξουμε μια ματιά!\p"
	.string "Τι θα κάνει ο/η {STR_VAR_2};$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Τι θα κάνει ο/η {STR_VAR_2} μετά;$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Και τώρα, τι θα κάνει ο/η {STR_VAR_2};$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Στο τέλος, ο/η {STR_VAR_2} έκανε {STR_VAR_3} βήματα\n"
	.string "στη SECRET BASE του/της {STR_VAR_1}\l"
	.string "πριν αποχωρήσει.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Χμμ…\p"
	.string "Φαίνεται πως η SECRET BASE του/της\n"
	.string "{STR_VAR_1} δεν ενδιέφερε τον/την {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "Ο/η {STR_VAR_2} φαίνεται να απόλαυσε\n"
	.string "τη SECRET BASE του/της {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "Ο/η {STR_VAR_2} φαίνεται να έγινε\n"
	.string "μεγάλος fan της SECRET BASE\l"
	.string "του/της {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Ίσως και οι τηλεθεατές να θέλουν\n"
	.string "να δουν τη SECRET BASE του/της {STR_VAR_1}.\p"
	.string "Συντονιστείτε για μια άλλη\n"
	.string "SECRET BASE! Ευχαριστούμε!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Ο επισκέπτης σταμάτησε!\p"
	.string "Ο επισκέπτης δεν κινείται καθόλου!\p"
	.string "Ήταν η SECRET BASE του/της {STR_VAR_1}\n"
	.string "τόσο αδιάφορη;$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Ο επισκέπτης σταμάτησε!\p"
	.string "Ο επισκέπτης δεν κινείται καθόλου!\p"
	.string "Είναι από κούραση;\n"
	.string "Μήπως αποκαμώθηκε ο επισκέπτης;$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Ο επισκέπτης κάθισε σε μια καρέκλα!\n"
	.string "Ο επισκέπτης κάθισε!\p"
	.string "Δείτε αυτό το βλέμμα χαράς!\p"
	.string "Αυτή η καρέκλα πρέπει να είναι\n"
	.string "πολύ άνετη για τέτοια αντίδραση!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Ο επισκέπτης όρμησε σε ένα μπαλόνι!\p"
	.string "Έσκασε!\n"
	.string "Ω, θεέ μου, έκανε μπαμ!\p"
	.string "Ο επισκέπτης δείχνει ξαφνιασμένος\n"
	.string "από τον ξαφνικό θόρυβο!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Ο επισκέπτης μπήκε σε μια TENT!\p"
	.string "Ο επισκέπτης τρέχει γύρω-γύρω!\p"
	.string "Ω, ο επισκέπτης παιχνιδίζει!\p"
	.string "Ο επισκέπτης δείχνει έκπληκτος\n"
	.string "από το μέγεθος της TENT!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Ο επισκέπτης περιεργάζεται\n"
	.string "ένα φυτό σε γλάστρα!\p"
	.string "Ο επισκέπτης έχει παραδόξως\n"
	.string "ώριμο γούστο!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Ο επισκέπτης περιεργάζεται\n"
	.string "μια GOLD SHIELD!\p"
	.string "Τα μάτια του επισκέπτη δείχνουν\n"
	.string "να λάμπουν από θαυμασμό!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Ο επισκέπτης περιεργάζεται\n"
	.string "μια SILVER SHIELD!\p"
	.string "Ο επισκέπτης έχει γουρλώσει μάτια!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Ο επισκέπτης περιεργάζεται\n"
	.string "ένα GLASS ORNAMENT!\p"
	.string "Ω, όχι!\p"
	.string "Ο επισκέπτης το αγγίζει!\p"
	.string "Γεμίζει όλο με\n"
	.string "δακτυλικά αποτυπώματα…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Ο επισκέπτης βλέπει τηλεόραση!\p"
	.string "Φαίνεται πως έχουμε μεγάλο fan!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Ο επισκέπτης πάτησε μια MUD BALL!\p"
	.string "Ο επισκέπτης δείχνει κατενθουσιασμένος!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Ω;\p"
	.string "Ο επισκέπτης ψάχνει μες στην τσάντα\n"
	.string "του και ανακατεύει τα πράγματα!\p"
	.string "Ο επισκέπτης έβγαλε έξω\n"
	.string "ένα {STR_VAR_2}!\p"
	.string "Δείτε πώς χαμογελάει ο επισκέπτης\n"
	.string "καθώς κρατάει ψηλά το {STR_VAR_2}!\p"
	.string "Είναι σαν τηλεοπτική διαφήμιση!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Ο επισκέπτης αρπάζει ένα μαξιλάρι…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…και αρχίζει να το χτυπάει!\p"
	.string "Μήπως έχει πολύ άγχος ο επισκέπτης;$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…και το αγκαλιάζει σφιχτά!\p"
	.string "Μήπως νιώθει χαρούμενος ο επισκέπτης\n"
	.string "για κάτι;$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Ο επισκέπτης κουβεντιάζει\n"
	.string "με τον/την {STR_VAR_1}!\p"
	.string "Φαίνεται πως ετοιμάζονται\n"
	.string "να κάνουν μια μάχη!\p"
	.string "Και…\p"
	.string "Είναι ο επισκέπτης!\n"
	.string "Ο επισκέπτης νίκησε εκτός έδρας!\p"
	.string "Ο επισκέπτης κάνει\n"
	.string "έναν χορό νίκης!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Ο επισκέπτης κουβεντιάζει\n"
	.string "με τον/την {STR_VAR_1}!\p"
	.string "Φαίνεται πως ετοιμάζονται\n"
	.string "να κάνουν μια μάχη!\p"
	.string "Και…\p"
	.string "Νικητής είναι ο/η {STR_VAR_1}!\n"
	.string "Ο επισκέπτης έχασε!\p"
	.string "Ο επισκέπτης δείχνει απογοητευμένος!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Ο επισκέπτης κουβεντιάζει\n"
	.string "με τον/την {STR_VAR_1}!\p"
	.string "Φαίνεται πως ετοιμάζονται\n"
	.string "να κάνουν μια μάχη!\p"
	.string "Και…\p"
	.string "Όχι, ο επισκέπτης αρνήθηκε!\p"
	.string "Δεν θα γίνει μάχη τελικά!\p"
	.string "Μήπως ο/η {STR_VAR_1} φάνηκε\n"
	.string "απωθητικός/ή στον επισκέπτη;$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Ο επισκέπτης κοιτάζει επίμονα\n"
	.string "μια αφίσα!\p"
	.string "Άραγε του αρέσει η αφίσα;\p"
	.string "…Αλλά… Υπάρχει κάτι ανησυχητικό\n"
	.string "στο επίμονο βλέμμα του επισκέπτη.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Ο επισκέπτης πάτησε ένα NOTE MAT!\p"
	.string "…Χμμ…\n"
	.string "Έγραψε μια αστεία μελωδία!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Ο επισκέπτης κουβεντιάζει\n"
	.string "με τον/την {STR_VAR_1}!\p"
	.string "Φαίνεται πως ετοιμάζονται\n"
	.string "να κάνουν μια μάχη!\p"
	.string "Και…\p"
	.string "Είναι ισοπαλία!\n"
	.string "Κανένα αποτέλεσμα!\p"
	.string "Και οι δύο TRAINERS δείχνουν πολύ\n"
	.string "απογοητευμένοι!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Ο επισκέπτης πάτησε σε ένα\n"
	.string "SPIN MAT!\p"
	.string "Φαίνεται πως ο επισκέπτης ζαλίστηκε!\p"
	.string "Παραπατάει από δω κι από κει!\n"
	.string "Προσοχή!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Ο επισκέπτης πάει να αγγίξει\n"
	.string "ένα SAND ORNAMENT!\p"
	.string "Ω!\p"
	.string "Θρυμματίστηκε!\n"
	.string "Διαλύθηκε εντελώς!\p"
	.string "Ο επισκέπτης δείχνει ντροπιασμένος\n"
	.string "και ένοχος!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Ο επισκέπτης σκουπίζει ένα γραφείο\n"
	.string "με το δάχτυλό του!\p"
	.string "Προφανώς, ο επισκέπτης σιχαίνεται\n"
	.string "τη σκόνη!\p"
	.string "Ενδιαφέρεται παραδόξως πολύ\n"
	.string "για την καθαριότητα!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Ο επισκέπτης κοιτάζει ένα BRICK!\p"
	.string "Ίσως σκέφτεται το αντικείμενο\n"
	.string "που βρίσκεται πάνω στο BRICK.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Ο επισκέπτης περπατάει πάνω\n"
	.string "στη SOLID BOARD.\p"
	.string "Ο επισκέπτης κοιτάζει συνέχεια κάτω.\p"
	.string "Φαίνεται να είναι παραδόξως\n"
	.string "δειλός και προσεκτικός!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Ο επισκέπτης κοιτάζει επίμονα\n"
	.string "έναν FENCE!\p"
	.string "Μήπως του ήρθε μια νέα ιδέα\n"
	.string "για παγίδα στο μυαλό;$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Ο επισκέπτης πάτησε σε ένα\n"
	.string "GLITTER MAT!\p"
	.string "Ο επισκέπτης παίρνει διάφορες\n"
	.string "πόζες!\p"
	.string "Φαίνεται να φαντασιώνεται\n"
	.string "πως είναι είδωλο της ποπ!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Ο επισκέπτης κοιτάζει επίμονα\n"
	.string "ένα TIRE!\p"
	.string "Μήπως σκέφτεται τι είδους\n"
	.string "αυτοκίνητο θα το φορούσε;$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Ο επισκέπτης ανέβηκε σε ένα STAND!\p"
	.string "Κοιτάζει όλη τη BASE του/της\n"
	.string "{STR_VAR_1} από ψηλά!\p"
	.string "Και…\p"
	.string "Βγάζει έναν βρυχηθμό!\n"
	.string "Ο επισκέπτης βρυχάται!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Ο επισκέπτης όρμησε με το κεφάλι\n"
	.string "σε μια BREAKABLE DOOR!\p"
	.string "Και γελάει ξεκαρδιστικά!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Ο επισκέπτης μιλάει σε μια DOLL!\p"
	.string "…Είναι λιγάκι ανατριχιαστικό…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Ο επισκέπτης ανεβαίνει τη σκάλα\n"
	.string "μιας SLIDE!\p"
	.string "Και…\p"
	.string "Τσουλήθησε κάτω!\p"
	.string "Φαίνεται πως περνάει φανταστικά!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Ο επισκέπτης ανεβαίνει τη σκάλα\n"
	.string "μιας SLIDE!\p"
	.string "Και…\p"
	.string "Κατέβηκε πάλι πίσω\n"
	.string "από τη σκάλα!\p"
	.string "Μήπως κόρδωσε ξαφνικά;$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Ο επισκέπτης πάτησε σε ένα\n"
	.string "JUMP MAT!\p"
	.string "Πήδηξε μία φορά!\p"
	.string "Πήδηξε δύο φορές!\p"
	.string "Και προσγειώθηκε με επιτυχία!\p"
	.string "Ο επισκέπτης χειροκροτεί!\n"
	.string "Τι σόλο εμφάνιση!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: Λοιπόν, φίλοι μου!\n"
	.string "Πετάτε SAFARI BALLS, ε;\p"
	.string "Να είστε σίγουροι πως η SAFARI\n"
	.string "ZONE είναι γεμάτη POKéMON!\p"
	.string "Ας κάνουμε μια κουβεντούλα με\n"
	.string "αυτόν τον καλό SAFARI GUIDE!\p"
	.string "Λοιπόν, φίλε, πώς τα πηγαίνουν\n"
	.string "οι επισκέπτες TRAINERS;$"

gTVSafariFanClubText01::
	.string "GUIDE: Όλοι δείχνουν να προσπαθούν\n"
	.string "πολύ σκληρά.\p"
	.string "Ο/η {STR_VAR_1} τα πάει περίφημα.\p"
	.string "Φανταστείτε, ο/η {STR_VAR_1} έπιασε\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Ξέρει να χρησιμοποιεί {POKEBLOCK}S.\n"
	.string "Έβαλε {STR_VAR_2} εκείνη τη φορά.$"

gTVSafariFanClubText03::
	.string "Δεν χρησιμοποίησε ούτε ένα\n"
	.string "{POKEBLOCK}! Ούτε ένα!\p"
	.string "Αυτό θα πει πραγματικός ειδικός!$"

gTVSafariFanClubText04::
	.string "REPORTER: Αλήθεια ε;\p"
	.string "Φαίνεται πως ο/η φίλος/η μας {STR_VAR_1}\n"
	.string "είναι μεγάλος master του SAFARI!\p"
	.string "GUIDE: Ελπίζω να ξαναέρθει\n"
	.string "και να μας δείξει την τεχνική του/της.$"

gTVSafariFanClubText05::
	.string "GUIDE: Κανείς δεν φαίνεται να τα\n"
	.string "πηγαίνει πολύ καλά.\p"
	.string "Για τον/την {STR_VAR_1} ήταν δύσκολα.\p"
	.string "Φανταστείτε, κατάφερε να πιάσει\n"
	.string "μόνο {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE: Κανείς δεν φαίνεται να τα\n"
	.string "πηγαίνει πολύ καλά.\p"
	.string "Για τον/την {STR_VAR_1} ήταν δύσκολα.\p"
	.string "Φανταστείτε, δεν έπιασε ούτε\n"
	.string "ένα POKéMON. Ούτε ένα!$"

gTVSafariFanClubText07::
	.string "Χρησιμοποιεί πάντως {POKEBLOCK}S.\n"
	.string "Έβαλε {STR_VAR_2} εκείνη τη φορά.\p"
	.string "Αλλά, αχ, θα ήθελα να τα πάει\n"
	.string "λίγο καλύτερα σε αυτό.$"

gTVSafariFanClubText08::
	.string "Πιστεύω θα είχε καλύτερη τύχη\n"
	.string "με {POKEBLOCK}S, που δεν χρησιμοποίησε\l"
	.string "καθόλου εκείνη τη φορά.$"

gTVSafariFanClubText09::
	.string "REPORTER: Αλήθεια ε;\p"
	.string "Φαίνεται πως ο/η {STR_VAR_1}\n"
	.string "θέλει ακόμα εξάσκηση στο SAFARI.\p"
	.string "GUIDE: Ελπίζω να μας επισκέπτεται\n"
	.string "συχνά για να πάρει τον αέρα.$"

gTVSafariFanClubText10::
	.string "REPORTER: Πολύ σωστά!\n"
	.string "Οι προκλήσεις είναι σημαντικές!\p"
	.string "Τηλεθεατές, ελάτε στη SAFARI\n"
	.string "και δοκιμάστε τις δυνάμεις σας!\p"
	.string "Μέχρι την επόμενη φορά, αντίο!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "MC: Ευχαριστούμε που είστε μαζί μας!\p"
	.string "Είμαστε ζωντανά από τη σκηνή του\n"
	.string "{STR_VAR_1} που μόλις τελείωσε.\p"
	.string "Η αίθουσα είναι ακόμα γεμάτη με\n"
	.string "κοινό που δεν θέλει να φύγει.\p"
	.string "Θεατής: {STR_VAR_2}!\p"
	.string "Θεατής: {STR_VAR_3}!\p"
	.string "MC: Όπως ακούσατε, στον CONTEST\n"
	.string "νικητής αναδείχθηκε το POKéMON {STR_VAR_2}\l"
	.string "του/της {STR_VAR_3}.\p"
	.string "Θεατής: {STR_VAR_2}!\n"
	.string "Είσαι ο καλύτερος!\p"
	.string "Θεατής: {STR_VAR_3}!\n"
	.string "Έτσι μπράβο!\p"
	.string "MC: Ας ακούσουμε τι έχουν να πουν\n"
	.string "οι fans γι' αυτόν τον CONTEST.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Θεατής: Το {STR_VAR_2} ήταν πρώτο\n"
	.string "και στους δύο γύρους αξιολόγησης!\p"
	.string "Αυτό το {STR_VAR_2} θα συνεχίσει να νικά!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Θεατής: Το {STR_VAR_2} δεν πήγε\n"
	.string "καλά στον πρώτο γύρο, αλλά τα σάρωσε\l"
	.string "όλα στον δεύτερο γύρο!\p"
	.string "Ήταν μια θαυματουργή ανατροπή\n"
	.string "για αυτό το {STR_VAR_2}. Γιούπι!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Θεατής: Το {STR_VAR_2} έμεινε\n"
	.string "σταθερό και στους δύο γύρους.\p"
	.string "Ο/η {STR_VAR_3} και το {STR_VAR_2},\n"
	.string "δεν είναι κανένα τυχαίο δίδυμο!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Θεατής: Στο να δείχνει {STR_VAR_1},\n"
	.string "αυτό το {STR_VAR_2} ήταν εξαιρετικό.\p"
	.string "Ελπίζω όμως να κάνει καλύτερες\n"
	.string "παρουσιάσεις την επόμενη φορά.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Θεατής: Όταν το {STR_VAR_2} αγχώθηκε,\n"
	.string "δεν μπορούσα να σταματήσω να φωνάζω\l"
	.string "λόγια ενθάρρυνσης.\p"
	.string "Θέλω να πω σε αυτό το {STR_VAR_2},\n"
	.string "“Συγχαρητήρια!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Θεατής: Η παρουσίαση του {STR_VAR_2}\n"
	.string "ξάφνιασε ακόμα κι εμένα!\p"
	.string "{STR_VAR_2}, ήσουν φανταστικό!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Θεατής: Το combo appeal αυτού του\n"
	.string "{STR_VAR_2} ήταν εκπληκτικό!\p"
	.string "Με συγκλόνισε συθέμελα!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Θεατής: Η παρουσίαση του νικητή\n"
	.string "{STR_VAR_2} έκανε την καρδιά μου να χτυπά!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Ήσουν cool!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Ήσουν beautiful!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Ήσουν cute!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Ήσουν smart!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Ήσουν tough!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Θεατής: Η παρουσίαση του νικητή\n"
	.string "{STR_VAR_2} ακόμα μου κρατά την καρδιά!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Είσαι ο ορισμός του cool!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Είσαι το πιο όμορφο απ' όλα!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Είσαι απλά το πιο χαριτωμένο!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Είσαι το εξυπνότερο των έξυπνων!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Είσαι το πιο tough απ' όλα!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Θεατής: Ακόμη κι όταν το {STR_VAR_2}\n"
	.string "έκανε ένα διάλειμμα,\l"
	.string "δεν μπορούσα να πάρω τα μάτια μου.\p"
	.string "Με έχει συνεπάρει αυτό το {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Θεατής: Όταν το {STR_VAR_2}\n"
	.string "ξαφνιάστηκε από άλλο POKéMON,\l"
	.string "ήμουν έτοιμος/η να κλάψω.\p"
	.string "{STR_VAR_2}, έδειξες αντοχή!\n"
	.string "Έτσι μπράβο!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Θεατής: Ω…\n"
	.string "Το {STR_VAR_3} αυτού του {STR_VAR_2}!\l"
	.string "Το {STR_VAR_3} αυτού του {STR_VAR_2}!\l"
	.string "Το {STR_VAR_3} αυτού του {STR_VAR_2}!\l"
	.string "Πώς γίνεται να είναι τόσο υπέροχο;$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Λοιπόν, αυτά είχαμε. Ο χώρος\n"
	.string "είναι γεμάτος από fans του {STR_VAR_1}!\p"
	.string "Να πω επίσης πως ένα άλλο POKéMON,\n"
	.string "το {STR_VAR_3} του/της {STR_VAR_2}, \l"
	.string "μου τράβηξε την προσοχή.\p"
	.string "Το {STR_VAR_3} του/της {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Δεν έκανε ούτε μία παρουσίαση στον\n"
	.string "δεύτερο γύρο από τη νευρικότητα.\p"
	.string "Την επόμενη φορά, θα ήθελα να δω\n"
	.string "τον/την {STR_VAR_1} να κάνει έστω μία.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Ήρθε τελευταίο και στους δύο γύρους\n"
	.string "αξιολόγησης.\p"
	.string "Ελπίζω ο/η {STR_VAR_1} να εκπαιδεύσει\n"
	.string "αυτό το {STR_VAR_2} ξανά και να σβήσει\l"
	.string "την ντροπή αυτής της τελευταίας θέσης.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Δεν κατάφερε να εκμεταλλευτεί τον\n"
	.string "ενθουσιασμό του κοινού για να κάνει\l"
	.string "μια κατάλληλη παρουσίαση.\p"
	.string "Ελπίζουμε ο/η {STR_VAR_1} να μάθει πώς\n"
	.string "να νιώθει το κοινό και να ανεβάζει\l"
	.string "τον ενθουσιασμό του την επόμενη φορά.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Αν και βγήκε πρώτο στον αρχικό γύρο,\n"
	.string "οι παρουσιάσεις του στον δεύτερο\l"
	.string "γύρο δεν είχαν αποτέλεσμα.\p"
	.string "Υπέστη μια ταπεινωτική ήττα από\n"
	.string "ανατροπή.\p"
	.string "Είμαι σίγουρος/η πως ο/η {STR_VAR_1}\n"
	.string "μελετά πώς να κάνει καλύτερες appeal.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Το κοινό δεν ενθουσιάστηκε καθόλου με\n"
	.string "τις παρουσιάσεις του στον 2ο γύρο.\p"
	.string "Ελπίζουμε να σταματήσει να ανησυχεί\n"
	.string "για άλλα POKéMON και να εστιάσει\l"
	.string "περισσότερο στο να κερδίσει το κοινό.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Έχασε από το {STR_VAR_2} του/της\n"
	.string "{STR_VAR_1} για ελάχιστη διαφορά.\p"
	.string "Πρέπει να είναι σκληρό να φτάνεις\n"
	.string "τόσο κοντά στη νίκη και να χάνεις.\p"
	.string "Δεν θα παραξενευόμουν αν ο/η {STR_VAR_3}\n"
	.string "έκλαιγε για αυτό το αποτέλεσμα.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Απογοήτευσε τον JUDGE κάνοντας\n"
	.string "τις ίδιες παρουσιάσεις ξανά και ξανά.\p"
	.string "Είναι ασυγχώρητο λάθος σε CONTEST\n"
	.string "και το POKéMON το πλήρωσε ακριβά.\p"
	.string "Ο/η {STR_VAR_1} πρέπει να νιώθει\n"
	.string "τύψεις για αυτή τη θλιβερή εμφάνιση.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "Ο/η {STR_VAR_1} έκανε γενναία προσπάθεια,\n"
	.string "αλλά…\p"
	.string "Ήταν μάταιο, καθώς τερμάτισε τελευταίο.\p"
	.string "Ο/η {STR_VAR_1} πρέπει να μάθει από αυτή\n"
	.string "την ήττα για το μέλλον.$"

ContestLiveUpdates_Text_Outro::
	.string "Θα ήθελα να κλείσω την εκπομπή με τον\n"
	.string "συνηθισμένο χαιρετισμό στους νικητές.\p"
	.string "Αυτή τη φορά, στον/στην {STR_VAR_1} και\n"
	.string "στο {STR_VAR_2}!\p"
	.string "MC: Είναι όλοι έτοιμοι;\n"
	.string "Όλοι μαζί τώρα!\p"
	.string "Κοινό: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Συγχαρητήρια!\l"
	.string "Είστε οι νικητές του CONTEST!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON BATTLE UPDATE!”\p"
	.string "Σας μεταφέρουμε τα αποτελέσματα των\n"
	.string "POKéMON battles μόλις καταφτάνουν!$"

gTVPokemonBattleUpdateText01::
	.string "Οι TRAINERS {STR_VAR_1} και\n"
	.string "{STR_VAR_2} ήρθαν αντιμέτωποι σε\l"
	.string "μια {STR_VAR_3} BATTLE.\p"
	.string "Η μάχη έληξε με νίκη του/της\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Στη μάχη, το {STR_VAR_2} του/της\n"
	.string "{STR_VAR_1} ήταν μια τρομερή δύναμη\l"
	.string "χρησιμοποιώντας {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "Το {STR_VAR_2} του/της {STR_VAR_1}\n"
	.string "είχε μια αδύναμη εμφάνιση.$"

gTVPokemonBattleUpdateText04::
	.string "Συγχαρητήρια για τη νίκη σου,\n"
	.string "{STR_VAR_1}!\p"
	.string "Και για τον ηττημένο {STR_VAR_2},\n"
	.string "ελπίζουμε σε καλύτερο αποτέλεσμα!\p"
	.string "Εδώ ολοκληρώνεται το επεισόδιο του\n"
	.string "“POKéMON BATTLE UPDATE!”$"

gTVPokemonBattleUpdateText05::
	.string "Οι ομάδες των TRAINERS {STR_VAR_1} και\n"
	.string "{STR_VAR_2} βρέθηκαν σε MULTI BATTLE.\p"
	.string "Αυτή η αναμέτρηση έληξε με νίκη\n"
	.string "της ομάδας του/της {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Στη μάχη, το {STR_VAR_2} στην ομάδα\n"
	.string "του/της {STR_VAR_1} ήταν μια τρομερή\l"
	.string "δύναμη χρησιμοποιώντας {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "Η αδύναμη εμφάνιση του {STR_VAR_3}\n"
	.string "στην ομάδα του/της {STR_VAR_2} κόστισε.\p"
	.string "Συγχαρητήρια στην ομάδα σου\n"
	.string "για τη νίκη, {STR_VAR_1}!\p"
	.string "Όσο για την ηττημένη ομάδα,\n"
	.string "ελπίζουμε σε καλύτερο αποτέλεσμα!\p"
	.string "Εδώ ολοκληρώνεται το επεισόδιο του\n"
	.string "“POKéMON BATTLE UPDATE!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Ω! Μόλις εντοπίσαμε έναν\n"
	.string "σκληροτράχηλο TRAINER εδώ πέρα!\p"
	.string "Ωραία, ξεκίνα την κάμερα!\n"
	.string "Ας πάρουμε αυτή τη συνέντευξη.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Ω! Είσαι ο/η {PLAYER}! Γεια!\n"
	.string "Μας θυμάσαι από την προηγούμενη φορά;\p"
	.string "Μπορείς να μας δείξεις πόσο πιο\n"
	.string "δυνατός/ή έγινες; Πάμε για συνέντευξη!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Τα μάτια μου δεν με γέλασαν!\n"
	.string "Ανακάλυψα έναν απίστευτο TRAINER!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Φανταστικά! Φανταστικά!\n"
	.string "Ποιος/α είσαι;!\p"
	.string "Ήξερα ότι θα βρίσκαμε κάτι σπουδαίο\n"
	.string "όταν σε εντοπίσαμε!\p"
	.string "Ω, ας εξηγήσω. Ταξιδεύουμε παντού\n"
	.string "παίρνοντας συνεντεύξεις από TRAINERS.\p"
	.string "Λοιπόν, θα μας αφιερώσεις λίγο χρόνο\n"
	.string "για μια συνέντευξη;$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Θυμάσαι; Αυτό μας είπες ως την\n"
	.string "ατάκα της νίκης σου την προηγούμενη.\p"
	.string "Δεν ξεχνώ ποτέ τέτοια πράγματα!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Την προηγούμενη φορά μας νίκησες\n"
	.string "πριν προλάβουμε να προετοιμαστούμε…\p"
	.string "Τι λες λοιπόν;\n"
	.string "Θέλεις να σου πάρουμε συνέντευξη πάλι;$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Την προηγούμενη φορά, δεν πετάξες\n"
	.string "μια POKé BALL πάνω μας;\p"
	.string "Πάθαμε σοκ! Και το είπαμε σε όλους,\n"
	.string "μα σε όλους, για αυτό!\p"
	.string "Τι λες λοιπόν;\n"
	.string "Θέλεις να σου πάρουμε συνέντευξη πάλι;$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Την προηγούμενη φορά, η ικανότητά\n"
	.string "σου στα items μας αποτελείωσε.\p"
	.string "Τι λες λοιπόν;\n"
	.string "Θέλεις να σου πάρουμε συνέντευξη πάλι;$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Την προηγούμενη φορά, καταφέραμε\n"
	.string "να σταθούμε αξιοπρεπώς.\p"
	.string "Τι λες λοιπόν;\n"
	.string "Θέλεις να σου πάρουμε συνέντευξη πάλι;$"

GabbyAndTy_Text_InterviewAgain:
	.string "Τι λες λοιπόν;\n"
	.string "Θέλεις να σου πάρουμε συνέντευξη πάλι;$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Αλήθεια;!\n"
	.string "Ευχαριστούμε!\p"
	.string "Θέλω να περιγράψεις τα συναισθήματά\n"
	.string "σου για τη μάχη μας, αλλά σύντομα\l"
	.string "και περιεκτικά. Εμπρός!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Μμμ, ναι!\n"
	.string "Αυτό είναι το τέλειο κλείσιμο!\p"
	.string "Έχω την αίσθηση πως αυτό θα κάνει\n"
	.string "μια υπέροχη τηλεοπτική εκπομπή.\p"
	.string "Υπάρχει πιθανότητα να το παίξουν\n"
	.string "στην TV, οπότε έχε το νου σου!\p"
	.string "Ωραία!\n"
	.string "Θα τα ξαναπούμε!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Ω…\p"
	.string "Εντάξει, αλλά μην τα παρατάς!\n"
	.string "Θα έχουμε το νου μας για σένα!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Θα έχουμε το νου μας\n"
	.string "για σένα!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Υπάρχει κανένας δυνατός\n"
	.string "TRAINER με πολλά POKéMON;$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Πω πω, είσαι απίστευτος/η!\p"
	.string "Έχεις γίνει πολύ πιο δυνατός/η\n"
	.string "από την προηγούμενη φορά.\p"
	.string "Είχαμε δίκιο για σένα όταν σε\n"
	.string "ξεχωρίσαμε ως έναν καλό TRAINER.\p"
	.string "Τι λες λοιπόν;\n"
	.string "Θέλεις να μας δώσεις μια συνέντευξη\l"
	.string "αυτή τη φορά;$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Ήταν μια έντονη μάχη!\n"
	.string "Τα κατέγραψες όλα αυτά;$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Για δες εδώ! Ένας δυνατός\n"
	.string "TRAINER εδώ πέρα, από όλα τα μέρη!\l"
	.string "Η κάμερα γράφει!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Για δες εδώ!\n"
	.string "Σε θυμάμαι!\p"
	.string "Θα καταγράψω όλη τη μάχη\n"
	.string "σε αυτή την κάμερα!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Είσαι ταλέντο!\n"
	.string "Έχω μερικά τέλεια πλάνα εδώ πέρα!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Έχεις μόνο ένα POKéMON;\n"
	.string "Αυτό είναι όλο;\p"
	.string "Αν είχες περισσότερα POKéMON,\n"
	.string "θα είχαμε καλύτερο υλικό, αλλά…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Ναι, σίγουρα βρήκαμε καλό TRAINER.\n"
	.string "Αυτό είναι μεγάλο αποκλειστικό!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Ναι, τα έχω όλα.\n"
	.string "Όλη η μάχη είναι στην κάμερα.$"

gTVInSearchOfTrainersText00::
	.string "ΑΝΑΖΗΤΩΝΤΑΣ TRAINERS…\p"
	.string "GABBY: Γεια σας! Σήμερα επισκέπτομαι\n"
	.string "μια περιοχή κοντά στο/στη {STR_VAR_1}.\p"
	.string "Προσπαθούμε να εντοπίσουμε μερικά\n"
	.string "νέα υποσχόμενα ταλέντα.\p"
	.string "Σήμερα, στρέψαμε τον φακό μας\n"
	.string "στον/στην TRAINER {PLAYER}.\p"
	.string "Κάτι σε αυτόν/αυτή τον/την TRAINER\n"
	.string "μας κίνησε ιδιαίτερα την προσοχή.$"

gTVInSearchOfTrainersText01::
	.string "Έχουμε μονομαχήσει με τον/την {PLAYER}\n"
	.string "στο παρελθόν, αλλά μπορούμε να\l"
	.string "εγγυηθούμε πως έχει βελτιωθεί πολύ.\p"
	.string "Ήξερα πως πρόκειται για κάτι\n"
	.string "ξεχωριστό όταν τον/την είδαμε!$"

gTVInSearchOfTrainersText02::
	.string "Ο καλύτερος τρόπος για να δεις\n"
	.string "πόσο δυνατός είναι ένας TRAINER…\p"
	.string "Λοιπόν, ο πιο γρήγορος είναι η μάχη.\n"
	.string "Και έτσι ξεκινήσαμε την έρευνα!\p"
	.string "… …\p"
	.string "Κάπως έτσι καταλήξαμε να παλεύουμε\n"
	.string "με τον/την {PLAYER}.\p"
	.string "Με μια σαρωτική εμφάνιση,\n"
	.string "μας ισοπέδωσε εντελώς!\p"
	.string "Ο/η {PLAYER} είναι τρομερά δυνατός/ή…\p"
	.string "Ορίστε οι εντυπώσεις μας μετά τη\n"
	.string "μάχη με τον/την TRAINER μας.$"

gTVInSearchOfTrainersText03::
	.string "Ο συνδυασμός του/της {STR_VAR_1} και\n"
	.string "του/της {STR_VAR_3} ήταν θεϊκός!\p"
	.string "Το θέαμά τους--{STR_VAR_1} και\n"
	.string "{STR_VAR_3}--να αλληλουποστηρίζονται\l"
	.string "ανιδιοτελώς μες στη μάχη…\p"
	.string "Ήταν ένα υπέροχο θέαμα!\p"
	.string "Το {STR_VAR_2} ήταν η κίνηση που\n"
	.string "έκανε τελευταία στη μάχη μας.\p"
	.string "Αυτή η κίνηση είναι σημάδι φιλίας\n"
	.string "μεταξύ {STR_VAR_1} και {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…Έχασα την αυτοπεποίθησή μου\n"
	.string "μετά από αυτή τη συνάντηση.\p"
	.string "Μας νίκησε πριν καν προλάβουμε\n"
	.string "να κάνουμε έστω μία επίθεση.\l"
	.string "Ωωω… Κλάψ…\p"
	.string "Παρόλα αυτά, οι μάχες του/της {PLAYER}\n"
	.string "αξίζουν πραγματικά να τις δείτε.\p"
	.string "Συνιστώ σε σίγουρους TRAINERS\n"
	.string "να προκαλέσουν τον/την {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Ένα πράγμα έχω μόνο να πω.\n"
	.string "Μην τολμήσετε να πετάξετε\l"
	.string "POKé BALL σε μάχη TRAINER!\p"
	.string "Ο/η {PLAYER} είναι σίγουρα δυνατός/ή\n"
	.string "αλλά δεν ξέρει τους βασικούς κανόνες.\p"
	.string "Προς το κοινό μας, έχω μια παράκληση.\p"
	.string "Αν δείτε τον/την {PLAYER},\n"
	.string "σας παρακαλώ κάντε του/της σύσταση!$"

gTVInSearchOfTrainersText06::
	.string "Ο/η {PLAYER} είναι ικανός/ή στο να\n"
	.string "διαβάζει τις κινήσεις του αντιπάλου.\p"
	.string "Ο συγχρονισμός στη χρήση των items\n"
	.string "ήταν απίστευτα αποτελεσματικός!$"

gTVInSearchOfTrainersText07::
	.string "Ειλικρινά, πίστευα πως\n"
	.string "μπορεί να ήμουν και αρκετά καλός/ή.\p"
	.string "Αν και χάσαμε στο τέλος,\n"
	.string "δώσαμε μια σκληρή μάχη.\p"
	.string "Αλλά αν δυσκολεύεσαι μαζί μου,\n"
	.string "έχεις δρόμο ακόμα, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Μετά τη μάχη, ζητήσαμε από τον/την\n"
	.string "{PLAYER} μια σύντομη δήλωση.\p"
	.string "Απάντησε, “{STR_VAR_1}.”\p"
	.string "Τα POKéMON του/της {PLAYER},\n"
	.string "τα {STR_VAR_2} και {STR_VAR_3}…\l"
	.string "Και το “{STR_VAR_1}”…\p"
	.string "Μμμ! Αυτό είναι βαθύ! Κρύβει\n"
	.string "μεγάλη σημασία αυτή η δήλωση!\p"
	.string "Δεν είναι έκπληξη--ένας καλός\n"
	.string "TRAINER έχει πάντα σοφά λόγια να πει.\p"
	.string "Αυτά για σήμερα!\n"
	.string "Θα τα ξαναπούμε στην επόμενη εκπομπή!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "MC: Με συγχωρείτε για τη διακοπή\n"
	.string "και ευχαριστούμε που είστε μαζί μας!\p"
	.string "Σας μεταδίδουμε ζωντανά από\n"
	.string "τη σκηνή ενός {STR_VAR_1}\l"
	.string "που μόλις ολοκληρώθηκε!\p"
	.string "Θεατές: ?!!!!\p"
	.string "MC: Ω! Φαίνεται πως οι συμμετέχοντες\n"
	.string "του CONTEST έρχονται προς τα εδώ!\p"
	.string "Θα προσπαθήσω να πάρω μια αυθόρμητη\n"
	.string "συνέντευξη για εσάς στο σπίτι!\p"
	.string "Θεατές: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: Με συγχωρείτε!\n"
	.string "Ευχαριστούμε που είστε μαζί μας!\p"
	.string "Να σας συγχαρώ για τη νίκη σας;\p"
	.string "Ποιο ήταν το κλειδί για τη σημερινή\n"
	.string "εκπληκτική σας επικράτηση;\p"
	.string "BEAUTY: Δώσαμε τον καλύτερο εαυτό\n"
	.string "μας σήμερα, το {STR_VAR_2} μου κι εγώ!\p"
	.string "Αλλά σίγουρα δεν θα τα καταφέρναμε\n"
	.string "χωρίς όλη τη βοήθεια που είχαμε\l"
	.string "πριν από τον CONTEST!\p"
	.string "MC: Έχετε κάποιον ξεχωριστό\n"
	.string "να μοιραστείτε τη χαρά σας;\l"
	.string "Ας το ακούσουμε ζωντανά!\p"
	.string "BEAUTY: Εσύ εκεί έξω!\p"
	.string "{STR_VAR_3}! Βλέπεις;\n"
	.string "Τα καταφέραμε!\l"
	.string "Σε ευχαριστώ!$"

ContestLadyShow_Text_Lost::
	.string "MC: Με συγχωρείτε!\n"
	.string "Ευχαριστούμε που είστε μαζί μας!\p"
	.string "Πρέπει να είστε απογοητευμένη.\n"
	.string "Έχετε κάποιο σχόλιο;\p"
	.string "BEAUTY: Είναι θλιβερό…\n"
	.string "Το {STR_VAR_2} μου κι εγώ, προσπαθήσαμε…\p"
	.string "Αλλά νιώθω πως απογοήτευσα όλους\n"
	.string "όσους μας υποστήριξαν σε αυτό.\p"
	.string "MC: Δεν θέλω να το πω, αλλά τα\n"
	.string "χρώματα του POKéMON υστερούν λίγο.\p"
	.string "BEAUTY: {STR_VAR_3}, λυπάμαι πολύ…\n"
	.string "Θα πάω καλύτερα την επόμενη φορά…\l"
	.string "…Σνιφ… Ουάάάά!\p"
	.string "Θεατές: Το είδατε αυτό;\n"
	.string "Το καημένο το κορίτσι!\p"
	.string "MC: Ωχ… Ωχ…\p"
	.string "Ε… Αυτός είναι όλος ο χρόνος μας!\n"
	.string "Ευχαριστούμε που μας παρακολουθήσατε!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Με συγχωρείτε!\n"
	.string "Ευχαριστούμε που είστε μαζί μας!\p"
	.string "Πώς πήγε η εμφάνισή σας;\p"
	.string "BEAUTY: Τίποτα δεν πήγε δεξιά…\n"
	.string "Για κάποιο λόγο, το {STR_VAR_2} μου\l"
	.string "δεν μπόρεσε να κερδίσει δημοτικότητα.\p"
	.string "MC: Δεν θέλω να το πω, αλλά τα\n"
	.string "χρώματα του POKéMON υστερούν λίγο.\p"
	.string "BEAUTY: … … … … … …\n"
	.string "…Σνιφ… Ουάάάά!\p"
	.string "Θεατές: Το είδατε αυτό;\n"
	.string "Το καημένο το κορίτσι!\p"
	.string "MC: Ωχ… Ωχ…\p"
	.string "Ε… Αυτός είναι όλος ο χρόνος μας!\n"
	.string "Ευχαριστούμε που μας παρακολουθήσατε!$"


