PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Ο NORMAN έγινε ο νέος GYM LEADER\n"
	.string "της πόλης μας.\p"
	.string "Νομίζω ότι φώναξε την οικογένειά\n"
	.string "του από κάπου πολύ μακριά.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Πάλεψα με τον NORMAN μια φορά, \n"
	.string "αλλά, ουφ, ήταν πολύ δυνατός.\p"
	.string "Πώς να το θέσω;\p"
	.string "Απλά ένιωσα ότι εκείνος ζει\n"
	.string "για τα POKéMON.$"

