OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Όταν ξεκινά μια POKéMON μάχη, αυτό \n"
	.string "που είναι αριστερά στη λίστα \l"
	.string "βγαίνει πρώτο.\p"
	.string "Έτσι, όταν αποκτήσεις περισσότερα \n"
	.string "POKéMON στην ομάδα σου, δοκίμασε \l"
	.string "ν' αλλάξεις τη σειρά των POKéMON \l"
	.string "σου.\p"
	.string "Θα μπορούσε να σου δώσει πλεονέκτημα.$"

