Route110_TrickHousePuzzle6_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_TrickHousePuzzle6_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route110_TrickHousePuzzle6_OnWarp
	.byte 0

Route110_TrickHousePuzzle6_OnTransition:
	special RotatingGate_InitPuzzle
	end

Route110_TrickHousePuzzle6_OnWarp:
	map_script_2 VAR_TEMP_0, VAR_TEMP_0, Route110_TrickHousePuzzle6_EventScript_InitPuzzle
	.2byte 0

@ NOTE: This rotating gate puzzle makes use of VAR_TEMP_0 - VAR_TEMP_5
Route110_TrickHousePuzzle6_EventScript_InitPuzzle::
	special RotatingGate_InitPuzzleAndGraphics
	end

Route110_TrickHousePuzzle6_EventScript_Scroll::
	lockall
	goto_if_eq VAR_TRICK_HOUSE_PUZZLE_6_STATE, 0, Route110_TrickHousePuzzle6_EventScript_FoundScroll
	goto Route110_TrickHousePuzzle_EventScript_ReadScrollAgain
	end

Route110_TrickHousePuzzle6_EventScript_FoundScroll::
	setvar VAR_TRICK_HOUSE_PUZZLE_6_STATE, 1
	goto Route110_TrickHousePuzzle_EventScript_FoundScroll
	end

Route110_TrickHousePuzzle6_EventScript_Sophia::
	trainerbattle_single TRAINER_SOPHIA, Route110_TrickHousePuzzle6_Text_SophiaIntro, Route110_TrickHousePuzzle6_Text_SophiaDefeat
	msgbox Route110_TrickHousePuzzle6_Text_SophiaPostBattle, MSGBOX_AUTOCLOSE
	end

Route110_TrickHousePuzzle6_EventScript_Benny::
	trainerbattle_single TRAINER_BENNY, Route110_TrickHousePuzzle6_Text_BennyIntro, Route110_TrickHousePuzzle6_Text_BennyDefeat
	msgbox Route110_TrickHousePuzzle6_Text_BennyPostBattle, MSGBOX_AUTOCLOSE
	end

Route110_TrickHousePuzzle6_EventScript_Sebastian::
	trainerbattle_single TRAINER_SEBASTIAN, Route110_TrickHousePuzzle6_Text_SebastianIntro, Route110_TrickHousePuzzle6_Text_SebastianDefeat
	msgbox Route110_TrickHousePuzzle6_Text_SebastianPostBattle, MSGBOX_AUTOCLOSE
	end

Route110_TrickHousePuzzle6_Text_WroteSecretCodeLockOpened:
	.string "Το {PLAYER} έγραψε τον μυστικό\n"
	.string "κωδικό στην πόρτα.\p"
	.string "“Ο TRICK MASTER είναι η ζωή μου.”\n"
	.string "… … … … … … … …\p"
	.string "Η κλειδαριά άνοιξε!$"

Route110_TrickHousePuzzle6_Text_SophiaIntro:
	.string "Όταν άκουσα ότι υπάρχει ένα\n"
	.string "περίεργο σπίτι, ήθελα να \l"
	.string "το ελέγξω.$"

Route110_TrickHousePuzzle6_Text_SophiaDefeat:
	.string "Ανακάλυψα ένα δυνατό TRAINER!$"

Route110_TrickHousePuzzle6_Text_SophiaPostBattle:
	.string "Σίγουρα περνάω καλά \n"
	.string "εξερευνώντας αυτό το μέρος.\p"
	.string "Είναι μια πρόκληση που νομίζω\n"
	.string "ότι αξίζει να επαναλάβεις!$"

Route110_TrickHousePuzzle6_Text_BennyIntro:
	.string "Ίσως θα μπορούσα να κάνω το \n"
	.string "POKéMON-ΠΟΥΛΙ μου να \l"
	.string "πετάξει πάνω από τον τοίχο…$"

Route110_TrickHousePuzzle6_Text_BennyDefeat:
	.string "Γκουάαα! Το χάλασα!$"

Route110_TrickHousePuzzle6_Text_BennyPostBattle:
	.string "Εχεχεχε… Μάλλον έχασα\n"
	.string "επειδή προσπαθούσα να \l"
	.string "κλέψω.$"

Route110_TrickHousePuzzle6_Text_SebastianIntro:
	.string "Ζαλίζομαι από αυτές τις\n"
	.string "περιστρεφόμενες πόρτες…$"

Route110_TrickHousePuzzle6_Text_SebastianDefeat:
	.string "Όλα γυρίζουν γύρω γύρω.\n"
	.string "Δεν το αντέχω άλλο αυτό…$"

Route110_TrickHousePuzzle6_Text_SebastianPostBattle:
	.string "Δεν φαίνεται να σε επηρεάζει\n"
	.string "καθόλου.\n"
	.string "Ή μήπως έχεις βάλει το poker \l"
	.string "face σου;$"

