PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Τα ταξίδια είναι υπέροχα!\p"
	.string "Όταν ήμουν νέος, περιπλανιόμουν\n"
	.string "σε θάλασσες και βουνά!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Αχ…\p"
	.string "Μακάρι να μπορούσα να πάω σε μια\n"
	.string "περιπέτεια με μερικά POKéMON…\p"
	.string "Να σέρνομαι σε υγρό γρασίδι…\n"
	.string "Να σκαρφαλώνω βραχώδη βουνά…\p"
	.string "Να διασχίζω αγριεμένες θάλασσες…\n"
	.string "Να περιπλανιέμαι σε σκοτεινές \l"
	.string "σπηλιές…\p"
	.string "Και, μερικές φορές, να νοσταλγώ\n"
	.string "ακόμη και το σπίτι μου…\p"
	.string "Πρέπει να είναι υπέροχο το ταξίδι!$"

