FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Μιλώντας για τα POKéDEX, \n"
	.string "θυμήθηκα κάτι.\p"
	.string "Συνάντησα αυτόν τον TRAINER, τον \n"
	.string "STEVEN, όταν έψαχνα σπάνιες πέτρες.\p"
	.string "Πω πω, είχε κάτι απίστευτα POKéMON \n"
	.string "μαζί του.\p"
	.string "Δεν ήταν απλώς σπάνια, ήταν και \n"
	.string "εκπαιδευμένα σε τρομερό βαθμό!\p"
	.string "Μπορεί να είναι και πιο δυνατός από \n"
	.string "τη GYM LEADER αυτής της πόλης…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Τι είναι αυτό το πράγμα εκεί;\p"
	.string "… … … … … …\p"
	.string "Ω, λέγεται POKéDEX;\n"
	.string "Είναι πραγματικά φανταστικό!$"

