LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Τα μεγαλύτερα μυστήρια αυτού του \n"
	.string "πλανήτη βρίσκονται στον πάτο \l"
	.string "της θάλασσας.\p"
	.string "Κάποιος το είπε αυτό,\n"
	.string "αλλά δεν ξέρω…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Υπάρχει μια βαθιά υποβρύχια τάφρος\n"
	.string "μεταξύ MOSSDEEP και SOOTOPOLIS.\p"
	.string "Αυτό μου είπε κάποιος, τέλος πάντων.$"

